### ISSUE TITLE
Specify how/where to identify individuals from a project to join the CPC

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#1026]
Part of the [onboarding checklist](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md#onboarding-checklist) requires that a project to...

> Identify individuals from the project to join the CPC

How/where should this be done?
Maybe the project could specify it in a specific repo in their org?
(Is presuming the use of GitHub an OK thing to do?)

Whatever the decision, could this be made clearer in the onboarding checklist so this isn't a question in future? =]

Tracking for JSON Schema: https://github.com/json-schema-org/community/issues/349

**Comment by mhdawson** [comment]
> Identify individuals from the project to join the CPC

There is no specific way mandated in terms of how representatives are elected for impact projects.  In the case of non-impact projects it is still good to get people from projects to join the CPC. It would still be up to the project as who/how they would want to encourage to join.  

If you have any related questions I'm happy to chat about how we elect representatives in the Node.js project. In terms of encouraging others, it's mostly just by making people aware that it is a possibility for any project member.

**Comment by mhdawson** [comment]
I think they can open an issue to add themselves to the CPC and indicate that they are from project X.  Maintainers from that project could then chime in in the issue indicating that they support those people representing the project.
