### ISSUE TITLE
Node.js TSC charter change

### ISSUE THREAD

**Issue by Trott** [openjs-foundation/cross-project-council#1028]
Node.js TSC charter changes require CPC approval. The TSC has consensus for the change in https://github.com/nodejs/TSC/pull/1350 which removes a minimum meeting attendance requirement to be a TSC member and changes the nomenclature for _TSC member_ (to _TSC voting member_) and _TSC emeritus member_ to _TSC member_. Can we get CPC approval for this?

EDIT: If we're counting approvals here as votes (which I hope we will), I guess I should make it clear that I support this change.

**Comment by Trott** [comment]
@openjs-foundation/voting-members

**Comment by joesepi** [comment]
I approve.

**Comment by Trott** [comment]
> @openjs-foundation/voting-members

It looks like @imurchie was previously accidentally omitted from that team so pinging separately.

**Comment by ljharb** [comment]
I approve.

**Comment by eemeli** [comment]
I approve.

**Comment by TheLarkInn** [comment]
I approve!

**Comment by imurchie** [comment]
I approve!

**Comment by Trott** [comment]
By my count, 8 of the 15 voting members have approved the proposed charter change (imurchie, tobie, TheLarkInn, eemeli, ljharb, timmywil, joesepi, Trott). Is it OK at this point to consider this approved? Or is there something more in the CPC process that needs to happen?

**Comment by mhdawson** [comment]
+1 from me.

**Comment by Trott** [comment]
The CPC charter seems to me to suggest that this does not require a vote if it has lazy consensus, which it seems to have, and that if it were a vote, simple majority is the requirement with no further defined process, so 9 out of 15 approvals by voting members seems to me to indicate this proposal has passed. I'm going to close this issue, but feel free to re-open if I'm wrong or for any other reason.
