### ISSUE TITLE
Is a project OK to use CC CoC 2.1 before OpenJS Foundation does?

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#1029]
In JSON Schema, we are using the Contributor Covenant Code of Conduct to v2.1: https://github.com/json-schema-org/community/issues/162

I suggested that the OpenJS Foundation updated to use v2.1: https://github.com/openjs-foundation/cross-project-council/pull/851

This triggered some work to build a patch process, as the OpenJS Foundation version is modified: https://github.com/openjs-foundation/cross-project-council/pull/972

It is taking a long time for patch process work to be completed.
Can we check off the Code of Conduct box in our [list of onboarding tasks](https://github.com/json-schema-org/community/issues/129) while we wait?

**Comment by tobie** [comment]
This shouldn't be a blocker to onboard you and can be resolved after the case (please just keep note of the issue where relevant so this can be fixed later on).

**Comment by joesepi** [comment]
I dont see why this would be an issue. We discussed it briefly in today's CPC call and no one seemed to have obvious objections.
