### ISSUE TITLE
GitHub Org Discussions: Propose member projects to adopt this feature

### ISSUE THREAD

**Issue by ovflowd** [openjs-foundation/cross-project-council#1030]
GitHub recently (April 2022) released a new feature, namely ["Org Discussions"](https://github.blog/changelog/2022-04-12-organization-discussions/). Those are org-level discussions (but also show discussions from all the repositories with discussions enabled).

The Node.js project recently enabled the feature from [this nodejs/admin issue](https://github.com/nodejs/admin/issues/770). And so far, this has been useful. Especially for me when I posted about the OpenJS Collab Summit [here](https://github.com/orgs/nodejs/discussions/47037).

This is a fantastic channel for letting the CPC make announcements on the member-project's organisations without the members having special access to the org.

The idea is that we debate about how interesting this is for us and member projects and relay the idea so that each project's governing body might enable this feature if they see fit.

**Comment by ovflowd** [comment]
cc @openjs-foundation/cpc

**Comment by timmywil** [comment]
I like the feature, but don’t want to require it.

**Comment by ovflowd** [comment]
> I totally understand where you're coming from, but I really don't think the CPC or the foundation should set requirements as to how projects are run, especially not by forcing projects to use specific products. It might be worth driving towards your underlying intent through education and/or a statement of values, so I suggest exploring what that would look like.

Interesting, I definitely agree on that. I guess I had some poor wording here, let me update the original issue.

**Comment by ovflowd** [comment]
> That's a different proposition that should be discussed in the context of the various channels available to the CPC. What problem would it be solving? How would its reach differ and allow the CPC access to different stakeholders and to what end?

I think my wording definitely was not the best 😅

The gist is that letting the member project's now the benefits of GitHub Org Discussions is basically what I'm trying to achieve here. There's better communication and a better way for even the governing bodies of each project to make announcements or for members to create discussions about general aspects of their projects.

Now for us, there's the benefit of being able to reach out both the governing bodies and the individual contributors/community of each project through GitHub Discussions, as I exemplified with the Collab Summit announcement 😄

**Comment by mcollina** [comment]
> I totally understand where you're coming from, but I really don't think the CPC or the foundation should set requirements as to how projects are run, especially not by forcing projects to use specific products. It might be worth driving towards your underlying intent through education and/or a statement of values, so I suggest exploring what that would look like.

I concur with @tobie.

**Comment by ljharb** [comment]
Github has already let them know - if they were using team discussions, they saw the same message that node saw. If they weren't using them, they probably don't have a need for the new feature.

**Comment by ovflowd** [comment]
I guess then we can close this issue. Didn't know orgs were notified already and it makes sense to keep at their discretion.

Thank you folks for yall your opinions!
