### ISSUE TITLE
CPC Elections: CPC Director & CPC Chairperson 

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1041]
It is time to hold an election for the following CPC roles:

1. [CPC Director](https://forms.gle/6NpAMDyVREoyMX219) - Currently held by Sarah Chipps
2. [CPC Chairperson](https://forms.gle/tGSb7JqGqYXgYoiT8) - Currently held by Joe Sepi

Please fill out the above forms if you would like to put yourself or someone else forward as a nominee. The schedule for these elections is as follows:

Nomination Window: March 31 - April 10
Voting Period: April 11 - April 17

Once nominations are received, we will post them publically in a Github issue.

**Comment by tobie** [comment]
@bensternthal, did you write those forms up? They're great!

Could we make sure to store them somewhere (maybe make a copy in the CPC repo?) for future reference?

**Comment by bensternthal** [comment]
@tobie these are a combination of previously used forms with some tweaking by me. Unfortunately, they are in google forms, so we can't make a usable copy to store in github. However, I could "templatize" them, open up permissions and plop them in a shared google drive directory.

**Comment by tobie** [comment]
Whatever can be done to keep them around and accessible would be great.

**Comment by joesepi** [comment]
Yay!
