### ISSUE TITLE
Should we have a co-chair?

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#1043]
As we're about to run CPC Chair elections again, I'm again concerned about our lack of strategy around maintaining and passing on institutional knowledge for roles like this one.

Should we think about electing a co-chair (or a chair and vice-chair) in order to help with this?

@joesepi's been running an incredible show here. What will happen when he decides to move on? How would we manage that transition?

**Comment by Relequestual** [comment]
JSON Schema is planning to have a co-chair almost immediatly as the TSC is formed. I think it not only helps with long term sustainability, but reduces the mental burden of a chair.

**Comment by tobie** [comment]
It’s bundled in https://github.com/openjs-foundation/cross-project-council/pull/1055.

**Comment by tobie** [comment]
Closed by #1055 in 8b03828a53cbf8d50a7ddb2203ddf3a7777b22c0.
