### ISSUE TITLE
Open Up Community Board Seat

### ISSUE THREAD

**Issue by SaraJo** [openjs-foundation/cross-project-council#1054]
At last CPC meeting we discussed opening up the third CPC board seat. 

In addition, we also talked about making the number of board seats dependent on the number of projects, so that as the org grows the support for projects can grow.

**Comment by tobie** [comment]
Some proposed bylaws changes: https://docs.google.com/document/d/1x-zRBQZShLMWE53J2yNlD88oudVWSj5UG8QfR2_RayI/edit?pli=1

**Comment by mcollina** [comment]
Great work @tobie

**Comment by tobie** [comment]
> Great work @tobie

Aww, thank you! The true great work's convincing the Board, though. ;)

**Comment by bensternthal** [comment]
Below are the proposed changes from legal:

<img width="1060" alt="Screenshot 2023-08-08 at 11 36 10 AM" src="https://github.com/openjs-foundation/cross-project-council/assets/198507/99c89764-01b5-428d-97d9-45febed55d75">

**Comment by tobie** [comment]
We had discussed this in https://github.com/openjs-foundation/cross-project-council/pull/1055#issuecomment-1650290705. This option isn't meaningfully different to the one that we agreed to and proposed. During the CPC call, we agreed to go ahead with the board's proposal.

**Comment by bensternthal** [comment]
Bylaws have been approved. This can be closed and we will run the election in the near future.
