### ISSUE TITLE
JSON Schema charter request to review

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#1056]
Having undergone a number of revisions based on feedback, I present the first JSON Schema charter, looking for your feedback and approval, as required by the OpenJS Foundation.

https://github.com/json-schema-org/community/pull/325

I have requested review on the PR from the five individuals which will form the initial TSC with myself as chair.
We have had three approvals on the PR, and one request for changes, which is now resolved and waiting for re-review.

For timley responses, you can find me on slack. I may be somewhat slow to reply to direct comments here, although I'm making a note to check back on a regular basis.

---

[Requirements](https://github.com/openjs-foundation/cross-project-council/blob/main/governance/GOVERNANCE.md#approving-project-charters):

> The request is approved when:
> 
> - There are no outstanding objections
> - There are two or more approvals by voting CPC members
> - The board has been consulted in the case of substantial changes
> - The issue has been open for at least 14 days

- [x] There are no outstanding objections
- [x] There are two or more approvals by voting CPC members
- [ ] The board has been consulted in the case of substantial changes
- [ ] The issue has been open for at least 14 days

---

### Update 2023-08-09
We have undergone several rounds of feedback and revision, and based on the individual CPC reviews, I believe we are ready for formal review from the CPC.

I guess this should reset the 14 day timer, per requirements.

**Comment by tobie** [comment]
Congrats on reaching this important milestone! I’ll block time to make comments before the next CPC meeting.

**Comment by joesepi** [comment]
I know a lot of work has gone into this @Relequestual and its exciting that it is nearly completed. Congratulations!

Let me ask just to be sure: there is one checkbox left in the description
> Require all initial TSC members to review and approve of the PR

Has this been achieved? If not, it would seem premature for the CPC to approve. Just let us know. I'm happy to review it!

**Comment by tobie** [comment]
Alright, did a [full review](https://github.com/json-schema-org/community/pull/325#pullrequestreview-1393675331) this morning. I recommend at least addressing the overarching issue of separation between policy (belongs in the charter) and process (implementation, belongs in dedicated docs that don't need CPC review) before moving forward with the CPC review.

**Comment by Relequestual** [comment]
> I know a lot of work has gone into this @Relequestual and its exciting that it is nearly completed. Congratulations!

Thank you!

> 
> Let me ask just to be sure: there is one checkbox left in the description
> 
> > Require all initial TSC members to review and approve of the PR
> 
> Has this been achieved? If not, it would seem premature for the CPC to approve. Just let us know. I'm happy to review it!

It has not, but we are presuming that it will be without any major changes.
Although, with @tobie's feedback, it looks like I'll be doing some work to move chunks out into a different document.

So, I'll remove the agenda label and mark it blocked, pending updates 🙏.

I don't think there will be any major changes now (just removals and shuffling), so I'm still open and looking for feedback!

**Comment by mcollina** [comment]
Added some feedbacks.

**Comment by Relequestual** [comment]
The associated JSON Schema charter PR is now ready for re-review.
See https://github.com/json-schema-org/community/pull/325#issuecomment-1609202713 for comments.

**Comment by Relequestual** [comment]
We have undergone several rounds of feedback and revision, and based on the individual CPC reviews, I believe we are ready for formal review from the CPC.

I've also edited the opening post to include this update.
