### ISSUE TITLE
OpenJS World Europe 2023: Planning

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1073]
With OpenJS World North America now behind us, it's time to start thinking about OpenJS World 2023 EU (September 19-23, 2023 in Bilbao, Spain). We'd love your feedback and ideas! (tagging in @rginn for visibility)

**Comment by rginn** [comment]
Our OpenJS Program Committee resumes meeting on Wednesdays. Check out our public calendar if you're interested in participating: calendar.openjsf.org. 

We're also looking for feedback and interest in participating in the Collab Summit at OpenJS World EU for project contributors and maintainers.
