### ISSUE TITLE
Add pronouns on members list.

### ISSUE THREAD

**Issue by AugustinMauroy** [openjs-foundation/cross-project-council#1081]
In goal of better etique we should add pronouns.
It's allow us to know good pronouns .

Example :
```md
* Augustin Mauroy (@AugustinMauroy) _he/him_
```

**Comment by ovflowd** [comment]
I don't see this being done anywhere. Could you give an example of open-source projects that do this and explain why adding pronouns to the list is better?

**Comment by AugustinMauroy** [comment]
> Could you give an example of open-source projects that do this

I will search. But we can be the first.

>  and explain why adding pronouns to the list is better?

This allows anyone to use the right pronouns when talking about someone or with someone.

**Comment by ovflowd** [comment]
> I will search. But we can be the first.

Why would we want to be the first? I don't see the benefit of having this added to the README.

> This allows anyone to use the right pronouns when talking about someone or with someone.

I'm not sure how this is necessarily helpful on GitHub, at least (Mostly because we use people's usernames/handles to interact with each other, and we already mostly use gender-inclusive language (99% of the time I use they/them/their by default). GitHub already has a feature for pronouns. If you hover over my username, you'll see my pronouns.

This is honestly "profile" information, in my opinion. Note that I'm not dismissing the benefits of knowing someone's pronoun. I'm debating over this being useful here.

**Comment by AugustinMauroy** [comment]
We can be the first.

And about GitHub profile we need to have the profile picture. But if it's on the list you don't have to do an extra action.

**Comment by ovflowd** [comment]
I still don't think these are valuable arguments. Being the first for the sake of being isn't an argument.

And I still believe that people will naturally hover someone's profile when interacting.

I don't see why we should go to the extra mile and require people to put their pronouns there. Some people might not even feel comfortable on adding this sort of info. (Not saying it should be required if it is added)

Anyhow, I gave my 2cents. Let's see what the remainder of the CPC have to say 🙃

**Comment by AugustinMauroy** [comment]
> I still don't think these are valuable arguments. Being the first for the sake of being isn't an argument (at least imo)

Yeah that not real argument 🙃. Just if we are the first to do that other can follow us.

> I don't see why we should go to the extra mile and require people to put their pronouns there. Some people might not even feel comfortable on adding this sort of info. (Not saying it should be required if it is added)

We can just add for people want.

Other point on mobile to see pronouns you have to click ->open new tabs look -> back to the first tab -> writing we good pronoun.

**Comment by Trott** [comment]
Node.js includes pronouns in the README, but it's purely optional. Most collaborators have opted to include it. I'm sure other projects have done this too.

https://github.com/nodejs/node/

![image](https://github.com/openjs-foundation/cross-project-council/assets/718899/8236bcc8-730d-4e74-9f52-c230d2fe0393)

**Comment by ovflowd** [comment]
Huh! See, this is something I didn't notice at all! And what is even funnier is that I also have a pronoun set 🤡. Anyhow, I still stand with what I say that adding pronouns doesn't necessarily bring value, but hey, it's not a matter of being right or wrong here, and if the CPC feels this is a good thing, we can add. But keep them optional (hopefully) 😅 

![image](https://github.com/openjs-foundation/cross-project-council/assets/12037269/5df1d3b3-11df-4d4a-812c-b37467bb2c09)

**Comment by ljharb** [comment]
I'm comfortable with adding pronouns - it sends a good signal - but given that github already has a source of truth for this, I would be -1 against adding any more duplicated information to the readme without a programmatic means to keep it all in sync with github (so if someone changes their pronouns, this readme wouldn't have the wrong ones for long)

**Comment by tobie** [comment]
Closing for the reasons mentioned by @ljharb and @ovflowd above.

**Comment by tobie** [comment]
Closing for the reasons mentioned by @ljharb and @ovflowd above.
