### ISSUE TITLE
Remove brianwarner from default issue assignee on GitHub issue template. 

### ISSUE THREAD

**Issue by TheLarkInn** [openjs-foundation/cross-project-council#1090]
@tobie Had informed me that brianwarner is not apart of the LF anymore so it doesn't make sense to have him as the default Issue Assignee on our GitHub issues for this repo. 

![image](https://github.com/openjs-foundation/cross-project-council/assets/3408176/b23a26f4-f6ce-4f62-84b5-11886b219dfd)

As seen here its default assigned when it was generated. We should fix that (whether its in the template or some other setting).

**Comment by ljharb** [comment]
I don't think we need to discuss this in the meeting; we can just change it to the CPC team I think, with a PR or a commit.
