### ISSUE TITLE
Document process for requesting Organisation Billing (Codespaces + Runners + Etc)

### ISSUE THREAD

**Issue by ovflowd** [openjs-foundation/cross-project-council#1092]
With #1009 we've started to provide Billing Support for GitHub organisations belonging to our member projects. This is a great step for providing resources to our project's GitHub organisations.

Webpack seemed to be the pilot for Codespaces. Which is also awesome!

Yet, we should document the process of requesting such resources and also have documented which organisations have billing enabled to X features.

I also wonder if the CPC should have access to the "recurring costs" of the billing for the sake of analysis and transparency.

This issue is about drafting a Markdown file that documents the process of requesting access to resources, such as Codespaces, or Large Runners or etc (#1089) and which current project's have access to those (The later one could be an update on README.md adding a sort of emoji or label that they have access to resource X, or somewhere else, or in the same document where we request resources).

**Comment by ovflowd** [comment]
Hey @bensternthal any updates here? 👀

**Comment by bensternthal** [comment]
@ovflowd thanks for the poke. Here is what I am thinking for an outline of this doc.

- What kind of Github Resources are eligible for funding
- How to request funding from the CPC
- What happens next 
   - LF budget approval
   - Billing contact/virtual credit card
- Markdown table listing each project, what resources are funded and how much

I can write all the bullets except the CPC one. ..

1. Should the CPC approve these requests? (I feel like yes but am open to other ideas)
2. If so, would you be able to help draft the CPC approval process portion? I suspect this would be filing an issue with specific information etc.

**Comment by ovflowd** [comment]
I'd like the CPCP to approve these resources. We can talk about this at the next CPC meeting. I would be able to draft the CPC process portion, but my English is probably not the best suited for these nuances. 

I would love to get some help. We can craft a PR together, and the CPC can review/add feedback/suggest changes to the wording.

What about we work on this together at the next CPC Working Session/Meeting?

**Comment by bensternthal** [comment]
Sounds like a plan!

**Comment by joesepi** [comment]
@bensternthal and @ovflowd worked on this last week and there should be a PR coming. 🎉
