### ISSUE TITLE
Create package.json research hub

### ISSUE THREAD

**Issue by Ethan-Arrowood** [openjs-foundation/cross-project-council#1102]
As a result of last weeks working session, we are going to begin researching all of the various package.json fields and collecting it all into one place. I envision a "research hub" of sorts. At first, this will be a collection of markdown files in a GitHub repository (I'm working with @ljharb to get this started). Later, we could build some sort of public website for better access to the research. 

This issue is meant to be a public record declaration of our continued efforts for standardizing package.json. As I explained in the [previous package.json related thread](https://github.com/openjs-foundation/cross-project-council/issues/1082#issuecomment-1599187877), we are looking at a new, bottom-up approach. This approach will have multiple smaller efforts (starting with this one) with the collective end goal of standardizing and improving the developer experience of package.json.

**Comment by tobie** [comment]
Seems we should be able to close this one now that the collab space has been launched.

**Comment by Ethan-Arrowood** [comment]
For future people finding this issue, join us over at https://github.com/openjs-foundation/package-metadata-interoperability-collab-space 😄
