### ISSUE TITLE
Do charters which use the template need to include MIT?

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#1105]
I was looking at the CPC repo license to see if charters created using the template have any obligations under the license.

Given the repo defines MIT, does that mean I also need to include that specific MIT license and copyright at the end of our new project charter?

**Comment by tobie** [comment]
Not a lawyer. My assumption would be that this falls under fair use or that the content that made it to your charter isn't copyrightable (as it's essentially just titles and/or short phrases, see [Circular 33 of the US Copyright Office](https://www.copyright.gov/circs/circ33.pdf)). I also add that this ever becoming a genuine legal issue seems incredibly farfetched.

That said, the CPC isn't in a position to formally state on this as it is a legal issue, so if my above comment isn't satisfying, I suggest you reach out to the foundation directly [through the appropriate channel](https://github.com/openjs-foundation/cross-project-council#help-with-legal-questions-for-existing-projects-only). Either way, I suggest we close this.

**Comment by bensternthal** [comment]
I reached out to our legal council on this one, below is the response:



> The answer may be that the repository needs an explanation to clarify this.
> 
>  The overall IP governance document for OpenJS is the Intellectual Property Policy. The relevant text there is the following:
> 
>  Except as may be approved by the Board:
> 
> -  All new code contributions to any Project shall be made under the Project Code License accompanied by a Developers Certificate of Origin (DCO, available at http://developercertificate.org/), which will bind the individual contributor and, if applicable, their employer to the Project Code License.
> - All outbound code files will be made available under the Project Code License.
> - All documentation, image, and audiovisual files (e.g., .txt., .rtf, .doc, .pdf, .jpg, .tif, .mp3, .wav, and some .html files) (including without limitation code that is intended as sample code if included in a documentation file) will be contributed to the Project and made available under one of the following licenses selected by the Project’s technical governing body (the “Project Documentation License”):
> - Creative Commons Attribution 4.0 International License (CC BY 4.0) (available at http://creativecommons.org/licenses/by/4.0/), or
> - The MIT License (available at https://opensource.org/licenses/MIT).
> 
> So the take away is that the MIT License is for code and not associated documentation, and therefore the MIT license would not be appropriate - the CC 4.0 would.
> 
> But - note that the IP Policy is directed at code and other materials that are contributed to Projects and are intended to be reused, changed, and redistributed by downstream users of Project software and related materials. In this case, we’re talking about a document that is intended only for internal governance purposes, and there’s no need for anyone other than the CPC to do anything more than read a charter, nor does the IP Policy actually apply.
> 
> So the bottom line is that there is no policy that directly applies to this situation, and a simple copyright line would be appropriate.

###

**Comment by tobie** [comment]
I'm a little confused by the answer from the counsel.

1. The [IP policy](https://ip-policy.openjsf.org) states fairly clearly that documentation can be provided under a CC-BY-4.0 _or_ an MIT license, as pointed out by the very text quoted in the reply, yet the counsel comes to a different conclusion ("So the take away is that the MIT License is for code and not associated documentation, and therefore the MIT license would not be appropriate - the CC 4.0 would."). Can the counsel clarify that MIT is actually appropriate for documentation?

2. The CPC repository has an MIT license. I have contributed to the CPC with the expectation that my contributions here would benefit the CPC, the OpenJSF, and its projects, _but also any other foundation or project that would wish to leverage these resources pursuant to the the terms of the MIT license_ (or any other similar, OSI-certified open source license, for that matter). Can we get confirmation from the counsel that the CPC repository is in fact MIT-licensed, will stay as such, and that IP Policy actually applies to it too?

3. @Relequestual's question was about the reusability of the [charter _template_](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_CHARTER_TEMPLATE.md) in a specific project. Was that clearly presented to the counsel? As outlined in [Circular 33 of the US Copyright Office](https://www.copyright.gov/circs/circ33.pdf), titles, short phrases, and _blank forms_ are not copyrightable. The charter template is essentially a blank form, so shouldn't be copyrightable. Can we get the counsel to clarify whether or not the charter _template_ is copyrightable?

4. Should the template be deemed copyrightable by the counsel, could we either:
    - adopt an [MIT-0 license](https://opensource.org/license/mit-0/) (specifically designed for such use cases, and approved by the OSI a few years ago) for templates, or
    - provide a copy of the template under all licenses accepted by OpenJSF, so that we don't force multiple licenses on projects just to use the charter template that we're asking them to use? That seems counterproductive.
   
Thanks!

**Comment by bensternthal** [comment]
@tobie I send your comments to our legal council and below is the response. I hope this is helpful :)

The [IP policy](https://ip-policy.openjsf.org/) states fairly clearly that documentation can be provided under a CC-BY-4.0 or an MIT license, as pointed out by the very text quoted in the reply, yet the counsel comes to a different conclusion ("So the take away is that the MIT License is for code and not associated documentation, and therefore the MIT license would not be appropriate - the CC 4.0 would."). Can the counsel clarify that MIT is actually appropriate for documentation?
>>While the MIT License could be used for documentation, and you’re correct that the policy does not restrict documentation to the CC license, the consensus in the legal community is that a CC license is generally more appropriate for many types of documentation use. Since, as already noted, the IP Policy doesn’t by its terms apply to a Charter for a committee, as compared to contributions to a Project, it doesn’t restrict what a committee could do, either. So if the CPC wants to stick with the MIT License, that would not violate any rules and would therefore be fine.

The CPC repository has an MIT license. I have contributed to the CPC with the expectation that my contributions here would benefit the CPC, the OpenJSF, and its projects, but also any other foundation or project that would wish to leverage these resources pursuant to the the terms of the MIT license (or any other similar, OSI-certified open source license, for that matter). Can we get confirmation from the counsel that the CPC repository is in fact MIT-licensed, will stay as such, and that IP Policy actually applies to it too?

>>See last response. Since the MIT License in the root is the only license mentioned in the repo, it would be reasonable to assume that all contributions to that repo would be subject to it.

[@Relequestual](https://github.com/Relequestual)'s question was about the reusability of the [charter template](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_CHARTER_TEMPLATE.md) in a specific project. Was that clearly presented to the counsel? As outlined in [Circular 33 of the US Copyright Office](https://www.copyright.gov/circs/circ33.pdf), titles, short phrases, and blank forms are not copyrightable. The charter template is essentially a blank form, so shouldn't be copyrightable. Can we get the counsel to clarify whether or not the charter template is copyrightable?
>>Yes, I understood that. Regarding copyrightability, that would depend on which text you are referring to. You’re correct that the bare bones template would not involve any creative element justifying copyright ownership. On the other hand, some of the text of the annotated form found here would be entitled to copyright protection:  [cross-project-council/PROJECT_CHARTER_TEMPLATE.md at main · openjs-foundation/cross-project-council · GitHub](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_CHARTER_TEMPLATE.md) As noted in the Circular you cite, “Contracts, insur[1]ance policies, and other documents with “fill-in” spaces may also be registered if there is sufficient literary authorship that is not standard or functional,” and text such as the following from the annotated form rises to that level: “ Imagine trying to explain your work to a colleague who is familiar with related technical concepts but unfamiliar with the project.”

Should the template be deemed copyrightable by the counsel, could we either:
adopt an [MIT-0 license](https://opensource.org/license/mit-0/) (specifically designed for such use cases, and approved by the OSI a few years ago) for templates, or
>>As noted above, yes.

provide a copy of the template under all licenses accepted by OpenJSF, so that we don't force multiple licenses on projects just to use the charter template that we're asking them to use? That seems counterproductive.
>>I’m not sure I totally understand the question here, but let me try to respond. We need to distinguish here between the template charter (which I understood the original question to be about) and the charters that projects adopt using the template. As noted, it would be fine to use the MIT License for the annotated template, and there’s no need to worry about copyright at all for the bare bones, empty set of data fields (although you could make that available under the MIT license as well, just users wouldn’t have to think or worry about their rights to use it. When it comes to the charters created using the template, though, the rules will be as set forth in the OpenJS IP Policy, so, unless the Board of Directors approves a separate license in any given case, an actual  Project Charter could be made available under either the MIT License or the CC 4.0. Also, note that while the MIT and CC 4.0 are in many ways similar, the CC 4.0 is somewhat more restrictive (e.g., it prohibits adding any additional legal or technological restrictions.

>>Unrelatedly, I note that the Project Charter Template does not include a field to specify which license the project will use. The IP Policy states that, unless the Board of Directors has approved a different license, “The technical governing body of each Project is free to choose, as its Project Code License, any of the following licenses:…” The Project Charter would be a logical place to record that decision, so you may wish to consider updating the template to include a field for that information.

**Comment by tobie** [comment]
Thanks, @bensternthal, that's super useful and great feedback from our counsel. It confirms my initial response to @Relequestual that the content from the template (what the counsel calls "the bare bones") that makes it into a project's charter isn't copyrightable. The project's charter, however, should be licensed under CC-BY 4.0 or MIT [with a copyright notice as per our IP policy guidance doc](https://github.com/openjs-foundation/cross-project-council/blob/main/governance/IP_POLICY_GUIDANCE.md#2-copyright-notices).

With regards to the counsel's suggestion to record a decision of which licenses are used by a project in the charter itself, it is worth noting that:
- projects often have multiple repositories, with potentially different licenses,
- checking the license of every repository is already part of the onboarding process, so adding a such information to the charter would be duplicative of information already contained in every repository, potentially creating confusion as to where the source of truth lies.
- if the IP policy changes in the future, projects would need to update their charter to match the new guidance, creating unnecessary churn.

It might be more worthwhile to create a template repository that all new foundation projects may use instead (or something similar).

**Comment by joesepi** [comment]
We are closing this issue as it seems the original question was answered. If you disagree @Relequestual just reopen. Thanks!
