### ISSUE TITLE
Fix broken New Issue templates

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#1109]
### What is this issue about?

What is this field about?

### Request Details

2 of the 4 New Issue templates seem to be broken. They look like they are supposed to open in a new window to something somewhere but just give a 404

### Request Type

Repository bug report (e.g. broken link)

**Comment by ovflowd** [comment]
@joesepi which ones have a broken libk? 🤔

**Comment by ovflowd** [comment]
Okay, I've found the issue and made a hot-fix. The issue was that it was referencing the PR branch instead of the main branch.

**Comment by joesepi** [comment]
Thanks @ovflowd !!!
