### ISSUE TITLE
Standardize on Collab Spaces over Working Groups

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#1110]
We have Collab Spaces and Working Groups. I don't think we need both and I've heard from multiple people that having both is confusing.

Related: openjs-foundation/cross-project-council#1108

There's agreement to move forward with this. Here are the steps:

- [x] **CPC decisions**
    - [x] CPC to agree that Collab Spaces can have authority delegated to them via their charter
    - [x] CPC to agree to migrate Standards WG to a Collab Space
    - [x] CPC to decide what to do with the CoC WG (the CPC agreed in principle to close that WG as it was no longer active, noting that the WG has nothing to do with CoC enforcement)
- [ ] **Courtesy Board update** (also because they'll need to approve the tiny CPC charter modification)
    - [ ] Explain reasons for proposed change (simplification)
    - [ ] Demonstrate CPC charter change is tiny
    - [ ] Demonstrate that there are no Bylaws change
- [ ] **Collab Spaces documentation update**
    - [ ] Amend Collab Spaces documentation to mention possible authority delegation via their charter
    - [ ] Update Collab Space charter template to add dedicated section to authority delegation
- [ ] **Update charters of existing Collab Spaces** (to be explicit about absence of authority delegation)
- [ ] **WG migration**
    - [x] openjs-foundation/standards#253
    - [ ] Migrate Standards WG to Collab Space
    - [ ] Sync with Standards WG to have its repo updates accordingly
    - [ ] Migrate CoC WG to Collab Space or close it (depending on prior CPC decision)
- [ ] **Removal of WG documentation**     
    - [ ] Remove all current references to WGs in CPC repo
    - [ ] Update CPC charter accordingly
    - [ ] Board to approve CPC charter change

**Comment by mhdawson** [comment]
The concept of working groups as inherited from the Node.js project makes less sense to me in the context of the foundation.  I'd favor consolidating into Collab Spaces.

**Comment by tobie** [comment]
This doesn't seem so bad to fix: No bylaws impact. Just a single mention of WGs in the charter.

The only question is want we want to do with the _authority delegation_ aspect of WGs. For the record, the CPC delegates a scoped decision-making power to the WG via the WG's charter. A WG is able to represent the Foundation in that context. That is not currently the case for Collab Spaces.

IMHO, this power delegation is important in some cases, for example, to allow WG members to represent the Foundation in standard bodies, so we need to keep it around.

I think we can just specify in the Collab Space's charter whether or not the CPC delegates decision-making power to the Collab Space (and what exactly is delegated if that's the case). We'd just need to amend the docs accordingly and update existing Collab Space charters to be specific that there isn't any delegation go
/ing on for them.

Concretely:

- [ ] **CPC decisions**
    - [ ] CPC to agree that Collab Spaces can have authority delegated to them via their charter
    - [ ] CPC to agree to migrate Standards WG to a Collab Space
    - [ ] CPC to decide what to do with the CoC WG (migrate or close?)
- [ ] **Courtesy Board update** (also because they'll need to approve the tiny CPC charter modification)
    - [ ] Explain reasons for proposed change (simplification)
    - [ ] Demonstrate CPC charter change is tiny
    - [ ] Demonstrate that there are no By Laws change
- [ ] **Collab Spaces documentation update**
    - [ ] Amend Collab Spaces documentation to mention possible authority delegation via their charter
    - [ ] Update Collab Space charter template to add dedicated section to authority delegation
- [ ] **Update charters of existing Collab Spaces** (to be explicit about absence of authority delegation)
- [ ] **WG migration**
    - [ ] Migrate Standards WG to Collab Space
    - [ ] Sync with Standards WG to have its repo updates accordingly
    - [ ] Migrate CoC WG to Collab Space or close it (depending on prior CPC decision)
- [ ] **Removal of WG documentation**     
    - [ ] Remove all current references to WGs in CPC repo
    - [ ] Update CPC charter accordingly
    - [ ] Board to approve CPC charter change

**Comment by joesepi** [comment]
are there any objections from anyone on the @openjs-foundation/cpc to simplify and standardize on collab spaces?

in today's meeting, we had no objections and would like to move forward on the work.

**Comment by joesepi** [comment]
Lets make sure to alert @openjs-foundation/standards if they haven't been already.

**Comment by tobie** [comment]
> Lets make sure to alert @openjs-foundation/standards if they haven't been already.

Beat you to it: https://github.com/openjs-foundation/standards/issues/253

**Comment by anfibiacreativa** [comment]
@joesepi as discussed I found the following mentions of "working groups" across the repo. I made some suggestions as to how to handle them, but of course, feel free to correct. I can open a PR for changes if course of action is approved.

Working groups.

I have found the following occurrences of ‘Working groups’

| path | line | mention | suggestion |
|-----|-----|---------|-------------|
| [https://github.com/openjs-foundation/cross-project-council/tree/main/readme.md](https://github.com/openjs-foundation/cross-project-council/tree/main/readme.md) | 232 | Link to working spaces governance | mark deprecated |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/readme.md](https://github.com/openjs-foundation/cross-project-council/tree/main/readme.md)  | 240 |’”…Collaboration Spaces and Working Groups”  | remove |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/CPC-CHARTER.md](https://github.com/openjs-foundation/cross-project-council/tree/main/CPC-CHARTER.md) | 89 | “…or working groups” | remove |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/governance/GITHUB_ORG_MANAGEMENT_POLICY.md](https://github.com/openjs-foundation/cross-project-council/tree/main/governance/GITHUB_ORG_MANAGEMENT_POLICY.md) | 26 | “…added to any working group  | replace |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/governance/GOVERNANCE.md](https://github.com/openjs-foundation/cross-project-council/tree/main/governance/GOVERNANCE.md) | 196 | “...including approving changes to working groups” | replace |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/approved/CPC-CHARTER.md](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/approved/CPC-CHARTER.md) | 132 | “...create subcommittees or working groups.” | replace |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/approved/EXPECTATIONS/EXPECTATIONS.md](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/approved/EXPECTATIONS/EXPECTATIONS.md) | 100 | “…contribute to working groups or initiatives.” | remove or archive |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/artifacts/EXPECTATIONS/EXPECTATIONS.md](https://github.com/openjs-foundation/cross-project-council/tree/main/artifacts/EXPECTATIONS/EXPECTATIONS.md) | 100 | “…contribute to working groups or initiatives.” | remove or archive |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/approved/SECURITY_REPORTING/README.md](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/approved/SECURITY_REPORTING/README.md)/ | 45 | “…security working group at foundation level.” | remove or archive |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/ANNUAL_ECOSYSTEM_REPORT/README.md](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/ANNUAL_ECOSYSTEM_REPORT/README.md) | 25 | “…a new working group should be created.” | replace |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/ANNUAL_ECOSYSTEM_REPORT/README.md](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/ANNUAL_ECOSYSTEM_REPORT/README.md) | 2 | “…working group will create a report” | replace |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/ANNUAL_ECOSYSTEM_REPORT/README.md](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/ANNUAL_ECOSYSTEM_REPORT/README.md) | 58 | “Creation of a working group” | replace |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/COLLABORATION_SUMMIT/README.md](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/COLLABORATION_SUMMIT/README.md) | 25 | “…team/working group” | replace |
| [https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/COLLABORATION_SUMMIT/README.md](https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/COLLABORATION_SUMMIT/README.md) | 27 | “…team/working group” | replace |

A great amount of mentions are found under [https://github.com/openjs-foundation/cross-project-council/tree/main/governance/WORKING_GROUPS.md](https://github.com/openjs-foundation/cross-project-council/tree/main/governance/WORKING_GROUPS.md) and under meeting logs, which can be archived.
The mentions in [https://github.com/openjs-foundation/cross-project-council/tree/main/COLLABORATION_SPACE_PROGRESSION.md](https://github.com/openjs-foundation/cross-project-council/tree/main/COLLABORATION_SPACE_PROGRESSION.md) and [https://github.com/openjs-foundation/cross-project-council/tree/main/COLLABORATION_NETWORK.md](https://github.com/openjs-foundation/cross-project-council/tree/main/COLLABORATION_NETWORK.md]) that explain the differences between collaboration spaces and working groups, probably need to stay in place.

**Comment by joesepi** [comment]
Meeting notes:
  * Need someone to do the work/pull request
