### ISSUE TITLE
Simplify generic issue template

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#1112]
### What is this issue about?

Simplifying the generic issue template

### Request Details

Could we roll back the template for the generic issue and just use a standard one instead?

This is adding a lot of noise and duplication both when creating and reading through issues, increasing the cognitive load for no concrete benefits imho.

### Request Type

General discussion that requires the CPC attention

**Comment by ovflowd** [comment]
> This is adding a lot of noise and duplication both when creating and reading through issues, increasing the cognitive load for no concrete benefits, IMHO.

Define a lot of noise. The only difference is that we have 3 headings now. You're still free to write as you wish.

**Comment by tobie** [comment]
@ovflowd and I discussed this off-thread. We agreed that GH Issue forms are a little underwhelming at this point, as there's no automation possible using them. For example, we'd want to be able to pick a label from the dropdown menu, not just print the output out. So until things improve and we can actually leverage the forms for triaging purposes, @ovflowd was OK rolling back the generic issue to using the basic issue template. One of us will open a PR.

**Comment by joesepi** [comment]
Thank you! I found the generic issue to be a bit overkill. 🙏
