### ISSUE TITLE
2023 CPC Summer Elections

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1126]
This issue tracks the CPC summer elections for 2023

- Director 2 election - term ends July 31
- CPC Impact voting member selection - term ends July 31
- CPC At-Large voting member election - term ends July 31
- CPC Regular member voting member election - term ends July 31

```[tasklist]
### Elections & Selections
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1142
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1143
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1144
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1145
```

```[tasklist]
### Other Tasks
- [ ] https://github.com/openjs-foundation/cross-project-council/issues/1148
- [ ] Post elections: Update groups.io/mailinglists, Github readme
```

**Comment by mhdawson** [comment]
I'm out on vacation next week, but I'm planning to run for one of the `CPC Regular member voting member election` positions again this year.

**Comment by mcollina** [comment]
I'm running for the Director position again.

**Comment by tobie** [comment]
Hey @bensternthal, for the last election you set up Google forms with some great questions (see https://github.com/openjs-foundation/cross-project-council/issues/1041) with the intention of publishing the answers in an issue.

1. Are we planning on doing the same thing again?
2. The plan was to share the replies publicly in an issue so folks could knowingly vote on them. I can't seem to find where that happened. Any idea?

**Comment by eemeli** [comment]
I will not be standing in either of the voting member elections, as I don't really have the bandwidth available to participate in the biweekly calls anymore. Very happy to continue as a regular member though!

**Comment by bensternthal** [comment]
@tobie I was waiting for the next CPC meeting to discuss the elections, how they have been run in the past, and what help from me might be needed.

**Comment by ljharb** [comment]
I’ll be running for Regular member voting member again.

**Comment by tobie** [comment]
@bensternthal and @joesepi to work together on this.

Only request from @tobie is for the candidate statements to be made public.

**Comment by bensternthal** [comment]
OpenJS website is updated. If anyone wants different bio text or a different profile photo please reach out.

**Comment by tobie** [comment]
Am I still possibly seeing a cached version? For example, I don't see Yagiz in the CPC voting members.

**Comment by bensternthal** [comment]
Yep likely cached you can add a query at the end to get a noncached version:

https://openjsf.org/about/governance/?foo=bar
