### ISSUE TITLE
Updated OpenJS Foundation Tiered Marketing Offerings

### ISSUE THREAD

**Issue by kyliewd** [openjs-foundation/cross-project-council#1128]
Hi all - Kylie here from OpenJS marketing/comms. I'd like to share an updated document for guidelines and tiering when working with the foundation on marketing services, and to talk through this at an upcoming CPC Meeting. See here: [OpenJS Tiered Marketing Services - July 2023](https://docs.google.com/presentation/d/1zCwX1soKegoY9oZgveDH8iQsQCAgTMMehQjVoBTNO7U/edit#slide=id.g258b47f455d_0_467)

TLDR:

- The 3 tiers (incubation, at-large and impact) all receive different levels of marketing support, with impact receiving the most support.
- Marketing services and budget are up to the discretion of the foundation team – all projects are different. Please reach out to me if you have any questions about this, happy to work with you!
- The majority of our staff is only half time on the OpenJS Foundation, meaning that there isn’t a sole dedicated resource for marketing and management efforts.

**Comment by tobie** [comment]
Thanks for sharing, @kyliewd.

Feels like it would be worthwhile to fold the slide deck into the support documentation for what resources the foundation offers to projects.

**Comment by mhdawson** [comment]
> The majority of our staff is only half time on the OpenJS Foundation

It might be good to document somewhere what percentage we have of what people, to help set expectations.

**Comment by joesepi** [comment]
> It might be good to document somewhere what percentage we have of what people, to help set expectations.

It lays percentages out in the deck linked in description of this issue, but the gist is everyone is 50% except for Executive Director (Robin), who is 100%.

**Comment by joesepi** [comment]
We have a "project resources" directory in our repo here. We should replace this outdated Marketing Services pdf with a new one: https://github.com/openjs-foundation/cross-project-council/blob/main/project-resources/OpenJSF%20Marketing%20Services%20-%20Dec.%202019.pdf

/cc @kyliewd
