### ISSUE TITLE
Pin project-status repo to landing page

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#1140]
The [`project-status` repo](https://github.com/openjs-foundation/project-status) should be easier to find. Let's pin it to the organization's landing page.

This will require removing one of the previously pinned repo, for example `code-and-learn`, which is for a 2019 event.

**Comment by joesepi** [comment]
Done. It seems like Github chose random projects to pin because when I went to edit the list of pinned projects, none were selected already. I chose what I thought made the most sense but I'm open to others thoughts.
