### ISSUE TITLE
Election: CPC Regular Voting Members

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1145]
As per the [CPC charter](https://github.com/openjs-foundation/cross-project-council/blob/main/CPC-CHARTER.md), the regular members elect 2 voting CPC members:

>up to two Voting members may be nominated by the Regular members. Once nominated these members must be ratified by the CPC Voting members before becoming a Voting member.

These members will be elected for a term of 1 year.

### Nomination Process
We are now taking nominations for these two positions on the Voting CPC Member body from the [regular membership list](https://github.com/openjs-foundation/cross-project-council#regular-members). Anyone who has been active in the foundation or one of its member projects, as described in the CPC Governance may request to become a regular member by opening a PR to add themselves to the list of regular members.

Any Regular CPC member can nominate themselves (or another, with permission) by emailing the chair of the CPC with their interest in running for the CPC. The nomination period will be open for 2 weeks at which point the CPC chair will list the nominees in the issue.

Each of the candidates listed will then be asked to open an issue in the CPC repo which includes the following:

- Projects they are part of
- Description of their background
- The reasons they would like to act as a non-impact CPC voting member
- Confirmation that they can devote the required time/effort.
- Their employer (if applicable). This is needed due to the limitations on maximum employer representation in the CPC voting members.

```[tasklist]
### Election Schedule
- [x] Nomination Period August 14-25
```

**Comment by anonrig** [comment]
> @joesepi, I don’t think the process requires folks to email you. Am I missing something?

Taken from the issue:

```
Any Regular CPC member can nominate themselves (or another, with permission) by emailing the chair of the CPC with their interest in running for the CPC. 
```

**Comment by tobie** [comment]
@anonrig yeah, but where is this process documented?

**Comment by bensternthal** [comment]
@tobie please see https://github.com/openjs-foundation/cross-project-council/blob/main/governance/GOVERNANCE.md#election-process-for-non-impact-voting-cpc-members

**Comment by tobie** [comment]
Thanks, @bensternthal! I skimmed it earlier and missed the line about emailing.

This really needs a cleanup, plus adopting the same process for all CPC-related elections, not just the voting member one.

As you're running most of it, would you like to suggest changes?

**Comment by bensternthal** [comment]
@tobie Yes agreed it does need a cleanup and it would be much easier to run if all these elections operated in the same way. After the current round of elections, I intend to suggest some alterations that will hopefully make things much simpler.

**Comment by bensternthal** [comment]
Per https://github.com/openjs-foundation/cross-project-council/pull/1161, closing this out.
