### ISSUE TITLE
CPC Charter Update To Reflect OpenJS By-Laws Change Enabling Additional CPC Director Seats

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1152]
Our legal council made a first pass at changes to the CPC charter, reflecting the changes recently made to the OpenJS bylaws to enable additional CPC director seats.

I suggest we use a google doc and comments to get to a consensus on changes prior to filing a PR. 

https://docs.google.com/document/d/1Py4POLS1SdPF00qb117XuEz9XMAuONqs/edit

Note our legal council stated:

> I’ve taken a crack at what the CPC Charter should now look like if the CPC wants to keep as close to the current model as possible, but it may be that the CPC might want to reconsider how Board seats are filled, given the time that has passed and the expansion of the number of available seats.(e.g., should projects get more influence now than individuals?) Perhaps they’ve already discussed this. Either way, I’d be happy to make any further changes to track their intentions as approved by the Board.

Please note that the board will need to approve the changes to the CPC charter.

**Comment by tobie** [comment]
Please note that we had already prepared such a proposal. You'll find it right here: https://github.com/openjs-foundation/cross-project-council/pull/1055

**Comment by bensternthal** [comment]
Darn it, sorry I missed that. I will close this issue and add the above as a comment.
