### ISSUE TITLE
Regarding compliance of copyright notice requirement for projects

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#1155]
I'm trying to fulfil the requirement laid out in the IP policy: https://github.com/openjs-foundation/cross-project-council/blob/main/governance/IP_POLICY_GUIDANCE.md#2-copyright-notices
for the JSON Schema project.

> The recommendation is to use a general copyright statement of the following form (where XYZ is the project's name):
> 
>     Copyright The XYZ Authors.
>     Copyright The XYZ Contributors.
>     Copyright Contributors to the XYZ project.
> 
> By using this format, the project avoids having to deal with names of copyright holders, years or ranges of years, and variations on the (c) symbol.

Our Issue: https://github.com/json-schema-org/community/issues/321
The PR: https://github.com/json-schema-org/json-schema-spec/pull/1380

We already have A copyright notice in our license file: https://github.com/json-schema-org/json-schema-spec/blob/main/LICENSE

We are [unclear](https://github.com/json-schema-org/json-schema-spec/pull/1380#issuecomment-1673404283) if we should update this in some way (modify the format or wording), and if we need to also duplicate it to the repo readme.

Please advise what is required to resolve the onboarding requirement. Thanks.

**Comment by tobie** [comment]
As the IP Policy Guidance you reference mentions, you want to address legal questions that aren't clearly answered by the guideline itself or by the IP policy [over email](https://github.com/openjs-foundation/cross-project-council/blob/main/governance/IP_POLICY_GUIDANCE.md#getting-help).

**Comment by Relequestual** [comment]
You are correct. Thanks.
I've reached out.

**Comment by tobie** [comment]
Closing. Feel free to reopen this is issue or a new one if there’s a followup as a result.
