### ISSUE TITLE
Create Google Intake Form Based On Scoring Rubric

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1164]
One the travel fund rubric is approved (#1154) we will need to create a google form to intake the required information.

**Comment by tobie** [comment]
Let’s separate the questions that should make it into the form from the rubric as part of a decision-making mechanism.

**Comment by bensternthal** [comment]
Per discussion in the CPC working group section and this [issue](https://github.com/openjs-foundation/cross-project-council/issues/1154#issuecomment-1691517141), I mocked up what the form might look like.

Please review the below and add comments/questions.

https://docs.google.com/document/d/1JZFKAGuVZ-8Vx8DLQDUVlRiuYm93o3VRFmplf31mRwc/edit?usp=sharing

**Comment by bensternthal** [comment]
@tobie perhaps this can be reviewed in next weeks CPC meeting? Note I'll only be able to join the last 30 minutes.

**Comment by bensternthal** [comment]
I moved the form from Google Docs into Google Forms https://forms.gle/ErrBo3cUeHKeEV56A, happy to rev on this in our next working session.

**Comment by bensternthal** [comment]
Given the state of the google form and the addition of the DEI question, I think this can be closed.
