### ISSUE TITLE
Anonymize Public Reporting Of Travel Fund Spend

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1166]
We recommend continuing to publish metrics about the CPCTF to Github however, we should limit the information to the following:

- Event
- Attendee Type
- Company / Independent
- Actual Amount Expensed
- Endorsed Working Group
- Diversity Information (e.g., Identify as an underrepresented minority)

This provides transparency on spend without revealing personally identifiable information about a requestor.

**Comment by tobie** [comment]
Fixed in #1230
