### ISSUE TITLE
Launch New Travel Fund Approval Process

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1167]
```[tasklist]
- [ ] #1154 
- [ ] #1164 
```

**Comment by tobie** [comment]
I think we should repatriate the fund policy and process to the CPC repo and archive the existing repo. What do people think?

**Comment by ljharb** [comment]
Yes, but not before the new process is fully set up.

**Comment by ovflowd** [comment]
> I think we should repatriate the fund policy and process to the CPC repo and archive the existing repo. What do people think?

I rather have a separate repo for the community-fund. Having everything on the cross-project-council might confuse the average audience just trying to get ahold of how to request for travel fund.

**Comment by ljharb** [comment]
that's a good point.

**Comment by tobie** [comment]
> I rather have a separate repo for the community-fund. Having everything on the cross-project-council might confuse the average audience just trying to get ahold of how to request for travel fund.

I think the argument can be made both ways: it's easier if everything is in the same repo vs. it's easier if everything has its own repo. Currently we're sitting in the middle of this, and that's not the best outcome, imho.

For example, everything related to the CoC is in the CPC repo, yet we could make the argument that it should be in its own repo.

Imho, we should opt for a direction here, and attempt some reasonable level of consistency.

I used to be pushing more towards having separate repos. However, over the past few years I'm leaning more towards grouping things. The problem I've seen with separate repos here is that (1) we regularly forget some of them exist and (2) it creates a bunch of extra work to get things in sync.

So my hunch would be to move things to a mono CPC repo, and provide shortcuts to specific entry points (CoC, travel fund, etc.) via subdomains (e.g. travel-fund.openjsf.org) like we already do for a number of other things (e.g. [code-of-conduct.openjsf.org](https://code-of-conduct.openjsf.org)).

**Comment by bensternthal** [comment]
I would support moving the travel fund docs to the main CPC repo.

**Comment by ovflowd** [comment]
If we transfer the travel fund docs over here, we might also want to make it very easy to point these docs to people who stumble upon this org just for the travel fund.

Like making it clear on the README. It also depends on how and where we point people for travel fund-related things.

Would the journey of someone requesting funding be from a form in the future? Or is it from the appointed docs?

**Comment by ljharb** [comment]
the CoC should definitely be in its own repo as well :-)

**Comment by joesepi** [comment]
We had a very productive CPC working session today and made good progress on the travel fund. Below is a summary.
 
[Travel Form](https://forms.gle/qQCd3Rhq223e1Cc37)
We reviewed the questions on the form and feel this is good enough to proceed. We can always adjust later. You may notice the DEI section in the form is currently empty -- we plan to add that portion back in very soon. Just awaiting some guidance around data retention if I remember correctly.
 
[Process Recommendations](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit)
The working session participants [recommend](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit#heading=h.baxa9cw1owrt) we define budgets per quarter with flexibility around things like rollover and perhaps specific event budgets (like collab summits)
The working session participants [recommend](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit#heading=h.qyg11a7kvot7) we approve travel fund requests every two weeks, likely as a part of the CPC meetings.
The working session participants used the form questions to develop a [V1 scoring rubric](https://docs.google.com/document/d/10Tl09Bw2820rQjeYoAPiltA7YkUUetNTK-gBlPa-r-o/edit#heading=h.fbxtnhs2b9da). We think this is a good place to start and recommend using the next working session to dive into assigning points/scoring
 
All of this is malleable as we move forward but this progress is great and starts to set us up nicely for next year.

**Comment by bensternthal** [comment]
PR for approval process is here https://github.com/openjs-foundation/cross-project-council/pull/1230

**Comment by tobie** [comment]
Can we close this? Do we want to archive the repo first and link to the new process?

**Comment by bensternthal** [comment]
Yep we can close, the other [repo](https://github.com/openjs-foundation/community-fund) was archived and a link added to the new process.
