### ISSUE TITLE
Develop Process For OpenJS To Handle Certificate Renewals

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1169]
Two projects require certificates (Node, Electron) on Mac & Windows. We would like a well-defined process for handling certificates for these and other projects, and we'd like LF IT to take responsibility for renewals. We want to avoid having certs purchased and maintained by individuals.

To accomplish this, we will need to:

- [x] Have OpenJS council review the applicable terms of the certificate vendors (e.g. Apple, Digicert) and verify they are acceptable
- [x] Have OpenJS council approve OpenJS delegating responsibility to LF IT
- [x] Have LF IT take on this responsibility 
- [x] Document the cert renewal proces

Note the electron certificates have the following expiration dates:

- Apple expires December 2024 
- Windows expires December 2023

**Comment by mhdawson** [comment]
+1, This is a good way for the foundation to add value for projects.

**Comment by PaulaPaul** [comment]
Circling back on this, how was the electron Windows certificate renewal handled?

**Comment by bensternthal** [comment]
@PaulaPaul I will write up the documentation for this shortly.
