### ISSUE TITLE
Archive tech-strategy

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#1172]
Much as I'd like the Foundation to have a clear mapping between the goals and how it supports the participants in the ecosystem through the https://github.com/openjs-foundation/tech-strategy this has been stalled and I don't see moving forward.

My suggestion is that we rename/archive the repository and remove any external links to it (if there are any remaining) so that people don't come across it.

**Comment by tobie** [comment]
CPC agrees to archive it as it is easily reversible if necessary.
