### ISSUE TITLE
Ask for additional Travel Budget

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#1178]
My understanding is that we've been told by the board to just ask for an increase in the Travel budget if we ever ran out (ie budget is can be adjusted if that was needed)

From what I understand we have run out and so we should consider asking for more for this year, and to have the budget for next year be bigger as well.

**Comment by mcollina** [comment]
We talked about this in the previous Board meeting, and there is no space in this year budget after the conferences and committed travel.

We'll try to expand it for next year.

**Comment by mhdawson** [comment]
Ok, still good to document that the CPC asked the board and the answer was `no`. 

Was there any discussion of how much we might be able to expand it next year?

**Comment by edsadr** [comment]
AFAIK this still needs to be discussed, there were some talks but I don't remember the board reaching a final decision, is an item that needs to be officially decided in the next board meeting cc @bensternthal

**Comment by mcollina** [comment]
@mhdawson there was no question from the CPC on this, so there was no "formal" response. We talked about it, and my comment here was about my understanding of the budget. We can get a formal answer for next meeting.

**Comment by mhdawson** [comment]
@mcollina thanks for the clarification. What's important to me is that we just don't assume an answer and get a formal answer to the question.

**Comment by tobie** [comment]
Suggestion to have a specific $ amount ask for the board by next board meeting (Oct. 23). Will be discussed during next working session.

**Comment by mhdawson** [comment]
We discussed in the CPC meeting today and agreed to ask for an additional 10k as a number which is not too big but would allow us to support travel for 4 or 5 people in the next few months if requests come it.

@mcollina @SaraJo can you take this ask to the Board?

**Comment by mcollina** [comment]
Will do

**Comment by joesepi** [comment]
I believe this was discussed at a recent board meeting. @mcollina @SaraJo can you share any info? Thanks!

**Comment by mhdawson** [comment]
This is in the minutes from the CPC meeting on

**Comment by mcollina** [comment]
Sorry about not engaging on this, I've been traveling for the past 5 weeks and I'm a bit behind on github issues (250 to go).

There is not more to add in a public setting. I'm happy to discuss it in the private part of the CPC meeting.
