### ISSUE TITLE
Revisit Emeritus Stage Definitions

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1185]
The Sovereign Tech Fund infrastructure project includes supporting sunsetting/emeritus projects.

As we look to audit our projects to see which (if any) might be emeritus, it's a good time to revisit the [current definition](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md#emeritus-stage) and see if we want to make any changes. 

From my perspective, I am hoping we could get a more precise definition of "active development" and the process for nominating and voting on a potential emeritus project. I think we should also look at the sunsetting checklist (per Tobie's suggestion) and think about any additional or changes to the infrastructure piece.

A potential example can be seen [here](https://www.opendaylight.org/about/lifecycle-releases). Specifically section 2.3.5:

> 2.3.5 Termination Review
> - Termination Proposal Posted for 2 weeks:
> - States reason for project termination being sought
> - Calls out impact on other project, users, communities, and how those will be mitigated
> - Indicates where the project would be archived
> - Can be initiated by vote of project committers
> - Can be initiated by TSC or PMC of containing project if there are either no remaining committers for the project or there have been no commits to the SCM in 18 months

**Comment by tobie** [comment]
Worth looking at the [Sunsetting Checklist](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md#v-sunsetting-checklist) on that same page too.

**Comment by PaulaPaul** [comment]
Happy to help move this forward @bensternthal

**Comment by PaulaPaul** [comment]
Tagging the notes from today's call here @bensternthal (so that I can keep them handy for next time) https://docs.google.com/document/d/1u2DbBRwOGdWLdV9wqM_X583xdR7XwgvklzYh9Yx03OE/edit?usp=sharing

**Comment by bensternthal** [comment]
Here is the WIP doc we'd like to review with the CPC. Once we get through some rounds of editing in Google we can create a PR to refine the content further.

https://docs.google.com/document/d/1HcKsUgw7EMSMueaNcl_VCC5tOJl8uF4aOW3dZpbpgjA/edit

**Comment by tobie** [comment]
This is great work! So glad to see this progressing like this.

--tobie

**Comment by ljharb** [comment]
Looks great overall! Although I notice under archival:
> Provide a clear explanation for why the project is being archived and, if possible, recommend alternatives or forks.

> Update the project's description and website link on GitHub to indicate that it is archived and where to find potential active forks or alternatives.

i don't notice anything similar under EOL. For example, I would assume that one possibility in both cases would be linking to long-term support providers when applicable?
