### ISSUE TITLE
Term of Service, Privacy Policy and cookie banner

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#1192]
Most websites nowadays must include:
- Term of Service
- Privacy Policy
- cookie banner (EU)

I would love for OpenJS to provide some templates to use.

(On top of that, it would be great to have a bit of a cheatsheet for projects to follow).

**Comment by tobie** [comment]
I think most of what you're asking for can be found here: https://github.com/openjs-foundation/artwork#copyright-notices-for-project-website-footers and is referenced from our IP Guideline.

**Comment by ljharb** [comment]
Do most software project websites collect any data, run a service, or need cookies at all such that any of those would be required?

**Comment by ovflowd** [comment]
> Do most software project websites collect any data, run a service, or need cookies at all such that any of those would be required?

I second @ljharb point here; I think this is a scarce situation for any open-source project website to have anything tracking-related at all... Even functional cookies.
