### ISSUE TITLE
Election: CPC Director

### ISSUE THREAD

**Issue by jasuarez90** [openjs-foundation/cross-project-council#1194]
This Issue tracks the election of the third CPC Director. Details about the role can be found in the [CPC charter](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/CPC-CHARTER.md#section-8-board-representation).

### **Nomination Process**

[Please complete this form](https://docs.google.com/forms/d/12lRUkXgRTaivXgCrOItfMH60mrZIYlaGOX3muorAc8A/edit).

### **Eligibility**

Nominees for this role must be an [Active OpenJS Collaborator](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/governance/GOVERNANCE.md#definition-of-an-active-openjs-collaborator) at the time of their selection, as defined in the CPC's Governance document.

### **Term**

Term begins November 28, 2023 and concludes November 27, 2024.

```[tasklist]
### Election Schedule
- [x] Nomination Period October 27-November 10
- [x] Voting Period Via Opavote November 13-November 17
- [x] Announcement of Election Winners November 20th
```

**Comment by tobie** [comment]
Hey @jasuarez90, same issue with this form. It's not publicly accessible.

**Comment by bensternthal** [comment]
The form is fixed and should be accessible.

**Comment by bensternthal** [comment]
Folks, since it looks like there were some permissions issues with the form, I have extended the nomination deadline to this Friday, November 10th.

**Comment by bensternthal** [comment]
Please join me in congratulating @joesepi on winning the 3rd CPC Director seat election!
