### ISSUE TITLE
Update Individual Membership Documentation

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1196]
The [individual membership documentation ](https://github.com/openjs-foundation/cross-project-council/blob/main/proposals/approved/INDIVIDUAL_MEMBERSHIP/INDIVIDUAL_MEMBERSHIP.md )is out of date and no longer accurate. 

I think the entirety of the document can be removed with a paragraph describing and linking to [JavaScriptLandia](https://javascriptlandia.com/).

**Comment by ovflowd** [comment]
Thanks for opening this, Ben 🫶
