### ISSUE TITLE
Discuss the Foundation's perspective on DEI in Wake of US Affirmative Action Ruling 

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#1197]

**Comment by ljharb** [comment]
My understanding is that the ruling only affected academic institutions, but the _implication_ is that any other non-military affirmative-action-ish policies, if challenged, would likely get the same ruling. Is that a reasonable tl;dr of the broader situation, or if not, what am I missing?

**Comment by PaulaPaul** [comment]
I think it's important not to over react to the ruling, and to be clear on the process and the reasons for our dei efforts. It is not against the law to have a dei program- https://www.dwt.com/blogs/employment-labor-and-benefits/2023/06/scotus-affirmative-action-dei-programs

**Comment by ljharb** [comment]
Affirmative Action in general isn't against the law either; that's not necessarily what a Supreme Court ruling, or this one, means.

**Comment by tobie** [comment]
This issue was opened following concerns expressed over the removal of DEI from the travel fund goals in #1188. Giving we're backing out of those, I suggest we close this issue once #1188 is closed.

**Comment by bnb** [comment]
my bad for editing, clicked a button that I didn't know what it did ("Add Tasklist") and it did stuff that I reverted 😛

**Comment by tobie** [comment]
Agreement to close it in the November 14 CPC meeting.
