### ISSUE TITLE
Election: CPC Vice Chair

### ISSUE THREAD

**Issue by jasuarez90** [openjs-foundation/cross-project-council#1198]
This Issue tracks the election of the CPC Vice Chair. Details about the role can be found in the [CPC charter](https://github.com/openjs-foundation/cross-project-council/blob/main/CPC-CHARTER.md#section-7-elections).

Nomination Process
[Please complete this form](https://docs.google.com/forms/d/e/1FAIpQLSdbvX5xDPDJqVbUTzT-wUY_Uu4FwbaRg2BFopkz_3M19op9GA/viewform?usp=sharing).

Eligibility
Nominees for this role must be a Regular or Voting member of the CPC, as defined in the CPC's Governance document.

Term
Term begins December 1, 2023 and concludes November 30, 2024.

```[tasklist]
### Election Schedule
- [x] Nomination Period November 2-November 10
- [x] Voting Period Via Opavote November 13-November 17
- [x] Announcement of Election Winners November 20th
```

**Comment by tobie** [comment]
Heads-up that (1) the eligibility for the role is to be a regular or voting CPC member (not just an active contributor), (2) the role is that of a vice chair, not co-chair, and (3) the role isn't a director role (so doesn't come with the duties and responsibilities a board director would have). I edited the post accordingly.

**Comment by jasuarez90** [comment]
Thank you!--Julian SuarezProject Coordinator , The Linux ***@***.*** | m: 919.610.5960On Nov 1, 2023, at 12:55 PM, Tobie Langel ***@***.***> wrote:﻿
Heads-up that (1) the eligibility for the role is to be a regular or voting CPC member (not just an active contributor), (2) the role is that of a vice chair, not co-chair, and (3) the role isn't a director role (so doesn't come with the duties and responsibilities a board director would have). I edited the post accordingly.

**Comment by tobie** [comment]
@jasuarez90 the form isn't public.

**Comment by bensternthal** [comment]
The form is fixed and should be accessible.

**Comment by tobie** [comment]
This seems to be a weird mix of the form for the board director role and the vice chair role.

**Comment by bensternthal** [comment]
@tobie indeed. I corrected and also adjusted the dates for the election.

**Comment by tobie** [comment]
Thanks @bensternthal!

**Comment by bensternthal** [comment]
Please join me in congratulating @tobie on winning the CPC Vice Chair election!
