### ISSUE TITLE
Google Season of Docs: Node.js Learn Material

### ISSUE THREAD

**Issue by ovflowd** [openjs-foundation/cross-project-council#1216]
Hey there 👋 I was a while (long while ago, since I haven't had time to open this issue sooner 😅) that we could bring the Google Season of Docs back; And I wanted to pivot an initial project for the Node.js Website Redesign, where we are redoing the existing Guides and creating new Learn material.

The Node.js Website Learn material is meant to be introductory and go through the basics of concepts of Node.js and technologies involving the Node.js architecture (such as ESM Loaders, Node.js Event Loop, etc)

I feel this is a perfect opportunity to have an intern to write technical content for us with Google's Season of Docs program.

I'm writing this issue to kickstart a discussion regarding how we could ingress the Google Season of Docs program (make OpenJS a participant project there) and if we want to; Not to mention:

- What were our prior experiences with the program?
- Is this something we want to run?
- What would be the requirements, prerequisites and sort of documentation (on how we would run this, and how projects might become eligible, mentoring eligibility, etc)
- Any other pending questions?

**Comment by PaulaPaul** [comment]
Looks like the 2024 program will spin up in January - I've joined the Season of Docs Announrement list so that I can find out when the applications open up for 2024. https://groups.google.com/g/season-of-docs-announce
Looks like an interesting program! I haven't been involved with it in the past and intrested to see how it works.

**Comment by mcollina** [comment]
I think we could apply for Fastify

**Comment by ovflowd** [comment]
> Looks like the 2024 program will spin up in January - I've joined the Season of Docs Announrement list so that I can find out when the applications open up for 2024. [groups.google.com/g/season-of-docs-announce](https://groups.google.com/g/season-of-docs-announce) Looks like an interesting program! I haven't been involved with it in the past and interested to see how it works.

I have been mentoring on GNOME's GSoC for the last 4 years and was an admin for their last year, not sure how GSoD is different, but would love to support you there with anything there :)

**Comment by joesepi** [comment]
See also: https://github.com/openjs-foundation/cross-project-council/tree/main/mentorship/2020/google-season-of-docs

**Comment by bensternthal** [comment]
Unfortunately, this year, we were not selected to participate.
