### ISSUE TITLE
2024 Google Summer Of Code

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1228]
The [2024 GSoC](https://summerofcode.withgoogle.com/programs/2024) application period for open-source projects will be **January 22 - Feb 6th**.

If this is something we want to participate in as the OpenJS Foundation, we'll need to assemble the following:

* A [list of ideas](https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list)
* [Mentors](https://google.github.io/gsocguides/mentor/) matched to the ideas
* Answers to the [short answer questions on the application](https://docs.google.com/document/d/1OL62tQtj72NB94gsEiu8DsqQGmCJgnhVKiKWXruGd0o/edit)

From Google:

> Starting in 2024 we will have small (~90 hour projects), medium (~175 hr projects) and large (~350 hour) projects available to GSoC contributors. Orgs should have medium and large projects available in their Project Ideas lists. Small project ideas are not required for orgs, but if the smaller size project works for your org they should  be included in your Organization’s Ideas List.

I'd like to recommend the following process. Please add any ideas or indicate willingness to be a mentor in comments on this thread **prior to February 2nd**. If we have enough ideas (per Google, at least four) and paired mentors on February 2nd to form a viable application, I will assemble the suggestions into an ideas page and submit the application prior to the program deadline.

Here are some reference documents regarding GSoC:

* [Mentor guide](https://google.github.io/gsocguides/mentor/)
* [How to define an ideas list](https://google.github.io/gsocguides/mentor/defining-a-project-ideas-list)
* [What makes a good mentor?](https://google.github.io/gsocguides/mentor/what-makes-a-good-mentor)
*  [HOWTO Write Project Proposals](http://wiki.inkscape.org/wiki/index.php/SOC_Writing_Project_Proposals)
* [Inkscape's Accepted Proposals](http://wiki.inkscape.org/wiki/index.php/SOC_Accepted_Proposals)
* [RedHat's experience](https://opensource.com/article/21/10/google-summer-code)

Finally, I know some projects apply to GSoC directly. This is of course wonderful and encouraged, especially if you have an internal process for matching ideas with mentors. The intent of this particular thread is to organize interest from any projects that don't plan to apply on their own and would like to use Foundation resources to help coordinate this process.

## Ideas

If you have a project idea, here's a template with the questions we'll need to answer on the application:

```
### Description

### Expected Outcome(s)

### Recommended Skills

### Potential mentors (at least two)

### Expected size of project 

### Difficulty (easy, medium, hard)

### Upstream Issue (URL):

```

## Mentoring

If you're willing to be a lead mentor or co-mentor for an idea someone else proposed, please add a comment to this thread and link to the idea you'd like to help with.

If you do volunteer, please ensure you can provide whatever level of mentorship you've offered should the idea be funded. This is to ensure we can meet our commitments to the students and to the program.

If you have any questions, please ask!

**Comment by ovflowd** [comment]
Hey @bensternthal are we applying for the Google Season of Docs or Google Summer of Code? Or both?

**Comment by bensternthal** [comment]
@ovflowd This ticket is specifically for Summer of Code. We can also join the Season of Docs program, but I haven't come across any announced dates. If you have any information on this, please share it with me.

**Comment by bensternthal** [comment]
Closing this out, we did not receive enough submissions to submit as an organization.
