### ISSUE TITLE
Emeritus Pass on Regular Members

### ISSUE THREAD

**Issue by bnb** [openjs-foundation/cross-project-council#1234]
Looks like there's quite a few people who have not been active or involved in the CPC who are still regular members. IMO because of the elevated access this gives, we should be restrictive with that access and have an activity requirement. I'd say literally _any_ activity in the last 6 months in the OpenJS Foundation repos should be a minimum requirement - I don't think we need to make it too complicated.

**Comment by dylans** [comment]
fwiw the regular meeting time rarely works well for me, so I've mostly stayed active with the event/conference side of things.

The simplicity of any activity at all seems fair.

**Comment by WaleedAshraf** [comment]
@bnb thanks for raising this. I was looking for if we have a process for Emeritus but couldn't find it.

**Comment by tobie** [comment]
In today's CPC, @ljharb offered to file a new issue to the CPC, @-mentioning CPC members who haven't been active for a while and providing them with context as to why we they would be moved to emeritus status, what they could do to prevent that, and what they could do should they want to become active again in the future.

**Comment by ljharb** [comment]
Here's the current list of Regular Members, with board members and the last 3 months of various meeting participants removed to the best of my knowledge:
- Abigail Cabunoc Mayes (@abbycabs)
- Abraham Jr Agiri (@codeekage)
- Antón Molleda (@molant)
- Ben Hutton (@relequestual)
- Ben Michel (@obensource)
- Christopher Hiller (@boneskull)
- Dhruv Jain (@maddhruv)
- Divy Tolia (@designmoreweb)
- Eemeli Aro (@eemeli)
- Even Stensberg (@evenstensberg)
- Kris Borchers (@kborchers)
- Marcin Hoppe (@MarcinHoppe)
- Mohammed Keyvanzadeh (@VoltrexKeyva)
- Nick O'Leary (@knolleary)
- Parris Lucas (@GrooveCS)
- Rifa Achrinza (@achrinza)
- Sara Chipps (@sarajo)
- Sendil Kumar (@sendilkumarn)
- Waleed Ashraf (@waleedashraf)
- Yagiz Nizipli (@anonrig)
 
 If you are on this list and prefer to remain a Regular Member, please comment here (or, attend an OpenJS meeting I'm in :-p ) and I'll cross you out. On Thursday 2/29, anyone remaining will be moved to Emeritus status, and can request to be re-added to the list by following the described [process](https://github.com/openjs-foundation/cross-project-council?tab=readme-ov-file#regular-members).

**Comment by evenstensberg** [comment]
Want to remain a member

**Comment by designMoreWeb** [comment]
I want to remain a member

**Comment by VoltrexKeyva** [comment]
I want to remain a member.

**Comment by anonrig** [comment]
I want to remain a member

**Comment by WaleedAshraf** [comment]
I want to remain a member.

**Comment by eemeli** [comment]
I want to remain a member. I don't really have the time to participate in many live meetings, but I try stay on top of activity in the repo.

**Comment by knolleary** [comment]
I would like to remain a member and will try to increase my participation in general activities.

**Comment by achrinza** [comment]
I would like to remain as member. Looking for more ways to contribute directly to OpenJSF's output moving forward.

**Comment by joesepi** [comment]
Perhaps we can add something to the dates and reminders file or check on this around elections?

**Comment by ljharb** [comment]
That sounds like a great idea.
