### ISSUE TITLE
Update/move jsf-clabot for new fdn

### ISSUE THREAD

**Issue by knolleary** [openjs-foundation/cross-project-council#124]
We make use of https://github.com/jsf-clabot in Node-RED and presume that will continue.

I haven't seen an item anywhere to track updating that bot for the new foundation - such as migrating its [repo from the JSF org](https://github.com/JSFoundation/cla-assistant) over to the new org, and its general branding.

Is there even a desire to keep that bot around in the new foundation? I know there has been discussions around CLA vs DCO going on. Would be good to get a plan in place for it either way.

**Comment by jorydotcom** [comment]
super duper - adding this to the checklist in #121

**Comment by ryanblock** [comment]
Just bumping this! We've continued to see issues with the (presumably older) version of CLA Assitant running on all our repos.

Please and thank you! 🙏🌈

**Comment by brianwarner** [comment]
Just confirming that I caught this, per the discussion in the CPC meeting.  We are looking at the best way to offer a CLA for projects which want to continue using one.  At a high level, here's what to expect from the process:

1. We're working with OpenJS Foundation's counsel to come up with draft guidance.
2. We'll review the guidance with the member legal counsel
3. We'll publish guidance for the projects.

And as always, if you want to talk through a specific question on the topic, you can ping me (bwarner@linuxfoundation.org) and I can help to find answers.

**Comment by ryanblock** [comment]
No movement here since late July, any news to share?

**Comment by brianwarner** [comment]
The replacement CLA text is on the agenda for approval at Friday's board
meeting. Once that's done, we will be able to get the new CLA tool online,
and simply decommission the old one.

**Comment by brianwarner** [comment]
Now that the [IP policy](https://ip-policy.openjsf.org), [individual CLA](https://individual-cla.openjsf.org), and [corporate CLAs](https://corporate-cla.openjsf.org) are all approved by the board, we can begin the process of converting projects over to EasyCLA.

Please note that per the IP policy, projects may choose whether to require a CLA.

To get started, email operations@openjsf.org.

**Comment by joesepi** [comment]
I believe we can close this now per @kborchers comment: https://github.com/openjs-foundation/cross-project-council/issues/453#issuecomment-579316522
