### ISSUE TITLE
Proposal To Move CPC Meetings Into LFX

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1244]
## Background

The issue tracks moving the CPC meetings into [LFX](https://lfx.linuxfoundation.org/). This was initially discussed in the CPC call on [2023-11-28](https://docs.google.com/document/d/1-ydQUy11mu7A0yY-nTDY7UtMIjEM2Zd8UMwarmG_U5A/edit). Since then, the platform has been reviewed with both @tobie & @joesepi .

## What Is Being Proposed

LF has incorporated a meeting management feature into the LFX platform, leading to the transition of all LF projects to this system for meeting coordination. We have already successfully migrated the OpenJS board meetings and OpenViz meetings to LFX, and are now looking to shift the CPC meetings to this platform.

## Why The Change

LF meetings is being rolled out by LF and is a requirement in 2024 for board/tac/tsc meetings.

## What Is Changing

Rather than manage the CPC meetings directly using Zoom, we would use the LFX platform. Folks will get a new calendar invite and have a new Zoom link. When people click this link they will be prompted either:

- Login using their LFX ID
- Proceed as a guest

After that, it is just a regular Zoom call.

## What Stays The Same

- Meetings remain public, anyone can join, you do not need an LFX account
- Meetings can be set to auto record
- Meetings can still be streamed via Zoom
- Meetings can appear in the public calendar
- Meetings will have a persistent Zoom link

## Benefits

- Enables easier meeting management and the ability to take and track attendance (over time)
- Allows meeting participants to see all LF meetings in LFX dashboard
- Recordings and transcripts will appear in dashboard
- Ability to designate alternative hosts/share host key with anyone
- Attendees can specify a preferred meeting email address
- Invite list can be based on committee list in LFX
- Zoom AI training was disabled on the enterprise account used for LFX

```[tasklist]
## Tasklist
- [ ] Remove old meetings from the public calendar, and cancel old meetings
- [ ] Create new CPC working session & CPC regular meetings in LFX
- [ ] Copy meetings to public calendar
- [ ] Update zoom link in templated github issued e.g. #1233
```

**Comment by PaulaPaul** [comment]
At the CPC working call, we chatted about the potential changes in calendar sync as something that might confuse/concern people, and @bensternthal answered all the questions, and also let everyone know that they could be added directly to the invitations once they are on the LFX calendar (avoiding the need to sync).  Having all the meetings in LFX will simplify my calendar syncing - thanks!

**Comment by tobie** [comment]
iirc this was discussed twice in the CPC. I feel like the concerns raised (notably around ability to join anonymously and keeping the same URL for the call across meetings) were properly addressed. We can go forward with this.

**Comment by bensternthal** [comment]
Meetings have been created in LFX, and old meetings have been removed.
