### ISSUE TITLE
2024 Google Season Of Docs

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1247]
The [2024 GSoD](https://developers.google.com/season-of-docs) application period for open-source organizations will be **February 22 - April 2nd**. See [timeline](https://developers.google.com/season-of-docs/docs/timeline#want_to_know_more).

If this is something we want to participate in as the OpenJS Foundation, we'll need to assemble a list of ideas. To do this, please open a pr adding your idea to this [doc](https://github.com/openjs-foundation/cross-project-council/blob/main/mentorship/2024/google-season-of-docs/README.md) prior to **March 15**.

**Comment by mcollina** [comment]
Node.js Undici would definitely need some help.

**Comment by bensternthal** [comment]
Unfortunately, this year, we were not selected to participate.
