### ISSUE TITLE
Looking for members interested in helping with the Annual Ecosystem Report

### ISSUE THREAD

**Issue by edsadr** [openjs-foundation/cross-project-council#1253]
For context, please take a look at: https://github.com/openjs-foundation/cross-project-council/tree/main/proposals/incubating/ANNUAL_ECOSYSTEM_REPORT

To make this proposal a reality, we would need a new collaboration space focused on creating the annual ecosystem report, which ideally should be done at the end of Q3 2024, and in the process, define all the guidelines and methodology for years to come. 

We will follow the process described here: https://github.com/openjs-foundation/cross-project-council/blob/main/collaboration-spaces/COLLABORATION_SPACE_PROGRESSION.md#ii-collaboration-space-proposal-process, so far working with @anfibiacreativa to make this happen.

We are currently seeking CPC members who are interested in contributing to this initiative. Some of the responsibilities will be:

- Participate in defining the scope, objectives, and methodology for the Annual Ecosystem Report.
- Contribute to data collection, analysis, and interpretation.
- assist in drafting, reviewing, and finalizing the report.
- Engage with the community to gather feedback and disseminate the findings.

**Comment by tobie** [comment]
Just skimmed through this. It looks intriguing; I'd love to understand the ecosystem better! My key questions are:

1. What are the goals and desired outcome of this project?
2. How does the proposed solution help meet those goals?
3. What other options are there to meet those goals and why was the proposed solution picked over them?

**Comment by mhdawson** [comment]
Sounds interesting to me.

**Comment by edsadr** [comment]
Hey @tobie 

Here are the answers:

> 1. What are the goals and desired outcome of this project?

The first goal is to create a standard process to get the feedback and thoughts of the end-users of the JS ecosystem.
The second goal is to create a standard report of that feedback and thoughts from the end-users, including also the latest news, roadmaps, and activities for the OSS projects associated with the foundation. 

We are currently lacking both mechanisms, and I think it is important for the foundation to work in that direction to foster a more connected relationship with our users.

> 2. How does the proposed solution help meet those goals?

The proposal will work to create the process from scratch to produce the instruments to provide the two-way communication channel with end-users and will establish a repeatable project for years to come.

> 3. What other options are there to meet those goals and why was the proposed solution picked over them?

This is the first proposal I am aware in that direction, ideas are welcome.

**Comment by tobie** [comment]
Thanks for answering my questions, @edsadr. I really like the idea of getting more info about our projects and how they're used. Some follow-up questions (to answer here or takeaway as input to this work, as you see fit):

4. In what way will this effort differ from [State of JavaScript](https://stateofjs.com/), [Stackoverflow's survey](https://survey.stackoverflow.co/2023/), or [State of Open Source survey](https://www.openlogic.com/resources/2023-state-open-source-report)?
5. What additional insights do we hope to gather?
6. How actionable will those insights be? Do we have buy-in from projects to actually consider end-user inputs? Are we planning on building end-user groups for certain projects? Or the foundation as a whole? Do you know of end-user groups in foundation projects or elsewhere (e.g. CNCF) and have you talked with those projects? Etc.
7. The initial project talks about gathering data from projects (notably roadmaps). Is this still something you're considering?
8. Beyond roadmaps, I'm fairly concerned about project sustainability and maintenance. Are these topics you're considering gather information about?
9. There are ongoing security efforts/inventory. Are you thinking about leveraging and surfacing this information too?
10. Have you considered data analysis tools like [Bitergia](https://github.com/bitergia) to help with this?

**Comment by italojs** [comment]
amazing project
do you already have a to-do list or some specific topic to discuss?

**Comment by edsadr** [comment]
Welcome @italojs

Thanks for your interest, this issue is for getting people to signup for the new collaboration space. If you want to join this effort, I would recommend you start attending the CPC meetings and once the collaboration space is created, we will invite you to attend the space meetings, there we will plan every task to execute.

**Comment by tobie** [comment]
@edsadr wrote:
> Would you be joining this space? I think your insights would be invaluable in shaping the initiative.

I like where you're taking this. I'll do my best to show-up but won't be taking a leadership/driving position (I just don't have the time).

**Comment by edsadr** [comment]
Ok, I will be requesting the creation of the Collaboration Space today. I will add everyone involved in this issue as part of the initial group and will use this issue to update on the progress. 

Thank you, everybody, for your interest.

**Comment by PaulaPaul** [comment]
Hello! @edsadr I'm interested in joining the collab space -
Thanks-

**Comment by mhdawson** [comment]
I'm interested in joining at least the first few calls to better understand the work the space will do.

**Comment by edsadr** [comment]
The PR is this one: https://github.com/openjs-foundation/cross-project-council/pull/1282 

once we get the report will add few issues there and we will move the discussions there, the first step will be to find a space to meet and start the initial planning

**Comment by joesepi** [comment]
This is moving forward
