### ISSUE TITLE
Exception for travel fund submission deadline for the Node.js collaboration summit

### ISSUE THREAD

**Issue by joyeecheung** [openjs-foundation/cross-project-council#1254]
It seems we overlooked the flexibility of the default deadline when we reviewed https://github.com/openjs-foundation/cross-project-council/pull/1230 which landed 3 weeks ago.

> The default deadline for submitting a community fund request is 8 weeks prior to the travel date to allow for all requests for an event to be reviewed at the same time.
> https://github.com/openjs-foundation/cross-project-council/pull/1230 

Due to organizational overhead, the Node.js collaboration summit was only [confirmed 2 weeks ago](https://github.com/openjs-foundation/summit/issues/387), which was already 8 weeks from the event dates, and we did not realize the impact of this new rule on the summit during the review. For this summit I propose that we make an exception for the deadline because:

1. The deadline rule is new. It's not yet tested on an event organized by an impact project before and is still up for discussion. And for the first event organized by an impact project, this is creating more obstacles than what it enables.
2. The travel fund is not used much in Q1 yet. There are no other major events where multiple requests would be expected in sight for Q1-Q2 either. 
3. Historically, Node.js makes use of most of the travel fund. The collaboration summit is also usually prioritized compared to events not organized by ourselves.
4. From the data collected from the attendance poll https://github.com/openjs-foundation/summit/issues/386 our estimate of the total amount requested would be within 10.5K at maximum. 8K if we only grant the requests to Node.js core collaborators, which should fit the budget easily (even if just assigning the unused leftover budget from Q1 to this event, it would be more than enough).

On what exception to make: given that it's time sensitive, it would be more efficient if we can assign a maximum collective budget to this collaboration summit (say 8K or 10.5K) and the Node.js TSC can take on the review and allocate them to applicants for this summit at our discretion, instead of having the CPC review the requests for each individual which only happen once a month. If we go over the budget, we can request additional reviews from the CPC for less prioritized applicants. The reason is:

1. This is an event organized by the project itself so there will be bulk requests. The CPC may not have clear idea about the applicants while the Node.js TSC already has more background about the eligibility of the applicants and what kind of impact the travel fund can sponsor for them.
2. It's getting close to the event and waiting for the monthly review is going to make things very difficult for the applicants to book travel. With the risk of abuse from granting travel requests to Node.js collaborators to attend a Node.js collaboration summit being extremely low, we would be able to make better use of the travel fund by granting it more efficiently through reviews from the Node.js TSC instead of waiting for another month. Otherwise it's likely that the funds would not be used for supporting the collaboration summit at all and sit in idle, which is against the purpose of the travel fund and is a win for no one.

**Comment by joyeecheung** [comment]
cc @joesepi @mcollina @bensternthal

**Comment by mcollina** [comment]
+1 for me.

**Comment by Trott** [comment]
Given the facts of the matter here, I'm certainly in favor loosening or eliminating the 8-week rule for this event.

**Comment by tobie** [comment]
Yeah, as a matter of policy, we should make it clear to everyone, always, that we're outcome-focused, not process-focused. If a rule creates undesirable outcomes, we make exceptions and then fix it. Worth noting here, btw, that the 8-week deadline is described as "default", hence suggesting it can be moved to match requirements.

Let's discuss the rest of the issue (delegating to the Node TSC and providing an envelope) during today's call.

**Comment by mhdawson** [comment]
+1 from me as well.

**Comment by ovflowd** [comment]
+1 and we should expedite this

**Comment by joyeecheung** [comment]
What's the conclusion from the CPC meeting?

**Comment by ovflowd** [comment]
> What's the conclusion from the CPC meeting?

@joyeecheung, Robin should be reaching you out soon 🙇

**Comment by joyeecheung** [comment]
I just need to know whether we can tell collaborators that the deadline is lifted for this summit and they should apply now. This is time sensitive.

**Comment by ljharb** [comment]
I'd think they should be applying regardless, just in case.

**Comment by ovflowd** [comment]
> I just need to know whether we can tell collaborators that the deadline is lifted for this summit and they should apply now. This is time sensitive.

Yes, pleas, they should apply, definitely.

**Comment by tobie** [comment]
Conclusion of the CPC meeting today was:

1. We lifted the deadline, so folks are welcomed to apply beyond the 8-week deadline.
2. However, folks should apply as soon as possible, and ideally **before Tuesday Feb 27**. There are limited funds and we will be going through all of the requests during the CPC working session next week. Requests made after this date will still be considered but might not received funding even if they would otherwise have been electable.
3. Delegating request review to project TSCs would add overhead and require additional process to be decided and implemented. The CPC decided to go-ahead with the process as planned and revisit if it did appear that the CPC was a bottleneck. To make sure requests are addressed on time, the CPC has decided to address requests weekly for now. The CPC also noted that it is composed for a large part of project representatives and that these should make sure to attend CPC meetings ahead of collab summits to help assess fund requests.
4. That said, it would be really useful to have a sense of the fund expected to be needed by the different projects for collab summit. @rginn will reach out to projects and ask for yearly projections so that the CPC can plan accordingly and let projects know whether their needs are feasible or not.

**Comment by joyeecheung** [comment]
Thanks, I'll send an email to those who answered about travel fund support in the attendance poll and suggest them to submit the request before Feb 27.

**Comment by tobie** [comment]
We're tracking fund estimation requests in https://github.com/openjs-foundation/cross-project-council/issues/1181, so I'll go ahead and close this. Feel free to reopen or file a new issue if you feel like we haven't properly addressed this.
