### ISSUE TITLE
Document best practices for community health files

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#1263]
Some suggestions to start the conversation:

## For single-repo projects
- `CODE_OF_CONDUCT.md` pointing to https://code-of-conduct.openjsf.org
- `CHARTER.md`
- `SECURITY.md`
- `GOVERNANCE.md` ?

## For orgs
- `.github`
  - `CODE_OF_CONDUCT.md` pointing to https://code-of-conduct.openjsf.org
- `governance` / `tsc` repo with:
  - `CHARTER.md`
  - `SECURITY.md`
  - `GOVERNANCE.md`

**Comment by sheplu** [comment]
in an org, the `.github` repository seems to be a good idea for all files that would be shared like the CoC and Security. 
Other files like `CHARTER` or `GOVERNANCE` are not "shared" in the same way.

What would also be the recommendation for other documents, like the Contributing? Or Triager? Especially for large organization?

**Comment by ljharb** [comment]
I'd assume any conventionally named repo - "admin", "tsc", something like that? nvm only has one repo of consequence, so i just stuck those files in the nvm repo.

**Comment by tobie** [comment]
CPC meeting update: Express is offering to be a guinea pig for this. Seems it would be useful to have a joint CPC / Express working session to iron issues out and write down recommendations in the CPC repo / onboarding checklist.

**Comment by ctcpip** [comment]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by tobie** [comment]
CPC call: Let's go with a simple version based on the GH docs. The idea is to provide info to onboarding project much like the IP guidelines do. Should be linked from the onboarding checklist.

**Comment by ctcpip** [comment]
I'll take the first stab at this

**Comment by ctcpip** [comment]
requesting the creation of a `.github` repo for the `openjs-foundation` organization
