### ISSUE TITLE
Update Onboarding Checklist To Include Contribution Agreement

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1264]
As part of researching project onboarding at OpenJS I realized that the step of signing a contribution agreement is not included in the checklist.

This issue tracks adding this item.

**Comment by tobie** [comment]
That's for individuals though, not the project itself, right?

Or is this for trademarks?

**Comment by bensternthal** [comment]
It's the "[Project Contribution Agreement](https://docs.google.com/document/d/151tCHoS84PYpA2T-s7Wk6Us2Pv9tWJfa_C6XrBoHJto/edit?usp=sharing)", it is what transfers the trademarks, accounts, and limited power of attorney.

This has been a practice for quite some time, I just noticed it was not clearly documented anywhere.

**Comment by tobie** [comment]
Still todo:

- [ ] update https://github.com/openjs-foundation/project-status/blob/HEAD/.github/ISSUE_TEMPLATE/00-project-onboarding-checklist-template.md
