### ISSUE TITLE
Create new Ecosystem Sustainability Program

### ISSUE THREAD

**Issue by rginn** [openjs-foundation/cross-project-council#1277]
OpenJS Foundation is proposing a new Ecosystem Sustainability Program (ESP) to generate a new revenue stream to underwrite the myriad of activities required to sustain our projects. The ESP would further our OpenJS mission for security and sustainability for the ecosystem.

ESP partners would provide commercial services for security fixes to OpenJS-hosted projects that are unsupported because they are archived, end-of-life, or are older versions of current projects. Working in partnership with the Foundation and our participating projects, ESP partners would offer a revenue share based on enterprise sales.

HeroDevs is the first ESP provider and the inspiration for this program:
- HeroDevs is offering a significant percentage revenue share to OpenJS on all official OpenJS Foundation projects enrolled in the program. 
- Revenue would be based on HeroDev's enterprise customer billing and be split between OpenJS-hosted projects’ maintainers/TSCs to manage and to the Foundation.
- HeroDevs will provide public notifications for critical CVEs after working with project authors to fix issues that they find.

Project maintainers are able to continue providing public support to any version of their software, including versions covered by an ESP partner, without constraint.

The ESP is non-exclusive for providers that can provide credible technical support to projects. It would be open to any provider based on the following requirements:
- Gold or Platinum member of OpenJS.
- Co-marketing together with trademark license agreement.
- Endorsed/sponsored by OSS project TSC/Core team, if applicable. 
- Endorsed/sponsored by the CPC, if the project is abandoned (in this case, all proceedings would go to the Foundation).

Participating projects would leverage the LFX Crowdfunding platform, to receive and manage funds transparently. 

The OpenJS Board of Directors has discussed the ESP and supports this new initiative pending approval from the CPC.

Support from the CPC and our hosted projects are essential to the success of this program.
- Project endorsement is critical because marketing is contingent on projects’ adding website banners and links.
- Most OpenJS projects would need to set up a budget governance model that the CPC will drive with support from OpenJS staff.

A primary advantage to the ESP program is making the Foundation less dependent on membership fees. The 5% allocated to the Foundation would help cover project supporting activities including:
- Legal (IP management, IP management, Trademark registration/renewals/defense, Domain registration & websites, Compliance: privacy, antitrust & export control) 
- Infrastructure support (CI/CD, CDN, GitHub)
- Community forums (Slack & Discord)
- Meeting infrastructure (Zoom, YouTube)
- Access to security experts / Security audits
- Research
- Marketing / Communications / Analyst Relations (events/collab summits, awards, blogging, case studies, dev profiles, content development, videos, paid advertising, graphic design, SWAG)
- Budget host and management
- Affiliate memberships with Standards orgs
- Training: online and workshops
- Certification: testing platform, proctoring, SME for content, program management
- Code of Conduct and moderation management
- Budget and finance management including audits and taxes
- HR support
- Staff support

**Comment by dylans** [comment]
I think this is a great idea. My only complaint is that this didn't exist 10 years ago!

**Comment by wesleytodd** [comment]
Love this. I think even with the trade-offs of patches being private and proprietary this partnership sounds valuable to projects and users. I do think that there are a lot of questions to answer and a detailed FAQ and robust set of example situations should be provided before this is finalized.

**Comment by edsadr** [comment]
On behalf of NodeSource, I would like to express publicly our enthusiasm and strong interest in participating in the Ecosystem Sustainability Program (ESP) proposed here. 

NodeSource has been deeply committed to the Node.js ecosystem for many years, and we believe that this initiative aligns perfectly with our mission to support and sustain the growth and security of Node.js and related projects.

Our dedication to the Node.js community is evident through our continuous contributions, support, and engagement. We understand the importance of maintaining a healthy and secure ecosystem, especially for projects that are critical to the infrastructure of countless applications worldwide.

**Comment by tobie** [comment]
Discussed in the CPC today. There was consensus in the CPC call to move ahead with this but we would like to formalize the CPC decision. If you want to object to this moving forward, please add a thumb down (👎) to this comment and provide a reason for objecting below. Thumbs up in favor aren't required but are appreciated.

**Comment by mhdawson** [comment]
+1 from me. Adding  as a comment because after some number you lose the ability to easily see who added their thumbs up in the reaction

**Comment by UlisesGascon** [comment]
+1 from me, following Michael's advice

**Comment by rginn** [comment]
The ESP partner program has been approved by the CPC and the Board. We'll be officially announcing the program on Tuesday, May 21. We'll be following up with the projects on next steps, and the CPC on related issues, such as best practices for managing project funding contributions.

**Comment by chadwhitacre** [comment]
"[HeroDevs Joins OpenJS Foundation’s Ecosystem Sustainability Program As First Partner](https://www.herodevs.com/blog-posts/herodevs-joins-openjs-foundations-ecosystem-sustainability-program-as-first-partner)"  🥳 🎉 ([X](https://x.com/herodevs/status/1792952636544626897))

Also seeing https://openjsf.org/ecosystem-sustainability-program. 👍 Congrats, all! This is wonderful to see! 🙌

**Comment by bensternthal** [comment]
Closing this issue as we are moving forward with individual projects. Thanks to everyone who collaborated on this work!!
