### ISSUE TITLE
Create Proposal For: Node.js Learn -- Creating World-class Learning material for Node.js

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1278]
@ovflowd In yesterday's CPC session we decided to move forward with your proposal "Node.js Learn -- Creating World-class Learning material for Node.js" \o/

The next step is to submit the formal project proposal to Google prior to [April 2nd](https://developers.google.com/season-of-docs/docs/timeline).

To submit the project I will need you to expand your proposal following [Google's template](https://developers.google.com/season-of-docs/docs/org-proposal-template). I think we can put your proposal [here](https://github.com/openjs-foundation/cross-project-council/tree/main/mentorship/2024/google-season-of-docs) as a standalone file.  Please reach out if you need help and/or if you want to complete this together in a working session.

**Comment by bensternthal** [comment]
@ovflowd I'll reach out via slack.

**Comment by anfibiacreativa** [comment]
This is something I'm interested in helping with.
