### ISSUE TITLE
Revisit CPC meeting times

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#1289]
I am no longer able to attend the 2pm ET meeting and working sessions.

Additionally we have folks who have joined the efforts somewhat recently who are in different time zones that make it harder for them to engage as well.

Let's figure out some new meeting times?

**Comment by anfibiacreativa** [comment]
Thank you for opening the issue, Joe. It's been very hard for me as you mention, to attend due to work meeting related conflicts and how late the 2pm ET meeting is in CET hours. I know time-zones are really hard to find work-arounds for, that are a fit for everyone. An idea is to alternate the times to an early PST and a late PST session. That would more or less give the chance for everyone to participate of a session, even if fortnightly.

**Comment by joesepi** [comment]
We discussed this in today's working session. Rather than spinning up a doodle poll or a spreadsheet, we are going to propose a handful of options and look for emoji on the options. However, please feel free to comment here if you would prefer a different option and we can consider those as well.

Put one or multiple emojis on this comment reflecting your preferences, according to the emoji in each option:

🎉  - 11AM ET (no alternate, just one meeting time every week)
👍  - 11AM ET + 12PM ET (only one hour difference, but could be helpful for PST folks)
🚀  - 11AM ET + 1PM ET (a little better for PST)
😄  - 11AM ET + 2PM ET (keep current later time and move earlier time one hour forward)

Reminder: working sessions happen at the same time as the meeting of the previous week, so keep that in mind.

**Comment by ljharb** [comment]
11AM ET is 8AM PT, which conflicts with me taking my kids to school, so i wouldn't be able to make any of those.

**Comment by tobie** [comment]
To be clear, is this still Tuesdays?

**Comment by joesepi** [comment]
> To be clear, is this still Tuesdays? I can't make 11AM ET on Tuesdays either.

Yes. Thanks for clarifying. I updated my comment.

**Comment by ovflowd** [comment]
I'm not sure I got the options, are we suggesting two meetings to happen at the same day?

**Comment by joesepi** [comment]
We discussed the meeting times during a couple meetings and were unable to find a change that would make things better for the larger group of people attending or interested in attending. 

Basically, the thinking is that not everyone will be able to make both times but hopefully one of the times works for individuals.

We are open to revisiting this issue any time in the future.
