### ISSUE TITLE
Review meeting times

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#129]
Current meeting times are 9 EST and 2EST on Mondays.

Please comment/discuss if these times still work for the team?

Edit (mborins)

The Sheet: https://docs.google.com/spreadsheets/d/12e8lN9ywi-2kAtcW08WS3x3S-6TXiOO8_yxs3j0Sm2E/edit#gid=0

**Comment by keywordnew** [comment]
Suggestion to amplify issue #123 for more meeting chairs.

With the bootstrap meetings now intended to morph into CPC meetings over time, we'd benefit from improved timezone coverage. With chairs from different timezones we'd be able to better include people not in UTC-8 through UTC+4.

**Comment by keywordnew** [comment]
2 EST still works for me :)

**Comment by mcollina** [comment]
The time still work for me. Mondays are generically bad as I'm typically traveling to some place on Monday, and I end up being on flights.

Also, do we still need _weekly_ bootstrap/CPC meetings?

**Comment by jorydotcom** [comment]
Per our meeting today, I've updated James' awesome spreadsheet to start collecting availability for new times. 

Please take a look at [this google spreadsheet](https://docs.google.com/spreadsheets/d/12e8lN9ywi-2kAtcW08WS3x3S-6TXiOO8_yxs3j0Sm2E/edit#gid=0) and add your availability for Tuesdays and Wednesdays - note that there are two sheets in the same doc.

**Comment by bnb** [comment]
We're setting a deadline of May 1st to close the spreadsheet above 👍

**Comment by mhdawson** [comment]
I believe we agreed to change to 12 EST on Wednesdays at least for a start.  One note is that 1/3 weeks it will overlap with the Node.js TSC meeting.

**Comment by mhdawson** [comment]
I've updated the calendar to reflect the new time and updated the generator so that it should create the meeting issue next Monday.

**Comment by evenstensberg** [comment]
Whichever time works for webpack, we're adaptive as long as it's european times

**Comment by joesepi** [comment]
We have discussed this in the last couple meetings (every meeting?) and I suggested that I propose some time pairings. In the times I am suggesting, I aimed to keep them on the same day, but maybe others would prefer alternating days and times. Also, 1600 was best on both days, so I worked on pairings with that time (except one wildcard). All times below in UTC.

Please vote with emoji

**Wednesday**

| emoji | time1 (rank) | time2 (rank) |
| --- | --- | --- |
| 👍 | 1600 (84) | 1900 (81) |
| ❤ | 1400 (73) | 2000 (79) |

**Tuesday**

| emoji | time1 (rank) | time2 (rank) |
| --- | --- | --- |
| 🚀 | 1600 (89) | 2100 (84) |
| 🎉 | 1600 (89) | 1900 (80) |
| 😄 | 1600 (89) |  1800 (84) |

**Comment by boneskull** [comment]
This might come in handy: https://www.timeanddate.com/worldclock/converter.html

**Comment by mhdawson** [comment]
The TSC meeting shared  Wed 16,19 we would just need to ensure we schedule so they oppose as insterad  of lining up.

**Comment by joesepi** [comment]
Documenting what was discussed and decided on at today's meeting.

We are moving the weekly Cross Project Council meeting to Tuesdays, alternating between 1600 and 1800 UTC, starting next Tuesday at 1800 UTC. 🎉 

@brianwarner will work with @mhdawson to get calendar updated and such.

/cc @openjs-foundation/cpc-voting-members @openjs-foundation/cpc-regular-members
