### ISSUE TITLE
Selection of new Code of Conduct Team Community Members

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#1298]
We recently revamped the [code of conduct](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md), its associated [policies](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/COC_POLICY.md) and [team charter](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/COC_TEAM_CHARTER.md) and are ready to run the yearly [selection process](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/COC_TEAM_CHARTER.md#member-selection) to bring in new people to the Code of Conduct Team.

The [responsibilities](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/COC_TEAM_CHARTER.md#responsibilities) of the CoC Team are outlined in its charter along with [eligibility requirements](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/COC_TEAM_CHARTER.md#eligibility) for team members.

We are looking for 3 [primary community members](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/COC_TEAM_CHARTER.md#primary-members) and a variable number of [alternate community members](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/COC_TEAM_CHARTER.md#alternate-community-members). (Alternate members get called in when there aren't enough primary members available to manage a particular incident.)

Please self-nominate by commenting below and/or encourage someone you think would be a good candidate for this role. You do not need to be part of the CPC to self-nominate. Please indicate whether you'd like to be selected for a primary role, and alternate role, or are OK with both. Please confirm that you understand the eligibility requirements and agree with them.

**Comment by tobie** [comment]
I'd like to self-nonimate as an alternate community member. I have read the eligibility requirements and agree with them.

**Comment by ljharb** [comment]
I'd like to self-nominate as a primary community member (or alternate, as a fallback).

**Comment by benjamingr** [comment]
Happy to self nominate reference https://github.com/openjs-foundation/cross-project-council/issues/985#issuecomment-1360048060

**Comment by tobie** [comment]
@benjamingr: as a primary, alternate member, or either?

**Comment by benjamingr** [comment]
Whatever helps honestly, moderation isn't usually a high-capacity high-demand job but typically involves bursts of discussions and janitorial work.

I was provided training by the foundation (back when it was still the Node.js foundation!) as well as 8 years of experience as a moderator in Node.js and I am happy to contribute at whatever capacity helps.

**Comment by mcollina** [comment]
I'm happy to serve on this one.

**Comment by anfibiacreativa** [comment]
I'm happy to be selected as an alternate member. I have read the requirements.

**Comment by PaulaPaul** [comment]
Hello, I understand the responsibilities and eligibility requirements, and am happy to serve as an alternate (ready to serve if selected and called).

**Comment by ctcpip** [comment]
`Iff` there are not enough volunteers, I am happy to help. (For either role.)

**Comment by ovflowd** [comment]
I'd also would love to serve as an alternate, since I'm already a moderator on the Node.js project, and I understand that often there might be conflict of interests/or not enough time for me to act as a main moderator :)

**Comment by mlaurencin** [comment]
I am happy to serve as an alternate member and have read the requirements.

**Comment by nektro** [comment]
I'd like to self-nonimate as an alternate community member. I have read the eligibility requirements and agree with them.

**Comment by ovflowd** [comment]
Awesome to see folk's from different projects nominating! Awesome to see more diversity here 😍

**Comment by benjamingr** [comment]
This is the longest nomination process I've ever participated in. I feel like I've self-nominated ~[2 years ago](https://github.com/openjs-foundation/cross-project-council/issues/985) and nothing has happened.

Some presidents had shorter election campaigns than this volunteer request for janitorial work 😅  

What happened here?

**Comment by ovflowd** [comment]
We should prioritise this to the next Working Session. cc @bensternthal

**Comment by tobie** [comment]
> What happened here?

Organizing this is… volunteer work (same as maintaining open source).

**Comment by benjamingr** [comment]
> Organizing this is… volunteer work (same as maintaining open source).

As everything else here :] Other projects genuinely don't get enough spam/CoC complaints/issues for this to become pressing?

**Comment by tobie** [comment]
To be clear, the foundation has had a functioning CoC team all along. It's agreeing on the terms of the new, wider CoC team which took time and delayed this selection process.

**Comment by ljharb** [comment]
That said, i also believe/suspect node is an outlier here due to its popularity.

**Comment by joesepi** [comment]
Meeting notes:
  * Private session two weeks ago wanting to choose team members but had issues to work through still
  * Working session last week revealed that the process was not broken but the decision/selection is particularly difficult for private reasons.
  * Will work on this more today in private session today

**Comment by tobie** [comment]
@mcollina: to be clear, as alternate or primary or both?

**Comment by tobie** [comment]
Summarizing the results of the self-nomination process below (by alphabetic order):

| Name |  Github handle |  Affiliation |  Primary |  Alternate |
|---|---|---|---|---|
| Benjamin Gruenbaum |  @benjamingr |  Eon |  ✅ |  ✅ |
| Chris de Almeida |  @ctcpip |  IBM |  ✅ |  ✅ |
| Claudio Wunder |  @ovflowd |  HubSpot |  ❌ |  ✅ |
| Jordan Harband |  @ljharb |  HeroDevs |  ✅ |  ✅ |
| Matteo Collina |  @mcollina |  Platformatic |  ? |  ✅ |
| Meghan Denny |  @nektro |  Oven |  ❌ |  ✅ |
| Michaela Laurencin |  @mlaurencin |  Microsoft |  ❌ |  ✅ |
| Natalia Venditto |  @anfibiacreativa |  Microsoft |  ❌ |  ✅ |
| Paula Paul |  @PaulaPaul |  Greyshore Associates |  ❌ |  ✅ |
| Tobie Langel |  @tobie |  UnlockOpen |  ❌ |  ✅ |

Worth noting that per the CoC Team's charter, @mcollina and @benjamingr wouldn't be able to both serve as primary community members as _"No two primary community members can work for the same employer nor hold leadership positions in the same OpenJSF project"_ and they are both on the Node TSC.

I'd also want to point out that the CoC Team's Charter states the _"CPC is responsible for ensuring that the CoC Team is as representative and diverse as possible"_  and that, _"to do so, the CPC commits to reach out proactively to individuals from underrepresented groups."_ In light of the above, I note that candidates for primary roles aren't exactly the most diverse group of people (no offense implied) and encourage all other candidates to consider stepping up as primary members.

**Comment by benjamingr** [comment]
@mcollina let me know if you prefer to be primary or alternate and I'll happily do the other one or whatever else works.

**Comment by mcollina** [comment]
I’m happy to be the alternate.

**Comment by PaulaPaul** [comment]
I am also happy to be considered as primary if there is a need.
