### ISSUE TITLE
2024 Foundation Project Health Survey

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1313]
As part of our new annual review process, we are distributing this year's Project Health Survey.

More information about the survey can be found [here](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md#annual-foundation-project-health-survey).

We kindly request that CPC members respond to the following form by June 28th.

https://forms.gle/8xCap7HooCGsRR3W6

**Comment by bensternthal** [comment]
Next steps on this one:

1. Regroup with @UlisesGascon and @PaulaPaul we only got 9 responses
2. We need to understand why folks did not respond, did they not get the note or are they no longer active, or something else?
3. We need to digest the responses we did receive and share back to the CPC

**Comment by bensternthal** [comment]
## Summary

The 2024 OpenJS CPC Heartbeat Survey aimed to evaluate the activity levels and satisfaction of various projects within the OpenJS Foundation. The survey received feedback from 9 projects, 25 projects did not respond.

### Key Findings

- **Activity Levels:** The survey assessed the activity levels of the responding projects, with most projects rating their activity as moderate to active (2.78 average out of 3).
- **Support Satisfaction:** Projects generally expressed moderate to very happy satisfaction with the support from the OpenJS Foundation and the Cross Project Council (CPC) (2.78 average out of 3).
- **Freeform Feedback:** Respondents highlighted concerns about balancing the needs of projects, the community, and the foundation. Specific concerns included the handling of the LFX platform and the need for better promotion of at-large projects. Positive feedback included appreciation for the support provided by the CPC, especially for project reboots.

### Concerns and Areas for Improvement

- **Participation**: A low response rate, with only 9 out of 34 projects responding, raised concerns about engagement. Suggestions for increasing participation included offering small incentives such as gift cards or sponsorships.
- **Project Activity:** There is a need to explore how to increase the activity levels of the projects, particularly for those who did not respond to the survey.
- **Foundation Satisfaction:** To improve satisfaction, more detailed feedback and expectations from the projects could be collected through interviews or focused discussions.
- **Security Audits:** Audits were a mixed bag with at least one project reporting an issue with an audit vendor


## Survey Responses

### Projects That Responded (9)

nvm
jQuery
Express
jQuery
Appium
Fastify
Express
Electron
Node.js

### Projects That Did Not Respond (25)

AMP
architect
Dojo
ESLint
Esprima
Globalize
Grunt
Interledger.js
Intern
JerryScript
Jest
kepler.gl
Lodash
LoopBack
Marko
messageformat
Mocha
Moment
NativeScript
Node-Red
QUnit
vis.gl
WebdriverIO
webhint


| Project Name | How active has the project been this year? (Scale of 1-3) | How happy have you been with the support from the OpenJS Foundation and Cross Project Council (Scale of 1-3)|
|--------------|-------------------------------------------|-------------------------------------------------------------------------------------------------|
| nvm          | 2                                         | 3                                                                                               |
| jQuery       | 2                                         | 3                                                                                               |
| Express      | 3                                         | 3                                                                                               |
| jQuery       | 3                                         | 3                                                                                               |
| Appium       | 3                                         | 3                                                                                               |
| Fastify      | 3                                         | 2                                                                                               |
| Express      | 3                                         | 3                                                                                               |
| Electron     | 3                                         | 2                                                                                               |
| Node.js      | 3                                         | 3                                                                                               |


### Free Form Responsed (Slightly Edited)

#### Do you have any concerns or questions for the CPC?

> Just that I want to continue discussions about hero devs.

> I like how active things seem to be lately, but I think that we are still trying to find our balance between serving the projects, serving the community, and serving the foundation. I would love to see some more clear guidance on how the foundation balances and makes tradeoffs for this. For example, I am glad we are not funding another conference in partnership with the linux foundation, but I think that things like the LFX platform stuff still feels a bit like a tradeoff which many project might struggle with. Especially ones where the leadership is not as involved on the foundation level.

> More things could be done to help promote at-large projects. On top the experience with the audit was worse than expected...

#### Any Other Feedback?

> Great job team, I seriously look forward to continuing the great work everyone is doing.

> We are very thankful for the support from the OpenJS CPC when we rebooted the project at the beginning of this year.

**Comment by dylans** [comment]
For what it's worth I'm so overloaded with notifications and communications that I didn't even notice the survey until randomly seeing this email.

In general I think everyone is drowning in a cesspool of noise/spam and I'm not sure of the best way to address that. But I would have been happy to answer the survey had I noticed it, and a gift card or sponsorship wouldn't have made a difference if I didn't notice it. :(

**Comment by shirakaba** [comment]
Agreed, I did not engage as I was not tagged in any issue, nor emailed anything. In general, my engagement with CPC proceedings is low because the ratio of signal to noise in the CPC repo feels low, and because our committee members don't often raise any Foundation-related matters.
