### ISSUE TITLE
Proposal for a dedicated sustainability collab space

### ISSUE THREAD

**Issue by UlisesGascon** [openjs-foundation/cross-project-council#1357]
It seems like there's a growing interest across various projects in exploring sustainable practices ( https://github.com/expressjs/discussions/issues/228, https://github.com/nodejs/next-10/issues/273). Additionally, the OpenJS Foundation has made significant strides with the new Ecosystem Sustainability Program (ESP) (https://github.com/openjs-foundation/cross-project-council/issues/1277).

Given these developments, I propose we create a dedicated space where we can collectively share our experiences and ideas concerning sustainability. This could greatly enhance our approach to securing long-term viability and support for all OpenJS projects.

---

**Our Goals**
- Ensure long-term sustainability and support ambitious growth objectives for all OpenJS projects.
- Establish, document, and promote best practices in funding and resource management in a transparent and inclusive manner.

**Desired Outcomes**
- Enhance the financial stability and resource availability for OpenJS projects, thereby strengthening the software supply chain.
- Increase financial contributions (grants, donations, and sponsorships) from public, private, and philanthropic organizations.
- Strengthen partnerships between funding bodies and JavaScript project maintainers to foster innovative sustainability solutions.

---

I look forward to your thoughts and feedback on this proposal!

**Comment by voxpelli** [comment]
If its only to focus on the financial / funding aspects, then I think it should be a "funding collab space"

Sustainable maintenance involves much more than funding – it involves mental and social well being, regrowth, contributions, ecosystem support, tech and issue debt etc – funding is a means to an end when it comes to sustainable maintenance and a collab space that focuses on it should brand itself with "funding" rather than claiming the entire sustainability space.

**Comment by voxpelli** [comment]
Relatedly, I'm currently drafting on a `Collective Funds Guidelines` with initial targets being `mocha`(OpenJSF-project) and `neostandard` (not an OpenJSF-project) that other has also shown interest in – would love to collab on it when the first draft is complete 👍

**Comment by ljharb** [comment]
In capitalism, virtually all of those things are gated by funding - i think sustainability is the right term (so the goal remains front and center) and funding is the right focus (as the primary means of achieving it).

**Comment by UlisesGascon** [comment]
@voxpelli you made a great point!

Actually, while the current trigger is related to funding aspects, I think we have a lot of room for mental and social well being, regrowth, contributions, ecosystem support, tech and issue debt etc :+1:. I will rewrite the goals and Desired Outcomes to include them.

**Comment by tobie** [comment]
Discussed in today's CPC call. General agreement to move forward with this. Next steps would be to follow the process described here: https://github.com/openjs-foundation/cross-project-council/tree/main/collaboration-spaces

**Comment by voxpelli** [comment]
> Relatedly, I'm currently drafting on a `Collective Funds Guidelines` with initial targets being `mocha`(OpenJSF-project) and `neostandard` (not an OpenJSF-project) that other has also shown interest in – would love to collab on it when the first draft is complete 👍

Following up on this, first draft is published over at: https://github.com/collective-funds/guidelines Once this collab space is up I would love to get feedback from people here on it 👍

**Comment by UlisesGascon** [comment]
@rginn and I had a very productive meeting today defining the next steps. We plan to hold the meetings right after the Security collab sessions.

**Who wants to join the new collab space? 🙌**

**Comment by voxpelli** [comment]
@UlisesGascon Time allowing, I do

**Comment by mhdawson** [comment]
I'd join to start.

**Comment by rxmarbles** [comment]
Same I'd love to join, hopefully time wise it works out.

**Comment by rginn** [comment]
Cool! I added you @rxmarbles and @mhdawson.

**Comment by tobie** [comment]
🙋

**Comment by rginn** [comment]
Gotcha @tobie! Added.
