### ISSUE TITLE
2024 OpenJS Foundation CPC Selections:  Impact, At-Large, and Regular

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1370]
Folks, this year we are trying to simplify the CPC selection process by having one issue and one form to collect submissions. To that end please use the following [form](https://forms.gle/EVwZ8QN2bXaK7rjx7) to submit nominations for the following CPC Roles:

- Impact Voting Members
- At Large Voting Members
- Regular Voting Members

For more information please see https://github.com/openjs-foundation/cross-project-council/blob/main/CPC-CHARTER.md#voting-members

Please complete your submissions by October 18, 2024.

Mentioning The Following Incumbents For Visibility:

### Impact

**Appium**
* @jlipps
* @KazuCocoa  

**Dojo**
* @dylans 

**Electron**
* @erickzhao 
* @mlaurencin 

**jQuery**
* @mgol
* @timmywil 

**Node.js**
* @joesepi 
* @mcollina 

**webpack**
* @alexander-akait
* @TheLarkInn 

### At Large

* @ljharb 
* @tobie 

### Regular

* @mhdawson 
* @anonrig

**Comment by mcollina** [comment]
Node.js confirms @joesepi and myself

**Comment by mgol** [comment]
Timmy already submitted the form for him & me so I assume we're good.

**Comment by bensternthal** [comment]
Below are the nominations for the roles that require ratification by the CPC. This will be addressed during the next CPC call.


**At Large**

- Jordan Harband
- Ulises Gascón

 
**Regular**

- Michael Dawson
- Chris de Almeida
