### ISSUE TITLE
Should we have a foundation-wide Discord

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#1389]
(like we already have a foundation-wide Slack)

**Comment by ljharb** [comment]
Discord has awful UX; and I’d prefer not to have multiple places we all have to pay attention to.

**Comment by rxmarbles** [comment]
@ljharb I believe the goal isn't to have multiple places to look, but to be inviting to more folks (or generations) that are more comfortable in discord. This would help increase the visibility of the foundation and be more inclusive. I don't have strong feelings on either way this goes, but I do understand why it would be considered

**Comment by ctcpip** [comment]
No, not unless we would be migrating completely and eliminating the Slack workspace.  (Which I also would not want to do -- at least not to Discord.)

**Comment by tobie** [comment]
**Notes from this week's CPC call:**

  * decision to close issue
  * Express can feel free to experiment if they want to and open new issue if they help with it
