### ISSUE TITLE
Election: 2024-2025 CPC Chair & Vice Chair

### ISSUE THREAD

**Issue by bensternthal** [openjs-foundation/cross-project-council#1390]
Folks, this issue tracks the election of the CPC Chair & Vice Chair for 2024-2025.

If you are interested in the role, please self nominate via this [form](https://forms.gle/F3G4kQ5262SzhWjPA) by EOD Wednesday November 13th. 

These roles are open to regular and voting members of the CPC. More details can be found in the [CPC Charter](https://github.com/openjs-foundation/cross-project-council/blob/main/CPC-CHARTER.md#section-7-elections).

**Comment by tobie** [comment]
**Notes from this week's CPC call:**

only two candidates so far, no elections unless there are more

**Comment by bensternthal** [comment]
There are two candidates running for each role, so elections are underway for both positions. Candidate statements have been shared through the private mailing list, and voting is currently being conducted via OpaVote.

**Comment by bensternthal** [comment]
Please join me in congratulating Joe Sepi and Tobie Langel on being re-elected as CPC Chair and CPC Vice Chair \o/

Many thanks to the other candidates.
