### ISSUE TITLE
Stickers/Flyers for JSConf Chile

### ISSUE THREAD

**Issue by UlisesGascon** [openjs-foundation/cross-project-council#1392]
I want to ask for feedback/visibility on https://openjs-foundation.slack.com/archives/CS23BMK1P/p1729640714427199

- event details: https://jsconf.cl/
- cc: @mfdebian

**Comment by tobie** [comment]
**Notes from this week's CPC call:**

  * hard to ship hardware
  * can share artwork
  * resources for artwork here: https://github.com/openjs-foundation/artwork
  * will forward artwork directly to Alfredo, done

**Comment by tobie** [comment]
Closing as already addressed by @bensternthal. Feel free to reopen if necessary.

**Comment by mfdebian** [comment]
No one can say OpenJS wasn't present in the Chile JSConf 2024 😊  thank you @tobie @bensternthal and specially @UlisesGascon 💚 also thank you @ErickWendel for the good vibes! I had such a great time! 🙌 

![Image](https://github.com/user-attachments/assets/c0c59e45-d08d-48f1-ac58-e6f2e4ae253e)
![Image](https://github.com/user-attachments/assets/04e7a9c5-3ff8-42ff-9ec4-ca91a9b8c6c3)
![Image](https://github.com/user-attachments/assets/9da5c58a-e38a-47a9-b373-b4306f579247)
![Image](https://github.com/user-attachments/assets/d8ce3204-5758-4b5c-9511-dff8faeb2ff2)

**Comment by ErickWendel** [comment]
> No one can say OpenJS wasn't present in the Chile JSConf 2024 😊  thank you @tobie @bensternthal and specially @UlisesGascon 💚 also thank you @ErickWendel for the good vibes! I had such a great time! 🙌 
> 
> ![Image](https://github.com/user-attachments/assets/c0c59e45-d08d-48f1-ac58-e6f2e4ae253e)
> ![Image](https://github.com/user-attachments/assets/04e7a9c5-3ff8-42ff-9ec4-ca91a9b8c6c3)
> ![Image](https://github.com/user-attachments/assets/9da5c58a-e38a-47a9-b373-b4306f579247)
> ![Image](https://github.com/user-attachments/assets/d8ce3204-5758-4b5c-9511-dff8faeb2ff2)
> 

It was amazing seeing you my friend!!!
