### ISSUE TITLE
Additional repo, docs/discussion around Node.js+JS interactive reviews

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#148]
Discussed in CommComm meeting.  We want a place we can post info/discussion around selection process to make it transparent.

We thought it should be in OpenJS org as it should be across the projects.

Would something like "Conference Management" make sense?

**Comment by inidaname** [comment]
Conference Management will be cool but then it may house other future conferences, if the use case is only for Node.js+Js interactive then this may confuse other conference organizer. 

I would have suggested Node.js+JS interactive as it name but then this will lead to many others with similar purpose.

Yeah in my opinion Conference Management is :+1:

**Comment by mhdawson** [comment]
I agree perhaps conference management with a directory which is named Node.js+JS Interactive

**Comment by SarahKConway** [comment]
We're hoping to publish the CFP early this week. Would be great to get more input on the conference overview, topics, and types of sessions. 

December 10-12, 2019 Montreal, Canada
https://events.linuxfoundation.org/events/nodejs-interactive-2019/

At Node+JS Interactive, attendees collaborate face-to-face, network, and learn how to better their JS skills in serverless, IoT, backend and frontend contexts. The program will cover a broad spectrum of the JavaScript ecosystem including Appium, Dojo, jQuery, Node.js, or webpack, as well as frameworks, best practices, and stories from successful end-users. 

Submissions must be received by 11:59pmPST on April 20, 2018. 

Topics:
Architectures in Node.js
Expanding JS to JavaScript
Community Building
Diagnostics (Performance, Debugging)
Workshops
Emerging Use Cases (AI, Big Data)
Front-end Engineering
Node.js in Production
Deep Dive on Appium, Dojo, jQuery, Node.js, or webpack projects 
Security
Operations (Serverless, Containers, Orchestration)
Wildcard
JavaScript Ecosystem
JavaScript in Production
JS in Multimedia & Arts
JS in Serverless 
The Case for Appium, Dojo, jQuery, Node.js, or webpack
IoT
Frameworks (Lessons in Selection, Considerations, Migration, Comparisons)
Tooling
Testing Frameworks (Appium, Mocha) 
Internationalization
Accessibility
Building and Evolving APIs
Mobile
PWAs
Other, please specify…

Submission Type*
BoF
Lightning Talk
Panel (*maximum 4 panelists & 1 moderator)
Presentation (*maximum 2 presenters)
Hands-On Workshop

**Comment by bkardell** [comment]
Is this an example of last year's text or a copy/paste error in the new one?

"Submissions must be received by 11:59pmPST on April 20, 2018."

**Comment by SarahKConway** [comment]
That's a copy and paste error. Submissions must be received by 11:59 pmPST on June 21, 2019.

**Comment by SarahKConway** [comment]
A request was made in the last CommComm meeting to summarize key CFP review information. 

Please consider this a work in progress document. 
https://docs.google.com/document/d/1c0y-XSssZdEZGyCo0FVU6Wnd2TM3Ye-63xi18xjKVGM/edit

It includes the following information: 

-people who have volunteered to be part of the CFP review process this year. Call for volunteers still open.
-changes for this year's review CFP process 
-key CFP review dates
-feedback from last year's Node+JSInteractive attendee survey

**Comment by mcollina** [comment]
> -people who have volunteered to be part of the CFP review process this year. Call for volunteers still open.

Where is the call for volunteers? Are there any limitations - can somebody send a proposal and evaluate as well?

**Comment by SarahKConway** [comment]
If anyone is interested in joining the CFP review process, please volunteer here. We are also going to ask for volunteers from the TSC. Anyone interested can send their name to me. I'll make sure they are added to the CFP review team. 

No limitations. Someone can submit talks as well as review proposals.

**Comment by Jonahss** [comment]
@SarahKConway I'll volunteer :)

**Comment by MylesBorins** [comment]
I'd like to help

**Comment by SarahKConway** [comment]
Thanks! @MylesBorins and @Jonahss. Will add you to the list.

**Comment by inidaname** [comment]
@SarahKConway I will be happy to help too.

**Comment by christian-bromann** [comment]
@SarahKConway would love to volunteer too!

**Comment by alolita** [comment]
@SarahKConway I'd like to volunteer to review proposals too. :-)

**Comment by kborchers** [comment]
Please also add me to the list @SarahKConway 🙂

**Comment by mcollina** [comment]
@SarahKConway I'm happy to join as well.

**Comment by SarahKConway** [comment]
Thanks all. Volunteers are being tracked in this document. https://docs.google.com/document/d/1c0y-XSssZdEZGyCo0FVU6Wnd2TM3Ye-63xi18xjKVGM/edit

@hackygolucky and christian-bromann will be the event co-chairs this year. They will be reviewing input from the CFP committee and responsible for making the final decisions on talks/speakers who get accepted. Thank you both!

**Comment by cjihrig** [comment]
I'd like to participate in the review process.

**Comment by fhinkel** [comment]
Happy to join as well.

**Comment by gabrielschulhof** [comment]
I would also like to participate in the review process.

**Comment by gireeshpunathil** [comment]
I would like to volunteer too, thanks!

**Comment by sendilkumarn** [comment]
I am also happy to help here, thanks :)

**Comment by cjihrig** [comment]
@SarahKConway is there anything else to do for the people who have asked to be added to the document in the last few comments?

**Comment by cjihrig** [comment]
Let's try this again... @mhdawson is there any update here?

**Comment by mhdawson** [comment]
@cjihrig I've not heard anything yet, will send email to @SarahKConway to ask for a follow up.

**Comment by RRomoff** [comment]
UPDATE: If you haven't already done so, please nominate yourself to the review committee here if you'd like to participate ( even if you've raised your hand elsewhere) This is the best way to ensure you get notified of next steps.  https://events.linuxfoundation.org/events/nodejs-interactive-2019/program/program-committee/

The deadline to add yourself to this list is June 14 (tomorrow)
The deadline for CFPs is June 21 and the review process will start Monday, June 24th.

**Comment by codeekage** [comment]
@RRomoff the link to the form looks broken

**Comment by RRomoff** [comment]
@codeekage Updated my comment to include the form to add yourself as well as the program committee details. Should be good now! LMK if not.

**Comment by codeekage** [comment]
Thank you! Working now.

**Comment by RRomoff** [comment]
FYI, an email with next steps for the Node+JS Interactive program committee was sent out this afternoon from Shannon Jessee, from the Linux Foundation. If you did not receive that email, and you'd like to be on the committee, please let me know. We pulled everyone who raised their hand to help from this discussion, as well as the form, but if someone was unintentionally missed, we want to get you added and ensure everyone who wants to participate can! Thanks all!!

**Comment by MylesBorins** [comment]
Closing as reviewers have been identified and given access to review site. Please reopen if this was a mistake
