### ISSUE TITLE
Document/define initial process for handling reports to report@openjsf.org

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#160]
Copied from https://github.com/openjs-foundation/bootstrap/issues/115

Need to document process for reporting / moderating

**Comment by keywordnew** [comment]
Draft of process: https://docs.google.com/document/d/1O-LNZ1WSCQNMsYy45JqCWuxx2VC-WjcloiCreUszXro/edit#

**Comment by boneskull** [comment]
To be clear, this is not the same mailing list as cpc-private?

**Comment by MylesBorins** [comment]
@boneskull it is a different list. Code of conduct reports in node have not traditionally been triaged by the TSC or CommComm, but rather a moderation team specifically focused on conflict resolution

**Comment by keywordnew** [comment]
I've gotten helpful feedback that step 8 could get circular, so I've added a way to break out of deadlocks.

**Comment by mhdawson** [comment]
Agreed in CPC meeting today that next step is to PR into the CPC repo and then we can review/comment there.

**Comment by mhdawson** [comment]
PR https://github.com/openjs-foundation/cross-project-council/pull/271

**Comment by mhdawson** [comment]
#271 landed so closing
