### ISSUE TITLE
Draft initial process for electing voting members from the non-impact projects.

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#161]
How do non impact project elect their representatives? Process for election + voting should be documented.

**Comment by mhdawson** [comment]
Thoughts from Nick/Michael brainstorm and discussion in bootstrap meeting

https://docs.google.com/document/d/1h5Z2gzTmJ1lzY3-5Do0NQAZTc48dRYeEA71Q9SKleQE/edit

**Comment by MylesBorins** [comment]
Here is an example of using Helios voting inspired by the OSI board election

https://vote.heliosvoting.org/helios/elections/0b5d2178-6530-11e9-b1af-3a80b3d3e862/view

details --> https://wiki.opensource.org/bin/Main/OSI+Board+of+Directors/Board+Member+Elections/

> Currently the OSI is using Helios Voting to manage and administer our elections.
> 
> * Each eligible voter (Individual Member or Affiliate Member Representative) is  pulled from CiviCRM and batch uploaded in to Helios.
> * A voter alias is generated for each voter where identities are replaced with aliases, e.g. "V12", in the ballot tracking center.
> * The ballots are generated with the candidates names randomized on each ballot for each voter.
> * Voters will be able to vote for as many candidates as seats open representing their constituency.
>   - For example, if there are two Individual Member seats open, Individual Members may vote for two candidates on their ballots; if there are three Affiliate Member seats open, Affiliate Representatives may vote for three candidates on their ballot. (Individual Members may only vote for candidates running for Individual Member Seats, and Affiliate Representatives may only vote for candidates running for Affiliate Member Board seats).
> * Those candidates who receive the greatest number of votes (i.e. Member vs. Affiliate) will be submitted to the Board for appointment.
> * If there are two Individual Member seats open, the two candidates with the most votes will be declared the winners. For example, if Candidate A receives 100 votes, Candidate B receives 500 votes, Candidate C receives 50 votes, and Candidate D receives 1000 votes, then Candidates B & D would be declared the winners.
> * Importantly, per the OSI By-laws these elections are advisory, and the OSI Board must vote to adopt the results formally.

**Comment by Jonahss** [comment]
helios example: I assume the instructions to voters can be modified? it was unclear that you could vote for multiple candidates.

**Comment by MylesBorins** [comment]
@Jonahss I'm not 100% if we can add more info on the landing page, but we can definitely include it in an email

**Comment by mhdawson** [comment]
@MylesBorins this
> Voters will be able to vote for as many candidates as seats open representing their constituency.

does not seem to match what you were mentioning.  I had thought you said each person could vote for any many candidates as they wanted.

**Comment by mcollina** [comment]
How can we specify who can vote in Helios?

**Comment by MylesBorins** [comment]
@mhdawson I think that the "constituency" bit there is a bit more generic for the OSI board election as it was for all community representatives. We likely need to augment the docs for our use case. The link above implements the spirit of what was discussed

@mcollina right now it was set as open, but we can submit specific emails and keep to voting list limited to the list of imported voters

**Comment by mhdawson** [comment]
@Myles thanks for the clarification. I had thought you'd mentioned that OSI voting allowed you to vote for as many candidates that you wanted.  Either way I still think its a good idea.

**Comment by MylesBorins** [comment]
@mhdawson for the OSI election that I participated in I was able to vote for every candidate. I'm unsure why the copy paste is not aligning with my experience 
¯\\\_(ツ)\_/¯

**Comment by brianwarner** [comment]
Here's an example of the other system we discussed.  Same excellent poll (strong showing in the poll question, Myles, well done).

This is a public poll, but you can also set it to private so that each person gets a magic link.

https://civs.cs.cornell.edu/cgi-bin/vote.pl?id=E_7de60f6d9d38711f&akey=53e8e722a450a21e

**Comment by Jonahss** [comment]
I liked the rank choice voting in the civs demo more than the simple checkboxes of the helios demo. Also liked how you could have no opinion on some of the candidates.

**Comment by mhdawson** [comment]
@brianwarner it does say that the rankings will be publicly visible afterwards.  Even if they are anonymized the first 2 rankings might give it away. It is possible that they be private?

**Comment by brianwarner** [comment]
@mhdawson Yes, this can be configured on a per-poll basis.  

If it's helpful, here is the poll creation page, which lays out all of the available options: https://civs.cs.cornell.edu/civs_create.html

**Comment by mhdawson** [comment]
They both seem to work pretty well.  Of the 2 though for some reason I'm thinking being able to vote for as many as I'd like without having to rank them might work best in the situation we are in.

**Comment by eemeli** [comment]
Besides the actual voting method, I have three questions:
1. Do you envision some platform for candidates to present themselves before the vote? As the timeframe is getting rather tight here if this is expected to be concluded by end end of the month (or earlier?), I'd suggest opening an issue in this repo with candidate presentations in its comments.
 2. Are emeritus projects eligible to vote for representatives?
3. What's a "voter" in this case, is it a project or an individual? If an individual has a controlling interest in more than one project, are they allowed to cast more than one vote?

**Comment by boneskull** [comment]
I too am wondering what a voter is.  

If it's an individual, assuming any maintainer of a project could vote, projects with a greater number of maintainers would have more representation.

If it's a project, then each project needs to vote for who they want to vote for.  Jeez, I hope my project votes for me...

**Comment by mhdawson** [comment]
My understanding would be that a voter would be a representative from the project (up to the project to decided how to select their representative). Each project would have the same number (we discussed 2).  There may be one or more candidates from each project.  Depending on the voting method chosen the representatives can potentially vote for more than 2 candidates, possibly in a ranked order depending on the system.  For example, in one system they can vote for any number of candidates and the weighting is equal, in another, the votes are ranked in order of preference.  In either case you will need votes from other projects as well to win.

**Comment by mhdawson** [comment]
PR with initial cut: https://github.com/openjs-foundation/cross-project-council/pull/220

Key thing to note is that as written there is no ranking of candidates, voters either vote or candidate or leave them out.  This is one of the 2 options we've discussed in this issue so if you feel ranking should be included please comment on the PR.
