### ISSUE TITLE
New process for CPC reps to share responsibility for Travel Fund

### ISSUE THREAD

**Issue by keywordnew** [openjs-foundation/cross-project-council#172]
We'll be needing a process for the CPC to begin voting on [Travel Fund](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md) PRs together with the @nodejs/tsc and @nodejs/community-committee in the near future.

This is based on the interpretation of the Travel Fund being on the CPC charter as a shared resource it's responsible for ensuring. Possibly a candidate for [Steps to Bootstrap CPC](https://github.com/openjs-foundation/bootstrap/projects/2).

**Comment by Trott** [comment]
I'd recommend being very careful in the approach taken here. The travel fund was set up by the Node.js Foundation board to promote Node.js and to be administered by the Node.js TSC and CommComm. Basically negating that and making it an OpenJS thing would have the appearance of confirming the fears of some on the TSC that the foundation merger would dilute Node.js resources.

Here's a way to get to the same place, probably, but with a process that (hopefully) doesn't provide fodder for anyone who might want to portray this as the merger taking something away from Node.js: 

* Leave the current travel fund alone for the rest of the year. (There might not much money left in it at this point anyway, once you deduct all the requests that have already been made. Maybe someone on the Foundation side can report the current projected balance.)

* Create a new fund for the CPC. It can be small this year. CPC (and Node.js for that matter) can always ask for more money if it runs out.

* Next year, dissolve the Node.js fund, but let the TSC and CommComm know that if they have a legitimate reason to want their own fund, they can request it.

Ultimately, this has the same effect as just having the CPC start voting on Node.js Travel Fund requests this year, but the way we get there matters (at least in my opinion).

**Comment by Trott** [comment]
(Actually, the above arguably has a better result in that travel fund ultimately is a CPC thing and the Node.js TSC and CommComm don't have to co-administer it.)

**Comment by MylesBorins** [comment]
Do we need a foundation wide fund? This seems to me like something that should perhaps be a project based budget.

**Comment by mcollina** [comment]
I have a _slightly_ different proposal, essentially splitting the reason why people use the Node.js Travel fund right now:

1. Attending the Collab Summit
2. Promoting Node.js at other events
3. Diagnostics summit and similar

In 2020, I would like to see:

1. a fund for the Collab Summits, managed by the Collab Summit team
2. a (micro) fund for the CPC - in case there is some travel planned (might not be needed, or handled in an ad-hoc form)
3. a much reduced fund for Node.js promotional activities, managed by TSC/CommComm

What do you think?

**Comment by mhdawson** [comment]
My first thought is that the projects should still manage the travel fund for their members.  The TSC/CommComm should be able to prioritize if necessary based on which events they believe are most important.  

So I'd see the funds being

1. a travel fund for Node.js which is pretty much the same as this year (assuming that is what the project wants).
2. a (micro) fund for the CPC - in case there is some travel planned (might not be needed or handled in an ad-hoc form)
3. a travel funds for other projects based on need/size

I'm open to a single fund managed by the CPC, but I think we'd want feedback/input from the  Node.js project (and other projects as well) first on that idea.  If it's a case where the projects would like the CPC to provide common management then it makes sense to me, but if that is not the case I think projects should be able to manage the budget themselves.

**Comment by Trott** [comment]
These other ideas (above) work for me too, although in addition to taking care to avoid appearing to (or actually) diluting Node.js, we also need to be careful to not appear to (or actually) treat Node.js as "more equal" than the other projects. it's a tough needle to thread!

**Comment by mhdawson** [comment]
@Trott just to clarify what I meant by "a travel fund for other projects based on need/size" was meant to be individual funds for each project as opposed to one for the other projects. ie. the same as for the Node.js project.

**Comment by mcollina** [comment]
https://github.com/openjs-foundation/cross-project-council/pull/187 landed. I'd work to move it to stage 2 and stage 3.

**Comment by MylesBorins** [comment]
Does this need to stay open?

**Comment by Jonahss** [comment]
@MylesBorins I think we should keep this open because it's being used to track Travel Fund administration in this CPC project: https://github.com/openjs-foundation/cross-project-council/projects/3

I have volunteered to work on a formal proposal of how to handle the OpenJS Travel Fund.

**Comment by brianwarner** [comment]
As mentioned in the call, happy to help with anything related to logistics, once the requests actually get approved.  Node just approved an alternate, streamlined process using Expensify, but the spreadsheets-and-photos process is still there as a fallback.  The relevant documentation is here:
https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md#reimbursement

**Comment by MylesBorins** [comment]
Closing as the travel fund proposal is landed as stage 1
