### ISSUE TITLE
Start accepting nominations for "regular" members

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#178]
Discuss if there is anything that needs to occur before people can start self-nominating.

**Comment by MylesBorins** [comment]
Perhaps we should have a documented process and way to ensure project representation

**Comment by MylesBorins** [comment]
one thought... do we require "regular" members to have the approval or buy in of their projects?

**Comment by mhdawson** [comment]
This is what the governance says

>Regular members have made a commitment to be involved in an ongoing manner and take on roles and responsibilities as outlined below. Regular member is implied when memership type is not specified. Anyone who has been a member of one of the projects under the OpenJS Foundation for at least three months may request to become a regular member by opening a PR to add themselves to the list of regular members. Regular members remain for as long as they are active within the work of the CPC. Regular members who have not been active in GitHub, participated in meetings, or other work of the CPC for 3 months may be removed from the list of Regular members. In addition, a Regular CPC member can be removed by voluntary resignation, or by a standard CPC motion.

We might just ask that one of the voting CPC members representing the project (or those representing the non-impact projects) confirm the requirement `been a member of one of the projects under the OpenJS Foundation for at least three months`.

**Comment by joesepi** [comment]
Do we need to update the CPC Charter to make clear how someone is eligible to be a regular member? I'm asking based on Michael's previous comment?
https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md

**Comment by mhdawson** [comment]
I don't think we need a charter update as it outlines the requirements.  What would be good it a doc outside the charter which captures the process and includes how the requirement is validated.

**Comment by MylesBorins** [comment]
+1 to what michael said... something good to get in governance.md

**Comment by mhdawson** [comment]
+1 for adding to governance.md

**Comment by MylesBorins** [comment]
Closing as we have landed members and the process is identified in the readme. Please reopen if this should not have been closed
