### ISSUE TITLE
OpenJS Foundation Cross Project Council Meeting 2019-05-20

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#180]
## Time

**UTC Mon 20-May-2019 18:00 (06:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Mon 20-May-2019 11:00 (11:00 AM) |
| US / Mountain | Mon 20-May-2019 12:00 (12:00 PM) |
| US / Central  | Mon 20-May-2019 13:00 (01:00 PM) |
| US / Eastern  | Mon 20-May-2019 14:00 (02:00 PM) |
| London        | Mon 20-May-2019 19:00 (07:00 PM) |
| Amsterdam     | Mon 20-May-2019 20:00 (08:00 PM) |
| Moscow        | Mon 20-May-2019 21:00 (09:00 PM) |
| Chennai       | Mon 20-May-2019 23:30 (11:30 PM) |
| Hangzhou      | Tue 21-May-2019 02:00 (02:00 AM) |
| Tokyo         | Tue 21-May-2019 03:00 (03:00 AM) |
| Sydney        | Tue 21-May-2019 04:00 (04:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Cross%20Project%20Council+Meeting+2019-05-20&iso=20190520T18
* or http://www.wolframalpha.com/input/?i=06PM+UTC%2C+May+20%2C+2019+in+local+time

## Links

* **Minutes Google Doc**: <https://docs.google.com/document/d/1ay1ND9Iv3kBWCMa52Lb0L0Ya3vaLlht0_0MskxgQHHU/edit?usp=sharing>
* _Previous Minutes Google Doc: <https://docs.google.com/document/d/1WDSJqX7l3vGz7L0GD2M4RFl1ezKghvGEmk9c7-sR-MI/edit>_

## Agenda

Extracted from **cross-project-council-agenda** labelled issues and pull requests from the **openjs-foundation org** prior to the meeting.

### openjs-foundation/cross-project-council

* Nominating Chair and Director [#179](https://github.com/openjs-foundation/cross-project-council/issues/179)
* Start accepting nominations for "regular" members [#178](https://github.com/openjs-foundation/cross-project-council/issues/178)
* New process for CPC reps to share responsibility for Travel Fund [#172](https://github.com/openjs-foundation/cross-project-council/issues/172)
* Draft initial process for electing voting members from the non-impact projects. [#161](https://github.com/openjs-foundation/cross-project-council/issues/161)
* Review meeting times [#129](https://github.com/openjs-foundation/cross-project-council/issues/129)
* Post-Bootstrap work to be managed by CPC [#115](https://github.com/openjs-foundation/cross-project-council/issues/115)

## Invited

* OpenJS Foundation Cross Project Council
* OpenJS Foundation Project Maintainers
* OpenJS Foundation Board of Directors

## Notes

The agenda comes from issues labelled with `cross-project-council-agenda` across **all of the repositories in the openjs-foundation org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

* link for participants: https://zoom.us/j/920010234
* For those who just want to watch: https://livestream.openjsf.org

**Comment by Jonahss** [comment]
Zoom link for participants?

**Comment by evenstensberg** [comment]
I won’t make it. Sitting on a plane to Oslo.

**Comment by MylesBorins** [comment]
Link for participants: https://zoom.us/j/920010234

**Comment by Jonahss** [comment]
Er, has it started? Can't access the zoom
