### ISSUE TITLE
Poll: CPC Meeting Monday 5/28

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#184]
As we adjourned our meeting today I realized that next Monday is a US holiday and many participants (like me) are probably traveling. Wanted to do a quick poll to see who would be able to make it if we proceeded as usual with a Monday meeting.

👍 If you will be there
👎 If you send your regrets

Thanks!

**Comment by kborchers** [comment]
I will not be able to make that meeting and reacted as such. I will not even have reliable internet access next week which I am very excited about! 😁

**Comment by matt-gadd** [comment]
It is also a UK holiday too! 😄

**Comment by MylesBorins** [comment]
The collab summit is later in the same week. I think it makes sense to just punt to then and get the official time broadcasted in advance and make it easy for people to dial in

**Comment by eemeli** [comment]
The current Collab Summit [agenda](https://docs.google.com/spreadsheets/d/14NvqXdtcQkh21U3mdqQuR24oQeUmGDWHer373swQGvg/edit#gid=674659463) would suggest that the live session will start at 13:00 CEST on Thursday 30 May.

**Comment by mhdawson** [comment]
I can make it but agree that since we are meeting later in the week we should just skip this one. It will also give us time to get the automation fixed up as I landed the PR to rename for the meeting generation automation and I won't be able to do the corresponding part until I get back on Friday.

**Comment by mhdawson** [comment]
Sounds like we should cancel the meeting on Monday.  Any objections? Otherwise I think we should remove from the node.js calendar.

**Comment by mhdawson** [comment]
ok, a bit late but I'll remove it from the calendar and assume no meeting.

**Comment by bnb** [comment]
See y'all at Summit <3

**Comment by jorydotcom** [comment]
can't wait to see everyone <3
