### ISSUE TITLE
Add admin policy docs

### ISSUE THREAD

**Issue by obensource** [openjs-foundation/cross-project-council#185]
## Description
There are a number of admin-focused policy docs that we [recently](https://github.com/openjs-foundation/cross-project-council/issues/155) decided not to facilitate via their own 'admin' repo (since we only have one Top Level Council).

There are still a few admin policy docs that will need to live in the [cross-project-council](https://github.com/openjs-foundation/cross-project-council) repo, such as:
- [ ] Transferring a repo into the OpenJS org
- [ ] GitHub Org Management Policy
- [x] Member Expectations Policy (different from the [membership definition](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#section-4-establishment-of-the-cpc) in the CPC charter, more like [this](https://github.com/nodejs/admin/blob/master/MemberExpectations.md) from the Node.js admin repo).
- [ ] Working Group Requirements

It seems we're at a good place to create the initial drafts for these. 👍

**Comment by obensource** [comment]
I can go ahead and take a crack at these since I was planning on doing it anyway via https://github.com/openjs-foundation/cross-project-council/issues/155.

🎉🎷😎🎉

**Comment by obensource** [comment]
Please feel free to let me know if you think any of these are unnecessary, or there are documents missing from this list. 🙏

**Comment by mhdawson** [comment]
I think this one should end op being a common baseline that the projects then extend: Member Expectations Policy.  If you want any help on these let me know and I can take a first cut on this one early next week.

**Comment by mcollina** [comment]
I think all of those are needed. However I don't expect that we transfer many repo in this org.
Every project would host their project wherever they prefer (their own org): they are independent organizations. As a result, we can deal with transfers as one-off most of the time.

I would prioritize the _Member Expectations Policy_

**Comment by mhdawson** [comment]
PR for member expectations: https://github.com/openjs-foundation/cross-project-council/pull/186

**Comment by obensource** [comment]
Thanks for putting that in @mhdawson! 👍
