### ISSUE TITLE
Creating a new Standards WG repo

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#190]
At the Collab summit standards session, we discussed several immediate next steps including: 

* Creating a standards repo within the OpenJS Foundation org
* Creating a 'team' / sub-committee / working group for our standards effort to collaborate in that repo
* Moving available educational and archival documents/materials about standards work into that repo
* Creating a calendar of events in that repo for upcoming meetings of working groups, standards meetings, etc
* Requesting (confirming for 2019) a standards travel budget for our reps to W3C/TC39

Assuming there are no objections, I'd like to proceed with setting up that repo and begin moving/referencing relevant materials.

**Comment by mcollina** [comment]
I'm +1!

**Comment by kborchers** [comment]
+1 from me as well!

**Comment by mhdawson** [comment]
+1 for new repo

**Comment by MylesBorins** [comment]
Removed label and closing as repo was created. If I was too hasty apologies... please feel free to reopen

**Comment by knolleary** [comment]
For completeness: https://github.com/openjs-foundation/standards-team
