### ISSUE TITLE
Are we meeting today?

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#191]
We don't have an agenda generated for today; I know a lot of people are either traveling back from JSConf or still in Berlin where our regular meeting time would be during peak dinnertime. 

who's available to meet/planning to attend?

👍 I'll be there!
👎 nope!

**Comment by mcollina** [comment]
I'm happy to skip!

**Comment by bnb** [comment]
I can meet but it's fine if we skip.

**Comment by jorydotcom** [comment]
I'm in the same boat as @bnb

**Comment by jorydotcom** [comment]
After chatting with @brianwarner in Slack, I think it's wisest to cancel the meeting for today because we are not really prepared to have one. I think we all prefer to have productive meetings and I'm just not sure we would be able to accomplish much without more preparation. 

I'll take some responsibility here for not planning further ahead in addressing this - apologies all!

**Comment by eemeli** [comment]
On that latest note, could/should we have a Slack channel somewhere?

**Comment by jorydotcom** [comment]
@eemeli I renamed the JS Foundation slack workspace to OpenJS Foundation - you can sign up for that [here](https://communityinviter.com/apps/js-foundation/join-openjs-foundation-on-slack) if you aren't already on it!

**Comment by joesepi** [comment]
Thanks @jorydotcom for jumping on this issue. I think its safe to close now. Closing....
