### ISSUE TITLE
Create proposal for Moderation work at the CPC level

### ISSUE THREAD

**Issue by hackygolucky** [openjs-foundation/cross-project-council#195]
There's been lots of discussion prior and leading up to the Collab Summit related to how moderation work should be considered at the CPC level. In the CPC's charter, the CPC is tasked with 

> Supporting projects in their enforcement of Code of Conduct violations and escalation.

### Consider:
- What scenarios(obfuscated, please) have we experienced/observed in the past that would be good examples to require a CPC-level moderation team outside of an individual project moderation team?

- What can we do as a foundation and CPC if an individual project does not have the ability to moderate their own project spaces?

### Context
For reference, the Node.js Moderation Team is not viewed as the sole moderators of the project(any contributor is encouraged to moderate and assist in moderation) but a trusted team of individuals selected by project top-level committee members to make important decisions on moderation scenarios and recommend policies to improve the trust, safety, and productivity of the Node.js project through better participant interactions.

**Comment by ljharb** [comment]
It would be helpful to codify what a member of the moderation team is allowed to share with other projects' moderation teams as well - specifically, let's say the same individual generates distinct reports, to two different foundation projects, and a third to a non-foundation project. In this hypothetical, I am a member of the moderation team/code of conduct committee on all three projects. Each project's team likely would benefit from the additional context of the individual's conduct elsewhere as they decide what actions to take.

What information am I obligated to share? What information am I permitted to share? Most importantly, what information am I prohibited to share?

**Comment by dmethvin** [comment]
In a (hypothetical) case like that it seems it would be best for the groups to share as much information as possible about the combined CoC issues, since it indicates a pattern of behavior and also would be easier to handle together rather than piecemeal. Would the questions about limits on sharing be better addressed by legal counsel? Can they be determined in advance (as in now) or should we include legal on situations like this when they occur?

**Comment by ljharb** [comment]
It seems wisest to establish a rough framework in advance, at least. I agree that it seems best to maximally share, but confidentiality concerns likely still apply.

**Comment by MylesBorins** [comment]
There is a proposal that is open so I'm going to close this.

If i've done so prematurely please lmk and I'll reopen
