### ISSUE TITLE
Project assets repo?

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/cross-project-council#198]
I've just finished sorting, cleaning up, and normalizing the logos and marks from the various hosted projects in the Foundation.

I'd like to propose that we create a repository called "artwork", similar to what's done at CNCF: https://github.com/cncf/artwork  The purpose would be to hold .svg and .png versions of each project's artwork.  In case the project has a style guide or color study, that could be hosted here as well.  I'd prefer to keep it here, so that if an asset is mangled or is out of date, I don't have to be a gatekeeper on fixing it.

Some projects have much more developed brands than others, so I don't think we'll necessarily have the same level of detail as CNCF at first.  My hope, though, is that we can get there for most of the existing projects, and ask for these assets when new projects arrive.

Thoughts?

**Comment by mhdawson** [comment]
+1

**Comment by mcollina** [comment]
Definitely +1.

**Comment by sendilkumarn** [comment]
+1 of course 👍

**Comment by MylesBorins** [comment]
+1

**Comment by codeekage** [comment]
+1

**Comment by evenstensberg** [comment]
+1

**Comment by brianwarner** [comment]
Thanks everybody, I went ahead and prepared everything, and it's ready to push once the repo is created.

That said, I'm going to hold off for a little bit.  I'm working to get the trademark guidelines updated, and would like to include that information in the initial push.  Once that's incorporated, I'll bring this back up.

**Comment by brianwarner** [comment]
Per discussion in the meeting, I'm removing the agenda label and closing the issue.  Once we get the final trademark text I'll re-open this one.  Everything else is staged and ready to go.
