### ISSUE TITLE
Approve charter changes for Node.js Charter

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#199]
Updates to charter are proposed here:  [#698](https://github.com/nodejs/TSC/pull/698)

Needs the CPC to review.

**Comment by mhdawson** [comment]
+1

**Comment by mcollina** [comment]
+1!

**Comment by eemeli** [comment]
LGTM

**Comment by kborchers** [comment]
I've left a few minor and [one substantive comment](https://github.com/nodejs/TSC/pull/698/files#r292089820) on the TSC PR which I believe should be addressed before approval.

**Comment by kborchers** [comment]
My comments have been addressed so LGTM

**Comment by mhdawson** [comment]
As per the CPC charter we need approval by the CPC voting members:

>Voting members are responsible for approving the charter (and any updates) for projects which are part of the OpenJS Foundation. As part of this review/approval the voting members will ensure that the updated charter is compatible with the mission of the OpenJS Foundation and reach consensus with the Board on more substantial changes before final approval by CPC. 

Looks like we have 3 approvals from 3 voting members so far. Would be nice to get a few more.

**Comment by knolleary** [comment]
+1

**Comment by dylans** [comment]
+1

**Comment by dmethvin** [comment]
+1

**Comment by joesepi** [comment]
LGTM https://github.com/nodejs/TSC/pull/698#pullrequestreview-251715636

**Comment by mhdawson** [comment]
It was discussed that this can land in the CPC meeting, but probably worth waiting for: https://github.com/openjs-foundation/cross-project-council/pull/238 before landing.

**Comment by mhdawson** [comment]
The PR for the updates in the TSC repo landed last week so this can close.
