### ISSUE TITLE
Confirming Date and Time of next CPC Meeting

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#206]
Looking to make sure that all are aware of/on the same page about the date and time change for our next CPC meeting, per Monday's discussion: 

Wednesday, 6/19 @ 16:00 UTC (8:00 PST, 12:00 EST, 17:00 BST, 2:00+ AEST)

Let me know if you came away with a different understanding!

**Comment by kborchers** [comment]
I realize it's only every 3rd week but are we sure we want this to overlap with the Node.js TSC meetings and especially for the first meeting where the date/time changed? It works for me but I want to make sure those folks are fully aware of that overlap.

**Comment by joesepi** [comment]
Scheduling is hard. I say let's keep this as agreed in last meeting and perhaps we collect the best handful of times and the voting members can vote on the best of the best.

**Comment by mhdawson** [comment]
I think we want 2 meeting times, that would reduce the overlap to 1/6...  I agree though that we should stick to this update for now as agreed and change once we have agreement for something different.  As an FYI I've already updated the calendar to reflect the new time: https://calendar.google.com/calendar/r/week/2019/6/19
