### ISSUE TITLE
Decide on a timeline for selecting/electing/ratifying the next CPC members

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/cross-project-council#214]
The inaugural meeting of the first CPC was held on 20 May 2019, ten days before the first OpenJS Collaborator Summit in Berlin. Here's what our current charter says:
> Voting members serve for a term of 1 year and must be re-nominated and ratified by the Voting CPC members each year.

We should figure out when in particular the elections of the next non-impact voting members will be held, as the likely proximity of the end of the nominal one-year term to next spring's OpenJS Collab Summit (should one be held) may make travel arrangements difficult for elected members. This term limit and its proximity to the summit may be challenging for the selection of other voting members as well.

As we've already flexed on the number of non-impact voting members, I believe there's some precedent here for flexing on the understanding of "1 year" for this initial CPC. I would therefore propose that a determination be made that this "year" ends either at least a month before or a month after a presumed spring 2020 OpenJS Collab Summit, and then to work backwards from there to develop a more complete timeline.

Development of the specific election method is being tracked by #161. As we do not yet have any voting members nominated by regular members, I believe the timeline of their selection is a separate issue from this one.

I myself am a non-impact voting member and so a rather interested party in this issue. My main interest here is to establish clarity on the timing sufficiently well ahead of it becoming potentially emotionally laden for any parties.

**Comment by eemeli** [comment]
Posting this intentionally as a comment: I think the best solution would be to end the first "year" 6-8 weeks before next spring's summit, so that any newly selected voting members may have sufficient time to make travel arrangements (if possible) in order to participate in the summit. Meeting people face-to-face always makes it much easier to continue discussions with them later online.

**Comment by mhdawson** [comment]
I agree having the voting members elected in advance is a good idea.  My suggestion is that we make the current term run until the end of April.  We don't really know when the summit will be held, but I think at least for this year, April is likely going to before the next one after Montreal.

**Comment by mcollina** [comment]
I think we should:

1. start the election process  at the beginning of March
2. elect the new representative by April 2nd
3. the new representative starts on May 1st

Essentially there would be one month of handover, and travel plans could still be feasible.

**Comment by dmethvin** [comment]
Seems like a reasonable plan, assuming the collab summit stays in a narrow range of dates.

**Comment by mhdawson** [comment]
+1 to @mcollina's suggestion.

**Comment by keywordnew** [comment]
+1 @mcollina's pre-summit timeline seems reasonable to me

**Comment by eemeli** [comment]
Resolved by the decision in #274 to terminate the first year's term on 31 March 2020.
