### ISSUE TITLE
TBD Document link is broken.

### ISSUE THREAD

**Issue by netil** [openjs-foundation/cross-project-council#226]
The link of `TBD Document` mentioned from the project progress document is broken.
(or where I can find the info of the benefit from Froundation membership?)

> For more information about how your project can benefit from Foundation membership and services, please see TBD Document.
> https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_PROGRESSION.md

**Comment by MylesBorins** [comment]
This has been fixed AFAICT
