### ISSUE TITLE
Broken links in Charter

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#230]
The link for `foundations mission + vision` as well as `bylaws` are dead links

/cc @brianwarner @mkdolan

**Comment by MylesBorins** [comment]
ping on this. where do we want to host these files?

**Comment by brianwarner** [comment]
The current adopted bylaws can always be found on https://openjsf.org/join (as it is relevant to potential new members).  Here's a direct link to the current version: https://openjsf.org/wp-content/uploads/sites/84/2019/03/OpenJS-Foundation-Bylaws-2019-03-06.pdf

As for mission + vision, I'm not sure that this exists as a separate document, although I could easily be mistaken on that.

**Comment by jorydotcom** [comment]
Closing as this was resolved by #406
