### ISSUE TITLE
Who can be an Observer?

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#234]
As @mhdawson points out in [#232](https://github.com/openjs-foundation/cross-project-council/pull/232#issuecomment-505201211) who can be an [Observer](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#observers) is not explicit about requirements.

I had always been under the impression that there was a requirement that Observers be active in an OpenJS Foundation project... but as Michael points out, this isn't documented anywhere.

Can anyone come as an observer? Should there be some sort of requirement?

**Comment by dmethvin** [comment]
I feel like we should start as inclusively as possible unless there is some downside that we should protect against. For example, there may be some non-OpenJS project that has an interest in several OpenJS projects because they are critical dependencies. We'd want their input.

The term Observer implies some passivity though, and the document says Observers can participate, including consensus seeking. I would want input but wouldn't want Observers to be disruptive or overbearing. Perhaps we just need some way to have Members exclude Observers judged to be disruptive? I'd hope that's rare though.

**Comment by eemeli** [comment]
I would prefer for us to be able to at least start with maximal openness on this, and to only add limitations or requirements if we find a reason to do so.

**Comment by wesleytodd** [comment]
As someone who would probably start as an observer, I think having an "observer comment" section would be great.  I probably will not want to start jumping in with both feet, but I may have input to share. Having an explicit time in the agenda to share that might stop "disruptive or overbearing" members without being off putting to the community.

**Comment by mhdawson** [comment]
@wesleytodd I agree that having a section where we welcome "new" people and ask if they have something they'd like to bring/up discuss is a good idea.  @joesepi something to consider for the standard agenda.

On the general topic adding some expectation to the Observer section could make sense.  We already have this for regular members:

> In addition, a Regular CPC member can be removed by voluntary resignation, or by a standard CPC motion.

We could add this

> Observers are expected to participate in a positive and collaborative manner as well as following
the [code of conduct](https://github.com/openjs-foundation/cross-project-council/blob/master/CODE_OF_CONDUCT.md) and [member expectations](https://github.com/openjs-foundation/cross-project-council/blob/master/MEMBER_EXPECTATIONS.md) like other CPC participants.  If an Observer fails to meet these expectations they can be excluded from future CPC meetings base on a standard CPC motion.

**Comment by MylesBorins** [comment]
Seems like we had consensus on this in the meeting so I'm going to close this

**Comment by joesepi** [comment]
Me or @jorydotcom will create a PR to update language to make expectations clear.

**Comment by joesepi** [comment]
Capturing the wording that @mkdolan had shared in the meeting a week ago from Meeting notes for posterity:
>Mike Dolan: Potential suggested text: “Observers are free to attend meetings and participate in
  the work of the CPC as well as the consensus seeking process. Observers are encouraged to
  participate and volunteer but should refrain from disrupting or blocking progress.

**Comment by sendilkumarn** [comment]
I think it is also better to capture what CPC will do when there is a disruption or blocking?

**Comment by mhdawson** [comment]
@sendilkumarn I think what you are suggesting is along the lines of what I suggested in https://github.com/openjs-foundation/cross-project-council/issues/234#issuecomment-505554951, right?  That is my preference as well.

**Comment by jorydotcom** [comment]
Added PR per last week's action item

**Comment by joesepi** [comment]
Will move the previous PR copy (#255) from Charter to ReadMe, per discussion in today's CPC meeting.

**Comment by jorydotcom** [comment]
The PR that addressed this issue has been landed; I believe this can now be closed (please re-open if you feel otherwise).
