### ISSUE TITLE
email address for the voting members

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#236]
What's mailing list of of the voting members only?

cc @brianwarner

**Comment by brianwarner** [comment]
The list for discussions that are sensitive for privacy reasons or because they are embargoed, pre-announcement, is: cpc-private@lists.openjsf.org

**Comment by mhdawson** [comment]
We should probably have a mailing list that includes voting + regular members?

**Comment by kborchers** [comment]
@mhdawson What would that list be used for and would it be different than the projects list? I would imagine (hope) that all voting and regular CPC members are also on that list and anything being communicated to that group I think could go to all projects. For example, I will be sending an update on the board meeting soon and was planning to send it to the projects list.

**Comment by brianwarner** [comment]
This would be a good topic to add to the agenda in the CPC meeting.

**Comment by mhdawson** [comment]
@kborchers , tagged this issue for the agenda so we can discuss

**Comment by mhdawson** [comment]
@kborchers it's possible the project's list might work.  I can see cases were there could be discussions that would occur with regular members and doing that on the project's list might seem like spam to those not part of the cpc.  We could always start that way and see if it was a problem.

**Comment by joesepi** [comment]
Discussed in CPC meeting. Will use cpc-private for private business and issues for public business.
