### ISSUE TITLE
Conflict between CPC charter and Governance doc for CPC charter changes

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#239]
Seems I overlooked this section in the CPC charter when doing the PR for adding the details for merging PRs into the repository.

The charter says:

> Note that, in addition to requiring a simple majority vote of the CPC Voting CPC members, all changes to this charter are also subject to approval from the OpenJS Foundation board.

in section https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#section-10-voting

In the PR guidance we said

> Pull requests that change governance of the CPC must meet the following conditions in addition to the ones listed for regular PRs.

> The PR has been open for at least 14 days OR consensus is reached in a meeting with quorum of voting members.

https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#merging-prs-into-this-repository

I can open a PR to fix this either to the Landing guidance or to the charter. Since the most recent conversation was on what landed in the merger PRs section I think we should agree on which is preferred before I open a PR.

@openjs-foundation/cpc

**Comment by mhdawson** [comment]
Actually the discussion may have been around changes to the governance, not the charter, PR to fix up governance for charter changes. https://github.com/openjs-foundation/cross-project-council/pull/240

**Comment by MylesBorins** [comment]
This seems to have been fixed
