### ISSUE TITLE
fast track errata and minor changes

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#241]
For example https://github.com/openjs-foundation/cross-project-council/pull/240

This change is obviously errata and non-controversial. In Node.js core we have the following documented

> Certain types of pull requests can be fast-tracked and may land after a shorter delay. For example:
> 
> Focused changes that affect only documentation and/or the test suite:
> code-and-learn tasks often fall into this category.
> good-first-issue pull requests may also be suitable.
> Changes that fix regressions:
> Regressions that break the workflow (red CI or broken compilation).
> Regressions that happen right before a release, or reported soon after.
> To propose fast-tracking a pull request, apply the fast-track label. Then add a comment that Collaborators may upvote.
> 
> If someone disagrees with the fast-tracking request, remove the label. Do not fast-track the pull request in that case.
> 
> The pull request may be fast-tracked if two Collaborators approve the fast-tracking request. To land, the pull request itself still needs two Collaborator approvals and a passing CI.
> 
> Collaborators may request fast-tracking of pull requests they did not author. In that case only, the request itself is also one fast-track approval. Upvote the comment anyway to avoid any doubt.

**Comment by mhdawson** [comment]
I had thought we might want to pull the fast tracking approach over as well so +1 from me.
