### ISSUE TITLE
Add Standards WG meetings to OpenJSF calendar

### ISSUE THREAD

**Issue by kborchers** [openjs-foundation/cross-project-council#244]
The Standards WG has started meeting and would like their meetings added to the OpenJSF calendar once the day/time/frequency is set. Additionally, they will need a Zoom link and someone in the WG will need to be able to host Zoom meetings.

**Comment by MylesBorins** [comment]
@brianwarner can you help with this?

**Comment by brianwarner** [comment]
Yes indeed.  Two things...

1) At this point, we have three OpenJS Foundation Zoom accounts.  One is a webinar-enabled account, the other two are just regular Pro accounts (but still accommodate 100 people per meeting, and you can record the call for uploading to YouTube ex post).

I think the most logical way to do this is to have a separate calendar for each Zoom account.  That should help reduce the risk of call collisions.  We already have calendar which holds the CPC meeting, but I can set two more up, unless there are concerns with this approach.

2) @kborchers, can you please ask the person who will run the meeting to email me at operations@openjsf.org?  I'll share the credentials via lastpass.

**Comment by MylesBorins** [comment]
I’ve already added the meeting as a recurring webinar on zoom fwiw

**Comment by brianwarner** [comment]
Right on, thanks @MylesBorins.  So then it looks like I'll just need to know who to share the credentials with, so that they can log in as the host and kick off a stream.

**Comment by MylesBorins** [comment]
@kborchers do we need to discuss this in the meeting? Can the label be removed?

**Comment by kborchers** [comment]
Label removed ... I think we've covered it. Thanks!

**Comment by jorydotcom** [comment]
I believe this issue can be closed. The meeting is on the OpenJSF Calendar and the standards wg has been effectively using zoom for several weeks now
