### ISSUE TITLE
openjsf.org robots.txt needs updating

### ISSUE THREAD

**Issue by Trott** [openjs-foundation/cross-project-council#253]
Not sure where to go with this, so I'm putting it here. Sorry if I should know better.

openjsf.org robots.txt should probably be updated to allow search engine indexing. It was probably set to mega-restrictive mode while the merger was under wraps. But now that it's happened, SEO plz.

<img width="327" alt="Screen Shot 2019-07-08 at 11 45 13 AM" src="https://user-images.githubusercontent.com/718899/60834610-e367ff80-a175-11e9-9e0c-260b1817c3db.png">

**Comment by Trott** [comment]
Current contents of https://openjsf.org/robots.txt:

```text
User-agent: *
Disallow: /
```

**Comment by brianwarner** [comment]
Good call @Trott, I'll take this one.

**Comment by brianwarner** [comment]
I forgot to post an update, this was fixed right after it was reported.  Thanks for catching it, @Trott.
