### ISSUE TITLE
Provide guidance on how to refer to the foundation in licenses/copyright statements

### ISSUE THREAD

**Issue by knolleary** [openjs-foundation/cross-project-council#258]
Not sure if this is covered by the post-bootstrap activities mentioned in #115 or the [project board](https://github.com/openjs-foundation/cross-project-council/projects/3).

We still have lots of references to the JS Foundation in our license files and other project docs. We should provide clear guidance on what updates need to be made to ensure copyright statements etc are accurate and proper.

**Comment by brianwarner** [comment]
Hi @knolleary,

I just got the first draft of this back from legal last night.  Once it's ready to go, I'll publish it.

**Comment by jorydotcom** [comment]
Just noting that we will need this information for #262

**Comment by kborchers** [comment]
@brianwarner reported in today's CPC meeting that copy is being sent to member orgs for legal review and he will update when approved.

**Comment by MylesBorins** [comment]
ping on this. Do we need to bring it to Friday's board meeting?

**Comment by dmethvin** [comment]
Lacking other guidance I would tend to use this:
```
Copyright OpenJS Foundation and other contributors, https://openjsf.org/
```
I used it already in [this repo](https://github.com/jquery/jquery-migrate/blob/febf8a51158538051b310721ce2b5db36560548d/LICENSE.txt) but can easily change it to some other information if our legal counsel prefers it.

**Comment by brianwarner** [comment]
The drafts are done and are out for review.  @MylesBorins you have a good deal of reading homework in your email... ;-)

**Comment by eemeli** [comment]
> Lacking other guidance I would tend to use this:
> 
> ```
> Copyright OpenJS Foundation and other contributors, https://openjsf.org/
> ```

Okay, so this might be a bit of a weird question, but does the foundation actually hold any source code copyrights? As in, are there actual contributions that have been made to *any* OpenJS projects, for which the copyright has actually been transferred to the foundation or one of its predecessors, rather than being kept by the original authors and a license granted to the foundation or its predecessors?

**Comment by kborchers** [comment]
I don't have the comprehensive list right now but copyright to most of the code in the previous JS Foundation was transferred to the foundation's ownership at one point and that ownership would transfer to OpenJS. That said, anything contributed under the CLA after that IP was transferred is still owned by the contributer and licensed to the JSF and so licensed to OpenJS Foundation.

**Comment by dmethvin** [comment]
We should have legal counsel make a call on this. I seem to recall that the foundation needed to have the copyright in order to defend it, should any dispute arise. Circa 2012 we did that via ink-signed transfer documents for the main contributors and the online CLA for the "other contributors". That's pretty cumbersome though so I wouldn't expect new projects to do it.

**Comment by eemeli** [comment]
I dug through my own mail archives, and found the copyright assignment paperwork for messageformat that I'd forgotten about, from about three years ago.

As I've understood it, we're not asking this anymore from new projects, right? If so, I think the guidance should not default to implying that the foundation does hold copyright over its projects.

**Comment by brianwarner** [comment]
It's been about a year, so I'm going to reawaken this one to ask if we're still blocked, or if we can close it? I believe that this was addressed [here](https://github.com/openjs-foundation/cross-project-council/blob/master/IP_POLICY_GUIDANCE.md#2-copyright-notices)?

**Comment by mhdawson** [comment]
Remove the "waiting on board" label as it's not waiting on the board.

@knolleary do you think we can close the issue, seems like the link @brianwarner pointed to covers the issue.

**Comment by knolleary** [comment]
@mhdawson looks good to me. That provides the guidance I was looking for. I don't think there's anything else that needs addressing.
