### ISSUE TITLE
Add entry point for projects wanting to join on README.md and review project progression (Jory will help with this one)

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#261]
Agreed to add the addition to the README.d in PR #165 which moves the process to stage 3.  This way we'll land together and it will be more discover-able only after it is in stage 3.

**Comment by joesepi** [comment]
@jorydotcom has some copy to add to readme and we have pull request #165 open relating to project progression.

**Comment by MylesBorins** [comment]
This landed 🎉

Thanks jory
