### ISSUE TITLE
Create issue template and new board to track applications to join the Foundation

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#262]

**Comment by jorydotcom** [comment]
@kborchers & I met yesterday - we went through the onboarding list and identified a few issues to be created for follow up, and also created a [template file](https://github.com/openjs-foundation/cross-project-council/blob/master/.github/ISSUE_TEMPLATE/project-onboarding-checklist-template.md) and [project board](https://github.com/openjs-foundation/cross-project-council/projects/4). 

Kris will be creating an issue for Arc's onboarding using the template. Also, @boneskull has volunteered to take Mocha through the process early as well. Should have some initial issues for projects to put in the 'doing' column very soon.
