### ISSUE TITLE
Forum for keeping certain project details

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#265]
Reviewing the onboarding checklist (see #262) we identified that we ask projects for information related to their: 

1) Infrastructure
2) Personal contact information

which we probably don't want to display _publicly_, but may need certain roles to have access to that information from time to time. @brianwarner suggested this could be a private repository for the ED, Program Manager, CPC Chair, and/ or other designated roles to keep up-to-date.

**Comment by jorydotcom** [comment]
Thinking further, for the contact information piece we may want to keep that as a public file with names; perhaps add this information to the projects.md file

**Comment by Jonahss** [comment]
That's not a bad idea.

**Comment by eemeli** [comment]
If we do end up with anything like a registry of personal data for projects, I trust that the foundation has everything in place to make sure that we're compliant with the GDPR and other such data protection requirements?

**Comment by jorydotcom** [comment]
@eemeli brings up a good point; using github to store names & email addresses would not be GDPR compliant. If we don't link to email addresses or anything I think this would be sufficient: 

`### project 1`
`* Technical Contact: A Name`
`* Marketing Contact: Another Name`
`* Legal: A Name, Esq.`
`* Project Comms Channel: [Gitter](), [IRC]()`

I think our bigger challenge is knowing who the right person is rather than how to reach them.

**Comment by kborchers** [comment]
@eemeli Yes. The Linux Foundation has a full process in place for handling GDPR requests. Someone, like a program manager or the ED, is notified of the request and will go through the process of fulfilling the request (whether it be to send them the data we have, delete it, etc). What we would want to check though, which is not necessarily part of this issue, is that we have the appropriate documentation on openjsf.org explaining how to make those requests.
