### ISSUE TITLE
Process to request legal advice for projects

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#273]
As titled, we need a process to allow projects to ask for legal advice. As an example, a project might consider bundling another dependency.

The process should ideally be private at the beginning, because these might be sensitive. The relevant CPC rep for the project should be involved as well.

**Comment by mhdawson** [comment]
Some keys things to include from my perspective:

*  Should include @cc to CPC representatives for the project making the request and the CPC board rep so that they are aware can ensure there is progress.

**Comment by MylesBorins** [comment]
@mcollina are you imaging this would be a proposal? Do we need to document a process? Is a documented email alias sufficient?

**Comment by mcollina** [comment]
I don't think a proposal is needed, an email address/process described on a `.md` will suffice.

**Comment by mhdawson** [comment]
Details were added to the README.md on how to request legal advice, closing.
