### ISSUE TITLE
Decentralize Budget Authority

### ISSUE THREAD

**Issue by rubys** [openjs-foundation/cross-project-council#28]
Preface
--------

Input on matters like [board representation of projects](https://github.com/nodejs/bootstrap/issues/24) tends to reflect individuals experiences with how one or both of the existing foundations' boards have operated in the past, as well as expectations as to how a merged board would operate.

Fortunately, we don't need to continue to operate as we have done in the past.

This issue extracts a cross-cutting concern (budget) and describes a different model of operating that has been time tested and seems to produce more feeling of individual empowerment and accountability than either of Node.js or JS foundation structures provides today.

Output of this discussion will inform matters like bylaws and charters.

Overview
--------

In the ASF, President is a volunteer, non-board position that is responsible for operations, including budget.  Reporting to the President is a number of officers each of which potentially owns a budget.  Budgets are approved annually, come with a scope, and an authorization amount.

Current list of officers:
* Brand Management
* Fundraising
* Marketing and Publicity
* Infrastructure
* Conferences
* Travel Assistance
* Finance

Additional line items (tracked by, but not reporting into, the President)
* Treasury
* General & Administrative
* Chairman's discretionary

Potentially, every Project (and in the ASF this would include the Incubator and Community Development), has an officer who can own a line item, but in practice we have never done this.

Officers tend to have committees that support them, which may be a mix of volunteers and paid staff.  The model we strive for is volunteers for oversight and setting direction, and paid staff when there is a demonstrable need for timely response.  Volunteers may join or leave a committee without involving either the board or the President.  It is up to committees to determine how this operates.

Officers themselves are named by the board or the President, depending on the reporting structure.  The President and EVP are named by the board, and need not be members of the board (and I would argue it is advantageous for them not to be, but people's opinion on this differ).

How this works
--------------

Annually, we do a five year plan.  This is where the board provides the most direct input, and is involved in setting strategic goals for the foundation.  This is done in conjunction with line item owners.  My recommendation is that we start this with the second year of the merged foundation.

Annually (typically 3 to 6 months after the five year plan is approved), the line item owners draft one year budgets with both scope and authorization.  The President gathers up these inputs and presents them to the board for ratification.  Typically, this gets unanimous approval as the strategic goals have been set.

When Bills come in, Line Item owners approve them; Accounting verifies the approval and schedules the payment, and the Treasurer releases the payment.  Being geeks, this information has traditionally been done through [version control systems (SVN)](http://treasurer.apache.org/), but we are exploring moving this to GSuite or other systems.

Monthly, the board gets reports from the Treasurer and the President.  These reports include both this month's and YTD budget vs actual income and expense by line item. These reports (elided occasionally when specific vendors are mentioned) are [posted online](https://whimsy.apache.org/board/minutes/Treasurer.html).

Commentary
----------

* While the ASF is a 501(c)(3) non-profit and both the Node.js and JS Foundations are 501(c)(6) business leagues, a model where the board sets long term direction and oversees that expenditures are spent according to plan but otherwise delegates both the short term planning and day to day execution to others could work for both.  The process described above provides plenty of insight to members as to how their monetary donations are being spent, and data for things like [annual](https://s.apache.org/FY2018AnnualReport) and quarterly reports that can be shared with potential new members.

* The ASF has never had an Executive Director.  At times, this is a matter of vigorous debate.  The crux of the matter is that the President's job is to delegate and therefore isn't a time consuming job when things go smoothly, but observationally it is rarely the case that things go smoothly.

* Officers (and their committees) have both oversight and autonomy.  They produce a detailed plan which is reviewed by the President and ratified by the board, and then executed in conjunction with accounting and the Treasurer, and monitored by the board.

* Projects don't tend to have direct representation.  In contrast to a model where a project has a single representative on the board who is responsible for input on every operational and strategic matter, resulting in direction that is handed down, the ASF's model enables every individual on a project to participate in a committee (or even be an officer) in the areas that they are interested in.

  So Travel Assistance would, for example, gather together a list of events for the year from the people who show up to the committee, produce a plan, and once the plan is ratified, execute on that plan - handling things like obtaining Visas and working with Travel Agencies.

  Conferences deals with hotels and producers.  Marketing deals with the Press.  Brand Management deals with lawyers.  Etc.  Each open to participation by interested members of projects, but largely offloading this responsibility and letting projects focus on code development.

**Comment by mcollina** [comment]
+1. Possibly with slightly different nuances for us, but it's a good starting point.

Who is responsible for fundraising?

**Comment by rubys** [comment]
> Who is responsible for fundraising?

I may not be understanding the question.  The ASF Fundraising committee has 13 members, including one volunteer VP of Fundraising and one paid person with the same title (this is indeed confusing, but the feeling was that titles matter to potential sponsors).  The paid VP of Fundraising reports to the volunteer.  The paid individual ensures that inquiries get a prompt response.  The volunteer sets direction, deferring to the committee whenever possible.  The Fundraising committee reports to the ASF President.

This may be one of the few areas where a 501(c)(6) is materially different than a 501(c)(3).

**Comment by boneskull** [comment]
My dumb question of the hour:

Is "fundraising" (or "development") in a 501(c)(6) essentially, "get more companies to become dues-paying members" rather than a 501(c)(3)'s "solicit donations?"

**Comment by rubys** [comment]
@boneskull probably a good first approximation, but it may not matter much.  In FY18, the ASF received 90.5% of its income from corporate donations.

**Comment by mcollina** [comment]
I'm actually _very_ positive about this structure. The goal is removing a lot of responsibility from the Board itself, and it would be extremely beneficial for all projects. Right now, the top benefit a Platinum member gets is a Board seat, with the Board diminished in role, would we risk the top tier losing its main advantage?

**Comment by rubys** [comment]
@mcollina excellent!

I don't see this as having a diminished role for the board, unless of course, those that seek Platinum membership are doing so because they wish to do the boring details of operational execution.  My belief is that current structure is one where the board centralizes operations and then delegates it to the Linux Foundation.  So, if anything it would be the LF that would be diminished, but I doubt that it would end up that way.

Let's walk through an example.  I'll start with Travel Assistance.

 * The board still gets to set long term strategic direction, primarily through the five year plan.  The board could collectively decide to radically ramp up, marginally ramp down, or eliminate entirely this program.  I see no evidence that the board would do anything but continue to encourage this program, but since the topic at hand is "diminished in role", it is fair to explore the edge cases.  The board still gets to ratify the plan without having to do the hard work of building consensus (or, given the current structure, "take the heat" of making hard decisions).
 * The Travel Assistance Committee (or whatever it gets to be named here) gets to build the plan as long as it conforms to the general constraints provided by the board.  We can bootstrap this by taking last years expenditures in this area as a baseline and ask the committee to justify any increases or decreases.  One approved, the committee gets to follow through.
 * The current corresponding ASF committee is 100% volunteer.  It doesn't need to be that way.  A good part of the work (booking tickets, sending visa requests) is very time sensitive.  A part of the budget request could be to hire someone (most likely provided by the LF?) to assist with this work.  This can keep with the ASF split of volunteers setting direction, with paid staff executing.  Think of how much more efficient and satisfying this will be if the paid staff works directly with the people that produced the plan, and those people are a part of the projects that directly benefit?

Don't get me wrong, making this work will be hard work, particularly for the first one to two years.  

A essential part of this is setting expectations.  As software engineers, we understand the concept that feature X didn't make release Y of project Z because nobody stepped up to implement it.  There always is release Y+1.  Operations is no different.  We need to set the expectation that barring an emergency (which doesn't need to be a bad thing, it could very well be an unexpected and welcome opportunity that it too good to pass up), the board should not be expected to revisit the overall level of funding for Travel Assistance (or any other expenditure) more than once a year.

Circling back to your original comment, I've added a link to the [most recent ASF Annual report](https://s.apache.org/FY2018AnnualReport) to the main text of this issue.  My experience and expectation is that corporate members will pleased both with the quality and quantity of the data that is made available to them, the quality of concrete and pre-vetted proposals for expenditures, and the increased opportunity to focus on the long term strategic aspects of the foundation.

P.S.  If it helps, I happen to work for one of those Platinum members.

**Comment by rubys** [comment]
> This sounds like a very good model.

That makes two of us that think that way.  Possibly three others based on 👍 's.

> How do we move this forward?

My sense is that this will require a lot more "bottoms up" excitement to get this issue noticed.  Perhaps the next step is for @jasnell to revisit https://github.com/nodejs/bootstrap/issues/24 with different assumptions?

Additionally, perhaps those of us that attend [NodeConf.eu](https://www.nodeconf.eu/) can self-organize a meeting to brainstorm how to proceed?

The [minutes](https://github.com/nodejs/bootstrap/blob/7ec7721964e97600c6a1eeea0affaa0902dbd381/meetings/2018-10-29.md) from Monday's meeting are a bit... sparse.  My takeaway from that meeting (others that were present are welcome to correct me if I got things wrong):

 * The lawyer that was present basically said that the model was workable, and another example (which I have since forgotten) of a similar model was mentioned.  All this means is that there likely isn't a legal show stopper here.  It is up to us to decide.
 * Of the people who were present, I sensed a lack of enthusiasm for the proposal.  Some concerns that volunteers are a risk, and that the alternative (a traditional board with a small number of project reps) is more of a known quantity.

While I can understand the perspective, it means that I have done a poor job of explaining the risks and benefits.  Here's what I see (speaking only for myself):

 * There is a lot of pent up frustration with the current organization structure, particularly of the Node.js foundation. If this merger is in any way a step backwards, or does not address some of the fundamental issues, it is likely only a matter of time before Node.js decides to separate from the foundation.  Spelling this out more clearly: the collective set of demands across all projects is likely to be unreasonable in that the board can't satisfy everybody, everytime. Most people will understand that, as long as it isn't **my** feature that isn't implemented, in which case, that's unacceptable.  My assessment is that unreasonable expectations combined with a "last chance to get it right" situation is a significant risk, and merits exploration of alternatives, such as the one I outline above.
 * It would be irresponsible for me to say that volunteers are not a risk.  That being said, the risk is inherently different.  If the volunteers operate openly and welcome people who want to contribute, I think there will be a bit more tolerance if the volunteers end up being late or outright fail.  After all, it is us that could have stepped up, not "them" who didn't do as asked.  That's a key reason why I believe that this is a lower risk than continuing with roughly the current organization.  Volunteers are more likely to get a second, third, or even fourth chance.
 * We talked a bit about an "unpaid" (by the foundation) member of the community volunteer (who in all likelihood receives a salary from a sympathetic corporation, much as I do as ASF President) vs a paid Executive Director.   I didn't speak up enough on this one. If we have an ED who is hired by the board, paid by the board, and evaluated by the board, we likely will get a different result than having a member of the community run things.  I'm struggling to find a way to express this, but the incentive structure is different.  The ED is incentivized to justify their continued employment.  A "volunteer" is more likely to understand that they have no real power, it is the committees that do the real work and deserve the credit.
 * I don't think I did as good of a job as I could have expressing the role of committees.  I sensed an impression that it takes a certain caliber of person to be an excellent ED, and a volunteer isn't likely to have the cycles to do that job effectively.  While true, that misses the point.  We are not looking for a small number of super-humans.  We are looking for perhaps a dozen or so members each for a half a dozen committees.  So 50 to 100 passionate people.  Spreading the work decreases burn-out.
 * Finally, volunteers for everything isn't the right model.  Paid staff (most likely hired by the LF but matrix reporting to a committee and/or directly to the President) is appropriate for things that require immediate responses and/or for work that no volunteer is interested in doing is the way to go.

I'm obviously passionate about this and willing to write at length on the topic.  I also have a body of work that I can point to (our mildly redacted) [board minutes](https://whimsy.apache.org/board/minutes/) are published on the web, and we have plenty of how-tos published.  I also know a large number of people who are understandably proud of the work they do who would be more than happy to spend some time explaining how their committees work.

**Comment by mcollina** [comment]
I'm actually fine with a Board with a number of project rep. This model scales better IMHO. However it'd be a big commitment now as it's not fully flashed out. How about we do both? I think the Board could decide to delegate certain responsibilities anyway - as an example, setting up a "travel assistance" committee with a budget makes 100% sense. We already have such a committee, which is the members of TSC+CommComm that are interested. 

Doing it step by step could increase the confidence in this model, as it won't be implemented overnight.

**Comment by rubys** [comment]
> as an example, setting up a "travel assistance" committee with a budget makes 100% sense. We already have such a committee, which is the members of TSC+CommComm that are interested.

I'm trying to figure out how this is different than the current model where each project makes requests to the board.  My understanding is that hasn't worked out so well.

**Comment by mcollina** [comment]
> > as an example, setting up a "travel assistance" committee with a budget makes 100% sense. We already have such a committee, which is the members of TSC+CommComm that are interested.

> I'm trying to figure out how this is different than the current model where each project makes requests to the board. My understanding is that hasn't worked out so well.

The travel fund is in fact what has been working the best.

**Comment by jorydotcom** [comment]
Meta question: what should we do with this issue? I don't think @rubys points have been fully addressed but we are starting to unlock process & progress on related items.

**Comment by indexzero** [comment]
The two questions I would explore answering on the road to a full plan / policy are

1. What are the initial budget buckets (i.e. budget allocations) are important enough to surface to the Board? The three allocations that exist today that are good candidates for this process to "adopt" are
   - Travel Fund
   - IT Infrastructure 
   - Community Programs
2. How does one propose a new budget bucket (i.e. budget allocation) and how do we hold them accountable against agreed upon KPIs for that budget over a 2-3 year period? Is there an exploratory phase or a similar maturity model?

**Comment by mhdawson** [comment]
There has been some discussion on this and I think in the short term that path forward could be:

* If there are funds/budget that community/projects want/need to manage they can open a proposal
  (following https://github.com/openjs-foundation/cross-project-council/blob/master/STAGING_PROCESS.md).  That proposal should cover how the money would be used, approval processes etc.
* Following the existing process the CPC could review, iterate and when ready ask the Board for a budget to support the proposal
* In parallel as the CPC ramps up activities/working groups we should think about where managing a budget makes sense and follow the same process to make proposals.

**Comment by mcollina** [comment]
I think this issue can be closed. Feel free to reopen otherwise.
