### ISSUE TITLE
Define & document a style guide for the foundation's name

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/cross-project-council#280]
We should make it clear how we wish the foundation to be referred to. Specifically, it's unclear at least to me whether the short form of the name should be "OpenJSF" or just "OpenJS".

For both the JS Foundation and Node.js Foundation, it was clear they could not use just "JS" or "Node.js" as an identifier, but that's not the case for "OpenJS", which as a term has surprisingly few other active meanings than this foundation.

Now, admittedly the website's domain is `openjsf.org`, but if that does mean that we prefer "OpenJSF", I think we should make an explicit decision about it.

This is an offshoot of #278, which now has commits and suggestions for both spelling variants.

**Comment by mcollina** [comment]
I think `openjsf` is the best option, mainly because there has definitely been some trademark checks when registering the domain name. However, we should sync up with legal to be more certain :D.

**Comment by joesepi** [comment]
Request: repo with style guidance and foundation assets. cc/ @brianwarner

**Comment by bnb** [comment]
I would very much like to see a repo exist. A simple name, like `branding` in this org would be 100% acceptable to me.

**Comment by bnb** [comment]
Also worth noting: I love doing this kind of work and would be happy to help if a repo is something we pursue.

**Comment by brianwarner** [comment]
I have a repo ready to push with all of the branding assets from the OpenJS
Foundation and all of the projects, once the trademark docs are final.
That's probably a logical place for this info as it already includes a
visual style guide.

**Comment by bnb** [comment]
@brianwarner not to bikeshed on one of the hardest parts of programming, but I'm curious about what you're planning on calling that repo ❤️

**Comment by joesepi** [comment]
Progress has been happening at the board. Nearing the finish line.

**Comment by tobie** [comment]
🤞 OpenJSF gets approved. I've been referencing the CPC quite a bit as part of the incubation process, and having to write out "OpenJS Foundation CPC" all the time (instead of just "OpenJSF CPC") is painful (and an additional cognitive burden on readers).

**Comment by joesepi** [comment]
We now have an artwork repo with styleguide and guidance.
