### ISSUE TITLE
Ask projects to start updating references to docs in cpc repo (ex coc etc.)

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#282]

**Comment by jorydotcom** [comment]
Reviewing this and other issues, I wonder if we aren't already capturing this issue concern in the onboarding work, or if this issue should be moved to the onboarding repo?

**Comment by mhdawson** [comment]
I think at this point this is being covered by the onbording for existing projects and can be closed.

**Comment by eemeli** [comment]
Closing, as per previous comment.
