### ISSUE TITLE
jQuery project infrastructure

### ISSUE THREAD

**Issue by dmethvin** [openjs-foundation/cross-project-council#285]
The jQuery project has some very old testing infrastructure that they'd like to get some help updating. I don't think we've come up with a process for this. Perhaps we can use it as a point of discussion about the role of the CPC in these activities.

https://github.com/jquery/infrastructure/issues/444

**Comment by mcollina** [comment]
The linked issue is a 404

**Comment by trivikr** [comment]
Looks like the repo is private?
I'm getting 404 on https://github.com/jquery/infrastructure

**Comment by dmethvin** [comment]
Sorry, l will figure out a way to summarize it.

**Comment by timmywil** [comment]
This is the issue on testswarm that prompted the infra issue and it's public: https://github.com/jquery/testswarm/pull/319.

Also, maybe we could put together a team on the jQuery org with all the cpc members.

**Comment by jorydotcom** [comment]
cc @kborchers & @brianwarner to make sure they see this issue. very important!

**Comment by kborchers** [comment]
Both the current infrastructure that exists for projects and how to manage/maintain that as well as what we want to be able to offer projects going forward is an active board discussion so hopefully we will have updates on that very soon. I will work to prioritize those conversations as much as possible in upcoming board meetings.

**Comment by jorydotcom** [comment]
@dmethvin & @timmywil, on a related note I would also say perhaps the jQuery & jQ Infra folks should chat about what services & sites we need to keep up vs. what we think can be safely archived / retired. IMO another challenge is just the breadth of everything & knowing what's important

**Comment by MylesBorins** [comment]
removed label and kicking conversation to the working group

**Comment by jorydotcom** [comment]
@dmethvin @timmywil Can we schedule some time with the jQ Infra group? I feel like we have enough information now to start putting a plan together to back us out of some of those issues in the /infrastructure repo

**Comment by timmywil** [comment]
Sounds good to me. @dmethvin who's in the jQuery Infra group?

**Comment by jorydotcom** [comment]
Groovy - for simplicity I should probably just post an issue there with a meeting request. Will do that shortly!

**Comment by mgol** [comment]
See https://github.com/jquery/infrastructure/issues/449

**Comment by Trott** [comment]
> See [jquery/infrastructure#449](https://github.com/jquery/infrastructure/issues/449)

Looks like something happened to the `jquery/infrastructure` repository and all the links to it in this issue are now 404?

**Comment by ljharb** [comment]
@Trott it's a private repo; i also don't have access to it.

**Comment by Trott** [comment]
> @Trott it's a private repo; i also don't have access to it.

Ah, as discussed above. Sorry for the repetition.

**Comment by jorydotcom** [comment]
@Trott If you're interested in helping out (or know someone who might be) LMK!

**Comment by rginn** [comment]
jQuery is the most recent recipient of an OpenSSF Project Alpha-Omega grant that includes funding to continue its infrastructure modernization project. https://openjsf.org/blog/2022/10/24/openssf-project-alpha-omega-invests-in-the-openjs-foundation-and-jquery/

The jQuery maintainers and our OpenJS team will document the journey and lessons learned through ongoing blogging to share with the industry.

I recommend we close this issue with a note that help and participation in the jQuery project is always welcome.
