### ISSUE TITLE
Commit to providing a reply to an application within a specific time frame

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#295]
Currently, when a project applies to join the foundation, there's a "silent period" during which the CPC meets and votes on whether to accept that project's application and allow the project to enter incubation. There is no time frame specified for how long the CPC is going to take to do so. That makes it very difficult to coordinate announcing that a project is entering incubation during a conference, for example.

Would it be possible to commit to getting back to applicants within a specific timeframe?

**Comment by MylesBorins** [comment]
We had originally discussed making the silent period time boxed to 2 weeks... although it could theoretically move faster. Do you have a preferred time frame?

**Comment by tobie** [comment]
If 2 weeks is doable, that would be great.

**Comment by mhdawson** [comment]
Discussion in the previous CPC meeting was that we were not comfortable committing to 
    a specific time.  Instead, we agreed to commit to an initial response in 48 hours and then a 
    weekly update.  This is covered in:
    https://github.com/openjs-foundation/cross-project-council/pull/321
