### ISSUE TITLE
[MEETING] Infra-wg Open Discussion

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#307]
Per our last CPC meeting, we decided that a separate session to move some #infra issues forward would be ideal. We opened a doodle poll and the date chosen is:

Monday, August 26
18:00-19:00 UTC

Join with this zoom info: 

Topic: infra-wg meeting
Time: Aug 26, 2019 02:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://zoom.us/j/619604917

One tap mobile
+16465588656,,619604917# US (New York)
+17207072699,,619604917# US (Denver)

Dial by your location
        +1 646 558 8656 US (New York)
        +1 720 707 2699 US (Denver)
Meeting ID: 619 604 917
Find your local number: https://zoom.us/u/aBTqBT2in

### Suggested Agenda

1. Scoping - a crack at decomposing the problem
 * Individual Project Infra Support Needs - how do we help projects upgrade, decommission, migrate infra for builds/releases etc...
 * Foundation-wide concerns - what do we provide for projects vs. what projects own on their own, eliminating bus factors, etc
 * Infra Sustainability - need a responsive infra support system
2. Current, related issues
 * jQuery Legacy Infra (#285)
 * Rethink Found. Infra & how we manage it (#291) 
3. Easy next steps
 * what can we start doing to make progress on the live issues today?

**Comment by Trott** [comment]
I'm almost certainly going to miss this meeting today, but hopefully @mhdawson, @rvagg, or someone else from @nodejs/build can be there. Rod and Michael are vastly more knowledgable about this stuff anyway. 

Will a recording be available after-the-fact?

**Comment by sendilkumarn** [comment]
@jorydotcom (from my notes) I think we also briefly touched up on how we will be differentiating the `contractors` (I'm not too sure on how to define them "those who have access") and `volunteers` (those who want to help).

--- 
> VMs/test devices

I think this will be a separate item and `CI/CD` will be a separate item

> Relating to 'First Services,' we identified that the foundation has some infra offerings for projects, 

IMO, the major problem w.r.t smaller projects are that they do not have a proper communication channel when they scale. Slack is great and awesome but the open source version doesn't scale very well. Providing them a workspace in Slack would be really great. 

> gathering this data/asking these questions across the categories

It will be really awesome, if someone checks out how different projects handle infra-related things and also what are the major concerns that they have w.r.t infra? Based on that we can split the list into nice to have, should have, etc., I think that will really help us how to phase things here.

**Comment by jorydotcom** [comment]
Following up on the action items from this meeting, @brianwarner and I have reached version 1 draft documentation of the services menu and data gathering. I think it makes sense to close this issue and open a new one to review these items. Please feel free to reopen if you feel otherwise!
