### ISSUE TITLE
Move User Feedback Survey efforts from Node.js to OpenJS

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#315]
The Node.js Community Committee spun up an initiative to gather user feedback and one avenue of that effort is to run user feedback surveys.

One example of running a survey exists in the repo:
https://github.com/nodejs/user-feedback/tree/master/data/2018-02-benchmarking-wg-survey

I have been working to build out a framework that would be self-serve for survey needs with the help of the foundation to give some guidance and to execute the survey and return the results.

This effort seems like it could be a benefit to more than just Node.js so I am proposing we move it up a level and make it available to all projects under the CPC.

Here is an issue referencing the effort: https://github.com/nodejs/user-feedback/tree/master/data/2018-02-benchmarking-wg-survey

The general goal of the framework is to:
1. Have an issue template that will outline the information expected to run a survey
1. Have an opportunity for the survey requester (from a project) to get some guidance from the foundation on question framing to elicit usable feedback data
1. Have the foundation execute the survey on behalf of the requester
1. Have the survey return results in a useful format

The issue template exists in the user-feedback repo: 
https://github.com/nodejs/user-feedback/blob/master/.github/ISSUE_TEMPLATE/1-user-feedback-survey.md
Or see it in action by beginning to create an issue using the template:
https://github.com/nodejs/user-feedback/issues/new?template=1-user-feedback-survey.md

**Comment by mhdawson** [comment]
+1, having been involved from the beginning I think this part of the user feedback work has a good fit with work at the CPC level and makes sense to be available to all of the Foundation projects.

**Comment by joesepi** [comment]
I'll propose a new repo and any other corresponding efforts/actions.

**Comment by jorydotcom** [comment]
pinging on this thread to see if we can finish it up & close!

**Comment by joesepi** [comment]
Yeah. I am working on this as we speak. :)

**Comment by joesepi** [comment]
I have "moved" the repo and very minimally updated the README. I need to do a bunch of cleanup from the larger effort and then can move over a few issues that are specific to user feedback surveys. https://github.com/openjs-foundation/user-feedback

**Comment by joesepi** [comment]
While more work needs to be done on user feedback, I'm going to close this since it has been moved to OpenJS foundation.
