### ISSUE TITLE
Add travis or github actions to org

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#317]
We now have a linter for the repo, would be nice to include travis to test that we don't regress

**Comment by wesleytodd** [comment]
I am sure we could apply and get GitHub to enable actions on this org.  I think an owner can just go here:

https://github.com/features/actions/signup/?account=openjs-foundation

If no one else here has a contact to request "fast-tracking" the request I can reach out to the ones who helped us get access for express.

**Comment by MylesBorins** [comment]
@wesleytodd just to confirm you are suggesting that we use an action rather than travis?

**Comment by wesleytodd** [comment]
Yes.

**Comment by MylesBorins** [comment]
actions is now enabled on the org and I've opened a PR to add an action.
