### ISSUE TITLE
Mailing lists for projects

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/cross-project-council#324]
As discussed in CPC meetings on [2019-07-30](https://youtu.be/zkCiKGTFW98?t=1470) and again today, it might make sense to provide a @lists.openjsf.org mailing list for each member project's maintainers. The main idea/benefit here would be to enable each project to maintain their own contacts, while providing the project maintainers with a public non-personal email address.

**Comment by brianwarner** [comment]
I can take care of this, @eemeli .  

Here's a general call-to-action for every project:
Please email me (bwarner@linuxfoundation.org) with your maintainers' names and email addresses.  I'll take care of the rest.

**Comment by jorydotcom** [comment]
Where would it make sense to document this sort of thing over the longer term?

Should we have a wiki for project maintainers? I can imagine it including this information, as well as stuff like our infra services guide (work in progress).

**Comment by joesepi** [comment]
This PR closes this issue: https://github.com/openjs-foundation/cross-project-council/pull/396
