### ISSUE TITLE
Responsible security disclosures

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#326]
Is there a standard way for OpenJSF projects to accept responsible security disclosures or is the expectation that projects set up their own solution?

Node.js has its [own policy](https://nodejs.org/en/security/), for example. I don't know about other projects.

I feel like it would be nice if this was something the foundation handled for projects (even if the project would be the one responsible for dealing with the disclosure itself).

**Comment by wesleytodd** [comment]
Related: https://github.com/nodejs/package-maintenance/issues/159

Our Node WG has been having some discussions around this.  If the foundation was going to have something it should align with what the Maintenance WG and Security WG recommend.

**Comment by MylesBorins** [comment]
We've definitely discussed trying to replicate some of the work that has
been done in core... especially around managing CNA and CVE stuff.

With githubs new announcement though perhaps we should look at working with
them... as the management of the CNA is a non-trivial amount of work.

**Comment by mhdawson** [comment]
The Node.js security work also does work in this area, and HackerOne who we work with handle CVE stuff for the ecosytem repors.  I've pinged that team through https://github.com/nodejs/security-wg/issues/578

**Comment by mhdawson** [comment]
There have been discussions as to wether part of the Node.js security-wg which focuses on ecosystem triage should move up to the OpenJS level.  This is probably a good time to continue that discussion.  @sam-github

**Comment by sam-github** [comment]
https://github.com/nodejs/security-wg/pull/579 relates to this slightly, in that if the responsibilities of the nodejs/security-wg become more clearly and singularly focussed on the Ecosystem outside Node.js, they might be a candidate to move up a level.

Also, note that even though many, perhaps most, of the vulns in the DB are reported against "Node.js" packages, a number of those packages can also run in the browser, and there are at least a handful (or were, last time I surveyed them a couple years ago) that are npm package that run ONLY in the browser, so the WG is already in some sense collecting and triaging non-Node.js vulnerabilities.

**Comment by MarcinHoppe** [comment]
I brought this up some weeks ago when triaging a report of a vulnerability in a React component: clearly only intended to work in the browser but still distributed via the npm.

I would definitely be up for discussion about taking our work in the Node.js ecosystem triage team to the OpenJS foundation level.

**Comment by mhdawson** [comment]
Created https://github.com/nodejs/security-wg/issues/589

**Comment by mhdawson** [comment]
PR in package main repo which is related: https://github.com/nodejs/package-maintenance/pull/277

**Comment by joesepi** [comment]
@MarcinHoppe has created draft security guidelines for the Node.js Package Maintenance team that you can see here: https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/security-guidelines.md

@MarcinHoppe has also started to capture current security practices for OpenJS projects here: https://gist.github.com/MarcinHoppe/b13a870770522c31a8386ada48b2e40f

@tobie has started the conversation within the AMP project here: https://github.com/ampproject/wg-security-privacy/issues/2

**Comment by mhdawson** [comment]
Followed up with Marcin today and noting that the next step is:

Minimal requirements that we'd expect Foundation projects to meet in terms of security reporting and a simple policy/implementation of that could be used by projects to meet that.

**Comment by MarcinHoppe** [comment]
I am back on track on this one and will have a revised version ready for the next round of reviews before the end of this week.

Thanks all for your patience about it.

**Comment by MarcinHoppe** [comment]
I added a new file with requirements, I'd love some feedback about it on the PR: https://github.com/openjs-foundation/cross-project-council/pull/489#issuecomment-635903804.

**Comment by tobie** [comment]
Thanks. Looped-in AMP‘s security team.

**Comment by mhdawson** [comment]
PR to move guidelines to stage 2 - https://github.com/openjs-foundation/cross-project-council/pull/566.  Thanks @MarcinHoppe

**Comment by mhdawson** [comment]
Last step is to move to stage 3, @MarcinHoppe do you want to open the PR to move to stage 3.

**Comment by MarcinHoppe** [comment]
@mhdawson I opened #602 to move the proposal to stage 3.

**Comment by MarcinHoppe** [comment]
Thanks for merging #633. Are we good to close this issue?

**Comment by tobie** [comment]
Hell ya! Thanks for your work!
