### ISSUE TITLE
Clarify whether the content of application becomes public if project is approved

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#327]
That seems implicit from the process, but it would be good if it was clarified.

Keeping the content of the application CPC-only helps applicants be more transparent about a project's shortcomings and helps everyone make a more informed decision.

**Comment by mhdawson** [comment]
Discussed in the CPC meeting today.  Until we have time to work on a process that might be more flexible the consensus is that they will be Private.

**Comment by tobie** [comment]
Sorry for missing the meeting today and last week. Added this as a suggestion to #321.
