### ISSUE TITLE
Typo on https://openjsf.org/

### ISSUE THREAD

**Issue by mikesamuel** [openjs-foundation/cross-project-council#328]
Apologies if this is the wrong place.  I couldn't find the repo for the openjsf.org content.

https://openjsf.org/ reads, in part

> Interested in joining? Email us at <del><b>email at</b></del> membership@openjsf.org for more information.

The "email at" seems extraneous.

**Comment by brianwarner** [comment]
Typo?  What typo?  ;-)

Just kidding, it's fixed now.  Thanks for the heads up @mikesamuel, and for transferring this here @MylesBorins
