### ISSUE TITLE
Administering Project Applications

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#331]
We currently have an application process deploy ~ yay!
We currently have no way to ensure we are actively responding to applicants ~ oh no!

I'd like us to commit to some for of administration and monitoring a very basic SLA so folks are getting timely responses and not lost in the cracks

**Comment by mhdawson** [comment]
I think that is covered in: https://github.com/openjs-foundation/cross-project-council/pull/321.

In terms of SLA and who.  In my opinion, we should just start following what's outlined there.

**Comment by mhdawson** [comment]
Specifically for the initial application:

```
1. An acknowledgement is sent to the applicant by Foundation staff within 48 hours (striving to reply within 24 hours when possible).
```

**Comment by tobie** [comment]
- Clarity as to who the project's champion is would be great. It's totally opaque from the applicant's perspective.

**Comment by joesepi** [comment]
Per discussion in CPC meeting, we'd like to keep this open, to:
- close pr #321 
- look further at tracking/tooling question in @MylesBorins original description

**Comment by joesepi** [comment]
Per CPC discussion today around potential tooling/process to track and manage onboarding projects, both through the private period and beyond, we've decided to start with github repos (one private for silent period applications; and one public) and a weekly private check in during the last 10min of the Cross Project Council meeting.

I will still keep this ticket open to check on the related pr (#321) as well as to make sure the agreed upon process outlined above gets implemented.

**Comment by jorydotcom** [comment]
Following up here to report that the private repository for tracking applications during the silent period has been created. I have begun to take a pass at organizing this repo somewhat. The @openjs-foundation/cpc team has been added. I think this issue can now be closed.
