### ISSUE TITLE
Infrastructure Improvement Follow-up

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#333]
As follow-up actions for issue #307 and related to #285, we were tasked with drafting an infrastructure menu of services as well as beginning a data-gathering process to understand the infra landscape around our current projects. 

We've reached a V1 of that work and are ready to have follow-up discussions in order to move this forward. I suggest that we host a follow-on #infra working group meeting but am open to other ideas!

**Comment by jorydotcom** [comment]
Per our discussion in the CPC meetings, I'm posting a link to the [Draft "Infra Services Menu"](https://docs.google.com/document/d/1yQgEMvnY0apAEYoiysfae7qqmbJAfd4eLgmGKviPZ_0/edit) which outlines the vendored services that the OpenJS Foundation currently supports from an IT perspective. This list is not intended to be immutable; it is just meant to communicate clearly what any OpenJS Foundation project will get in terms of "out-of-the-box" infra support from Foundation IT / program staff. 

This list is based in large part on the initial work we've conducted in creating an 'infrastructure inventory' for OpenJS Foundation projects. That work is not entirely complete, but is expected to be complete as we get through project onboarding. 

The ask is as follows: please take a look at the draft services menu and let me or @brianwarner know if there are any clarifications, asks, etc. Also, if we (you, me) haven't chatted about your project's infra setup let's do that soon!

**Comment by Trott** [comment]
@mhdawson @rvagg @joesepi @joaocgreis

**Comment by mhdawson** [comment]
I've already reviewed/commented as it was being developed. Subject to comments from other I think the next step is a PR to land in the CPC repo. It can then be updated/adjusted through follow on PR's as needed.

**Comment by bnb** [comment]
Given that this hasn't moved in about 3 years, I'm going to close it. Feel free to reopen if you think it's still relevant :)
