### ISSUE TITLE
Term of CPC directors?

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/cross-project-council#334]
I was going through some cleanup and documentation tonight, and noticed that we've defined the term length and expiration of the Voting members (#214).  However, I don't think we've defined the start/end date of the CPC board reps.

If I'm mistaken on that, please do point me in the right direction.  Otherwise, this would be a good agenda topic for an upcoming call.

**Comment by MylesBorins** [comment]
Seems like we have a section on elections

https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#section-7-elections

I believe the timing off this is defined in the bylaws. the below section implies it is an annual process... but this is a bit buried and seems like it might imply that they are in lock step with the corporate board member election (if there is one). The word `election` appears 34 times in the bylaws, `annual` appears 7 times, and `annual election` appears 4 times. Perhaps we should have legal review this and suggest how we should best define elections and what belongs in bylaws vs charter?

> **4.3 (g)**
>  Each Community Director shall serve in accordance with Section 4.3(k) below and until his
> or her successor is elected and qualified or until his or her earlier resignation or removal;
> provided, that in the event that after any election of Directors, the number of Platinum
> Members or participants in the Individual Membership Program (further described in Section
> 5.4(c) below) decreases such that the number of Community Directors then in office exceeds
> the number of Community Directors permitted by subclause “d,” “e,” or “f” (as applicable) of
> this Section 4.3, then the Community Directors then in office may continue to serve until the
> next annual election of Directors, at which time the required decrease in the number of
> Community Directors (if applicable) shall take effect. If, at the time of such next annual
> election, the terms of a sufficient number of Community Directors are not expiring, the
> selection of the Community Director to resign shall be determined by such procedures as may
> be set by the Board of Directors from time to time.

**Comment by mhdawson** [comment]
The term is captured in the CPC charter in this section: https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#section-7-elections at least for the CPC director, my assumption was that it is the same for all directcors but that could be tightened up in the language.

In my discussion with @brianwarner I thought the question was more about when that term would start if it was going to be other than 1 year from when the first elections were held.  The context is that we chose to make the term of the first Voting members end early at set date and the question would be if we should do the same for directors versus making it 1 year from the first election.

**Comment by MylesBorins** [comment]
Do we need to keep this open?

**Comment by mhdawson** [comment]
I don't think we answered

>I thought the question was more about when that term would start if it was going to be other than 1 year from when the first elections were held. The context is that we chose to make the term of the first Voting members end early at set date and the question would be if we should do the same for directors versus making it 1 year from the first election.

I'll put it on the agenda and we can see if we can close it out.

**Comment by mhdawson** [comment]
We agreed in the CPC meeting that then end of the first term should be July 1st (FYI @kborchers). Rational included:

* 6 months offset from corporate board elections
* Provides enough time after CPC voting member elections

It also roughly lines up with what would have been 1 year from the initial election of the first directors , so no too much of an adjustment of the standard 1 year term.

**Comment by mhdawson** [comment]
PR to add agreement to governance: https://github.com/openjs-foundation/cross-project-council/pull/440

Closing.
