### ISSUE TITLE
Help the applicant navigate the silent period

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#340]
For the applicant, the silent period is a complete blackbox.

What would really help would be for them to understand that there's a clear process happening, and where in this process we currently are. So for example:

- Reception of application
  - Receipt acknowledged within two business days by foundation staff (already in the process).
- CPC then has a week to decide who the champion is going to be.
- CPC chooses champion.
  - Foundation staff introduces champion to applicant.
- CPC then has _n_ weeks to collect input and have discussion about project.
  - Champion to advise applicant of deadline for questions by CPC members.
  - Champion to forward questions to applicant as they're received with the expectation of a fast turnaround (2 business days, max a week).
- Deadline for the initial set of questions reached
  - Champion to start collecting answer from applicant
  - Champion to advise on deadline by which answers are due (1 week).
- CPC then has _n'_ weeks to follow-up on answers to questions.
  - CPC may ask follow-up questions, triggering a new round of questions.
- Once all answers have been received, champion to announce to applicant that the CPC will provide its final answer by _date_.
- CPC to make decision
  - Champion to update applicant on decision
- Etc.

**Comment by MylesBorins** [comment]
@tobie do the changes in https://github.com/openjs-foundation/cross-project-council/pull/321 help clarify any of this for you? I think it was intending to solve a number of the points above. If there are things missing we may want to get it included in there or in a follow up PR

**Comment by tobie** [comment]
In part. I think what's missing is:

- **An initial kick-off email to the applicant that lets them know who their champion is.** For context, I learnt who my champion was through backchannels that I'm lucky to have. That's a privileged position we shouldn't assume every applicant is in. I believe this happened because it's not clear from the process whether that's the Champion's role or the Application manager's.
- **Clear milestones** (with deadlines) by which CPC members should have requested clarification requests and applicants should have replied. Clarification that those milestones should be announced by the champion to the applicant.
- **The notion of _a round of questions_.** During the first round, all topics are allowed, during subsequent rounds, only follow-ups on previous questions are allowed, unless, of course, new information, not disclosed in the application, is suddenly discovered. The goal here is to promote transparency from the applicant and reward it with a funnel-like process in which which progress is well defined.

**Comment by mcollina** [comment]
One of the things the CPC does not want to commit to are deadlines. The key reason is that each application should get enough review time. For the very same reason, having the concept of a "round of questions" is _complicated_. That can work well after we have received all the questions from _all_ the CPC voting members, and it would take time to collect them all before sending them. I think that would delay things further. Given the above, do you think that having a round of questions would still be useful?

(Note that a voting CPC member that cannot ask questions could just... -1 the application, so it might be counterproductive).

**Comment by mhdawson** [comment]
At this point I'd suggest a follow on PR.  @tobie would you be able to submit a PR which adds what you think are gaps in the progressions doc?

**Comment by tobie** [comment]
Will do, but won't be able to get to it for another couple of weeks.

**Comment by tobie** [comment]
This is still on my radar, but unfortunately not an immediate priority.

**Comment by bnb** [comment]
@tobie is this one that still needs to be done?

**Comment by tobie** [comment]
Yeah. I think we want to let @bensternthal settle in and see how much of this could be managed through improves operations.
