### ISSUE TITLE
Project Champion clarification

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#352]
In case whom is doing the new project application is a member of the CPC, can they be champion or there is a conflict of interest somewhere?

**Comment by mhdawson** [comment]
My initial thought is that it might be better to have them be different people.  My reservations are not that strong but some possible things to consider:

* Is there any perceived advantage for the application if the champion is the same person as the proposer
* Does having two people collaborate improve the process/result?

**Comment by mhdawson** [comment]
We discussed in the CPC meeting today.  The consensus was that docs should be updated to clarify that the champion should not be the same as the applicant.
