### ISSUE TITLE
Separate repo for onboarding?

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#376]
It seems like onboarding could cause a lot of noise in this repo

Thoughts?

**Comment by ljharb** [comment]
Great idea! Existing issues can be transferred there.

**Comment by tobie** [comment]
Isn't the current situation a one off thing, though?

**Comment by joesepi** [comment]
Per discussion around #331, we have decided to do a public repo and a private repo for onboarding projects. I've created the public repo. Waiting for Github upgrade to our org to create the private repo.

**Comment by brianwarner** [comment]
Just confirming that I've submitted an application to upgrade our organization to a GitHub for nonprofits account.  That would upgrade us to "Team" and allow for private repos.

**Comment by bnb** [comment]
Just for context, the link to the public repo discussed here (I was interested but there wasn't a link in the issue): https://github.com/openjs-foundation/project-onboarding

**Comment by brianwarner** [comment]
I am just reopening this for long enough to say: the GitHub for Non-Profits upgrade just came through today!
