### ISSUE TITLE
Clarify Travel Fund status & process

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/cross-project-council#377]
The travel fund proposal got advanced to Stage 3 in #312, and is therefore nominally "complete". However, its documents are only included under `proposals/stage-3/TRAVEL_FUND`, they contain a number of "TODO" mentions, and at least the 2019 record is missing some updates that have been made to the [nodejs/admin version](https://github.com/nodejs/admin/blob/master/TravelFunds/2019.md).

As an interested party to applying for the travel fund for the Montreal conference & summit, I actually have no idea about how I should proceed with my application. Should I apply here, or in the nodejs/admin repo? When is the process moving to this repo? How will any open requests be handled?

**Comment by Jonahss** [comment]
Open requests can be migrated. So apply through the old repo until #312 is fully completed.

The process itself (using expensify, email addresses) are all the same.

**Comment by Jonahss** [comment]
I plan on setting up the final PR for the proposal in the next 7 days. So if you want to wait for that, you can.

**Comment by christian-bromann** [comment]
Given that we were short in time at the CPC meeting, let me phrase my question in here:

- There is a section at the end on approved travel funds of previous year. Do we have already approval for travel fund this year? If so, by whom? Is it the OpenJS Foundation this time?
- Shall I make changes to the "complete" stage 3 proposal or should we move this back to an earlier stage?

**Comment by christian-bromann** [comment]
@eemeli please review final PR with suggested changes: https://github.com/openjs-foundation/cross-project-council/pull/441. Cheers!

**Comment by mhdawson** [comment]
Landed #441 so closing.
