### ISSUE TITLE
Ensure documentation covers assets that must be transferred from Foundation 

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#380]
We should ensure that the assets which must be transferred to the Foundation as a project joins are clearly documented.

**Comment by brianwarner** [comment]
With the caveat that there may be extremely unusual corner cases that have to be handled by the Board on an exception basis, this could be a starting point for the text:

> Assets to be transferred to the Foundation include any registered trademarks related to the open source project, and the project's domain.  From that point forward, the Foundation will be responsible for renewing and managing the trademarks and the domain.
> 
> To begin the process of transferring a registered trademark, please reach out to legal-questions@lists.openjsf.org. To begin the process of transferring a domain, please reach out to operations@openjsf.org.

**Comment by mhdawson** [comment]
This would imply that the transfer occur before the final Vote by the Voting members: https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_PROGRESSION.md#process

https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_PROGRESSION.md#process

Already covers the transfer of domains, and says

` Transfer logomark to the OpenJS Foundation`

But not entirely sure what a logomark is.  @MylesBorins would that have been intending to cover Trademarks?

**Comment by knolleary** [comment]
If a legal transfer is required prior to the vote, we could end up in a situation where the vote fails but the assets have already moved. Is that the scenario that makes you wonder about it @mhdawson ?

Perhaps it should be something like "all relevant assets have been identified and their transfer agreed in principle, subject to the final vote"

**Comment by ljharb** [comment]
https://github.com/openjs-foundation/cross-project-council/issues/380#issuecomment-547491241 is definitely a failure mode I'm concerned about.

**Comment by mhdawson** [comment]
@knolleary , @brianwarner, @ljharb that is defintely what I was thinking about.  I'd agree that it should be "agreement do so in good faith" .  We probably need a post-vote checklist in addition to the checklist for what needs to be in place before the vote.

**Comment by tobie** [comment]
See #378.
