### ISSUE TITLE
request: Review CommComm Charter Update

### ISSUE THREAD

**Issue by bnb** [openjs-foundation/cross-project-council#383]
Over the past few weeks, the Node.js Community Committee had built out and refined updates to our charter that reflect the Node.js project’s existence in the OpenJS Foundation rather than the Node.js Foundation.

We seem to have come to consensus with no objections, per our normal decision making processes. If there are any outstanding comments in it, I will resolve them prior to the next CPC meeting (PR rendering on mobile isn’t perfect).

Reference: https://github.com/nodejs/community-committee/pull/526

**Comment by bnb** [comment]
Update: I've addressed all outstanding comments and requested changes ❤️

**Comment by mhdawson** [comment]
+1 from me.

**Comment by kborchers** [comment]
+1 LGTM

**Comment by MylesBorins** [comment]
LGTM

since this removes references from the board it might be good for an FYI to the board before landing.

**Comment by mhdawson** [comment]
Sent FYI to the board on 11/18/2019, asked for any concerns to be sent to me before the end of the week.

**Comment by mhdawson** [comment]
No comment/issues from the board, believe we are good to go once approved by the CPC

**Comment by mhdawson** [comment]
+1 from me.

**Comment by mhdawson** [comment]
Based on the requirements for approving charter changes (see https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#aproving-project-charters) I think this is ready to land.  (2 voting members @joesepi, @kborchers)

**Comment by bnb** [comment]
Merged. Thanks y'all 🎊
