### ISSUE TITLE
Travel request for projects in incubation?

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#388]
See https://github.com/nodejs/admin/pull/433

Opening this to confirm that we should be accepting travel requests from projects in the incubation phase.  @tobie  is the requestor somebody you know?

**Comment by tobie** [comment]
I don’t. Maybe @mrjoro does?

**Comment by tobie** [comment]
What's the best venue to have a private conversation about this particular request.

Also, I have a few questions wrt these travel funds:

- who makes the decision to approve requests?
- on what basis are those requests made?
- why is the process to ask for funds public?

**Comment by Trott** [comment]
> Also, I have a few questions wrt these travel funds:
> 
> * who makes the decision to approve requests?
> * on what basis are those requests made?
> * why is the process to ask for funds public?

For the Node.js travel fund (where this request was filed and which might be going away after December 31 with the advent of the wider OpenJS travel fund), most of the answers can be found at https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md.

**Comment by mhdawson** [comment]
@tobie 

>What's the best venue to have a private conversation about this particular request.

Maybe private period of CPC meeting this week?

**Comment by tobie** [comment]
Not a 100% sure I can make the call. But if so that would work.

**Comment by tobie** [comment]
Closed as per https://github.com/nodejs/admin/pull/433#issuecomment-550563005.
