### ISSUE TITLE
Collab Summit sessions

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#390]
We should have either one or more Collab Summit sessions at Node + JS Interactive. @jorydotcom and I were discussing some ideas. I can see this either being one session where we break out in to corners of the room based on interest or we register multiple sessions to accommodate areas where there is more interest. Some ideas:

- transition process and support for emeritus projects
- standards working group
- infrastructure
- project progression (acceptance/rejection, silent process, onboarding/offboarding)

**Comment by joesepi** [comment]
Perhaps also "blue sky thinking" session per @mhdawson

**Comment by joesepi** [comment]
I have updated the issue in the nodejs/summit repo with a more robust proposal: https://github.com/openjs-foundation/summit/issues/199#issuecomment-553000459

**Comment by joesepi** [comment]
I've started a document for the agenda here:
https://docs.google.com/document/d/1hdyWxXjCXUe1iEUqaQE8jvt38N6ckQomxTCtgkdisnU/edit?usp=sharing

**Comment by tobie** [comment]
Hi, I initially thought about adding a session about the relation between the Board and the CPC like so:

> ## Relationship between CPC and Board
>
> A number of important issues (such as the IP Policy or earmarked funds) are the prerogative of the Board, which is absolutely understandable. However, these policies impact projects in a way that can sometimes be important.
> 
> - Is the Board aware of this impact?
> - How does the Board and the CPC communicate?
> - How can project leads bring to the attention of the board issues that impact their projects but are the prerogative of the board?

If feels like this would be more productive as a joint session between the CPC and the Board (though maybe folks like me wouldn't be invited to it?). Is this something that's planned or that could be organized?

**Comment by tobie** [comment]
Filed https://github.com/openjs-foundation/summit/issues/228 and https://github.com/openjs-foundation/summit/issues/227.
