### ISSUE TITLE
onboarding meta questions

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#398]
Question 1:
Should all issues related to onboarding be moved to the onboarding repo, or just the issues specific to onboarding individual projects?

Question 2:
Looking at required files, such as a code of conduct file, do we also require uniformity in naming - 'CODE_OF-CONDUCT.md' vs. 'CoC.md' for example?

**Comment by mhdawson** [comment]
Question 2:

I think ideally we'd go for consistency.  Do we think it will be an issue to ask projects to use common naming for the Code of conduct?

Question 1: my preference is macro questions like Question 2 be in this repo, and the ones that are specific to on-boarding a specific project be in the on-boarding repo.

**Comment by ljharb** [comment]
I think GitHub prefers `CODE_OF_CONDUCT.md`, so I'm not sure why anyone would want a different filename.

**Comment by tobie** [comment]
> Question 1: my preference is macro questions like Question 2 be in this repo, and the ones that are specific to on-boarding a specific project be in the on-boarding repo.

Thank you for clarifying this. I've been wondering about this as I was filing issues about the onboarding process in this repo.

Additionally, and that ties in to #400, are project-specific issues expected to be filed in the project's own org (as [AMP is doing](https://github.com/orgs/ampproject/projects/4)), or on the onboarding repo, or is that tbd on a case per case basis?

**Comment by mhdawson** [comment]
If github perfers CODE_OF_CONDUCT.md, then that is what I'd want as well.

**Comment by mhdawson** [comment]
> Additionally, and that ties in to #400, are project-specific issues expected to be filed in the project's own org (as AMP is doing), or on the onboarding repo, or is that tbd on a case per case basis?

My personal take would be that anything that needs significant CPC interaction it would be make  sense to be in the onboarding repo.  If its something that does not need CPC interaction then the project repo makes more sense.  In some cases you might want a tracking issue in the onboarding repo if there is cross-over  where most of the work is within the project but you want some CPC input/visibility.

**Comment by tobie** [comment]
> My personal take would be that anything that needs significant CPC interaction it would be make sense to be in the onboarding repo. If its something that does not need CPC interaction then the project repo makes more sense. In some cases you might want a tracking issue in the onboarding repo if there is cross-over where most of the work is within the project but you want some CPC input/visibility.

Thanks @mhdawson. Where would be the right place to document this practice?

**Comment by mhdawson** [comment]
Not 100% sure. Two ideas are either as a document in the top level of the CPC level repo or in the README.md for the onboarding repo.  Not sure which will be more visible, be found most easily by the right people.

**Comment by joesepi** [comment]
To be clear, based on previous CPC meeting conversations:
Q1: Onboarding repo is place for all onboarding issues and documentation. Exceptions may arise but should be dealt with as they come.
Q2: We should follow Github naming conventions. Per COC, @mhdawson will update CoC proposal to advise there but otherwise, we will not be explicit
