### ISSUE TITLE
Point of contact for onboarding

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#400]
While there is a clear point of contact during onboarding (the project champion and a single mailing list address), it's not super clear who to contact during incubation to help answer project-specific questions or how to do so.

I've cc'ed @brianwarner on a number of issues here and on various AMP repositories, but that feels brittle; I'm not sure Brian's always the right person, and if he received those GH notifications, and thus whether or not someone is actually working on those.

I also have specific issues that I need the CPC to answer (e.g. https://github.com/ampproject/wg-foundation-onboarding/issues/2), and I'm not sure how to go about that either.

It would be helpful to have a better idea of how to proceed here. Maybe a dedicated incubation GH team we could assign issues to? Maybe an incubation champion?

Maybe a lot of this is already organized and I'm just not aware of it.

**Comment by brianwarner** [comment]
Assigning (as opposed to cc'ing) is a good way to ensure I see it.  It also allows me to reassign if I'm not the right person.

**Comment by tobie** [comment]
Right, but that requires:

- The applicant to be a member of this org and have [_triage_ permission](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization) for this repository (or the incubation one) and each repository in the Applicant's own org in which you might be susceptible to be assigned an issue. 
- You to be a member of each org that's in incubation and have _triage_ permission on each repository where you're susceptible to have an issue assigned.
- Any of your colleagues susceptible to have an issue re-assigned to them be a member of each incubation org and have _read_ permission on each repository in which they're susceptible to have an issue re-assigned to them by you.

That's certainly doable, but it would be good to have it written down so it can be organized all at once.

**Comment by joesepi** [comment]
Champion remains point of contact through incubation. Documentation needs to be updated to make that clear.

**Comment by mikesamuel** [comment]
As discussed, I will send out a doc update PR.

(I don't have perms to assign to myself yet.)

**Comment by mikesamuel** [comment]
IIUC, I should update [PROJECT_PROGRESSION](https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_PROGRESSION.md) and maybe link reference to "champion" in [STAGING_PROCESS](https://github.com/openjs-foundation/cross-project-council/blob/master/STAGING_PROCESS.md) to the requirements that they be able to push things before the council.
