### ISSUE TITLE
AMP application post-mortem (applicant's perspective)

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#402]
@jorydotcom suggested a post-mortem of the application process would be useful. Thank you Jory, that's a great idea!

As mentioned in the mailing list, here's what went really well:

* The timing! I still can't believe we pulled that off. Thanks again more meeting that deadline. That was very impressive.
* How welcoming the CPC was, how well it received my input upstream of the application, and how understandable it was of the requirements and needs of large corporate-backed projects, and how it didn't hold those against the project.
* Both the CPC and our champion were very responsive (thank you @kborchers!).
* The CPCs questions and requests were meaningful and positively impacted the project in ways that I hadn’t anticipated. For example, questions around the ads working group got that working group to improve its (public facing) documentation and process. It also made the project realize the discrepancy between how it thought working groups were presenting themselves to the world and how that was actually perceived from the outside, and take steps to bridge that gap.
* Working with the foundation staff to sync on the announcement was seamless (thank you @RRomoff!).
* Robin (thanks!!) and members of the CPC being able to come to the contributor summit (thank you @bnb and @MylesBorins!) when the announcement was made was incredible. Having Robin on stage was really meaningful to the community, and I felt the breakout session that happened afterward really built bridges and brought the community together. I really recommend organizing such a breakout every time it's possible. The perception from contributors is often negative about foundation-like structures. Having that face to face time really helped transform that feeling.

Here's what could be improved:

* More clarity around who the champion is (addressed by #321).
* Better communication to the applicant about the application process and where in that process we currently are (tracked in #340, pending a pull request on my part).
* A clearer handoff from the champion to the foundation staff handling the onboarding process, maybe a meeting with the Applicant, the Champion, and the foundation staff taking over the project would be ideal.
* In general, better handoff (e.g. from the champion to the marketing/PR folks for syncing on the announcement). My feeling is there just needs to be process around this.
* I had a great 1:1 conversation with @Jonahss from the CPC who wanted to better understand the AMP project and the philosophy behind it. I was a little worried about that call before it happened but it turned out fantastic and added a human connection to the application process. It also gave me room to talk more genuinely about the project. I would strongly recommend building more face to face time into the application process.
* Calls are great. Video calls are much better. They help build rapport and they also make it easier to follow conversations for non-native speakers like me.

I thoroughly enjoyed working with you all, and I'm looking forward to do so more. <3

**Comment by mhdawson** [comment]
@tobie thanks for the great summary.  All of your questions and additions to the process and documentation are appreciated.

**Comment by eemeli** [comment]
@tobie Are there remaining tasks/questions for this issue, or should it be closed?
