### ISSUE TITLE
Github Admin

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#409]
Who are the admin on this org? How are they determined? I looked to do some admin tasks and I couldn't.
As a side note, can somebody add me to the summit repo maintainers?

**Comment by bnb** [comment]
+1 to better documenting this and also to adding Matteo as an admin to the summit repo.

**Comment by MylesBorins** [comment]
Oh hey, I think that this is me because I created the org. Who else should I add?

**Comment by mcollina** [comment]
All the CPC members? Or at least the voting members.

Il giorno mer 20 nov 2019 alle ore 19:32 Myles Borins <
notifications@github.com> ha scritto:

**Comment by kborchers** [comment]
I think all voting members seems reasonable. We should also document this in any voting member onboarding/offboarding processes.

**Comment by MylesBorins** [comment]
will wait for a few more folks to +1 the idea of voting members and then I'll go ahead and add them.

**Comment by MylesBorins** [comment]
Should foundation staff be included too?

**Comment by brianwarner** [comment]
Yes please, it would be helpful.

**Comment by MylesBorins** [comment]
I've made all voting members and @brianwarner owners of the org. I still remain an org owner.

Perhaps we can discuss in next meeting and confirm this is how we want to do it and if we want regular members to also be owners or not

**Comment by bnb** [comment]
Is there context for the necessity of Foundation staff to be owners? Not explicitly against it would just like to have reasoning documented / asserted ❤️

**Comment by mhdawson** [comment]
+1 to discussing in next meeting.

**Comment by mhdawson** [comment]
Discussion in CPC meeting was that both voting and regular members should be org owners.

**Comment by jorydotcom** [comment]
Action Items on Jory:
- All CPC members to be org owners
- Circle back with folks who do not have 2FA

**Comment by jorydotcom** [comment]
Reporting back that those action items are completed and I believe this issue can be closed.
