### ISSUE TITLE
December CPC Meeting Planning

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#417]
Per our brief discussion today, we are proposing to cancel the following CPC meetings in December due to holidays and Node + JS Interactive event travel:

* Tues., Dec. 10 (Node + JS Interactive)
* Tues., Dec. 24 (Winter Holiday)
* Tues., Dec. 31 (New Year Holiday)

**Comment by mcollina** [comment]
SGTM

**Comment by mhdawson** [comment]
SGTM

**Comment by bnb** [comment]
Unfortunate but SGTM

**Comment by mhdawson** [comment]
SGTM

**Comment by MylesBorins** [comment]
Seems like we have consensus, closing
