### ISSUE TITLE
Mocha: project charter review

### ISSUE THREAD

**Issue by boneskull** [openjs-foundation/cross-project-council#419]
Mocha has added a project charter which needs review by the CPC:

[Mocha's Charter](https://github.com/mochajs/mocha/blob/master/PROJECT_CHARTER.md)

I'm not sure if I was supposed to merge it first, or run it by the CPC first _then_ merge it, but whatever. 😝  We can change it if necessary.

@jorydotcom I'm not sure how we'd like to run this review process?  Here's the [original pull request](https://github.com/mochajs/mocha/pull/4088) which people could comment on.

**Comment by christian-bromann** [comment]
The WebdriverIO project recently also created a [project charter](https://github.com/webdriverio/webdriverio/blob/master/PROJECT_CHARTER.md). I noted that in the [on-boarding issue](https://github.com/openjs-foundation/project-onboarding/issues/21#issuecomment-559572366) but happy to create an issue here too if that is the desired process.

**Comment by eemeli** [comment]
I've read through and approve of Mocha's charter.

**Comment by mcollina** [comment]
Approved

**Comment by joesepi** [comment]
§ I approve

**Comment by jorydotcom** [comment]
This has met the requirements per our governance document and has been approved!
