### ISSUE TITLE
WebdriverIO: project charter review

### ISSUE THREAD

**Issue by christian-bromann** [openjs-foundation/cross-project-council#424]
WebdriverIO has added a project charter which needs review by the CPC:

[WebdriverIO's Charter](https://github.com/webdriverio/webdriverio/blob/master/PROJECT_CHARTER.md)

**Comment by eemeli** [comment]
I've read through and approve of WebdriverIO's charter. I noticed a few typos in the doc, and added a PR to fix them.

For reference, [here's our policy](https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#aproving-project-charters) for approving project charters.

**Comment by joesepi** [comment]
I approve.

**Comment by mcollina** [comment]
I approve

**Comment by MylesBorins** [comment]
Generally looks good to me. Sounds like you are good on TSC not having more than 1/3 would be good to confirm that.

**Comment by christian-bromann** [comment]
Members of the TSC and their employers are:

- @abjerstedt (Target)
- @erwinheitzman (Malmberg)
- @klamping (self employed)
- @mgrybyk (Ciklum)
- @WillBrock (Focus School Software)
- me (Sauce Labs)

**Comment by christian-bromann** [comment]
Removed the section on sponsorship in webdriverio/webdriverio#4884 as we are not utilizing any funding opportunities yet.

**Comment by mhdawson** [comment]
I approve

**Comment by jorydotcom** [comment]
Per today's CPC meeting, this charter has been accepted and the issue can be closed. Thank you @christian-bromann & the Webdriver team!
