### ISSUE TITLE
Start a Code of Conduct Team

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#432]
CoC Proposal is at Stage 2 but there is some consensus that it should be moved back to Stage 1 as we don't have full agreement on the aspects of CoC, including but not limited to documentation, moderation, reporting.

There were also a lot of good conversations at the Collab Summit around these three aspects and a number of volunteers to spin up a CoC team. The expectation is that this working group would work to shape the CoC implementation but is not the Code of Conduct Panel that would do moderation.

To begin, this team, it is expected that a repo would be created with a README that defines goals.

Edited: I incorrectly said it was at Stage 3.

**Comment by MylesBorins** [comment]
@joesepi I beleive it is at stage 2 and should be moved back to stage 1

**Comment by eemeli** [comment]
I would be interested in joining this working group.

I'm not sure that the current CoC proposal should be moved back from Stage 2 to Stage 1, as that would probably encourage feature creep. I think the actual contents of the proposal are relatively well agreed-to; the open questions are in addition rather than instead of the proposal. Instead I think we (or the working group) should draft a second CoC proposal for further development.

**Comment by mhdawson** [comment]
I'm in favor of what @eemeli suggested. It's better to get the parts that we have agreed documented if we believe that future changes will be mostly additions to scope versus changes to what is documented.

**Comment by mhdawson** [comment]
I'd be interested in being part of the team/working group.

**Comment by mhdawson** [comment]
In my mind the first steps are to answer the following questions:

1) Minimum viable CoC process. How close is the current proposal to that ?

2) What extensions would make sense, and do the projects agree to that.

**Comment by joesepi** [comment]
My quick notes from today's meeting:
---
Create a COC TEAM repo; capture issues for MVP and beyond'

Stepped up: Joe, Jory, Ben Michel

Write a problem statement to encapsulate what it is this group is going to work on
Send out invitation to projects
And to github
=> we want help

**Comment by jorydotcom** [comment]
For handy reference during our meeting, here's a link to the doc we started to work on the problem statement [https://hackmd.io/mxRxf239RPKJsiokQ94QGg](https://hackmd.io/mxRxf239RPKJsiokQ94QGg)

**Comment by joesepi** [comment]
First question: Is this a viable MVP? https://github.com/openjs-foundation/cross-project-council/pull/379

**Comment by eemeli** [comment]
As I've mentioned previously, I think we have a viable MVP in the currently-stage-2 proposal, and that we can advance with it while we simultaneously work on its improvements and expansion.

**Comment by jorydotcom** [comment]
A doodle poll has been created [here](https://doodle.com/poll/m2dgtnrn9ga5zq44) to organize this first ad hoc call.

**Comment by jorydotcom** [comment]
The poll was closed and the meeting scheduled for tomorrow, Wednesday 2/12: 

Topic: CPC Code of Conduct Ad Hoc Meeting
Time: Feb 12, 2020 02:00 PM Eastern Time (US and Canada)

Join Zoom Meeting
https://zoom.us/j/220602536

Meeting ID: 220 602 536

One tap mobile
+16465588656,,220602536# US (New York)
+16699006833,,220602536# US (San Jose)

Dial by your location
        +1 646 558 8656 US (New York)
        +1 669 900 6833 US (San Jose)
        855 880 1246 US Toll-free
        877 369 0926 US Toll-free
        +1 647 558 0588 Canada
        855 703 8985 Canada Toll-free
Meeting ID: 220 602 536
Find your local number: https://zoom.us/u/akVmLCTid

**Comment by nainar** [comment]
Sorry @tobie should have answered - I am happy to join the call! See you all tomorrow!

**Comment by jorydotcom** [comment]
Following up here to share some high level outcomes and also the meeting notes. The notes were captured in the [hackmd doc](https://hackmd.io/@ra-6t4fuRmeQNH1J5Rzv3A/S1Pgvi2xL) and that doc's permissions have been updated so it is no longer editable. I will PR them in to the repo shortly.

* Decision: The PR in #379 meets our criteria for stage 3 and should be merged
* Decision: The individuals who raised their hands for participation in the ad hoc CoC working group should become the first group of persons in the reporting@ group
* Decision: That group should further define process and seek to grow its membership in terms of diversity and in terms of participation from OpenJS projects

@mhdawson @joesepi @brianwarner @rginn please lmk if you have other high-level takeaways to add.

**Comment by joesepi** [comment]
Considering we have had our initial meeting and have other issues open to act upon, it was decided in today's cross-project-council meeting to close this issue. Cheers!
