### ISSUE TITLE
Enforcing org wide 2FA

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#437]
Hey All,

We had discussed in a prior meeting enforcing 2FA org wide. I just checked and we no longer have any members in the org with 2FA disabled. As such I took the liberty to turn on 2FA enforcement, meaning that any new members will need to enable 2FA before joining the org.

If anyone thinks I've acted out of line please feel free to chime in. It was my impression we had consensus on this and were waiting for folks to enable. This change should have no affect to current members.

**Comment by mcollina** [comment]
Good job Myles, and thanks for taking care of this.

**Comment by mhdawson** [comment]
+1

**Comment by sendilkumarn** [comment]
Good one @MylesBorins

**Comment by antsmartian** [comment]
+1.. Nice work @MylesBorins 🎉 🎉

**Comment by jorydotcom** [comment]
Thanks @MylesBorins! I def. missed that when I closed #409

**Comment by bnb** [comment]
+1 thank you.

**Comment by ljharb** [comment]
This seems closeable now :-) please reopen if I’m wrong.
