### ISSUE TITLE
2nd Director seat- post July 2020

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#438]
We agreed in the last CPC meeting that the first term for the CPC director representatives would be July 1
1st.

As per the CPC governance, the 2nd director seat was elected by the Node.js project for the first year.  This issue is to start the discussion around what we'll do with the second seat the following year. Some options include:

* Continue to allow Node.js project to elect 2nd director
* Have the CPC select the 2nd director in the same manner as the first
* Allow some other impact project elect 2nd director
* Come up with some other approach for electing the 2nd director.

@openjs-foundation/cpc please chime in with your thoughts.

@mcollina, @joesepi and myself should collect feedback from the Node.js project (TSC, CommComm etc.) to bring the viewpoint of the project (in addition to our individual viewpoints) to the discussion.

**Comment by mcollina** [comment]
I'll send an email to tsc and commcomm.

**Comment by joesepi** [comment]
A request borne out of discussions in the Node.js Community Committee: if the new rep is not from the Node.js project, it would be ideal to have a regular (monthly?) update from the board delivered by the rep in the two top level Node.js meetings (TSC/Community Committee).

**Comment by joesepi** [comment]
Node.js TSC and Community Committee:
>The Node.js project is happy to continue to provide a director representative and has people who are willing to volunteer for the position. If the CPC decides to no longer have the Director seat assigned to the Node.js project, the project would like to be consulted/involved in the discussion.

**Comment by dylans** [comment]
My suggestion during this week's CPC meeting was that we should outline what the board member is expected to do. This will help us determine if there's interest from any other projects in participating. We know this position requires a lot of effort, so we want to make sure that someone knows what it would entail, etc. Thanks!

**Comment by jaskirat2000** [comment]
This is great. I shared my interest.

**Comment by joesepi** [comment]
We left this ticket open as we worked through the process of board seats and elections. That process has culminated in this PR: https://github.com/openjs-foundation/cross-project-council/pull/587

This issue is specific to the direction of the secondary CPC Director seat, which I believe is settled.
