### ISSUE TITLE
Meta: Where shall certain resources live?

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#445]
We have some documentation that's been created for projects such as:

* infrastructure menu of services
* slide deck about Marketing services

And I imagine as we onboard more projects and help them get started, we will want to create other similar guides that help projects get familiar with what we can do to help. Where shall documents like this live long-term?

**Comment by jorydotcom** [comment]
More to the point, I'm afraid that just creating them as .md files in this repo will hurt their discoverability.

**Comment by mhdawson** [comment]
@jorydotcom do you have suggestions of where they would be better discoverable?

I agree that as the content grows some structure will help.  Did you have something in mind like a sub-directory called "Foundation Services" or a repo with a similar name?

**Comment by brianwarner** [comment]
How about a repo called "foundation"? It's a convention used in other projects, and opens the opportunity to set up an issue tracker for Foundation-specific tasks.

**Comment by jorydotcom** [comment]
Hmmm. @brianwarner I feel like that might not be the obvious place for a new project / community member to look - I don't know that I would think to look under 'Foundation'. I feel like I want something like 'Project Resources' or 'Project Benefits' or something?

**Comment by mhdawson** [comment]
My thinking is in line with @jorydotcom I think we need a name that will make people think its a list of resources/benefits that they can access.
