### ISSUE TITLE
Google Summer of Code 2020

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/cross-project-council#458]
The deadline for GSoC is February 5th.  Would anybody like to mentor? 

If so, please respond to this issue with confirmation that you have the time and intent to be a mentor, and one or more ideas using this template:  
* Project title:
* Short description:
* More detailed description of the project (2-5 sentences):
* Expected outcomes:
* Skills required/preferred:
* Mentor:
* Easy/Medium/Hard rating:
* Application instructions (e.g., what do you need to know?  What are the prerequisites?  What skills are mentors looking for?): 

This is open to all OpenJS Foundation projects!

I will consolidate and submit the application if we have any interested projects/mentors.

**Comment by maddhruv** [comment]
I would love to mentor, not sure on which projects to pick up and submit.

**Comment by joesepi** [comment]
Seems like this is a missed opportunity now that the Feb 5 deadline has passed. Bummer as it is a great initiative. We can try next year with more advanced notice and rally folks to get involved. Thanks for bringing it up @brianwarner -- please close this issue if we are not planning to be involved.
