### ISSUE TITLE
OpenJS Office Hours

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#465]
See what I did there?
OpenJS Open Office Hours? (The "Ours" is intentional -- it is, afterall, OURS! 😄 )

I proposed something this in Node.js Community Committee (https://github.com/nodejs/community-committee/issues/543) but I think it makes more sense to elevate it to the OpenJS level.

I'd like to encourage, onboard, enable, and support new and existing contributors to OpenJS projects. I'll focus on Node.js but will do my best to be a conduit to other projects as well.

My first meeting will be today at 1pm ET and will repeat bi-weekly.

I encourage others who are interested to join the call and/or the initiative. If you are interested in helping but will skip the open calls, I understand and will do my best to connect dots from any interested contributors to project leads and committers.

Please share far and wide. :)

https://zoom.us/j/478648416

**Comment by wesleytodd** [comment]
@joesepi Will you add this to the OpenJS Calendar?  I didn't see it on there, or did I just miss it?

**Comment by joesepi** [comment]
@wesleytodd its on the calendar now! Let's connect very soon about an Express focused section of the next meeting. 🙌

**Comment by mhdawson** [comment]
If you want to do a particular session that you think me being there would help just let me know.

**Comment by joesepi** [comment]
This is happening. See more here: https://github.com/openjs-foundation/open-office-hours
