### ISSUE TITLE
OpenJS Collaboration Network ?

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#474]
This outlines an idea I've been thinking about.  @openjs-foundation/cpc let me know if you think this makes any sense.

# The OpenJS Collaboration Network

The formation of the OpenJS Foundation was in support of a number of goals. 
The first was to support JavaScript projects, providing a neutral place for people to collaborate and resources needed by those projects (legal, marketing, best practices governance support, infra, etc.).

Good progress has been made on this front with governance for accepting and onboarding projects having been defined and the first projects working through the process.

The second goal was to foster greater collaboration in the JavaScript ecosystem.  Bringing
projects together in a single Foundation provides an easier path to collaboration between projects. We see this collaboration starting,  for example, in the formation of the Standards
working group. However, I feel support for collaboration efforts should be broader than that scope.

The OpenJS Foundation should act as a neutral place for people to collaborate on areas of
importance to the JavaScript ecosystem. In some cases, this may align with projects and in
other cases be independent of the member projects. Regardless of the alignment with existing
member projects, the OpenJS Foundation should provide support for collaboration in
a particular area.  Support could include but not be limited to:
* a repo in the OpenJS org
* marketing support
* mailing lists
* slack channels
* etc.
* representation on the CPC

In the same way, as we have a process/governance for reviewing projects that wish to join
the Foundation we could have process/governance for applications to start a new
`OpenJS Collaboration Space`.  Those submitting the application need not be within
member projects and the application would be reviewed/accepted by the CPC as is the
case with projects.

My hope is that this approach would help provide more focus/support for collaboration
as an effort independent from member projects.

Some of the `Collaboration Spaces` that I could envision include:

* Security 
* Test
* Runtimes (Node.js, electron, WASI, etc/.)
* Web Frameworks (Express, Fastify, Hapi, etc.)
* JavaScript Standards (existing Standards team?)
* Package management (npm, yarn)
* Registries, local caches
* Package ecosystem (Package-maintenance team in Node.js ?)

One key question is if this would better support collaboration versus just
adopting `Working Group` governance along the lines of what was supported
in the Node.js space. One area that would be different is that responsibility
would not necessarily be delegated from the CPC, as the "Space" might cover
an area with is outside the charter of the CPC, much like responsibility the
work in a specific project is outside the scope of the CPC.

**Comment by mcollina** [comment]
Definitely +1.

We should charter them somehow, and make sure there is some moderation in place.
I'd rather call them working groups anyway.

**Comment by juanpicado** [comment]
> as we have a process/governance for reviewing projects that wish to join
the Foundation we could have process/governance for applications to start a new
OpenJS Collaboration Space

I ❤️  this idea, but I have a doubt, could a project which begins under  `OpenJS Collaboration Space` move eventually join the foundation?

**Comment by mhdawson** [comment]
@juanpicado I see them being different but complementary. 

A collaboration space is for people to collaborate on a topic outside of a specific project.  If that collaboration results in one or more open source projects then those projects may later join the foundation. 

 For example, imagine if there were no JavaScript test frameworks today.  A collaboration space could be formed around how to test JavaScript.  The ideas which come out of that might result in the creation of one or more new projects, each of which could later decide to apply to join the Foundation.

Closer to reality, given that there are already JavaScript test frameworks, representatives from those projects could form a Test collaboration space to come together to collaborate on improving the methods, approaches for testing JavaScript but whether any of those projects choose to apply to join the Foundation would be independent of the work in the collaboration space.

**Comment by sendilkumarn** [comment]
Wow this is awesome ❤️ We should definitely do this. 

I'm also align towards calling them as `Working Group`.

**Comment by juanpicado** [comment]
Thanks for the explanation, I would like to be part of
the Registries, local caches group.

**Comment by mhdawson** [comment]
@juanpicado those groups were just examples of what I had in mind.  If we agree this is a good idea then we'd be looking for people to propose/lead different groups.

**Comment by mhdawson** [comment]
Myles comment in meeting "community group"?

**Comment by wesleytodd** [comment]
In generally I am a big 👍 to this.  I think that providing a more formal space for this is a good service the Foundation can offer.  Thinking about the slack groups we have, it is clear that there is a need for spaces to talk about this stuff, and it is just fragmented today.

> Working Group governance along the lines of what was supported
in the Node.js space

This seems reasonable to me.

> Web Frameworks (Express, Fastify, Hapi, etc.)

This is basically what we setup the Node.js Web Server Frameworks Team for.  I have some ideas about the differences, but can you talk about how you see this as different from what we have today?

**Comment by mhdawson** [comment]
@wesleytodd, I was just trying to list areas that it might make sense for.  So not necessarily any different except that it would possibly be at the OpenJS level and a bit more formally recognized.  Alternatively, it may make sense to leave it as part of the Node.js project. I don't have a strong opinion on that yet.

**Comment by mhdawson** [comment]
Initial cut at a PR for the proposal: https://github.com/openjs-foundation/cross-project-council/pull/497

**Comment by mhdawson** [comment]
Closing since this is moving through the proposal process. Ex: https://github.com/openjs-foundation/cross-project-council/pull/557
