### ISSUE TITLE
Transfer openjs-foundation npm org admin rights

### ISSUE THREAD

**Issue by mikesamuel** [openjs-foundation/cross-project-council#475]
https://www.npmjs.com/org/openjs-foundation exists.

I hold them currently.  @brianwarner has set up an alias.
Once that alias can have admin rights I will transfer.

**Comment by brianwarner** [comment]
Great idea registering this, @mikesamuel, and thanks for bringing it to my attention. The organizational account (https://www.npmjs.com/~openjsfoundation) is now set up.

**Comment by mikesamuel** [comment]
Oh, did I create the wrong kind of org?

**Comment by mikesamuel** [comment]
openjsfoundation is now an owner of openjs-foundation so should be able to demote me now.

**Comment by joesepi** [comment]
Confirmed with @brianwarner that this is good to close. Thanks everyone.
