### ISSUE TITLE
Projects with Windows and Mac installers?

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/cross-project-council#476]
We recently had to update the signing cert for Node that allows for signed and notarized installers on OSX.  From talking with Rod Vagg, there's a similar process for creating Windows installers.

During the last board meeting we'd discussed whether other projects in the Foundation with Windows or OSX installers might want the ability to sign them (and avoid the untrusted software warnings).

Can you please reply to this issue if you are interested in this for your project?

**Comment by mhdawson** [comment]
@jorydotcom can you put together and email to the projects to solicit info.

The key questions are:
* Do you have windows/mac installers and need to maintain certificates/development accounts etc. to be able to sign them?
* Would it be beneficial for the Foundation to manage the accounts (ex Apple developer account), handle paying for certificates
* Would it be ok if the signing was in the name of the Foundation or does it need to be project specific (ex installed signed on Behalf of OpenJS Foundation or instead the specific project (ex Node.js))

@brianwarner let me know if I got this incorrect.

**Comment by jorydotcom** [comment]
message sent! I've also added you and @brianwarner so you can track the responses as they come in.

**Comment by mhdawson** [comment]
@jorydotcom thanks !

**Comment by brianwarner** [comment]
@mhdawson that list of questions looks great, good call on the email.

@jorydotcom thank you so much for doing this!

**Comment by jorydotcom** [comment]
JIK people missed the email and come here needing the survey link: https://forms.gle/Xnv1SneGpSeQ8G3D8
