### ISSUE TITLE
webhint: project charter review

### ISSUE THREAD

**Issue by molant** [openjs-foundation/cross-project-council#482]
One of the checklist items is to get the charter of the project approved by the CPC.

We've created a new one and [merged it as draft](https://github.com/webhintio/hint/pull/3416).
I'm opening this issue to kick start the official review of webhint's charter by the CPC before removing the `-draft` suffix.

Thanks 🙏

**Comment by mhdawson** [comment]
Looks reasonable to me.

**Comment by joesepi** [comment]
LGTM

**Comment by molant** [comment]
Looking for official review of webhint's charter by the @openjs-foundation/cpc members to get it approved.

**Comment by eemeli** [comment]
LGTM

**Comment by designMoreWeb** [comment]
This looks great :)

**Comment by mcollina** [comment]
SGTM

**Comment by timmywil** [comment]
+1

**Comment by joesepi** [comment]
My official 👍

**Comment by dmethvin** [comment]
:+1:

**Comment by joesepi** [comment]
Consider this approved. Thanks all.
