### ISSUE TITLE
OpenJS in Google Season of Docs

### ISSUE THREAD

**Issue by codeekage** [openjs-foundation/cross-project-council#485]
Hello All --

Bringing this to our attention. I think it will be good for us to get involved and leverage the opportunity to improve documentation across the OpenJS _(JS)_ ecosystem.

Once registration opens. Just want to us have this on our radar if it's something that'll love to participate in this year. https://developers.google.com/season-of-docs/docs

cc: @MylesBorins @brianwarner

**Comment by maddhruv** [comment]
Hey @codeekage is it [Season of Docs](https://developers.google.com/season-of-docs) or Google Summer of Code, for which we already have an issue - https://github.com/openjs-foundation/cross-project-council/issues/458

**Comment by codeekage** [comment]
Season of Dcos. :)

**Comment by codeekage** [comment]
Hey All - 

Don't know if this something we'll want to do Foundation-wide, but there are some benefits it brings to member projects. 

Here's a link to the timeline https://developers.google.com/season-of-docs/docs/timeline

**Comment by MylesBorins** [comment]
I think this makes sense on a per project basis tqbh, the projects need to be scoped

**Comment by MylesBorins** [comment]
Node specific issue https://github.com/nodejs/admin/issues/483

**Comment by codeekage** [comment]
True. I'm going to close this now.
