### ISSUE TITLE
[Action Requested] Nominations Sought for 2020-2021 Voting CPC Membership 

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#488]
Attention: Impact, At Large, and Growth stage Project Leads & CPC representatives,

I'm excited to inform you that the nomination period for CPC Voting Representative is now open for the 2020-2021 term, which begins on April 1.

**We're looking for:**

- nominations for up to two representatives each for Impact-level projects.
- nominations from across the Growth & At Large projects for a total of two representatives from these project stages.

All nominees are expected to be able to abide by our Code of Conduct and the Member Expectations outlined [here](https://github.com/openjs-foundation/cross-project-council/blob/master/MEMBER_EXPECTATIONS.md). 

**Responsibilities of voting CPC representatives:**
Voting CPC Representatives are expected to:

- Commit the time necessary to participate regularly in CPC meetings.
- Participate in all voting matters (either by voting or explicitly abstaining)
- Stay abreast of CPC business, and respond or engage in a timely manner to questions or issues. 
- Enable the work of regular CPC members and Foundation staff by providing direction and input.

The responsibilities described above reflect a time requirement averaging 1-3 hours per week. Voting CPC reps are also eligible to hold positions on the CPC, such as Chair and Board Rep, which would increase the time commitment needed.

More information on voting CPC members (and other member categories) can be found [here](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#section-4-establishment-of-the-cpc).

**Submit your nominations**
The nomination period begins Tuesday, March 10 and concludes Tuesday, March 24.

Submit your name or the name of your project's nominee to the CPC Chair, Joe Sepi, via email: joesepi@ibm.com.

All nominees will be posted on the GitHub issue once the voting period has closed.

**Voting**
Nominees from the At Large & Growth projects will be elected via a vote, executed by Foundation staff once the nomination period has closed. See https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#election-process-for-non-impact-voting-cpc-members for more details.

Nominees from Impact level projects are elected or chosen at the project's discretion and in accordance with the project's governance.

**Comment by joesepi** [comment]
Below I will list the candidates for the next term of CPC Voting Members by Impact and non-Impact projects.

[Current guidance from our CPC Charter](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#voting-members) is the following:

# Voting members

Voting members are selected as follows:

- Each Impact project may nominate up to two members through a process of their choosing. Once nominated the member must be ratified by the CPC Voting members before becoming a Voting member.

- up to two Voting members may be nominated by the non Impact projects based on a process set by the CPC.

- up to two Voting members may be nominated by the Regular members. Once nominated these members must be ratified by the CPC Voting members before becoming a Voting member.

---

As such, I will list the nominees below grouped by Impact projects and then non-Impact projects.

The third bullet point above---up to two Voting members may be nominated by the Regular members---is not something I believe we've done before, but is something I wanted to call out here. This should be discussed in another issue: #504

You may also notice that I included a nominee from an incubating project. The Charter states two members may be elected from non-Impact projects and therefore I've included this nominee. If others disagree or if I am missing some clarifying documentation, please speak up. Thank you.

If I've missed a nomination in my email or some other oversight has occurred, please comment here or contact me directly as soon as possible: joesepi@ibm.com

## CPC nominations

### Node.js
- Matteo Collina (@mcollina)
- Joe Sepi (@joesepi)

### Dojo
- Dylan Schiemann (@dylans)

### jQuery
- Dave Methvin (@dmethvin)
- Timothy Willison (@timmywil)

### Non-Impact Level Projects
- Tobie Langel - AMP (@tobie)
- Anton Molleda - webhint (@molant)
- Nicholas O’Leary - Node-RED (@knolleary)
- Christopher Hiller - Mocha (@boneskull)
- Kris Borchers - architect (@kborchers)
- Eemeli Aro - messageformat (@eemeli)

🎉

**Comment by joesepi** [comment]
Per our [Governance]https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#election-process-for-non-impact-voting-cpc-members), each of the non-impact level project nominees need to  open an issue in the CPC repo which includes the following:

- Projects they are part of
- Description of their background
- The reasons they would like to act as a non-impact CPC voting member
- Confirmation that they can devote the required time/effort.
- Their employer (if applicable). This is needed due to the limitations on maximum employer representation in the CPC voting members.

Please do so at your earliest convenience. @tobie @molant @knolleary @boneskull @kborchers @eemeli 

Thank you! 🗳

**Comment by joesepi** [comment]
Our plan is to start voting next week: April 7!
Voting will remain open for 1 week.
Elected voting members will be announced the following meeting: April 14!

🗳 🎉

**Comment by boneskull** [comment]
Here's me: #510

**Comment by knolleary** [comment]
My nomination issue: #511

**Comment by kborchers** [comment]
I added my statement earlier this week but to ensure folks can find it I will follow the trend and add the link here 😃 #507

**Comment by tobie** [comment]
My nomination issue: #514

**Comment by joesepi** [comment]
The voting period has closed. The winners are:

- **Mocha**: Christopher Hiller (@boneskull, IBM)
- **AMP**: Tobie Langel (@tobie, UnlockOpen)

Thank you to all nominees. Congratulations to Chris and Tobie.

**Comment by joesepi** [comment]
PR open to update README. https://github.com/openjs-foundation/cross-project-council/pull/519
