### ISSUE TITLE
Document employers of voting members in README.md

### ISSUE THREAD

**Issue by bnb** [openjs-foundation/cross-project-council#491]
Given that [our charter](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#section-4-establishment-of-the-cpc) includes the following:

> No more than one-fourth of the Voting CPC members may be affiliated with the same employer.

I think it would be relatively reasonable to list employers within the `README.md`, associated with each individual voting member. Ideally, this will help increase transparency in-line with our charter.

**Comment by jorydotcom** [comment]
@bnb great idea! Shall we implement that when we merge the new voting members in, since that's only like 2 weeks away?

**Comment by bnb** [comment]
@jorydotcom that sounds totally reasonable to me 👍

**Comment by joesepi** [comment]
This is done now with the new crop of voting members coming in.
https://github.com/openjs-foundation/cross-project-council#cpc-members
