### ISSUE TITLE
add code of conduct and moderation information to openjsf.org

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#502]
noticed the code of conduct is nowhere to be found on the website

https://openjsf.org/

**Comment by joesepi** [comment]
@brianwarner has a good idea commented in a related issue: https://github.com/openjs-foundation/cross-project-council/issues/503#issuecomment-603900978

**Comment by joesepi** [comment]
Until we sort out #503, perhaps we can just have the subdomain link to the CPC CoC and then surface it clearly on the openjsf.org site, @brianwarner ?

**Comment by brianwarner** [comment]
Sure!

* https://code-of-conduct.openjsf.org now links to the CoC file in the CPC repo
* The Code of Conduct is now referenced on https://openjsf.org/collaboration
* There is now a Code of Conduct menu item under "About"

**Comment by joesepi** [comment]
Thanks @brianwarner and @MylesBorins
