### ISSUE TITLE
Voting members chosen by Regular members

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#504]
As mentioned in the current nominations/voting issue here: #488 

[Current guidance from our CPC Charter](https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#voting-members) is the following:

# Voting members

Voting members are selected as follows:

- Each Impact project may nominate up to two members through a process of their choosing. Once nominated the member must be ratified by the CPC Voting members before becoming a Voting member.

- up to two Voting members may be nominated by the non Impact projects based on a process set by the CPC.

- up to two Voting members may be nominated by the Regular members. Once nominated these members must be ratified by the CPC Voting members before becoming a Voting member.

---

The third bullet point above---up to two Voting members may be nominated by the Regular members---is not something I believe we've done before, but is something I wanted to call out here. 

I assume we should consider this process and call for nominees and vote following the current voting process for project related nominees/votes.

**Comment by mhdawson** [comment]
You are correct that we've not done it before.

**Comment by mhdawson** [comment]
I also agree its a good time to discuss if we should start that now as well.

**Comment by mcollina** [comment]
I'm +1 for electing them.

**Comment by joesepi** [comment]
I propose that after the current election period for project-related voting members, we go through this process of nominations and voting.

**Comment by joesepi** [comment]
Nominations for voting members from the regular members is open and will conclude in 1 week.

**Comment by tobie** [comment]
Regular members are listed in the [README](https://github.com/openjs-foundation/cross-project-council#regular-members) and so is the process of becoming a regular member.

**Comment by joesepi** [comment]
Please self nominate here! :)

**Comment by mhdawson** [comment]
I'd like to self nominate.

Not sure whether there will be a Node.js board director this year and if not I'd like to volunteer to be one of the CPC board members which requires being a voting member.

**Comment by kborchers** [comment]
I would also like to self nominate.

I would also like to volunteer to continue on as one of the CPC board members when that time comes. If you would like more info about me, [here is a link](507) to my nomination from the previous project voting member election. Thanks!

**Comment by timmywil** [comment]
Are we allowed to nominate members that are also staff? If so, I'd like to nominate @jorydotcom

**Comment by mhdawson** [comment]
I think the governance just says "regular members" without any additional conditions.  +1 to @jorydotcom's nomination if she's interested.

**Comment by eemeli** [comment]
I'd like to self-nominate. For a bit more information about me, see my nomination issue #505.

**Comment by jorydotcom** [comment]
Hi All - we are going to close nominations for this Tuesday, May 5 at 11:59 p.m. EST. If you haven't already done so and would like to nominate, please do so on this thread. Candidates are encouraged to submit a candidate statement along with their nomination or as a separate issue. 

Our current nominees are:

* Eemeli Aro - @eemeli - [candidate statement](https://github.com/openjs-foundation/cross-project-council/issues/505)
* Kris Borchers - @kborchers - [candidate statement](https://github.com/openjs-foundation/cross-project-council/issues/507) 
* Michael Dawson - @mhdawson 

We are running this election using an election tool called [OpaVote](https://www.opavote.com/).  Only regular CPC members are eligible to vote. Voting instructions will be presented on Wednesday, after the nomination period has closed.

---
*side note - thank you @timmywil @mhdawson for suggesting and supporting my own nomination;  however I've decided that it might create too much confusion to serve in this capacity while also being a member of foundation staff.*

**Comment by jorydotcom** [comment]
Hi everyone, issuing one last final call for nominees before I open the election... 

on our CPC meeting call today we agreed to use opavote and the [ScottishSTV method](https://www.opavote.com/methods/single-transferable-vote#scottish-stv) for this election. The eligible voters are the [regular members](https://github.com/openjs-foundation/cross-project-council#regular-members).
