### ISSUE TITLE
Nomination for CPC Voting Membership: Eemeli Aro

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/cross-project-council#505]
Hi, I'm @eemeli, and I maintain [messageformat](https://www.npmjs.com/package/messageformat), an at-large OpenJS project. As mentioned in #488, I'm interested in being re-selected to be a voting member of the CPC.

I've been an open-source developer since 2007, and I really like fixing things at the right level. Most code we write is only really used for one particular thing, but libraries and tools get used repeatedly, all over the place. The way I see it, application code does not need to be perfect or even beautiful, as long as it works -- but stuff that's used more often needs to be that much better. A step beyond that I'd put APIs, and further than that, the standards and structures that provide the foundations for our shared ecosystem. Hence my interest in the CPC, and helping to make sure that it can help all of us create more, and be more.

I've been decently active in the CPC over the last year, as well as the [Standards team](https://github.com/openjs-foundation/standards). I'm currently representing the foundation in the [Unicode MessageFormat Working Group](https://github.com/unicode-org/message-format-wg/), and I occasionally participate in the online meetings of ECMA-402. I expect my level of activity to continue at this level, in particular if I get to continue as a voting member. I think this work is important, and worth doing well.

For work, I'm employed by [Vincit](https://www.vincit.fi/en/), and through them I've been helping one of the larger Finnish banks improve their front-end developer experience over the past couple of years. Besides messageformat, my largest other open-source project currently is [yaml](https://www.npmjs.com/package/yaml), but I maintain a bunch of other smaller tools and libraries as well. Of the other OpenJS projects, I've contributed a little to Webpack and Mocha. Over the last year, I've also started to speak more at conferences in Europe & North America.

**Comment by ljharb** [comment]
Closing, per https://github.com/openjs-foundation/cross-project-council/issues/488#issuecomment-613607888
