### ISSUE TITLE
Nomination for CPC Voting Membership: Kris Borchers

### ISSUE THREAD

**Issue by kborchers** [openjs-foundation/cross-project-council#507]
Hey everyone, I am seeking re-election as a voting member of the CPC. Though I am a maintainer on a few different OpenJSF projects (at varying levels of activity), I am representing the [Architect](https://arc.codes) project specifically with this nomination. I am also currently one of the community representatives to the OpenJSF board of directors granted to the CPC.

I have been involved in many different aspects of open source over many years and many of you probably already know that most recently I was the executive director of the jQuery Foundation through its merger with the Dojo Foundation then into its restructure and rebrand as the JS Foundation. I then led the JS Foundation through its existence up until the announcement of the merge with the Node.js Foundation was made public. Since then I have been at Microsoft driving the Open Engineering program (open source, InnerSource, accessibility) for the Azure Production Infrastructure Engineering team. I am also currently on the [OASIS Open Projects Advisory Council](https://oasis-open-projects.org/advisory-council/) where we work to advise the Open Projects program at OASIS on collaborative efforts between standards and open source.

I am passionate about open source and open governance and enjoy being one of the voices representing the community within the OpenJS Foundation's governance and operations. I hope you will allow me to continue representing the Growth and At-Large level projects for another year and thank you for your consideration.

**Comment by ljharb** [comment]
Closing, per https://github.com/openjs-foundation/cross-project-council/issues/488#issuecomment-613607888
