### ISSUE TITLE
Nomination for CPC voting membership: Christopher Hiller

### ISSUE THREAD

**Issue by boneskull** [openjs-foundation/cross-project-council#510]
Hi, I'm Chris.  I currently represent growth and at-large projects as a maintainer of [Mocha](/mochajs/mocha) (I'm also a Node.js collaborator who leads the [Node.js Tooling Group](/nodejs/tooling), but I would not be representing Node.js on the CPC).

I'm from the jQuery generation; I learned jQuery, _then_ I learned JavaScript.  I started getting involved in the open source community about ten years ago, as a contributor to a UI library for AngularJS. I've 
 contributed to countless OSS projects since; mainly in the JS ecosystem.  I've been a maintainer of Mocha for almost six years now.  I'm coming up on my three-year anniversary as a developer advocate at IBM (where I was originally hired to work in IoT; I do some hobby electronics), where I am part of the open source developer advocacy team, focused on Node.js & the JS ecosystem.

Many of the "non-impact-level" projects in the OpenJS Foundation do, in fact, have an outsized impact.  For example, Mocha and ESLint are two of the most depended-upon projects on the npm registry.  As a maintainer of Mocha, I've experienced first-hand the incredible challenges of running a supremely popular project with few development resources; I'm in-tune to the needs of independent projects which lack significant corporate investment.  Projects like these are the most vulnerable in the ecosystem and need the resources of the OpenJS Foundation the most.  I will be representing these projects; even those that are _not_ foundation projects.  I will be your voice!

My role at IBM includes community work, so I have (as the record will show) and will continue to make time for the responsibility in my work schedule.  

I work at IBM, so overrepresentation may be an issue. 😜

**Comment by ljharb** [comment]
Closing, per https://github.com/openjs-foundation/cross-project-council/issues/488#issuecomment-613607888
