### ISSUE TITLE
Nomination for CPC voting membership: Nick O'Leary

### ISSUE THREAD

**Issue by knolleary** [openjs-foundation/cross-project-council#511]
Hi, I'm putting myself forward for the CPC as a Non-Impact project representative.

I'm a long-time IBMer, who created Node-RED as side-project whilst in our Emerging Technologies group. Since then I've moved to our Developer Advocacy organisation where I continue to lead the Node-RED project as the primary focus of my role.

As one of the smaller projects in the foundation, I'm keen that they get well represented at the CPC level so they do not get swamped by the larger, more widely known projects.

I have not been able to commit as much time as I had hoped over the last few months to the CPC work. Partly due to timezone clashes with the meetings as well as other matters. But I will, if elected, commit the time it needs to be a productive voting member of the CPC.

**Comment by ljharb** [comment]
Closing, per https://github.com/openjs-foundation/cross-project-council/issues/488#issuecomment-613607888
