### ISSUE TITLE
Nomination for CPC voting membership: Tobie Langel

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#514]
Hi folks,

I've been quite involved with the foundation for the last 6 to 8 month, stress-testing the onboarding process as part of my consulting work to bring the AMP project to the OpenJS Foundation.

Although I've spent the last few years heavily involved in more non-technical roles around open source governance, sustainability, strategy, and ethics, I actually have a deep JavaScript background.

I learnt to code by perusing and documenting the source code of the Prototype JavaScript Framework and the script.aculo.us effects library, long before jQuery was a thing. As a result I became a core-maintainer of Prototype for quite a while and used it heavily in client-side applications that I developed for clients.

I also got involved with Google's Caja project as a consultant, (that team was instrumental in making ES5 a thing), participated in the standardization of CommonJS modules, and wrote numerous open source client side libraries. I ended-up getting very involved with web standards, notably at Facebook, where I headed web standards, and at W3C, where I lead what became Web Platform Tests. More recently, as an independent consultant, I edited the WebIDL spec, and in particular, its JavaScript bindings.

What I care about is **for contributors to have a seamless, no bullshit experience when they participate in projects hosted by the Foundation.** This takes dedication and a lot of work. I'm ready to put that effort in to **make OpenJS a compelling home for projects from both an IP _and_ contributor experience perspective.**

Thanks for you support.

**Comment by ljharb** [comment]
Closing, per https://github.com/openjs-foundation/cross-project-council/issues/488#issuecomment-613607888
