### ISSUE TITLE
CPC Meetings - enable attendee video

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#527]
This has been brought up. Video has generally not been happening in CPC meetings, partially due to meeting type.

Should we change this?
And, @brianwarner, can you help us to change this?

Cool, thanks!

**Comment by brianwarner** [comment]
Sure can.  I also need to go in and set a meeting password (it'll be something trivial, just enough to deter zoombombing by randomly generating meeting IDs).  I'll do this at the same time.

**Comment by joesepi** [comment]
This looks done. Thanks!
