### ISSUE TITLE
Nominate OpenJS Foundation representative for OSI

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/cross-project-council#540]
The OpenJS Foundation was recently accepted as an affiliate member of OSI.  As part of this, we can select an individual to represent OpenJS Foundation interests.  This individual will be responsible for collecting feedback from OpenJS members and projects that informs their participation in OSI activities and elections.

Please use this thread for self-nominations, describing your interest in the role, how you will collect feedback from members and projects, and how you believe OpenJS Foundation will benefit from your involvement.

Please add your self-nominations as a comment by EoD on Tuesday, May 12th.

**Comment by mhdawson** [comment]
@MylesBorins should this be in the standards repo?

**Comment by MylesBorins** [comment]
@mhdawson there is an issue there as well

https://github.com/openjs-foundation/standards/issues/89

The nominations should likely happen in that issue.

**Comment by brianwarner** [comment]
Yes, per discussions yesterday the nominations should happen over there.  I'll leave this open as a pointer and then close it when nominations close.

**Comment by brianwarner** [comment]
As there were no further nominations by May 12th EoD, @MylesBorins will be the rep to OSI.  I'll let our contact at OSI know, and close this issue.  Thanks Myles!
