### ISSUE TITLE
CPC Chair election

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#549]
I dont believe this has been discussed recently, but the CPC chair position was opened up about a year ago and elected by June

https://github.com/openjs-foundation/cross-project-council/issues/179#issuecomment-494102846

We should lay out the term for CPC Chair and the election process and begin that process soon.

**Comment by joesepi** [comment]
I proposed this timetable in this week's meeting without objection:
- I'll have something written up before next meeting (my CPC chair experience) on June 2
- Nominations will be open from June 2 - June 9
- Election will be open from June 9 - June 16

**Comment by joesepi** [comment]
Doc outlining my experience: https://hackmd.io/@joesepi/cpc-chair-experience

**Comment by joesepi** [comment]
As discussed in today's meeting and laid out in a previous meeting, we are opening up nominations for the Cross Project Council's chairperson role.

The consensus was to have people nominate in this issue. To do so, post a comment in this issue with a candidate statement as a part of your nomination.

(If this issue gets too many comments for whatever reason, I will move candidate statements to the description. Feel free to request that if I dont act on it first, if needed)

The nominations will conclude in one week -- at the next CPC meeting -- on June 9.

The election will then be opened up and remain open for one week, closing on June 16 with the elected chairperson being announced at the meeting that day.

/cc @openjs-foundation/cpc

**Comment by joesepi** [comment]
Hi friends.

💁‍♂️ ___ I would like to self-nominate for the CPC chairperson role.

🥁 ___ I've been in this role for about a year. While there is always room for improvement (and I'm open to suggestions) I feel I've got a rhythm that is working well.

👷‍♂️ ___ I have the support of my management team at IBM to continue dedicating "work time" to this role. 

🤗 ___ I enjoy doing the work because I enjoy the people I work with -- all of you.

🙌 ___ If you'll have me, I'd be honored to continue in the chairperson role.

🎉

**Comment by joesepi** [comment]
If no objections are raised over the next week we will consider it final in next weeks meeting. Thanks.

**Comment by mcollina** [comment]
Thanks for volunteering Joe!

**Comment by mhdawson** [comment]
+1 from me

**Comment by joesepi** [comment]
Thanks yall!
