### ISSUE TITLE
We should launch the individual membership program

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/cross-project-council#551]
The [individual membership program](../blob/master/INDIVIDUAL_MEMBERSHIP.md) got to Stage 3 a bit over a year ago, with a rollout target of "Q4 2019". We should get this to advance a bit, and aim to actually launch it. At a minimum, the rollout target should be updated to a future date.

The rollout plan includes multiple phases. One aspect that's included in the first phase that we'll need to also advance are [town hall meetings](../blob/master/proposals/stage-0/REGULAR_TOWN_HALLS/README.md), which are still a proposal at Stage 0. @MylesBorins, are you still actively championing that?

**Comment by SaraJo** [comment]
Raised my hand to help in the last CPC meeting. A question I have for this group is if you are interested in moving forward with the proposal as-is, if there are things that still need to be determined, or if you would prefer to revisit First Principles and start from scratch. Any way it is approached I'd love to be helpful.

**Comment by MylesBorins** [comment]
I'd personally appreciate a revisiting from first principles

**Comment by eemeli** [comment]
Seconding the suggestion to revisit from first principles, in particular considering the intentions and desires of the individual membership program, and whether the sense still is that the program seems like the best way of reaching those.

My gut feeling is that the collaboration network proposal is covering a lot of the same ground, and that it may be able to reach those same goals more effectively.

**Comment by bnb** [comment]
> if you would prefer to revisit First Principles and start from scratch

This would be my preference 👍

Thank you for raising your hand for this @SaraJo 🙏

**Comment by SaraJo** [comment]
For next steps, it seems like reading the collaboration network proposal would be helpful. 

Do you think opening an issue in this repository to ask folks for their top (3) goals and top (3) non-goals for the membership program makes sense as a next step? 

Or, do you think it would be more helpful to sit down with a list of individual stakeholders?

Would love any historical docs that aren't in the [repository](https://github.com/openjs-foundation/cross-project-council/blob/master/INDIVIDUAL_MEMBERSHIP.md).

**Comment by sendilkumarn** [comment]
> Do you think opening an issue in this repository to ask folks for their top (3) goals and top (3) non-goals for the membership program makes sense as a next step?

Can we use the same issue to get the goals & non-goals (may be re-word the issue title) ? Then put up a google Doc / hackmd to refine the content (and share it with individual stakeholders & those who are interested), before creating a Pull Request.  

Thanks @SaraJo for initiating this 👍

**Comment by SaraJo** [comment]
@sendilkumarn I'll start a new issue, close this one, and share the content for feedback before creating a pull request.

**Comment by ljharb** [comment]
Closing in favor of #553, per https://github.com/openjs-foundation/cross-project-council/issues/551#issuecomment-633663881
