### ISSUE TITLE
Individual Membership - What are the goals? 

### ISSUE THREAD

**Issue by SaraJo** [openjs-foundation/cross-project-council#553]
This is a continuation of issue #551 please share your answer to the following questions in order to ensure a shared understanding of the membership program. 

1. What do you see as the top three goals of the program?
2. What are three non-goals this program should avoid? 
3. Who should I contact specifically (if anyone) to ensure all the needs that this program is addressing are accounted for?

**Comment by dmethvin** [comment]
These are great questions! Here are my thoughts, but I don't want them to be over-weighted against thoughts and sentiments of people who are doing the work.

1. Here are some goals I think the individual membership program could potentially accomplish:
   a. It helps engage OpenJSF software users with the software they use.
   b. It lets users know they can contribute (in many ways) to the projects they depend on.
  c. It gets the word out to the wider development audience about the OpenJSF and the projects it represents.
2. Conversely there are some things that the membership program should not assume:
   a. This is not likely to be an OpenJSF revenue stream. In previous nonprofits, there has been very little money from individual memberships after accounting for membership administration costs.
   b. People who join as members want to show their personal support, but don't necessarily have the time or skills to contribute to the project. We could encourage them to contribute in non-code ways (triage, documentation, etc.) but they may just want to throw in a tip to express some gratitude.
   c.  Individual members don't always have their company's support, and the company may not be open to the idea of open source contributions. We can help companies to understand that OSS contribution is good for their business.
3. An administrator is important. When and if this program is launched, someone needs to be responsible for running it and managing its membership. This is another cost of operation, whether it's money or someone's time.

**Comment by tobie** [comment]
1. What do you see as the top three goals of the program?
    1. Create a feeling of community ownership of the Foundation.
    2. Amplify the voice of developers.
    3. Give developers weight within the foundation's decision making process.
2. What are three non-goals this program should avoid?
    1. Being able to market to developers.
    2. Monetizing developers.
3. Who should I contact specifically (if anyone) to ensure all the needs that this program is addressing are accounted for?
    1. Project leads
    2. Community managers / devrel of Foundation projects

**Comment by SaraJo** [comment]
Added a pull request with a proposal for feedback [here](https://github.com/openjs-foundation/cross-project-council/pull/574).
