### ISSUE TITLE
CPC Collab Summit sessions

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#559]
Hello all.

We should submit some CPC sessions to the Collab Summit. I'll propose some ideas here but please feel free to comment with your thoughts and other ideas.

- [ ] OpenJS and CPC new contributors sessions (leads: Joe and Jory)
- [ ] Code of Conduct WG session
- [ ] Standards WG session
- [ ] Infrastructure session
- [ ] Security session
- [ ] Onboarding session
- [ ] Open Office Hours

**Comment by obensource** [comment]
@openjs-foundation/standards folks! Please give this comment a 👍 if you'd like to hold a Standards WG session at the upcoming CPC Collab Summit. 😄

**Comment by joesepi** [comment]
Done yall.
