### ISSUE TITLE
Incubation process clarifications

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#567]
As with a few governance and process documents that were written in a vacuum, there needs to be some clarification around Incubation process. The documentation states that the incubation graduation process concludes with a vote, but this step seems cumbersome and unnecessary.

https://github.com/openjs-foundation/cross-project-council/blob/master/PROJECT_PROGRESSION.md

The consensus at the most recent CPC meeting is that we should use the consensus seeking model at both entry and exit of incubation process:
- during application silent period, CPC members have an opportunity to object
- incubation process happens, onboarding checklist, charter approval, etc
- at graduation there is a final notification that project is graduating, this is an opportunity for any last objections but none should be expected as the process has been ongoing

For this last step, I propose that this happens as follows:
1. A pull request is opened to add the project to the readme at the appropriate stage (Impact, Growth, etc)
2. This pull request links to appropriate onboarding documentations, including a link to the onboarding checklist completed as well as charter issue approved
3. This is an opportunity to object, but none should be expected.
4. This pull request would follow process as any other general pull request: 2 approvals, open 72 hrs, no objections (https://github.com/openjs-foundation/cross-project-council/blob/master/GOVERNANCE.md#merging-prs-into-this-repository)

**Comment by jaskiratsingh2000** [comment]
Hi @joesepi what we can do is to set up the PR template with all the checklist that would help understand the things in the much better way for a reviewer reviewing

**Comment by mhdawson** [comment]
@joesepi that  seems to capture what was discussed in the meeting.  We might want to consider a longer review time than 72 hours to make sure people have time to review. Board approval of the change may also be needed as the progression process is directly referenced in the charter and I think we have done that for past changes (but could be remembering wrong)

**Comment by tobie** [comment]
I do think this doubles-up with the charter approval, though. As part of the charter approval, the CPC project becomes part of the foundation (it get's it authority to oversee technical aspects granted to it from the board via the CPC). Can't we merge these two things together?

**Comment by mhdawson** [comment]
@tobie we could defer the initial charter approval to be part of the final approval if that makes sense.

**Comment by eemeli** [comment]
I would appreciate us having some explicit final step like this. While I understand that the charter acceptance may be considered to be that, it doesn't really have the same _feel_ to it as an explicit change to the CPC repo.

Maybe the charter approval issue could be closed by the stage change PR? That would link these rather explicitly.

**Comment by joesepi** [comment]
This needs a PR to move this forward.
