### ISSUE TITLE
Continue CPC current board members until we get board seats sorted and new elections happen

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#573]
Hello All.

It was suggested (and I agree) that we should have current board members from the CPC continue serving until we get the board seats sorted and new elections happen. I expect we will get that sorted soon and be able to move forward.

Any objections?

**Comment by tobie** [comment]
That seems reasonable.

**Comment by MylesBorins** [comment]
+1

**Comment by mhdawson** [comment]
I'm happy to stay on until elections are held.

**Comment by joesepi** [comment]
We are still working through this in general, but this issue can be closed. Thanks.

Ref: https://github.com/openjs-foundation/cross-project-council/pull/609
