### ISSUE TITLE
proposal added: Individual membership (updated)

### ISSUE THREAD

**Issue by SaraJo** [openjs-foundation/cross-project-council#575]
Taking inspiration from the proposal drafted [here](https://github.com/openjs-foundation/cross-project-council/pull/82), and meeting with several CPC members (along with getting feedback [here](https://github.com/openjs-foundation/cross-project-council/issues/553)), there has been a new membership program [proposal](https://github.com/openjs-foundation/cross-project-council/pull/574) added today. 

Feedback welcomed, adding an issue so this can be discussed in tomorrow's meeting.

**Comment by joesepi** [comment]
I'm adding the label to the pull request. We can discuss there and in the meetings. Closing this. Thanks @SaraJo !!
