### ISSUE TITLE
OpenJS Foundation Cross Project Council Meeting 2020-06-30

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#576]
## Time

**UTC Tue 30-Jun-2020 16:00 (04:00 PM)**:

| Timezone      | Date/Time             |
|---------------|-----------------------|
| US / Pacific  | Tue 30-Jun-2020 09:00 (09:00 AM) |
| US / Mountain | Tue 30-Jun-2020 10:00 (10:00 AM) |
| US / Central  | Tue 30-Jun-2020 11:00 (11:00 AM) |
| US / Eastern  | Tue 30-Jun-2020 12:00 (12:00 PM) |
| London        | Tue 30-Jun-2020 17:00 (05:00 PM) |
| Amsterdam     | Tue 30-Jun-2020 18:00 (06:00 PM) |
| Moscow        | Tue 30-Jun-2020 19:00 (07:00 PM) |
| Chennai       | Tue 30-Jun-2020 21:30 (09:30 PM) |
| Hangzhou      | Wed 31-Jun-2020 00:00 (12:00 AM) |
| Tokyo         | Wed 31-Jun-2020 01:00 (01:00 AM) |
| Sydney        | Wed 31-Jun-2020 02:00 (02:00 AM) |

Or in your local time:
* http://www.timeanddate.com/worldclock/fixedtime.html?msg=Node.js+Foundation+Cross%20Project%20Council+Meeting+2020-06-16&iso=20200616T16
* or http://www.wolframalpha.com/input/?i=04PM+UTC%2C+Jun+16%2C+2020+in+local+time

## Links

* Minutes Google Doc: https://docs.google.com/document/d/1CQYZUFP9X06YZ2Np4XDdIUp7wdo-nGXxP72LqcQbnc0/edit

## Agenda

Extracted from **cross-project-council-agenda** labelled issues and pull requests from the **openjs-foundation org** prior to the meeting.

openjs-foundation/cross-project-council #575
proposal added: Individual membership (updated)
Taking inspiration from the proposal drafted here, and meeting with several CPC members (along with getting feedback here), there has been a new membership program proposal added today. Feedback welcomed, ...

openjs-foundation/cross-project-council #573
Continue CPC current board members until we get board seats sorted and new elections happen
Hello All. It was suggested (and I agree) that we should have current board members from the CPC continue serving until we get the board seats sorted and new elections happen. I expect we will get that ...

openjs-foundation/cross-project-council #567
Incubation process clarifications
As with a few governance and process documents that were written in a vacuum, there needs to be some clarification around Incubation process. The documentation states that the incubation graduation process ...

openjs-foundation/cross-project-council #565
Add Divy as a regular member
I have been active for the past 3 months with Node website redesign as well as have been attending the CPC meetings regularly.

openjs-foundation:master ← designMoreWeb:membership
openjs-foundation/code-of-conduct #8
Onboarding: Provide explicit feedback on what `escalation path` is and how to implement it + temporarily address in the Onboarding Checklist
Currently, this item is in the onboarding checklist: Update project CoC reporting methods to include OpenJS Foundation escalation path In investigating this for a currently incubating project, I've ...

openjs-foundation/cross-project-council #474
OpenJS Collaboration Network ?
This outlines an idea I've been thinking about. @openjs-foundation/cpc let me know if you think this makes any sense. The OpenJS Collaboration Network The formation of the OpenJS Foundation was in ...

openjs-foundation/cross-project-council #438
2nd Director seat- post July 2020
We agreed in the last CPC meeting that the first term for the CPC director representatives would be July 1 1st. As per the CPC governance, the 2nd director seat was elected by the Node.js project for ...

openjs-foundation/cross-project-council #414
Add Foundation-wide copyright guidance
This PR adds Foundation-wide copyright guidance on how to add copyright notices to source code headers. This document is based on the guidance document from CNCF, available here: https://github.com/cncf/foundation/blob/master/copyright-notices.md ...

openjs-foundation:master ← brianwarner:add-copyright-policy
openjs-foundation/cross-project-council #326
Responsible security disclosures
Is there a standard way for OpenJSF projects to accept responsible security disclosures or is the expectation that projects set up their own solution? Node.js has its own policy, for example. I don't ...

### openjs-foundation/code-of-conduct

* Onboarding: Provide explicit feedback on what `escalation path` is and how to implement it + temporarily address in the Onboarding Checklist [#8](https://github.com/openjs-foundation/code-of-conduct/issues/8)

## Invited

* OpenJS Foundation Cross Project Council
* OpenJS Foundation Project Maintainers
* OpenJS Foundation Board of Directors

## Notes

The agenda comes from issues labelled with `cross-project-council-agenda` across **all of the repositories in the openjs-foundation org**. Please label any additional issues that should be on the agenda before the meeting starts.

## Joining the meeting

link for participants: Zoom link: https://zoom.us/j/920010234
* For those who just want to watch: https://livestream.openjsf.org

---

**Invitees**

Please use the following emoji reactions in this post to indicate your
availability.

* :+1: - Attending
* :-1: - Not attending
* :confused: - Not sure yet

**Comment by joesepi** [comment]
I'm not sure I did my agenda search correctly as I'm rushing to get a million things done. So perhaps someone could check other openjs repos for cross project council agenda issues and add them to agenda. Thanks!

**Comment by jaskiratsingh2000** [comment]
Since its alternate and we missed previous meeting due to event so was this one not supposed to be held 2 hours later from the mentioned time?

**Comment by timmywil** [comment]
Just depends on whether you think of the last meeting as postponed or skipped. This time is fine with me tho.
