### ISSUE TITLE
Who should be on the new-projects mailing list?

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/cross-project-council#578]
I'm doing some cleanup, I see the new-projects mailing list had gotten out of sync. All current CPC voting and board members are now on the list.

Should I add regular members as well?

**Comment by joesepi** [comment]
I would think all CPC members (voting and regular) should be on that list.

Confidentiality during silent period should be made clear at the outset of communications on each project submission.

**Comment by mhdawson** [comment]
+1 to what @joesepi says

**Comment by joesepi** [comment]
Confirmed with @brianwarner that this is good to close. Thanks everyone.
