### ISSUE TITLE
By Laws should be updated after board seats are defined fully

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#588]
Based on my PR to define 2 of the 3 board seats and the work that is happening on the supporter program (individual membership) and its associated board seat as well, we should look back at the how the board seats are defined and referenced in the by laws.

https://github.com/openjs-foundation/cross-project-council/pull/587#discussion_r453066645

**Comment by tobie** [comment]
Closed by https://github.com/openjs-foundation/cross-project-council/pull/1055.
