### ISSUE TITLE
We should try an earlier CPC meeting time

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/cross-project-council#599]
Since time immemorial, the CPC has been meeting weekly, at a time that switches between 16:00 UTC and 18:00 UTC, This is morning/midday for North America, afternoon/evening for Europe, and middle of the night for Asia.

We should try a different time, and see how that goes. Specifically, I propose that we hold the meeting on **18 August 2020 at 13:00 UTC**, rather than its previously planned time of 18:00 UTC. This would be:

| Timezone | Time |
|--|--|
| US / Pacific  | 06:00 (6:00 AM) |
| US / Mountain | 07:00 (7:00 AM) |
| US / Central  | 08:00 (8:00 AM) |
| US / Eastern  | 09:00 (9:00 AM) |
| EU / Western        | 14:00 (2:00 PM) |
| EU / Central     | 15:00 (3:00 PM) |
| EU / Eastern     | 16:00 (4:00 PM) |
| Moscow        | 16:00 (4:00 PM) |
| Chennai       | 18:30 (6:30 PM) |
| Hangzhou      | 21:00 (9:00 PM) |
| Tokyo         | 22:00 (10:00 PM) |
| Sydney        | 23:00 (11:00 PM) |

The idea here would be to effectively see what happens: do we have fewer or additional participants showing up, thanks to the earlier time? I don't think there's necessarily a better way of testing this except by trying. Based on the experience we can better figure out whether the meeting times should be changed going forward.

**Comment by dylans** [comment]
Even though I'm US/Pacific time, the 6am would actually make it less likely that I have a meeting conflict. The 16:00 UTC is kind of prime normal meeting time for meetings with teams across the Atlantic.

**Comment by kborchers** [comment]
This time would likely work better for me as well so I am all for giving it a try!

**Comment by timmywil** [comment]
It's not great for me, but I can make it work.

**Comment by mhdawson** [comment]
I can do the proposed time on the 18th.

**Comment by knolleary** [comment]
Adding my virtual +1 for this time slot to be considered in the future - but as I'm on vacation next week I won't be able to +1 in person.

**Comment by joesepi** [comment]
As I understand it, we are going to try this new time on Aug 18 at 10am ET.

My question is what do we do beyond that? I think a one time thing isn't very meaningful. However, if we go to a 3 week rotation, it will interfere with the bi-weekly standards team meeting. Do we do a 4 week rotating cycle where the 2pm ET slot happens every other week and the 10am/12pm (ET) slot switches every other week?

I hate scheduling meetings..... :/

**Comment by mhdawson** [comment]
Since it sounds likes its agreed I'll move the time in the calendar for the 18th.

**Comment by mhdawson** [comment]
Seems like I cannot edit Foundation calendar events.  @joesepi can you move it ?

**Comment by joesepi** [comment]
I dont believe I can either. Perhaps @brianwarner or @jorydotcom can?

**Comment by mhdawson** [comment]
@joesepi, @brianwarner, @jorydotcom  we should probably ensure that more CPC members are able to manage the calendar.

**Comment by brianwarner** [comment]
I can move it. Unfortunately there are security restrictions on that particular calendar, where I can only allow people on the @linuxfoundation.org GSuite domain to make changes. I requested a change to this policy a few weeks back (this isn't the only calendar I'd like to be able to share broadly), I'll follow up and see where that landed.

In the meantime, @rginn and @RRomoff also have full access to this calendar.

**Comment by joesepi** [comment]
Based on the discussion in todays meeting, we've decided to alternate an earlier time with the current later time. The time of today's meeting was not prohibitive to most of the usual attendees, however, we will try moving it one hour later to help with US West attendees.

So the plan is to alternate between 10am ET and 2pm ET. Sorry to be ET centric.
I think that is 1400 UTC and 1800 UTC.

The question is when do we start this rotation. I propose we start immediately, which would mean next week would be another early meeting - 1400 UTC. And this way, the later time stays as it is in calendar.openjsf.org

**Comment by joesepi** [comment]
The week goes by fast. Tomorrows meeting is at its regularly scheduled 1600 UTC time. Let's discuss in the meeting and look to move to an earlier time in two weeks. Thanks.

**Comment by joesepi** [comment]
Closing in favor of new issue #634
