### ISSUE TITLE
Director election process

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#601]
I volunteered to take a first cut at the process for the upcoming director election.

I assumes that we'll get https://github.com/openjs-foundation/cross-project-council/pull/587 landed in the next week or so.

Top level process

* Issue opened in CPC repo to announce elections, asking for self nominations
* Email sent to CPC member list pointing people to the issue asking for nominations
* Jory sends email directly to maintainer list outlining the directors being elected and who is illegible to run for the seats.  If community director seat is up for vote, ensure to identify that any active OpenJS collaborator is eligible.
* Nominations close 2 weeks later
* Announce candidates, opovote votes set up with CPC voting members as those who can vote
* email sent to CPC member list and maintainer list with the list of candidates for each position and asking that people provide their input to their voting CPC members.
* Vote closes 1 week later, new directors announced.

We discussed if we should stagger the voting options include:

* Hold vote for both directors immediately same terms. Suggestion is that it would be better to have overlap so 1 director can 
  help the other come up to speed.
* Hold vote for both directors immediately stagger terms. Make one of the 2 director positions for 6 months only so that we have 
   an offset of 6 months going forward.
* Hold vote for 2nd director(previously community director) immediately, defer vote for first director by 6 months ask existing 
  director to continue for an additional 6 months.
* Hold vote for 1st director(previously CPC director) immediately, defer vote for second director by 6 months ask existing 
  director to continue for an additional 6 months.

@openjs-foundation/cpc please chime in with your thoughts on the overall process as well as the options related to staggering the votes.

**Comment by mhdawson** [comment]
My personal preference is to run the 2 elections now with one being for a shorter term, particularly since it will already be something like 14 months that the directors have been serving by the time we line up and hold the election.

**Comment by eemeli** [comment]
Umm, just to check, are we allowed to stagger the votes? Subclauses b, c, d, e, and f of Section 4.3 of the [OpenJS Foundation By-Laws](https://bylaws.openjsf.org/) each starts with the phrase "At the time of any election of Directors ...", and then gives a qualifier for the ability of e.g. the CPC or the foundation's gold members to take action regarding nominating their representatives to the board. My non-lawyer reading of this would lead me to understand that an election of any director is an election of all directors.

I would prefer us not to stagger Community Director elections, but to run one election for at least the first two seats, annually. This lets us use some form of preferential election method that is better able to ensure wider support for the directors, should it come to that. It would also take less of the CPC's time to only have to do this once a year.

If there is interest in staggering Board elections, that staggering should happen between categories of directors, not within the Community Directors.

**Comment by mhdawson** [comment]
@eemeli we've definitely not tied the election of the CPC directors to the timing of the other directors in the past.  I can see how the wording could be read that way, but I don't think that was the intention and it's not been practice either.

**Comment by mhdawson** [comment]
Thinking about it +1 to 

>I would prefer us not to stagger CPC Director elections, but to run one election for at least the first two seats, annually. This lets us use some form of preferential election method that is better able to ensure wider support for the directors, should it come to that. It would also take less of the CPC's time to only have to do this once a year.

In particular because of ` use some form of preferential election method that is better able to ensure wider support for the directors`

**Comment by bnb** [comment]
> I would prefer us not to stagger CPC Director elections, but to run one election for at least the first two seats, annually. This lets us use some form of preferential election method that is better able to ensure wider support for the directors, should it come to that. It would also take less of the CPC's time to only have to do this once a year.

As far as I can tell this doesn't address the reason that (to my understanding) staggered elections were suggested, which is knowledge transfer and onboarding.

Yes, right now that's not an issue but we certainly cannot guarantee that will perpetually be the case and have directors as willing/able to help in perpetuity or using the method @kborchers proposed (leveraging the current directors respective employers' platinum membership to help advise/onboard after their terms are complete). I'd prefer that we try to think ahead and plan for worst case scenarios and attempt to set folks up for success.

By "preferential election method" I assume you're referring to ranked-choice voting? I don't see why that wouldn't be possible with a staggered vote other than choosing the top ranked choice in each vs. choosing the top two for both with a single vote.

Quite honestly, I feel that if having to vote twice a year is too much for voting members of the CPC we may want to reconsider the structure of the CPC - they are voting members and the most important difference between voting members and regular members is voting.

Yes, people who want to participate in the roles we're talking about will have a higher workload in that they may have to apply to run multiple times a year but I would also fully expect that if someone is running for one of these roles they'd be able to take the small amount of time to do that work compared to the large amount of time that they'd be spending in the role. For voting members who _aren't_ applying, they'll... need to go vote. That would presumably be less than 10-20 minutes, including reading about the people who are running. For voting members, if committing to voting twice a year for our representation in the Board of Directors is too high of a commitment we should probably either reevaluate the structure of the CPC to eliminate voting members and just have Members or individuals who are not able to make the commitment to spend the time voting should reevaluate their membership as a voting member.

**Comment by joesepi** [comment]
Also, the eligibility of who can run for each of the first two directors is different. So ranked choice for top two doesn't really work, I dont believe.

As a reminder, the seat eligibility and voting requirements are defined in the current PR (#587) as such:

- The Primary CPC Director must be a current CPC Member
- The Second CPC Director must be an Active OpenJS Collaborator at the time of their selection, as defined in the CPC's Governance document as proposed in this PR (#587)
- CPC Voting Members will vote on candidates for both roles (paraphrasing; not implying one vote)

**Comment by mhdawson** [comment]
@joesepi good point about the eligibility side of things.

**Comment by bnb** [comment]
@mhdawson as a variant to your preference, would a middle ground be to have a vote to extend one of the two current Directors extended by 6 months?

**Comment by joesepi** [comment]
Details captured in this PR: https://github.com/openjs-foundation/cross-project-council/pull/609

**Comment by joesepi** [comment]
I think we are good to close this issue now. Thanks.
