### ISSUE TITLE
Electron may choose up to two voting members on CPC

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#604]
As outlined in our charter: https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#voting-members

**Comment by groundwater** [comment]
For transparency: A few weeks back we did an open solicitation amongst our governance for folks interesting in occupying those seats. We had three respondents, @molant, @codebytere, and @bnb. They came together and self-decided that our two voting members will be:

1. @codebytere
2. @bnb 

Where @molant will continue to join as a non-voting member when appropriate. Let me know if this is sufficient, or there is another location to submit their names.

**Comment by joesepi** [comment]
This is great news @groundwater. Welcome @codebytere and @bnb as Voting members. I'll work with @brianwarner to make sure things are lists and references are updated and such. 🎉

PR created to update README.md #608
