### ISSUE TITLE
Next Steps for Supporter Program

### ISSUE THREAD

**Issue by SaraJo** [openjs-foundation/cross-project-council#607]
We are generally aligned about the supporter program (especially since we all agree about having the best of both worlds with the newsletter). It seems like next steps are to talk through who will implement the initiative (from web, to messaging, to marketing) as well as how we intend to get the word out (and gather the 2000+ people for a robust supporter program).

I've put together a [doodle](https://doodle.com/poll/7cravu8qqrm98c56) to have a synchronous meeting. Whomever is interested, please fill it out by EOW.

**Comment by mhdawson** [comment]
PR that captures proposed changes: https://github.com/openjs-foundation/cross-project-council/pull/625

**Comment by joesepi** [comment]
I'm going to close this issue in favor of the open PR and ongoing work. Thanks!
