### ISSUE TITLE
growth project goal-setting plan

### ISSUE THREAD

**Issue by boneskull** [openjs-foundation/cross-project-council#613]
_(original discussion in #592)_

At the last CPC meeting, we discussed setting growth project goals.

1. Growth projects need goals; specifically, goals to "graduate" to the "impact" stage (AFAIK there has not been any discussion about this, nor have any "goal documents" been produced by anyone)
1. Goals should be discussed and approved by project leadership and the CPC 
1. It may be easier to work in groups, e.g., project representatives from _n_ growth projects will meet & work with a small team from the CPC to discuss general requirements for the goals and answer questions project leadership may have
1. Project leaders will submit a "goal document" for their project, outlining what needs to be done and by when
1. After review by the small team working with the growth projects, I imagine the CPC needs to _approve_ each of these documents; reaching the goals by the agreed-upon timeline means the project _will_ move into "impact" stage

While similar to "yearly reviews" as mentioned in #592, this is not the same process.

I think the next steps are:

1. **We need volunteers** from the CPC to work with these groups.  Unsure how many
1. The volunteers need to define "table stakes" for impact projects, which I think is outlined in the project progression documentation; could probably just reuse this?
1. We need to split the growth projects into two or three groups
1. The volunteers need to reach out to projects and try to find a meeting time for each group

Maybe others have some idea about the agenda for these goal-planning meetings...?

**Comment by joesepi** [comment]
I believe that since we have eliminated the category of "growth" projects, perhaps this issue is no longer needed and whenever any projects wants to implement a growth plan, we can tailor that plan to the projects goals.
