### ISSUE TITLE
Fastify charter review

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#617]
Fastify is getting closer to completing its [onboarding checklist](https://github.com/openjs-foundation/project-onboarding/issues/35).

[Fastify charter](https://github.com/fastify/fastify/pull/2045) is now ready to be reviewed by the CPC.

Let us know if there is something we need to change.

**Comment by eemeli** [comment]
Looks pretty good. I think a bit more clarity would be good regarding decision-making; it's clear that you have some internal structure in the team, with e.g. "lead maintainers" being defined, but I can't find any clarification on what that means for you. The Section 3 link to your CONTRIBUTING.md doc doesn't really help there, as that's just listing your GitHub teams.

Specifically, I'm left with these questions:
1. Who decides on things that are not charter amendments?
2. For charter amendments, do collaborators & past collaborators count for the required simple majority? They're both listed under the "Team" section of README.md, which is referred to as defining the "full FTM".

**Comment by joesepi** [comment]
Generally, I agree with @eemeli but approve of charter. Thanks.

**Comment by Eomm** [comment]
Working on it, I'll keep this issue posted 👍

**Comment by mhdawson** [comment]
I think `ex. Node.js TSC Charter` needs to be removed

**Comment by mhdawson** [comment]
I think it would also be good to have some info on how you can become a `collaborator` or a `lead maintainer`.  Even if its as simple as a consensus of the existing `lead maintainer` or `collaborators` in each case.  

If it's already in the repo somewhere, adding some links would work.

**Comment by SaraJo** [comment]
This looks great, congrats! I bet this is the result of a lot of hard work. I'm new, does the project charter need to be the same across projects? 

Agreed with @mhdawson, I think telling people how to get involved in the charter would be great. For y'all, more hands hopefully make shorter work (not always, but usually). 

Excited to see ya'll graduate.

**Comment by tobie** [comment]
The following sentence reads as a description of the OpenJSF where in fact it should describe the project itself (a project charter shouldn't be describing how the foundation operates):

> The Fastify project is part of the [OpenJS Foundation][openjs foundation], which operates transparently, openly, collaboratively, and ethically.

Maybe change it to:

> The Fastify project is part of the [OpenJS Foundation][openjs foundation]. It operates transparently, openly, collaboratively, and ethically.

**Comment by designMoreWeb** [comment]
This is fantastic I agree with Michael, Sara and Tobi on the changes and that we should have more clarity on how to get involved with Fastlify

**Comment by mhdawson** [comment]
@mcollina, made a few grammatical suggestions but looks good to me.

**Comment by joesepi** [comment]
Closing this as we seem to have consensus. Yay Fastify!
