### ISSUE TITLE
Should we share voting result details and if so, how?

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#629]
Brought up in today's CPC meeting by @eemeli

**Comment by eemeli** [comment]
I rather like the suggestion that came up during the meeting (sorry, can't remember who by) of sharing the results on the cpc-private mailing list. In general, though, I'd prefer us to have some clear policy on this so the question does not need to be asked separately with respect to every vote.

**Comment by brianwarner** [comment]
The one piece of advice I'd have here is that this can be really discouraging to people who rank near the bottom, particularly if they are newer to the community. It's the nature of elections for there to be a winner and a loser, but I'd suggest considering whether broadcasting the magnitude of the loss to the candidate's peers could be a barrier to gathering a comprehensive slate, and result in less engagement from the person after the election?

Non-voting Foundation staff will always have access to the rankings through the Opavote console, so if there were to be an issue (for example, a sudden withdrawal or ineligibility) we can refer back to it.

**Comment by bnb** [comment]
I'd +1 @brianwarner's assertion that this could be unnecessarily discouraging, though I'd go further and assert this could potentially be harmful in terms of DEI in the CPC.

I'd prefer us to not publish election results outside of the winner, since there's no real upside outside of extreme transparency which in this case doesn't meaningfully serve any obvious positive purpose; there's only a non-trivial potential downside of hurting people.

**Comment by tobie** [comment]
Not to mention that STV results don't give you much actionable information by themselves. The only meaningful info is the position in which the candidates end-up without any sense of how close you are to other candidates. If you want more info (like how far away you were from a seat, or what you'd need to do to get elected), you need to dig into the whole dataset and understand really well how STV works.

**Comment by timmywil** [comment]
I also lean towards not sharing this information and just posting the winner. That said, if someone really wanted to know, we don't need to withhold it.

**Comment by MylesBorins** [comment]
+1 to not sharing

**Comment by tobie** [comment]
From the minutes:

Concern about consequences of certain levels of transparency. Don’t want to discourage people from running again. Also STV is not conducive for certain amount of analysis. Foundation staff have access to the tooling to confirm and validate outcomes. Should the results be made available in the case of a request, or what kind of data do we want to share - for example voter turnout. What about in the case a candidate asks for their results?

DECISION: Consensus is that we will not share specific details on the results but will share general election data such as % voter turnout. Other info may be made available by request.

ACTION: Document this understanding where we document voting information (Section 7 of Charter, or move to the governance).

**Comment by mhdawson** [comment]
PR to add info to GOVERNANCE.md https://github.com/mhdawson/bootstrap/pull/new/voting

**Comment by mhdawson** [comment]
Closing this since #671 landed
