### ISSUE TITLE
Approving project charters is clunky in issues

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#630]
Currently we work through project charter reviews in an issue. It was raised in today's meeting that some sort of pull request tied to a specific git hash would be better. How exactly should we do that?

**Comment by eemeli** [comment]
The final proposal that was made during the meeting, based mostly on input from @bnb and myself, would be for the project charters to continue to live in each project's own repo, but for the CPC repo to include a list of links to them. One important part here would be for said links to use the canonical form that includes the commit ID, so we have a reference to update when approving a project charter.

As the `PROJECTS.md` file was dropped in #591, I can see three different possibilities for such a list of project charter links:
- Add it to `README.md`
- Add a separate page like `PROJECT_CHARTERS.md` with them
- Revert the `PROJECTS.md` removal, and be better about maintaining it in the future

**Comment by bnb** [comment]
@eemeli if we simply have PROJECTS.md as a list of projects with Charter links and force updating that as a part of our process in changing levels or joining the Foundation, I think there will be less of an issue. I do think that the requirement to update it is fundamental to that success, though.

Alternatively, this could just exist in the README.

**Comment by joesepi** [comment]
We discussed this in today's meeting. My proposal, which the group was supportive of, is to convert the list of projects in the README into a table, still broken up into stages, but also adding other helpful links. One would be the charter, but also include the CoC and Contributing links. We could also include a logo for each project. I hate managing tables in markdown, but I think this could be more engaging and useful for people coming to the CPC repo and also gives us a good place to PR in not only the graduation of the project, but also the Charter as well as CoC (and contributing).

**Comment by knolleary** [comment]
I'll take a pass at a PR for updating projects list in the readme. I live for Markdown tables.

**Comment by tobie** [comment]
This was fixed in #637. Closing.
