### ISSUE TITLE
Simplify proposal process

### ISSUE THREAD

**Issue by MylesBorins** [openjs-foundation/cross-project-council#635]
So it has been almost 18 months since we kicked off the OpenJS (omg time flies, is it still March?) and I think that it is time to re-evaluate the proposal process that we have in place. A couple thoughts

* I don't think Stage-0 vs Stage-1 has been a particularly useful. The original intent of Stage-0 was "hey this is something we are talking about", but most proposals that have landed stage-0 are practically at stage-1 already (this is ready for CPC approval) and ready to go for stage-2 (this is ready for board approval).
* There has been miscommunication and expectations due to different understandings of the staging process.

I'd like to propose a streamlined process with 3 stages that have more useful names

* Incubating Proposal
* CPC Appoved
* Board Approved

Thoughts?

**Comment by mhdawson** [comment]
+1 from me, I agree that reducing the stages would be good. At this point the early stages just seem to add opportunities for confusion and additional time.

**Comment by SaraJo** [comment]
I think this is a great improvement to the process. I found the idea of Stage-0 and Stage-1 to be good, but wasn't clear about what was expected in each besides some maturity and growth between stages. I think that the names are more clear and intuitive and will make the process easier.

**Comment by sendilkumarn** [comment]
This is a great idea. 👍 

However, if the project that is in `Incubating Proposal` stage, it is actually in `waiting for Board Approval` stage right. Can we do something like this?

Incubating Proposal -> Waiting for CPC approval -> Waiting for Board approval -> Proposal accepted.

This will also clearly show at what stage the project is in.

**Comment by MylesBorins** [comment]
@sendilkumarn 

> Incubating Proposal -> Waiting for CPC approval -> Waiting for Board approval -> Proposal accepted.

Is exactly what I had in mind 👍

**Comment by mhdawson** [comment]
Other than not all proposals will need board approval, so we should factor that it is not always required.

**Comment by mhdawson** [comment]
PR here: https://github.com/openjs-foundation/cross-project-council/pull/668

**Comment by joesepi** [comment]
I think we can close this issue once we get #675 complete. (autoclosed on that issue)

**Comment by mhdawson** [comment]
#675 close, closing
