### ISSUE TITLE
Should we have a lightweight mechanism to spin off ad hoc CPC working groups?

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#649]
We've had a series of groups of people focus on specific topics (CoC, DCO, Growth plan, etc.).

Each time someone has to find a way to schedule meetings, take notes, etc. It would be good to make this more seamless.

Also, having notes from these meetings public would be useful and improve transparency.

Finally standardizing how those groups are launched and who can join them would help everyone feel included and avoided accidentally creating cliques.

**Comment by eemeli** [comment]
Perhaps it'd finally be time to move the normal CPC meetings to be bi-weekly, and to use every other Tuesday for a working group session?

**Comment by tobie** [comment]
Suggestion during CPC call is to create an issue template for this.

**Comment by brianwarner** [comment]
Documenting my comments from the meeting:

* We can add others to the calendar, or you can email operations@openjsf.org and we'll add the event for you (note, event attendees can add other attendees)
* I can set up a generic meeting with livestreaming enabled which can be used for these.

My main thought is that we need to be diligent about managing traffic. I'd just suggest we have a pretty strict rule that if you want to use the Zoom you have to be on the calendar, and if there's a conflict the event on the calendar gets priority.

**Comment by mikesamuel** [comment]
I worry whether we might run into the following situation:
1. Some people spin off a committee using the lightweight process
2. Someone else, unaware of the CPC deliberations, joins and invests a lot of effort under the assumption that the CPC has already reached consensus that the end product of the committee will be used.
3. The committee reports back to the CPC which discusses and it quickly becomes clear that the CPC is far from consensus on the value of the committee's product.

Might labeling like "tentative" or "exploratory" help avoid such outcomes?

**Comment by tobie** [comment]
Hey, @mikesamuel, wanted to apologize for not being more actively inclusive of your above comment during Tuesday's CPC meeting.

I think you're raising an important underlying point; We need to be careful about setting correct expectations.

What I had in mind was simply to make it easer to organize a couple of meetings to discuss a particular agenda item in more depth. Something that we're already doing, but that's just painful to organize right now and not super transparent.

There shouldn't be opportunity in that context to invest a lot of effort beyond drafting a pull request. And that needs to be spelled out.

**Comment by mikesamuel** [comment]
@tobie No worries.  I think the observation that simplifying scheduling addresses a good part of the pain is a good one, and that using a slot where CPC people tend to be around probably creates more opportunities to detect and correct expectation mismatches organically.

**Comment by joesepi** [comment]
Consensus is to use CPC meeting time beyond agenda to do some working session work.

Another idea is to create a working session meeting template that would provide info on the following:
- Link to Doodle calendar scheduling
- Zoom link from OpenJS account
- HackMD or Google Doc link
