### ISSUE TITLE
Clarify the license of the materials in this repo

### ISSUE THREAD

**Issue by eemeli** [openjs-foundation/cross-project-council#651]
Basically, I just noticed this: https://github.com/openjs-foundation/cross-project-council/blob/880b733c69263151e5085d006c3c8a8553f36394/package.json#L18

That was added in #308 by @sendilkumarn, but as I recall not discussed at that time. Given the recent license preference discussions in #620 and otherwise, maybe it'd be good to have an explicit decision/clarification on this?

**Comment by eemeli** [comment]
Just after submitting this I realised that the LICENSE.md was added & updated by @MylesBorins in #20 and #434, but I still think it'd be good to assert that we still want to use MIT for our our own materials, while recommending Apache-2.0 for others.

**Comment by MylesBorins** [comment]
I was just responding about the LICENSE.md

TBH relicensing might be tough since we haven't required a CLA for this repo.

**Comment by MylesBorins** [comment]
Also (adjusts not a lawyer hat), as this repo is mostly copy and not code that additional patent protections offered by the Apache-2.0 license wouldn't necessarily give up much benefit (famous last words). We probably could license almost all the content in this repo with a CC license thinking of it as documentation ¯\\\_(ツ)\_/¯

**Comment by eemeli** [comment]
I would support a CC-licensing of all our non-code content, as that would be far clearer than the MIT license's sort of implicit inclusion of "associated documentation files" into its definition of "Software". Especially given that the repo does include a minimal amount of scripting, which could be seen as the "software" that the license covers, and that it's a really far stretch to consider all of the CPC content to be the documentation for it.

Also not a lawyer, but I think one of the following statements is true:
1. The MIT license explicitly grants the right to sublicense, so we should be able to add a CC license without requiring approval from every individual that has ever contributed.
2. The CPC materials have not in fact been covered by the MIT license, and we really should fix that.

**Comment by sendilkumarn** [comment]
Thanks for opening this @eemeli 

We should discuss this at the CPC. As @MylesBorins said, we can move this repo into CC since it is just a copy.

**Comment by eemeli** [comment]
Apologies if I'm putting words into @MylesBorins's mouth, but I think he meant "copy" as in [written material](https://en.wikipedia.org/wiki/Copy_(written)), not as a duplicate of some other thing.

**Comment by MylesBorins** [comment]
To be very clear. I don't think we should do anything here.

Relicensing is not easy without getting approval from every contributor

**Comment by tobie** [comment]
MIT is OK for documentation (see https://github.com/openjs-foundation/cross-project-council/blob/master/IP_POLICY_GUIDANCE.md#1-licensing). There’s a license file in the repo, so we are all set. Closing.
