### ISSUE TITLE
Update docs to indicate projects can just use ICLA if they want

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#657]
- [x] Need to update doc on [OpenJS web site](https://openjsf.org/about/the-openjs-foundation-cla/)
- [x] Need to update existing IP guidance: https://github.com/openjs-foundation/cross-project-council/blob/master/IP_POLICY_GUIDANCE.md

**Comment by mhdawson** [comment]
Checked website it's updated, closing.

**Comment by tobie** [comment]
Unsure how I missed the update (I had checked). 🤦
