### ISSUE TITLE
Add artwork for projects where artwork is missing in projects table in README

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#663]
Check here for existing artwork: https://github.com/openjs-foundation/artwork

@brianwarner may be of help if artwork is not readily available.

Thanks!

- [x] AMP (tracked in ampproject/wg-outreach#110)
- [x] Fastify
- [x] nvm

**Comment by joesepi** [comment]
Looking closer at this, it seems that the three projects missing artwork all joined after the artwork repo was created so we just need to gather their artwork and add it to the artwork repo and then drop them into this table!

Projects: AMP, Fastify, nvm

**Comment by ljharb** [comment]
nvm has no artwork.

**Comment by tobie** [comment]
Filed an issue for AMP here: https://github.com/ampproject/wg-outreach/issues/110

**Comment by tobie** [comment]
This seems fixed now. Closing.
