### ISSUE TITLE
Code of Conduct missing for a number of projects in projects table in README

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#664]
Perhaps these projects haven't been onboarded yet? Regardless, it is something we should work to update.

**Comment by tobie** [comment]
This should be part of the annual review.

**Comment by tobie** [comment]
This should be updated to reflect the project listed in the Foundation's [CoC](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md#report-an-issue-in-a-project).

**Comment by tobie** [comment]
I think we should make the Code of Conduct is the source of truth, not the CPC’s readme: https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md#report-an-issue-in-a-project

**Comment by tobie** [comment]
CPC Agreement to remove that column from the table and make the CoC the canonical resource for this. We want to make sure that the CPC's readme very clearly references the main CoC.
