### ISSUE TITLE
Google Summer of Code 2021

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/cross-project-council#673]
Google has announced the timeline for [Summer of Code](https://summerofcode.withgoogle.com/). The format has changed somewhat for next year, in that timelines are shorter, projects are smaller, and the pool of candidates is expected to be broader.

Organizational applications begin January 29, 2021 and close February 19, 2021. If your project is interested in being included in a consolidated OpenJS Foundation application, please comment here.

**Comment by tobie** [comment]
Worth bringing that up to the attention of the CPC and project maintainers.
