### ISSUE TITLE
Align directories and any supporting docs to the changes to proposal process

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#675]
There are directories that have to renamed and any READMEs and such to align with the simplified proposal process completed here: #668

**Comment by joesepi** [comment]
closes #635

**Comment by joesepi** [comment]
Move active proposals to a new Incubating directory.
Move approved proposals to a new Approved directory.

**Comment by mhdawson** [comment]
Closed by https://github.com/openjs-foundation/cross-project-council/pull/681
