### ISSUE TITLE
Prepare to open nominations for 2nd Board seat

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#687]
Given the upcoming December holidays and vacation periods, we want to put this item on our agenda early so that the election period does not sneak up on us. This election is for the 2nd seat, currently held by @kborchers; whose term ends on the last day of February.

**Comment by joesepi** [comment]
"Lets start surfacing this upcoming election now." - @jorydotcom

**Comment by mhdawson** [comment]
I'll also offer to talk to/answer questions from anybody who is considering running in terms of what's expected.

**Comment by joesepi** [comment]
Discussed in today's meeting. From the notes:

  * New term start 1 day of march
  * Vote Complete 9th Feb
  * Open Vote 2nd Feb
  * Eligible candidates: Current CPC members
  * Ones who vote: CPC Voting members

  * In terms of socializing
	* Open issue in Repo (Michael to open)
        * Send email to CPC list (Jory will send email)
	* Remind in each of the CPC meetings

**Comment by joesepi** [comment]
Closing this in favor of #707
