### ISSUE TITLE
December CPC meetings

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#688]
December tends to be busy for some folks, including me. I will be able to run next week's meeting (Dec 8) but then I wont be around the rest of December, returning for the January 5, 2021 meeting.

What do people want to do with the December meetings? @jorydotcom has offered to lead meetings in my absence. Perhaps we can just play it by ear? Regardless, i wanted to call attention to this potential matter. Thanks.

**Comment by mhdawson** [comment]
I'd suggest we do the meeting on the 14th, but skip the ones on the 21st and 28th

**Comment by eemeli** [comment]
+1 on the dates suggested by @mhdawson, in both senses of the operation.

**Comment by jorydotcom** [comment]
We just discussed this in the CPC call today (Dec. 8) - we've decided that Dec. 15 should be our final CPC meeting for 2020.
