### ISSUE TITLE
Non normative changes to the charter shouldn't require board reviews

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#689]
Case in point, https://github.com/openjs-foundation/cross-project-council/pull/682 is just fixing a typo. Seems like seeking Board approval for this is just a waste of everyone's time.

Is there anything that we can do to fix this?

**Comment by mhdawson** [comment]
I'd talk briefly with @brianwarner about this a few weeks ago. I think we should document what does not need board review. @brianwarner any chance you could take the first cut at that?
