### ISSUE TITLE
Create a specific growth plan template for a project wanting to move to Impact stage

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#692]
Per discussions with @jorydotcom and @boneskull we think removing the growth stage needs to be replaced with a growth plan template for wanting to move to Impact Stage

**Comment by boneskull** [comment]
I can take a swing at a draft

**Comment by tobie** [comment]
Is this something different than https://github.com/openjs-foundation/cross-project-council/pull/647 and  https://github.com/openjs-foundation/project-status/pull/56?
