### ISSUE TITLE
Improving Diversity and Inclusion at the OpenJSF

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#699]
There've been a few private conversations about diversity and inclusion at the OpenJSF and in OpenJS projects. Now that a lot of the CPC’s work has stabilized, I think it would be great to make diversity and inclusion an important topic of 2021, one where the foundation shows leadership. We have the opportunity to positively influence the whole industry. Let’s leverage it!

@SaraJo and I recently chatted about this. Here some of the topics and activities that came out of that conversation:

* Adding diversity requirements to the CPC and to the leadership groups of Impact level projects. Leadership teams are already expected to come from multiple vendors at this stage, why not also make them diverse?
* Organizing a survey of existing leadership teams to assess the situation and have a baseline to make progress from over the years. (Stackoverflow has experience organizing such surveys and @SaraJo could see if she can find someone to help steer us in the right direction, here.)
* Leveraging Linux Foundation tutorials such as the [Inclusive Speaker Orientation](https://training.linuxfoundation.org/training/inclusive-speaker-orientation/) to help educate ourselves on these topics.
* Forming a dedicated working group.
* Liaising with other organizations/foundations with D&I efforts (such as W3C’s Inclusion and Diversity Community Group)

Would love to hear your thoughts, suggestions, interest, etc.

Ongoing meeting notes here: https://docs.google.com/document/d/1HD_vnNkvdU9nOTrcZqaRU-_JHR_q6AZQlqjh6TXwis4/edit

**Comment by jorydotcom** [comment]
We talked about adding some sample "playbooks" for projects developing a growth plan; this could be one of the playbooks (in addition to "reaching impact stage" for example).

**Comment by tobie** [comment]
We organized work sessions on this topic.

First session notes here: https://docs.google.com/document/d/1HD_vnNkvdU9nOTrcZqaRU-_JHR_q6AZQlqjh6TXwis4/edit

**Comment by tobie** [comment]
## Meeting Notes 2021-02-09

### Present

Name (@github): dates attended

* Joe Sepi (@joesepi)
* Sara Chipps (@sarajo)
* Tobie Langel (@tobie)
* Robin Ginn (@rginn)
* Jory Burson (@jorydotcom)
* Rachel Romoff (@RRomoff)
* Mike Samuel (@mikesamuel)

#### Survey

* Input from Sara: CHAOSS work on this is actually really good: https://chaoss.community/metrics/#user-content-focus-area---governance
* Self-reporting seems to be the answer
* Scope: projects (but it is hard to dictate these things for projects if we’re not reflecting it internally)
* Goal: start with an assessment
* Dea-nonymization helped by combining the data for the different projects
* Q: Does it matter what projects members are on?
* Q: Do we want to reach out to gather more info? Or help them solve the problem of diversity?
  A: Projects might feel they are diverse, possible around different planes. Reporting this information might be scary to projects. Projects might get defensive.
* Q: How can the foundation help with this?
* What if we start with the CPC, first? +1 for dogfooding
* Important to account for size of project (different projects will have different needs)
* Linux Foundation focuses mainly on gender. Unclear why?
* LF questionnaire just asks the question about whether you identify with an underrepresented group without specifying which.
* Requirements from other CPC members to have more axes (race, notably).
* **DECISION:** create a set of questions using Stackoverflow survey as a basis. Present questionnaire to CPC. See if CPC is OK to take the questionnaire themselves. Gather input (especially if there’s pushback). Take the questionnaire. Then bring it to the broader community.

#### Tools to help projects improve diversity and inclusion; show that they are a welcoming space

* Checklist of “easy wins” to give to projects esp. smaller maintainer teams, e.g.: renaming branch names; adopting a diversity/inclusion statement; adopting policies RE project representation
* One issue here is making decisions without having members of some underrepresented minorities that we want to help present.
* Important to work with organizations to make this happen.
* Can we lend our platform to promote minoritized communities?
* Important to lift the voices of those who are doing really good work already.
* No formal program/process but marketing is really happy to retweet, etc.
* Partnership with orgs work better.
* Goal this year to better leverage communication channels of the projects

#### Next steps
- [ ] Sara to share survey questions from Stackoverflow
- [X] Decide whether we want new call on this topic during next CPC session

**Comment by tobie** [comment]
@SaraJo shared the survey questions from Stackoverflow on the google doc:

![image](https://user-images.githubusercontent.com/3392/108287429-0ef0ff80-718b-11eb-8f45-f64e7c955710.png)
![image](https://user-images.githubusercontent.com/3392/108287412-0ac4e200-718b-11eb-956b-b77200d99388.png)
![image](https://user-images.githubusercontent.com/3392/108287393-05679780-718b-11eb-873f-834139a3e4d8.png)
![image](https://user-images.githubusercontent.com/3392/108287379-01d41080-718b-11eb-8560-c4c9e517457b.png)
![image](https://user-images.githubusercontent.com/3392/108287335-f7197b80-718a-11eb-81af-8773b4f6fefc.png)
![image](https://user-images.githubusercontent.com/3392/108287326-f385f480-718a-11eb-8e59-de7a89b49a85.png)

**Comment by tobie** [comment]
I’m so impressed by these questions and how thoughtfully they've been laid out.

Are there similar sets around income, location, and native language?

Looking at those, however, I’m concerned about the privacy implications of collecting this data for such a small sample set as the CPC. Do we have someone that could explain the sample size needed to be able to truly protect the privacy of the respondents, here?

WRT to tooling, I’m wondering if the foundation has a preferred toolset or an account it could share.
Typeform has significant accessibility problems and a track record of not caring to fix it (see https://a11y.reviews/#typeform), so I’d rather we used something else.

**Comment by SaraJo** [comment]
There are similar sets around those questions, I can grab them. You make a good point about the sample size, maybe this is us learning about our approach. Do you have any thoughts on how we can make that less of an issue?

Happy to use something besides Typeform, not tied to it at all. Google forms is also good.

**Comment by designMoreWeb** [comment]
The templates for DUA (Data Usage Agreement) :

1.  [DUAToolkit](http://hcsrn.org/en/Tools%20&%20Materials/GrantsContracting/HCSRN_DUAToolkit.pdf)
This is a guide on how to create and use a DUA, also when and whom the DUA is for, depending on the data collected.

2. [The DUA template](https://www.cdc.gov/hai/docs/DUA-template.doc)
This is a DUA word template which is between Center for Disease Control and Prevention (“CDC”), National Healthcare Safety Network (“NHSN”) 

Hopefully these can help and provide assistance

**Comment by sendilkumarn** [comment]
Before we deep dive into collecting data, can we take a step back and list down what we would like to achieve in OpenJSF? 

1. There are some easy wins, like ensuring our documentation/ communication and project's documentation / communication are always inclusive (we can even have a system that proactively monitors this and ensures that we are always inclusive and alerts). 

2. How to enable more and more less represented communities in the project and enable them to contribute? This is one of the hardest problem out there to aolve. 

3. How to educate or the steps to do when there is a mistake?

4. Add D&I process to our project on boarding checklist. Every project will be at different stage here, how we can guide them in this process. 

IMO, if we have specific targets, then it will be easier for us to decide on what data do we need and how we can collect them.

**Comment by SaraJo** [comment]
@sendilkumarn I like this approach. 

1. This sounds like a great task to take on. This seems like value we can contribute immediately. 

2. It is. Additionally, all of this is volunteer work which is something that is easier for some than from others. I would love to solve this problem, but given we are not experts, I think that partnering with organizations that do. I like the idea of partnering with the folks at CHAOSS as they can share their learnings with us, and may have actionable feedback. 

3. This is something there is research around. Any thoughts on the best way to distribute this kind of info? 

4. Yes! I think this is the goal of this project. 

I also want to cc @designMoreWeb as I know he wanted to join the conversation/work here.

**Comment by bnb** [comment]
Closing, as we've moved this work to other more specific initiatives. Please feel free to reopen if necessary.
