### ISSUE TITLE
Intro to the LFx tools webinar on Jan 14

### ISSUE THREAD

**Issue by brianwarner** [openjs-foundation/cross-project-council#703]
Recently there has been discussion in CPC calls and on Slack about tooling and analytics. I just wanted to give everyone a heads up that a webinar is planned for Thursday to provide a general introduction to the free tooling provided by the LF, if anybody is interested in learning more.

As I mentioned previously, if you'd like to suggest enhancements I'm happy to take requests back to the group deploying and supporting these tools.

LFX Insights: Get a 360° View of Your Project
Thursday, January 14th, 2021 | 9:00AM PST

https://lfx.linuxfoundation.org/resources/webinars/

**Comment by joesepi** [comment]
@brianwarner is there a recording of this webinar? If so, perhaps you could drop it here and then we can close the issue at some point in the near future. Thanks!

**Comment by brianwarner** [comment]
Thanks @joesepi, yes there is. 

Here is a link to the [recording](https://www.youtube.com/watch?v=hwTOrDg3LsI).

**Comment by bnb** [comment]
can this be closed?
