### ISSUE TITLE
Primary CPC Director Election

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#707]
It's time to start the process for the election of the Primary CPC directory for 2021-2022.

From the CPC charter the primary CPC director is as follws:

https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#the-primary-cpc-director-as-defined-in-43d-in-the-openjs-foundation-bylaws

The Primary CPC Director (as defined in §4.3(d) in the OpenJS Foundation bylaws)
The first of these board seats is filled as outlined in Section 7 on Elections and is always in place.

  - Primary CPC Director eligibility: The Primary CPC Director must be a current CPC Member
  - Primary CPC Director voting: CPC Voting Members will vote on candidates

The proposed timeline for the election is:

  * Open Vote 2nd Feb
  * Vote Complete 9th Feb
  * New term start 1 day of march

@kborchers has mentioned that he is not going to run this time due to other commitments.

@openjs-foundation/cpc please let @joesepi know if you are interested in running.

**Comment by joesepi** [comment]
Its mentioned at the bottom there, but I'll bump it here:

Please let me know if you are interested in running. You can find me in our OpenJS Slack or on Twitter and send me a DM or email me directly: joesepi@ibm.com

And I believe that both @kborchers and @mhdawson have said they are open to questions or discussions on what goes into being a CPC Director.

✌️

**Comment by joesepi** [comment]
Huzzah, we have two excellent nominees vying your vote. Regardless of who wins, we all win.

Our nominees for Primary CPC Director are: 🥁 
- Sara Chipps (@SaraJo)
- Tobie Langel (@tobie)

I request that each candidate post a candidate statement as a comment on this issue below.

CPC Voting members will receive a link via email to vote in this election.

🎉

**Comment by mhdawson** [comment]
Thanks to both Sara and Tobie for being willing to take on the role!

**Comment by SaraJo** [comment]
I couldn't be more bummed to be running against @tobie, whatever way this election goes it's a win for the Foundation. 

About 2 years ago I discovered a very strange thing about myself: I love the bureaucracy behind open source. If you told me that 15 years ago I would have never believed it. However, there are quite a few things I love about the bureaucracy that you can't see from the outside:

1) Setting standards and creating opportunity: while being a part of OSS that deals with everything but the code you're ultimately serving coders enmasse. By participating in OpenJS at the CPC level I can help every project and its contributors in valuable ways without needing to choose Node Red, Node.js, AMP, or one of the other projects of the foundation.  

2) This stuff is boring: and I say that in the kindest of ways, but I remember back before I had pivoted my career into leadership how much I disliked all the maintenance work. The emails, the meetings, the reviews. Anything that got between me and my IDE was a waste of time and exhausting. However, now that I'm more of a grown up, I've learned that you can excel at these things. I've found a fondness for changing minds, and introducing new ideas in areas that have stagnated. I've grown to love the boring. 

3) Being a voice to champion change: this is the thing I take most seriously and strive to do my best at. I can sometimes fail but it's something that gives me energy every day. I hope to continue learning from those around me, and effecting change where I can. 

I won't make promises about things I would do as a board member, as I've learned that there is often context you learn in a role that you can't see from the outside. What I want to share through this comment is who I am, so you can evaluate your vote. I'm thrilled for the opportunity, thrilled to support Tobie in the role, and thrilled to continue as a member of the CPC.

**Comment by joesepi** [comment]
I think I speak for everyone involved in thanking both @tobie and @SaraJo for volunteering for this opportunity. Regardless of who won, we would all win as both candidates are great additions to our community and to the work we are doing. I thank them both for their previous work and their future work in any and all capacities.

But we did have an election and we do have a winner... 🥁 

🎉  Congratulations to Sara, our new Primary Board Director! 🎉 

I look forward to all the work you will do on behalf of the CPC, the projects and the community.

Also, I'M VERY SORRY for letting this slip a week. Announcement should have been made last week. My bad.

**Comment by tobie** [comment]
Congrats Sara! I was just as bummed as you, now *I* don't have to be! :)

Sara, you've proven in a really short time, with your work on JavaScriptLandia, that you're able to execute well and quickly on ambitious projects. I'm thrilled to have you as a representative of the CPC and the projects on the Board (now I now who else to bug besides @mhdawson). This is a great outcome for the Foundation. Again, congrats!

**Comment by mhdawson** [comment]
@SaraJo Congratulations!

@tobie thanks for being willing to server and being very gracious :)

**Comment by MylesBorins** [comment]
wahooooo congrats @SaraJo

**Comment by SaraJo** [comment]
Thank you, @tobie, @mhdawson, @MylesBorins, and everyone else who voted last week. It's an honor that you elected me to represent the CPC to the board. I will do my best to represent the larger community needs and goals I learn from the CPC and bring them back to the rest of the board, as well as keep the CPC up to date with what I learn in board meetings. I’ve really enjoyed working with everyone here over the past year and I’m looking forward to doing even more work with the foundation.

**Comment by mhdawson** [comment]
Election completed, closing.
