### ISSUE TITLE
CPC Working Sessions - Diversity and Inclusion

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#708]
**Agenda:** TBD based on related issue below

**Facilitator:** @tobie @SaraJo @joesepi 
**Related issue(s):** #699 
**Doodle link:** N/A
**Date:** 2012-01-26 1700 UTC
**Date:** 2012-02-09 1900 UTC
**Zoom link:** https://zoom.us/j/91398697172?pwd=QVgxRUFXdmtHVUNiODhoSU11ejF0QT09
** Notes : https://docs.google.com/document/d/1HD_vnNkvdU9nOTrcZqaRU-_JHR_q6AZQlqjh6TXwis4/edit?usp=sharing

Please wait for your meeting to be added to the [OpenJS Foundation calendar](https://calendar.openjsf.org) before using the Zoom meeting. If there are two conflicting meetings, please note that the meeting on the calendar takes precedence.

**Comment by jorydotcom** [comment]
@tobie @joesepi do we want to keep this issue open for tracking other meetings, or are we good to close this one?

**Comment by SaraJo** [comment]
I think it would be good to have a place to track updates. Is this the best place?

**Comment by SaraJo** [comment]
Oh, I see the other issue, seems like we can close this one!
