### ISSUE TITLE
Creating a new Twitch channel for OpenJSF 

### ISSUE THREAD

**Issue by sendilkumarn** [openjs-foundation/cross-project-council#710]
This came out of the discussion on OpenJS World planning meeting. 

Can we create a new Twitch channel for OpenJS Foundation and start hosting our AMA, quick updates, etc., via the Twitch channel?  

I think for AMAs, Twitch provides a better experience than compared to the Zoom meetings.

**Comment by joesepi** [comment]
The consensus was that this may not be the best approach unless there are "resources" (re: people) to put in the time and energy to build an audience.

However, it would be good for the marketing committee and the program committee to discuss further.
