### ISSUE TITLE
Rename master branches

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#711]
There's broad community agreement that using the term "master" for the main branch of Git is harmful.

GitHub has [made it easy](https://github.com/github/renaming) to switch to another name. The community consensus seems to be to use "main" instead.

Proposal:

- [x] Switch the default branch name of the GitHub `openjs-foundation` organization to "main".
- [x] Rename `master` branches to `main` for all `openjs-foundation` repositories.
  - [x] openjs-foundation/TEST-EasyCLA
  - [x] openjs-foundation/artwork
  - [x] openjs-foundation/code-and-learn
  - [x] openjs-foundation/code-of-conduct
  - [x] openjs-foundation/cross-project-council
  - [x] openjs-foundation/meet
  - [x] openjs-foundation/open-office-hours
  - [x] openjs-foundation/openjsf-landscape
  - [x] openjs-foundation/project-status
  - [x] openjs-foundation/standards
  - [x] openjs-foundation/summit
  - [x] openjs-foundation/user-feedback
  - [x] openjs-foundation/silent-onboarding
  - [x] openjs-foundation/directory-private
- [x] Through standard communication channel encourage all OpenJSF projects to do so as well.
- [x] Possibly create a dedicated place where folks tasked to *implement* this change (not discuss its pertinence or value) can help each other, notably with handling tools or services that have hardcoded the "master" branch name as default branch.
- [x] Eventually address issues uncovered by OpenJSF projects implementing this change at the foundation level (by reaching out to tools or services that make this change hard).

**Comment by mhdawson** [comment]
I think we should just rename them, with the new support to help move over PRs I think the impact on the work handled through CPC repos will be minimal.

**Comment by mhdawson** [comment]
Updated openjs-foundation/code-and-learn

**Comment by mhdawson** [comment]
Updated openjs-foundation/user-feedback

**Comment by mhdawson** [comment]
Updated openjs-foundation/openjsf-landscape

**Comment by mhdawson** [comment]
Updated openjs-foundation/project-status

**Comment by mhdawson** [comment]
openjs-foundation/artwork   - default branch is already main

**Comment by mhdawson** [comment]
updated openjs-foundation/standards

**Comment by mhdawson** [comment]
Updated openjs-foundation/TEST-EasyCLA

**Comment by mhdawson** [comment]
openjs-foundation/meet is already main

**Comment by mhdawson** [comment]
updated openjs-foundation/code-of-conduct

**Comment by mhdawson** [comment]
updated openjs-foundation/summit

**Comment by mhdawson** [comment]
renamed openjs-foundation/open-office-hours

**Comment by mhdawson** [comment]
renamed openjs-foundation/silent-onboarding

**Comment by mhdawson** [comment]
openjs-foundation/directory-private primary branch was already main

**Comment by mhdawson** [comment]
> Switch the default branch name of the GitHub openjs-foundation organization to "main".
This is already the default

**Comment by mhdawson** [comment]
updated openjs-foundation/cross-project-council

All repositories that did not already have main as the primary branch have been updated and the default for the org  was already main.

The next step is to grep through the contents of all of the repositories and update any references from master to main:

**Comment by joesepi** [comment]
I created this hackMD file to capture any issues, tips or guidance: https://hackmd.io/8sJrosPYSBi1uTM6C4GXjQ

**Comment by mhdawson** [comment]
Mass fast track request to get a number of the PRs referenced here landed: https://github.com/openjs-foundation/cross-project-council/issues/724

**Comment by joesepi** [comment]
This issue remains open for the last three checkboxes on issue description:
- Through standard communication channel encourage all OpenJSF projects to do so as well.
- Possibly create a dedicated place where folks tasked to implement this change (not discuss its pertinence or value) can help each other, notably with handling tools or services that have hardcoded the "master" branch name as default branch.
- Eventually address issues uncovered by OpenJSF projects implementing this change at the foundation level (by reaching out to tools or services that make this change hard).

**Comment by joesepi** [comment]
I think to close this issue, considering the three bullet points left to do, we should:
- send out an email to project maintainers suggesting they make the same change in their repos.
- in that communication, suggest the #infra channel on Slack to discuss any issues
- monitor that channel to see if there are any processes or tools we could create or use to make the process better.

**Comment by tobie** [comment]
That sounds like a great plan. We need someone to volunteer drafting an email.

**Comment by tobie** [comment]
Here's a proposal:

> Dear Maintainers,
> 
> There's broad community agreement that using the term "master" for the main branch of Git is harmful.
> 
> GitHub has [made it easy](https://github.com/github/renaming) to switch to another name. The community consensus seems to be to use "main" instead.
> 
> We have recently completed transitioning all of the CPC repositories and encourage you to do the same.
> 
> We acknowledge renaming the main branch of repositories with complex CI/CD pipelines can be challenging and take time.
> 
> Feel free to reach out on Slack (#infra) to discuss any issues you might have.
>
> The CPC

**Comment by timmywil** [comment]
I don't know if it's worth noting here, but I just finished changing all the default branches for all repos on the jQuery org to `main`.

**Comment by jorydotcom** [comment]
The template email, with a few minor edits, has been sent to our project leads!

**Comment by joesepi** [comment]
I believe we can call this issue done as we've done it in our org.
