### ISSUE TITLE
Mass fast track request

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#724]
We have a number of PRs across the repo related to changing the primary branch to main. These don't change any of the content in a material way.

As discussed in the CPC meeting today this is a mass fast track request for the following:

https://github.com/openjs-foundation/artwork/pull/12 (merged)
https://github.com/openjs-foundation/code-and-learn/pull/6 (merged)
https://github.com/openjs-foundation/code-of-conduct/pull/11 (merged)
https://github.com/openjs-foundation/cross-project-council/pull/716 (merged)
https://github.com/openjs-foundation/openjsf-landscape/pull/13 (merged)
https://github.com/openjs-foundation/project-status/pull/60 (merged)
https://github.com/openjs-foundation/standards/pull/123 (merged)
https://github.com/openjs-foundation/summit/pull/305 (merged)
https://github.com/openjs-foundation/user-feedback/pull/5 (merged)

Agreement was that once we get 2-3 CPC approvers, fast track request will be approved and we will land them all.

**Comment by mhdawson** [comment]
@joesepi @openjs-foundation/cpc

**Comment by joesepi** [comment]
All PRs merged. Closing issue. Thanks all!
