### ISSUE TITLE
[Ad hoc meeting] Moderation and CoC working session - Tue 9-Mar-2021 17:00

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#726]
**Agenda:** TBD

**Facilitator:** @joesepi and @jorydotcom 
**Related issue(s):** 
**Doodle link:** 
**Date:** UTC Tue 9-Mar-2021 17:00 (05:00 PM)
**Zoom link:** https://zoom.us/j/91398697172?pwd=QVgxRUFXdmtHVUNiODhoSU11ejF0QT09
**Meeting notes document:** TBD

Please wait for your meeting to be added to the [OpenJS Foundation calendar](https://calendar.openjsf.org) before using the Zoom meeting. If there are two conflicting meetings, please note that the meeting on the calendar takes precedence.

**Comment by joesepi** [comment]
I've created this issue for discussion of moving next week's meeting time to the earlier slot to accommodate EU timezones a little better.

I haven't moved the calendar entry to an earlier time yet.

**Comment by bnb** [comment]
No objection to moving the meeting.

**Comment by ljharb** [comment]
TC39 starts that day at 18:00 UTC, and i have the kids tuesdays, so i definitely can’t make it if it’s not between the 17-18 hour.

**Comment by tobie** [comment]
That works for me.

**Comment by joesepi** [comment]
I moved the calendar entry on the calendar.openjsf.org calendar to reflect the date/time in this issue's description.
