### ISSUE TITLE
Private slack channel for Node.js build team machine management

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#729]
We are exploring if the build team can use a private channel in the OpenJS slack to co-ordinate with one of our infra donators.

1) Opening this since I don't think we've had private channels like this in the OpenJS slack yet. Any concerns?
2) Can we share who the slack admins are as I assume that the admins would have access to the conversations in that private channel.

**Comment by brianwarner** [comment]
No concerns here. Other projects use private channels on the OpenJS slack.

I can set it up if you let me know what channel name you want and who would be in it.

**Comment by mhdawson** [comment]
@brianwarner thanks. Who all are the admins (you + who ?)

**Comment by brianwarner** [comment]
Certainly. 

Current admins are: Jory, Robin, Me, Myles, Kris B, and Dave M.

**Comment by mhdawson** [comment]
Discussed in the meeting this week. Sounds like using a private channel like this is consistent with existing practice.

If we want to create the private channel we just need to ask one of the admins to do that for us.

**Comment by mhdawson** [comment]
Closing since answered
