### ISSUE TITLE
Slack Moderators - Volunteers requested

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#747]
We'd love to have some volunteers to participate in the @moderators group on Slack, particularly ahead of the OpenJS World event wherein we will be doing online Q&A with speakers.

**Comment by designMoreWeb** [comment]
+1 :)

**Comment by joesepi** [comment]
I'm happy to help here.

**Comment by SaraJo** [comment]
Same! I am free over the next month to help.

**Comment by joesepi** [comment]
This was partly for the event and partly for ongoing moderation. The event is over and we believe we have an adequate amount of moderator volunteers on an ongoing basis. However, feel free to speak up if you are also interested in helping moderating moving forward. Thanks!
