### ISSUE TITLE
Nominations Open: Non-Impact Voting CPC Member Election

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#751]
Each of the At Large and Incubating Projects may nominate a candidate to fill one of two voting seats on the CPC which represent this group of projects as a whole. From those nominees, two voting members are chosen via an election process outlined in the [CPC Governance.](https://github.com/openjs-foundation/cross-project-council/blob/main/GOVERNANCE.md#election-process-for-non-impact-voting-cpc-members). 

We are now taking nominations for these two positions on the Voting CPC Member body from non-impact projects (seats which are currently held by @boneskull and @tobie). 

The election term is one year. Any member from one of the non-impact projects can self-nominate themselves (or another, with permission) by emailing the chair of the CPC with their interest in running for the CPC. The nomination period will be open for 2 weeks at which point the CPC chair will list the nominees in the issue.

Each of the candidates listed will then be asked to open an issue in the CPC repo which includes the following:
- Projects they are part of
- Description of their background
- The reasons they would like to act as a non-impact CPC voting member
- Confirmation that they can devote the required time/effort.
- Their employer (if applicable). This is needed due to the limitations on maximum employer representation in the CPC voting members.

ref: #745

**Comment by boneskull** [comment]
I will _not_ be nominating myself for the seat.

**Comment by joesepi** [comment]
Congrats and thanks to @tobie and @eemeli, who were chosen to be our At-large voting members
