### ISSUE TITLE
Nominations Open: Voting members chosen by Regular members

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#752]
Per our [CPC charter](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/CPC-CHARTER.md#voting-members) document, up to two regular members can be elected as voting members. The two regular members elected as voting members are currently Eemeli Aro (@eemeli) and Michael Dawson (@mhdawson).

We are now taking nominations for these two positions on the Voting CPC Member body from the [regular membership list](https://github.com/openjs-foundation/cross-project-council#regular-members). Anyone who has been active in the foundation or one of its member projects, as described in the CPC Governance may request to become a regular member by opening a PR to add themselves to the list of regular members.

The election term is one year. Any Regular CPC member can nominate themselves (or another, with permission) by emailing the chair of the CPC with their interest in running for the CPC. The nomination period will be open for 2 weeks at which point the CPC chair will list the nominees in the issue.

Each of the candidates listed will then be asked to open an issue in the CPC repo which includes the following:
- Projects they are part of
- Description of their background
- The reasons they would like to act as a non-impact CPC voting member
- Confirmation that they can devote the required time/effort.
- Their employer (if applicable). This is needed due to the limitations on maximum employer representation in the CPC voting members.

ref: #745

**Comment by mhdawson** [comment]
I'm happy to run again this time.

**Comment by joesepi** [comment]
Congrats and thanks to @mhdawson who was chosen to be our Regular Member Voting Member

**Comment by mhdawson** [comment]
Thanks, and happy to continue to represent the regular members :)
