### ISSUE TITLE
2021-05-04 Working Group Meeting: Tech Strategy, part 2

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#754]
**Agenda:**
* Technical strategy discussion, part 2 

**Facilitator:** joe, jory
**Date:** 2021-05-04
**Zoom link:** https://zoom.us/j/91398697172?pwd=QVgxRUFXdmtHVUNiODhoSU11ejF0QT09
**Meeting notes document:** https://hackmd.io/0kIgaLk5ThCvIsb2p_VgwQ

**Comment by tobie** [comment]
Won’t be joining tonight’s call. Have fun!
