### ISSUE TITLE
Create proposal(s) for the Community Fund

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#756]
As decided by the Board and reflected in #725, the OpenJSF now has a $60K Community Fund that's intended to serve the community beyond travel funds.

The Board expects proposal from the CPC on how to use this fund.

This issue is meant as a place to track those proposals.

**Comment by jorydotcom** [comment]
At today's working CPC meeting we reached a small-group consensus on the following (see [notes](https://hackmd.io/Ij5aT-3nQqKN_aVeJxxgRg?edit)) 
* Community Fund should primarily fund specific programs, e.g. Travel, Scholarship, Thank You, Standards Participation
* Programs should have clear requirements & processes to make approval & eligibility straightforward
* Project Maintainers should be able to request 'ad hoc' funding for things that do not fall within the established programs.
* 'Ad hoc' funding requests should have a clear evaluation rubric; Maintainers should have support from CPC to complete funding request forms
* Funding requests should have a cap; money/benefit should go to individuals while also being additive to the projects.
* There's a grey line to be mindful of - community fund should not be sole source of direct project support (e.g. hardware, surveys, code & learn)

**Comment by rginn** [comment]
Please see the overview and proposal for awarding 20 need-based scholarships for the Node.js Training and Certification program. This scholarship proposal was developed in a CPC working session, with support from the OpenJS and Linux Foundation staff, and training and certification teams.
https://docs.google.com/document/d/1vNdYSSzuENSlEyTU3j1XsHTx_8flos4_0oxMejH_tWs/edit?usp=sharing

**Comment by joesepi** [comment]
Doc from last working session on nov 11, 2021: https://hackmd.io/RnT9C7ClT_O3ZcNfuDweIw

**Comment by joesepi** [comment]
Please see the repo that we created at last week's working session: https://github.com/openjs-foundation/community-fund
