### ISSUE TITLE
Reminders for long term events

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#758]
We are regularly forgetting long terms events such as elections.

@bnb is building a Github Action-based solution for another project which we might be able to leverage here.

This is issue is a placeholder to remember implementing that solution down the road.

**Comment by ljharb** [comment]
Surely we'll remember _this_ long-term event :-p

**Comment by SaraJo** [comment]
This is great, as these things are hard. @bnb once you have something if you want to tag me in, I'd be happy to help.

**Comment by SaraJo** [comment]
Can we use this issue to get together a list of things we'd want to get on that calendar? So far: 

- CPC Impact voting member elections
- CPC Non-impact voting member elections

**Comment by mhdawson** [comment]
Adding to the list

CPC Chair election
Director 1 election
Director 2 election

**Comment by tobie** [comment]
* Would be useful to be able to mute (remove the `cross-project-council-agenda` label) any open issues until a given date.
* Checking on onboarding project updates?

**Comment by joesepi** [comment]
Related: https://github.com/openjs-foundation/cross-project-council/issues/610

**Comment by mhdawson** [comment]
Closed since https://github.com/openjs-foundation/cross-project-council/pull/794 landed
