### ISSUE TITLE
Build stronger ties between At Large maintainers and their CPC Rep

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#761]
At Large members have two CPC reps. Historically there hasn't been good communication channels between At Large maintainers and their CPC reps.

We'd like to change this and create stronger ties.

The goal of this issue is to brainstorm/discuss this and find ways the foundation can help support this.

/cc @joesepi @eemeli @jorydotcom

**Comment by tobie** [comment]
Lots of good proposals in today's CPC session.

Next step, check with @eemeli for availability (1pm EST, before or after our regular CPC meeting). If confirmed, @joesepi to organize first meeting.

**Comment by mhdawson** [comment]
I'm generally booked at that time but I'll see if I can make it once the call is scheduled.

**Comment by tobie** [comment]
@joesepi and I had talked about this a while back and had agreed that the best first step would be to create a Slack channel for At Large Maintainers and their CPC reps.

- [ ] create slack channel (suggesting #at-large-project-maintainers with description: _This channel is reserved for communication between At Large project maintainers and their CPC representatives._)
- [ ] @eemeli, @tobie, @mhdawson to join channel
- [ ] invite project maintainers to this channel (@jorydotcom can you help with this?)

**Comment by tobie** [comment]
Reminder in 6 weeks to check how this is going.

**Comment by tobie** [comment]
@Relequestual suggested incubating project maintainers should have access to "At large" channels.

I concur. I feel like the CPC "At Large" Rep role should extend to incubating projects.

**Comment by Relequestual** [comment]
There's one channel which is public, but it seems to have no posts since 2021.
Are there some private channels for other project maintainers to chat with each other?

**Comment by ljharb** [comment]
I would assume incubating X projects are treated as X projects, whether X is At Large or otherwise.

**Comment by tobie** [comment]
We're building a stronger relationship with projects as the whole of the CPC through initiatives like #1750. We've also flattened the CPC voting members roles in #1698. Closing.
