### ISSUE TITLE
approve Node.js TSC Charter revisions

### ISSUE THREAD

**Issue by Trott** [openjs-foundation/cross-project-council#762]
Refs: https://github.com/nodejs/TSC/pull/990

**Comment by eemeli** [comment]
LGTM

**Comment by mhdawson** [comment]
LGTM

**Comment by joesepi** [comment]
LGTM

**Comment by dylans** [comment]
LGTM

**Comment by mhdawson** [comment]
This just needs to hit the 14 days as per https://github.com/openjs-foundation/cross-project-council/blob/main/GOVERNANCE.md#approving-project-charters. Unless there are objections before then it already has the required 2 approvals by CPC members.

**Comment by mhdawson** [comment]
This has hit the 14 days, no objections and enough approvals from voting members, considering approved, closing.
