### ISSUE TITLE
CPC Chairperson election 2021

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#772]
Hello friends. It is that time again. Time to have an election for the chairperson role for the Cross Project Council.

I propose the following for a timetable:
- discuss this at next meeting on July 20, 2021
- begin nominations on that date and have them open for two weeks (July 20 - August 3)
- hold election over two weeks (August 3 - August 17)

The last election, we only had these processes open for 1 week, but I feel two weeks is more time for folks to consider and take the steps. Also: we've started doing the CPC meeting every 2 weeks too, so this lines up with that.

If anyone has any questions about the role, feel free to ask me in this issue or message me directly.
I wrote this up last election and it largely is still the same: https://hackmd.io/@joesepi/cpc-chair-experience

To be up front: I plan to run again. But if anyone has any interest, please don't hesitate to throw your hat in the ring. I am also very open to mentoring someone if they want to consider this role or similar roles in the future.

✌️

**Comment by mhdawson** [comment]
+1 on the proposed timeline.

**Comment by jorydotcom** [comment]
Those interested in nominating themselves privately can send their interest to me (slack preferred: @jorydotcom).

**Comment by jorydotcom** [comment]
Joe Sepi was the only candidate nominated for CPC Chairperson. We received no further nominations. Thus an election is not necessary and Joe can be confirmed as our 2021-2022 chair at the next CPC Meeting.

**Comment by joesepi** [comment]
Thanks yall!
