### ISSUE TITLE
Update list of project report methods/emails

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#781]
It seems that we should have the list of project reporting methods for every project on this list.

https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md

Related: #775

**Comment by tobie** [comment]
As @jorydotcom pointed out in #775 projects can either handle CoC violations themselves (with escalation to the CoCP when necessary) or delegate handling to the CoCP.

In the CoC however, there are three options:

1. projects which don't list a reporting solution at all,
2. projects which list the CoCP's email as their reporting solutions, and
3. projects which list their own reporting solution.
 
I think it would be clearer if we folded the first two options into one, either by:

1. listing every project and making sure that all projects which don't have their own reporting solution mention the CoCP's email (as you suggest here), or
2. only listing projects that have their own reporting solution and having a big fat link available for every other projects and for escalations.

I think I would prefer the second option at it feels easier for folks reporting violations and more robust as new project come in.
