### ISSUE TITLE
Kickoff election process for Secondary CPC Director.

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#784]
As per https://github.com/openjs-foundation/cross-project-council/blob/main/GOVERNANCE.md#term-for-cpc-board-representatives, my term as Seconday CPC Director ends Aug 31. That means it is election time.

@jorydotcom, @joesepi it probably makes sense for one of you two to run the election and have people let you know if they are interested in running.

From: https://github.com/openjs-foundation/cross-project-council/blob/HEAD/CPC-CHARTER.md#the-secondary-cpc-director-as-defined-in-43e-in-the-openjs-foundation-bylaws.  The requirements to run for the position are:

Secondary Director eligibility: The Second CPC Director must be an Active OpenJS Collaborator at the time of their selection, as defined in the CPC's Governance document.

**Comment by joesepi** [comment]
I propose we kick off the election on Tuesday at our meeting, have nominations open for two weeks and then voting for two weeks, which will put us right around the Aug 31 date.

People who are interested, once the nomination period begins, can message me directly on the OpenJS Slack.

**Comment by joesepi** [comment]
Hey Friends! We have two amazing candidates for this role: @tobie and @mhdawson 

CPC Voting members should have an email in their inbox thanks to @jorydotcom.

Election closes EOD Aug 31

Candidate statements, if candidates with to provide a statement, should be in this issue.

Huzzah!

**Comment by joesepi** [comment]
This election has concluded and Michael has received the most votes. Thanks for both Michael and Tobie for running. We have great people involved in the work we do and I greatly appreciate that.
