### ISSUE TITLE
Clarify requirements around CoC violation

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#786]
Currently there are no requirements beyond adopting the Foundation's CoC for projects.

It seems we would need additional requirements for projects who wish to handle CoC violations themselves. For example, having a clear process for raising a violation, certain guarantees around privacy, etc.

---

Next steps:

- [x] open a pull request against [FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS](https://github.com/openjs-foundation/cross-project-council/blob/main/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md) that adds a section listing the requirements outlined above (see #1135).
- [ ] open a pull request against the [onboarding checklist](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/PROJECT_PROGRESSION.md#onboarding-checklist) that includes implementing those requirements.
  - [ ] have an email reporting address
  - [ ] (required for impact and at-large) have at least more than one person selected by the project maintainership (through a process defined by the project) on that email address
  - [ ] publicly list who is on that email address
  - [ ] publicly document the decision-making process
  - [ ] confidentiality of reporter and victim
  - [ ] basic rules around data retention to meet legal requirements (e.g. GDPR) 
- [ ] following up on the audit @rginn is running to make sure that the projects that have opted in to run their own CoC enforcement have implemented those requirements.

**Comment by ljharb** [comment]
If a project doesn't have those things, then I'd argue it doesn't actually have a CoC.

**Comment by bnb** [comment]
- [ ] have an email reporting address
- [ ] (required for impact and at-large) have at least more than one person selected by the project maintainership (through a process defined by the project) on that email address
- [ ] publicly list who is on that email address
- [ ] document the decision-making process

**Comment by tobie** [comment]
Next steps here would be to:

- [ ] open a pull request against [FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS](https://github.com/openjs-foundation/cross-project-council/blob/main/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md) that adds a section listing the requirements outlined above.
- [ ] open a pull request against the [onboarding checklist](https://github.com/openjs-foundation/cross-project-council/blob/HEAD/PROJECT_PROGRESSION.md#onboarding-checklist) that includes implementing those requirements.
- [ ] following up on the audit @rginn is running to make sure that the projects that have opted in to run their own CoC enforcement have implemented those requirements.

**Comment by benjagm** [comment]
> Building on @bnb's comment above, we'd like to focus on the minimum set of requirements as a first step and leave broader conversations (e.g. training) to a later conversation. In addition to the list mentioned above, it seems the following should be listed in an initial set of requirements:
> 
> * confidentiality of reporter and victim
> * basic rules around data retention to meet legal requirements (e.g. GDPR)

I do think we can include additional elements to avoid conflict of interests:
* Recusation and mediation mechanism : If a Code of Conduct report involves a member of the Committee, that member will not participate in the investigation or any decisions related to that report. If the report involves multiple members of the Committee, it will be mandatory the mediation of the OpenJS Foundation Code of Conduct Panel (CoCP).
* Conflict of interests: Add an explicit section in the code of conduct or in the enforcement manual will help in these cases: In the event of any conflict of interests, a committee member must immediately notify the other members, and recuse themselves if necessary.

I do like how [Jupyter project](https://jupyter.org/) manages this specific scenarios:
- Enforcement Manual: https://github.com/jupyter/governance/blob/main/conduct/enforcement.md
- Reporting Guide: https://github.com/jupyter/governance/blob/main/conduct/reporting_online.md

**Comment by Relequestual** [comment]
> ...publicly document the decision-making process - @bnb 

It would be great if the OpenJS Foundation could model this (amoung other) items on the list of suggestions for enhancements =]

**Comment by benjagm** [comment]
> * basic rules around data retention to meet legal requirements (e.g. GDPR)

Is there any resource or policy within the Foundation to guide us on how to better complete this requirement?

**Comment by Relequestual** [comment]
@tobie You added a "waiting for PR" label to this repo, and you detailed some requirements in your [comment](https://github.com/openjs-foundation/cross-project-council/issues/786#issuecomment-900562549). However, who has the knowledge with which to fill the content for the titles/sections you say are needed?

Which of them can we (the CPC) answer, and for which of them do we need to involve legal?

**Comment by tobie** [comment]
> Which of them can we (the CPC) answer, and for which of them do we need to involve legal?

I'd say everything until outside of the data retention rules (though there probably might be enough in the org's privacy policy to just reference). Come to the next working session if you're interested in helping out, here.

**Comment by Relequestual** [comment]
> Come to the next working session if you're interested in helping out, here.

I'm interested, but the time makes it almost impossible if I want to keep a good work/life balance. I already have after hours meetings on a regular basis multiple times a week.

**Comment by tobie** [comment]
I get it.

**Comment by Relequestual** [comment]
If the CPC are largley in agreement with your list of next steps, copying them to the opening comment of the issue will allow us to track them better and try to move forward discussions on individual items (as they can then be convereted into individual issues too)

**Comment by tobie** [comment]
Good call. Done.

**Comment by benjagm** [comment]
> * basic rules around data retention to meet legal requirements (e.g. GDPR)

Does the Foundation have a formal line on GDPR compliance requirements for the management of the CoC violation reports?

**Comment by tobie** [comment]
Closing as duplicate of https://github.com/openjs-foundation/cross-project-council/issues/1255.
