### ISSUE TITLE
Approval for Node.js charter change.

### ISSUE THREAD

**Issue by mhdawson** [openjs-foundation/cross-project-council#803]
Please approve (or not) this Node.js charter change:

Adjust charter to simplify automated removal rules [1097](https://github.com/nodejs/TSC/pull/1097)

**Comment by joesepi** [comment]
+1 from me

**Comment by designMoreWeb** [comment]
LGTM

**Comment by tobie** [comment]
LGTM

**Comment by ljharb** [comment]
LGTM
