### ISSUE TITLE
Feedback Channels Between Projects

### ISSUE THREAD

**Issue by SaraJo** [openjs-foundation/cross-project-council#808]
At today's board meeting we discussed project leaders providing public feedback for other projects. [We have rules around this for OpenJS leadership](https://github.com/openjs-foundation/cross-project-council/blob/main/MEMBER_EXPECTATIONS.md), but wondered if there was opportunity here to be thoughtful about how project leads communicate amongst themselves.

**Comment by tobie** [comment]
Closing as this didn't see any movement in 2 years.
