### ISSUE TITLE
2022 CPC Meeting Schedule

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#816]
_Regular Meetings_ are meetings wherein the entire CPC meets to discuss issues / items that have been tagged on the cross-project-council-agenda label. These meetings are recorded.

_Working Meetings_ are meetings wherein CPC members interested in a particular topic/program meet to work on that topic more deeply. These may not be recorded at the discretion of the meeting organizer. 

### 2022 Meetings & Agendas

<details>
<summary>Past meetings</summary>

| Date     | Meeting Type    | Topic     |
| ------- | ---------------- | -------- |
| Jan. 4  | Regular |  |
| Jan. 11 | Working Meeting | Community Fund - Repo Creation |
| Jan. 18 | Regular |  |
| Jan. 25 | Working Meeting | Tech Strategy - Review candidate repo content |
| Feb. 1 | Regular |  |
| Feb. 8 | Working Meeting | Clarify requirements around CoC violation |
| Feb. 15 | Regular |  |
| Feb. 22 | Working Meeting | Security at OpenJS and beyond |
| Mar. 1 | Regular  |  |
| Mar. 8 | Working Meeting | Thank You Program |
| Mar. 15 | Regular |  |
| Mar. 22 | Working Meeting | "Repo Clean-up" |
| Mar. 29 | Regular  |  |
| Apr. 5 | Working Meeting |  No meeting  |
| Apr. 12 | Regular |  |
| Apr. 19 | Working Meeting | Code of Conduct meeting |
| Apr. 26 | Regular |  |
| May 3 | Working Meeting | CANCELLED |
| May 10 | Regular |  |
| May 17 | Working Meeting | Contributor Covenant / CoC |
| May 24 | Regular |  |
| May 31 | Working Meeting  |  |
| Jun. 7 | Regular |  |
| Jun. 14 | Working Meeting |  |
| Jun. 21 | Regular | |
| Jun. 28 | Working Meeting |  |
| July 5 | Regular~ |  |
| July 12 | Working Meeting~ |  |
| July 19 | Regular~ |  |
| July 26 | Working Meeting~ |OpenJS World Retrospective - Austin 2022|
| Aug. 2 | Regular |    |
| Aug. 9 | Working Meeting |cancelled|
| Aug. 16 | Regular |  |
| Aug. 23 | Working Meeting | |
| Aug. 30 | Regular |  |
| Sept. 6 | Working Meeting |Elections & Representation |
| Sept. 13 | Regular |  |
| Sept. 20 | Working Meeting |  |
| Sept. 27 | Regular |   |
| Oct. 4 | Working Meeting |Canceled with many folks attending NodeConf EU|
| Oct. 11 | Regular | |
| Oct. 18 | Working session | Repo clean-up. _Let's merge PRs and close issues!_ |
| Oct. 25 | Regular |  |
| Nov. 1 | Working Meeting | Code of Conduct / Moderation  |
| Nov. 8 | Regular |  |
| Nov. 15 | Working session | Repo clean-up. _Let's merge PRs and close issues!_ |
| Nov. 22 | Regular |   |
| Nov. 29 | Working Meeting  | Review governance/representation/elections #958  |
| Dec. 6 | Working Meeting | ad-hoc working meeting; zoom link in issue #979 |
| Dec. 13 | Working Meeting |  |
| Dec. 20 | Working Meeting |  |
| Dec. 27 | Working Meeting |  |

</details>

**Comment by Trott** [comment]
I can hide those spam comments, but I don't seem to have the appropriate privileges to block the user from this org.
