### ISSUE TITLE
Email for legal questions bounces - "server is misconfigured"

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#844]
I have tried to email the legal-questions group as per the readme in this repo, but my email was rejected.

The readme says...
> Projects with questions on relevant legal topics are encouraged to email the [legal-questions](mailto:legal-questions@lists.openjsf.org) mailing list. This is a private list, and we will route your question appropriately.
> In order to mail this list, you must be subscribed to at least one other OpenJS Foundation mailing list.

I am already subscribed to the main group.
Do I additionally need to be approved before I can email the legal-questions group?

**Comment by brianwarner** [comment]
Is this still happening? I was able to email it directly from a personal account. Could you send me the bounce?

To answer your other question, no, you wouldn't subscribe to this list directly, as it includes counsel on cc. Any member of an OpenJS list should be able to send to it.

**Comment by brianwarner** [comment]
Ok, let me try clearing the subscription request. My guess is that on the back end, the pending subscription request is causing groups.io to automatically block further mails, despite you being already subscribed to `main` (which is the only prerequisite).

I'll clear that now, you should be able to email after a minute or so.

**Comment by brianwarner** [comment]
I've also updated the instructions in #853.

**Comment by Relequestual** [comment]
I didn't get an immediate bounce, so it looks resolved now.
Not sure how I encountered the initial error though.

**Comment by brianwarner** [comment]
Ok, I'm guessing it was the subscription request that got in the way. I'll close this issue, I think we've gotten it resolved.
