### ISSUE TITLE
Code of Conduct preamble should be identified as aspirational

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#850]
> The OpenJS Foundation and its member projects use [Contributor Covenant v2.0](https://contributor-covenant.org/version/2/0/code_of_conduct) as their code of conduct.

All of the members SHOULD, but this isn’t the case, yet.

I know this may sound nitpicking, but I feel this should be changed to reflect the reality that this as aspirational.

This isn’t a complaint, simply an observation.
I was reading and accepting it at face value as fact, but it isn’t.

Does anyone have any feelings one way or the other about making a change to reflect the current factual situation here?

My reason for asking is, as I go through the [Project Progression Onboarding Checklist](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_PROGRESSION.md#onboarding-checklist), I was looking to see if I could guage how existing non-incubator projects met all of the criteria. I discovered they did not.

I understand this is likely due to the fact that some projects (if not most) were grandfathered in from a different foundation, and no one is asking them to be re-evaluated/look to comply. Again, I don't see this as a problem, but it's very difficult to understand the current situation in terms of project compliance without knowing this information.

**Comment by ljharb** [comment]
I don't think it needs to reflect reality, I think it needs to reflect the way it's supposed to be.

If a member project isn't using the right CoC, it needs to be fixed. Any effort here should be spent fixing that (which might be as simple as a PR to the project, or a DM to a project maintainer asking them to make a `.github` repo in their org).

**Comment by mhdawson** [comment]
I think "SHOULD" also implies that not using it is an option which is not the intent.

**Comment by ljharb** [comment]
Good point - "SHOULD" actually describes the current scenario accurately, but "MUST" would describe the intent :-)

**Comment by Relequestual** [comment]
OK. I'm going to find some time to evaluate how compliant all of the members are, purley as an observation and not a finger pointing game. Also gives me a excuse to play with some APIs.
