### ISSUE TITLE
Link checker broken (aka What happened with PR #841?)

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#858]
PR #841 had checks run which came back OK.
https://github.com/openjs-foundation/cross-project-council/pull/841/checks

However, when you look at the latest commit, https://github.com/openjs-foundation/cross-project-council/commit/821d46070372e8fa24d08a356d20440c4457475b you can see a check failed: https://github.com/openjs-foundation/cross-project-council/runs/5759210379

Currently, the links are broken =[
What happened @joesepi ?

(For the avoidance of doubt, I'm not trying to point a finger here and say someone did something wrong. I'm meerly trying to figure out what happened and why, and @joesepi might know in this instance.)

**Comment by Relequestual** [comment]
I THINK I've worked out what happened.

The URLs which fail on the commit but not the PR are all ones with fully qualified URLs.

As a result, they are FINE in the PR, but once deployed, they no longer work.

It looks like this should be fixable using a newer version of the [link checker](https://github.com/JustinBeckwith/linkinator).
In combination with configuration for URL rewriting, server root, and directory listing.

I'll see if I can verify this locally and make a PR.

**Comment by joesepi** [comment]
Thanks @Relequestual for noticing and looking into this. 🙌
