### ISSUE TITLE
Opportunity: Grace Hopper Open Source Day (virtual) Sept 16, 2022

### ISSUE THREAD

**Issue by rginn** [openjs-foundation/cross-project-council#898]
AnitaB's Grace Hopper Celebration (https://ghc.anitab.org/) (GHC) is the largest conference for women in computing (30K attendees with half virtual / half in-person). They are holding a virtual pre-event Open Source Day (OSD) on Friday, Sept 16, where our OpenJS projects have the opportunity to participate. Last year, over 1,000 people attended OSD with approximately 100 people per OSS project, although all 30K are invited. The goal is to provide a fast track for women and underrepresented communities to become open source contributors.

I met with the Grace Hopper OSD Co-Chairs today. They are looking for participation with one or all of the following:

1. **Projects**: They are looking for an open source project that attendees could contribute to during OSD 2022. Maintainers can work out a schedule to support between 8am – 3pm Pacific Time. Organizers would like good first issues be identified prior to event.
2. **Workshops**: They are looking for a workshop on any topics related to open source.
3. **Mentors**: They are looking for mentors who are interested in helping contributors by answering questions and reviewing code during OSD 2022. 

DEADLINE for participation / CFP is June 20, 2022. 

I can consolidate interest among OpenJS projects for the organizers. You also can apply independently through their CFP process - they are soliciting all ideas here: https://bit.ly/osd22-cfp. 

OpenJS and the Linux Foundation are sponsoring the in-person event in Orlando, FL, September 20-23, 2022. I am on point for the LF. We will have a 10x20 booth – ticket availability TBD, although I will be hitting y’all up for support as we get closer.

**Comment by rginn** [comment]
Node.js has been selected as a featured Open Source Day Hackathon project for the Grace Hopper Celebration virtual [Open Source Day](https://anitab-org.github.io/open-source-day/), Friday, September 16. This is an all-day hackathon where virtual attendees can work with peers and Node.js collaborators and mentors. Special thanks to our Node.js TSC friends for making this happen: [danielleadams](https://github.com/danielleadams) - Danielle Adams, [fhinkel](https://github.com/fhinkel) - Franziska Hinkelmann, and [Trott](https://github.com/Trott) - Rich Trott. 

In addition to the Node.js Hackathon, I will be participating in a virtual [workshop](https://anitab-org.github.io/open-source-day/agenda/) on “The Open Source Games” with others from Fannie Mae, U.S. Bank and more. Workshop attendees will participate in a mock open source problem resolution and develop a more nuanced understanding of the level of effort required to sustain open source software communities. 

OpenJS will be at the Grace Hopper Celebration conference in Orlando, Florida, from September 20-23. If you are attending in person, make sure to stop by the Linux Foundation booth and say hi to our OpenJS reps and me, as well as other projects from the LF including CNCF, Hyperledger, LF Training, OpenSSF and RISC-V.

Additionally, OpenJS and the Linux Foundations with Fannie Mae are hosting an Open Source Happy Hour on September 20 at [Café Tu Tu Tango in Orlando](https://www.cafetututango.com/). Contact me for a free ticket before they run out.

**Comment by tobie** [comment]
I'm really jealous y'all are going to get to hangout with @johnmark. Say hi and have fun!

**Comment by rginn** [comment]
We're grateful for the many contributions and support from OpenJS community leaders who volunteered their time and open source expertise to the Grace Hopper Celebration. Please see our wrap up blogs from the event:
OpenJS Foundation: [We’ve Built Inclusive Open Source Communities. Now What?](https://openjsf.org/blog/2022/10/04/weve-built-inclusive-open-source-communities-now-what/) 
Linux Foundation: [Supporting Women in Open Source at Grace Hopper Celebration](https://www.linuxfoundation.org/blog/supporting-women-in-open-source-at-grace-hopper-celebration)

**Comment by Trott** [comment]
Seems like this can now be closed. I'm going to close it, but please re-open if I'm mistaken.
