### ISSUE TITLE
Public Slides from June Board Meeting at OpenJS World

### ISSUE THREAD

**Issue by SaraJo** [openjs-foundation/cross-project-council#900]
Here is an edited version of the deck shared yesterday at our board meeting, important topics covered were:

- DDOS attack
- OpenSSF Project Alpha
- New Hires
- UCF Update

**Comment by tobie** [comment]
Was the deck shared anywhere? Thanks!

**Comment by joesepi** [comment]
THis one is a miss. Will do July in a private session with CPC members.
