### ISSUE TITLE
Open Call for Nominations for Secondary CPC Director Seat

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#903]
Getting ahead of this election (for once, yay) - It's almost time to run an election for this board seat. Let's discuss at the next meeting to settle on timeline.

**Comment by ljharb** [comment]
Who's the incumbent?

**Comment by mhdawson** [comment]
@ljharb that would be me, but as mentioned earlier I'm not planning on running this time.

**Comment by joesepi** [comment]
For more information on Community Board Seat Expectations: https://github.com/openjs-foundation/cross-project-council/blob/main/governance/COMMUNITY_BOARD_SEAT_EXPECTATIONS.md

**Comment by joesepi** [comment]
Director 2 election - term ends July 31
https://github.com/openjs-foundation/cross-project-council/blob/main/Dates-and-Reminders.md

**Comment by joesepi** [comment]
The discussion at today's meeting was to open nominations now and close them on July 19 (4 weeks) and then run a two week election cycle with the ability to announce the new person on the CPC meeting on August 2nd.

**Comment by joesepi** [comment]
Interested parties should email their desire to run to: operations@openjsf.org

**Comment by joesepi** [comment]
Requirements for this Board seat are defined here: https://github.com/openjs-foundation/cross-project-council/blob/HEAD/CPC-CHARTER.md#the-secondary-cpc-director-as-defined-in-43e-in-the-openjs-foundation-bylaws

**Comment by tobie** [comment]
Clarification request: does the foundation provide Directors and Officers (D&O) liability insurance for board members?

**Comment by tobie** [comment]
> Clarification request: does the foundation provide Directors and Officers (D&O) liability insurance for board members?

Yes, per CPC July 19th meeting.

**Comment by mcollina** [comment]
I was elected for this ;)
