### ISSUE TITLE
CPC Impact voting member selection

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#905]
We should begin this process as the term ends July 31
https://github.com/openjs-foundation/cross-project-council/blob/main/Dates-and-Reminders.md

**Comment by bnb** [comment]
what is the process on the Foundation's side in this process?

**Comment by rginn** [comment]
We manage the election via OpaVote.

**Comment by bnb** [comment]
Isn't this a selection, not a vote, though?

**Comment by joesepi** [comment]
But this is the "selection" process, so no election. I think the Foundation's role is to remind projects that its that time of year again.

**Comment by joesepi** [comment]
details: https://github.com/openjs-foundation/cross-project-council/blob/main/CPC-CHARTER.md#voting-members

**Comment by bnb** [comment]
Just a note: from Electron we've selected @erickzhao and myself.

**Comment by joesepi** [comment]
Node.js TSC has selected @Trott and myself to continue in this role. https://github.com/nodejs/TSC/issues/1258

**Comment by timmywil** [comment]
jQuery has selected @dmethvin  and myself to continue.

**Comment by rginn** [comment]
Updates are all recorded, and changes are in progress for the OpenJS website governance page.

**Comment by mcollina** [comment]
Can this be closed? @tobie @rginn ?

**Comment by rginn** [comment]
Yes, this can be closed.
