### ISSUE TITLE
CPC At Large voting member election

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#906]
We should begin this process as the term ends July 31

Just as we are doing with the secondary board seat election, it was suggested in today's meeting that we begin nominations now and have them open for 4 weeks. Followed by a two week election period with the results announced at the CPC meeting on Aug 2.

Nominations open and ending July 19
Two week election ends Aug 1
Announcement on Aug 2

Interested parties should email their desire to run to: operations@openjsf.org

**Comment by rginn** [comment]
Congratulations to our CPC[ voting representatives](https://github.com/openjs-foundation/cross-project-council/blob/main/governance/GOVERNANCE.md#election-process-for-non-impact-voting-cpc-members) recently elected:

At Large Project Representatives
- Eemeli Aro ([@eemeli](https://github.com/eemeli), Mozilla)
- Tobie Langel ([@tobie](https://github.com/tobie), UnlockOpen)

Elected by Regular Members
- Michael Dawson ([@mhdawson](https://github.com/mhdawson), Red Hat)
- Jordan Harband (([@ljharb](https://github.com/ljharb))

Thanks for your ongoing support and contributions to the governance of our projects and communities at OpenJS!

**Comment by Trott** [comment]
It seems like this can now be closed, but please re-open if I'm mistaken.
