### ISSUE TITLE
Main branch protection rules

### ISSUE THREAD

**Issue by WaleedAshraf** [openjs-foundation/cross-project-council#914]
There is a notification from GitHub that the "main" branch isn't protected.
From the options, I think we should add these two,

- Require a pull request before merging
- Require status checks to pass before merging

Screenshots:

![image](https://user-images.githubusercontent.com/8335457/178844908-0fa31a1f-9b7b-4db2-8655-6b39738465f0.png)
![image](https://user-images.githubusercontent.com/8335457/178844847-367fa7f5-b1c9-4b50-86fc-0080c63c403f.png)

**Comment by ljharb** [comment]
I don't think we should require a PR (typo fixes are nice to push directly), and while we should require statuses to pass, we don't have any enabled so it wouldn't add much value.

**Comment by ljharb** [comment]
good call, that's worth exploring - link checkers are often flaky, but we could certainly try it :-)
