### ISSUE TITLE
Should TC39 list OpenJS Foundation as opposed to JS Foundation?

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#941]
Came across the following list https://www.ecma-international.org/tc39-royalty-free-technical-committee-members/

It lists "JS Foundation".
Should this be updated to be "OpenJS Foundation"?

**Comment by joesepi** [comment]
Yes. It should be OpenJS Foundation as far as I know.

**Comment by ljharb** [comment]
cc @ecmageneva

**Comment by ecmageneva** [comment]
Thanks.
Yes, Wikipedia says also the following:
"The OpenJS Foundation is an organization that was founded in 2019 from a merger of JS Foundation and [Node.js](https://en.wikipedia.org/wiki/Node.js) Foundation.[[2]](https://en.wikipedia.org/wiki/OpenJS_Foundation#cite_note-verge-openjsfoundation-2) OpenJS Promotes the [JavaScript](https://en.wikipedia.org/wiki/JavaScript) and web ecosystem by hosting projects and funds activities that benefit the ecosystem.[[3]]"

So, I will tell the Ecma Secretariat to carry the new name everywhere it is needed for them.

**Comment by ovflowd** [comment]
Looks like they fixed it already 👀

**Comment by tobie** [comment]
Thanks for flagging and fixing.
