### ISSUE TITLE
slack-invite.openjsf.org no longer works

### ISSUE THREAD

**Issue by Trott** [openjs-foundation/cross-project-council#945]
Not sure where to put this, so I'm putting it here: https://openjsf.org/collaboration/ (and other places) mention slack-invite.openjsf.org but if you do not have a Slack account in the OpenJS Foundation Slack already, that link will not work. (Try opening it in Private/Incognito browsing to see.)

<img width="630" alt="image" src="https://user-images.githubusercontent.com/718899/194721362-14301959-a0b4-49b2-8fb6-a913012b4e99.png">

The link to CommunityInviter on the collaboration page doesn't seem to work either (or maybe I don't understand how CommunityInviter works).

**Comment by rginn** [comment]
Hi, you can join the OpenJS Foundation workspace through this [Slack invitation link](https://join.slack.com/t/openjs-foundation/shared_invite/zt-1hp190kw2-9R5r7UMspGrk86~wc5ZGlw). The change has been made on our OpenJS website on the Collaboration page.

TIL that Slack invite links can be used by up to 400, so it has to be reset for more to join.

**Comment by Trott** [comment]
> TIL that Slack invite links can be used by up to 400, so it has to be reset for more to join.

Does that mean we can expect this problem to recur?

**Comment by WaleedAshraf** [comment]
I see. In slack docs
> On the free, Pro, and Business+ plans, members with permission to send invitations can also share an invite link. Each invite link can be used by up to 400 people.

That means it will expire eventually. Maybe we can put something like,

Use the <invite-link> to join. If it doesn't work, send an email to join-slack@openjsf.org

**Comment by ljharb** [comment]
I wonder if we could pre-prepare a list of N links, and make a guess at how long it will take to use each one up, and then auto-rotate with that time period?

The only manual parts would be generating new links to pad the list (but that could maybe be automated), and if a link gets used up too fast, manually rotating.

**Comment by timmywil** [comment]
Maybe instead of guessing we automate generating a new link every day, assuming we get nowhere close to 400 uses a day.

**Comment by abbycabs** [comment]
In the past I've created a shortlink that points to whatever active link we have

**Comment by rginn** [comment]
I get weekly updates from Slack on new members, which tells me we should now update our link every few months. We will add this to our team tracking.

I reset the expiration date to never. A long join link is generated by Slack.

We have a domain redirect service that we use at the Linux Foundation. That's what I used for the new long link redirect to slack-invite.openjsf.org.

This doesn't guarantee we won't experience another broken invite, so we will look at increasing the frequency of updates and other ways to automate if we can. 

Open to hear from other projects who have experienced the same.

**Comment by WaleedAshraf** [comment]
> I get weekly updates from Slack on new members, which tells me we should now update our link every few months. We will add this to our team tracking.

That's great. I think then we are good for now. No need for automation and more complexity that comes with it.

**Comment by WaleedAshraf** [comment]
This is happening again.

https://slack-invite.openjsf.org/

**Comment by anonrig** [comment]
> This is happening again.
> 
> 
> 
> https://slack-invite.openjsf.org/

It is working for me.
