### ISSUE TITLE
draft proposal: Commons.js Program

### ISSUE THREAD

**Issue by jorydotcom** [openjs-foundation/cross-project-council#95]
The commons.js program (as discussed in #44 & other places) is an idea for non-foundation projects to take advantage of some foundation services. Since it is not part of the staging process (#88), it needs to be documented elsewhere, and I think that probably starts with a Stage 0 proposal 😄

**Comment by eemeli** [comment]
Is this still a thing that we're planning on doing? I don't think a proposal for this ever landed, though there is a mention of it in the charter. Adding this to the agenda to get a resolution on this.

Context, form the #44 discussion:
> **Commons.js** is a proposed _program_ that provides foundation resources such as a travel grant etc. or to _any_ open source project, via some process developed and overseen by a $foundation committee. The exact services available are dependent on the budget and discretion of that committee.
