### ISSUE TITLE
Funds for project-driven initiatives

### ISSUE THREAD

**Issue by mcollina** [openjs-foundation/cross-project-council#953]
The volunteer-based collaboration model that OpenJS foster _works_ for the general development of projects. Volunteers are driven by their motives but usually require visibility/recognition of their work. However, this model fails for tasks without recognition: if you do your job well, no one would know you did it. I propose to add a process for which projects could ask for funds to be dedicated at specific initiatives. Here is my proposal.

To access the funds, the project would need to prepare a 1-pager plan, including the purpose and type fo activity, success criteria, timeline, and funds requested. Once approved by the CPC (via a vote?), the funds will be transferred to an LFX Crowdfunding account for the project to manage.
Once the activity was completed, the project would write another 1-pager listing how the money was spent, whether success criteria were met (or explain why they weren't), and share any learnings.

There will be a spending limit:
* 10k for impact projects
* 2k for at-large projects

**Comment by tobie** [comment]
If there's a clear plan to solve a well-scoped issue, I don't think we necessarily need a fixed cap.

Also, would there be a dedicated fund for this? I'm assuming there needs to be a line item in the budget for this.

**Comment by mcollina** [comment]
Let's remove the fixed cap then!

**Comment by dylans** [comment]
I think this would be a good idea to move forward with given the need to get some of the less interesting work done for a project.

**Comment by rginn** [comment]
The OpenJS Board of Directors discussed the proposal and agreed that they are open to hearing requests for funding but cannot dedicate budget at this time to pay for open source software development. Funding requests can be brought to the Board on an ad hoc basis. Overall, the Board is being cautious with the budget given the current state of the economy.

**Comment by joesepi** [comment]
As I understand it based on conversation in today's CPC meeting:
- requests should be made on an ad-hoc basis
- requests should come through the CPC for evaluation
- requests should then be forwarded to the Board for approval
- dollar amounts will be determined on an ad-hoc basis

**Comment by ovflowd** [comment]
That sounds like a great outcome!
