### ISSUE TITLE
What are these repos?

### ISSUE THREAD

**Issue by Relequestual** [openjs-foundation/cross-project-council#957]
I was poking at the repositories under the OpenJS Foundation Github org, and struggled to know what was active and what was not.

Can I suggest marking the repos using repo status badges? (https://www.repostatus.org)

**Comment by tobie** [comment]
Let's clean that up in our next work session.

**Comment by joesepi** [comment]
We went through the repos not long ago and archived some and made some descriptions better. I'm closing this for now. Thanks!
