### ISSUE TITLE
Sharing Board Meeting Slides

### ISSUE THREAD

**Issue by SaraJo** [openjs-foundation/cross-project-council#973]
We've had this conversation for a little while, and I wanted to open an issue to give it transparency. I'd love to work on setting up 15 minutes in the CPC meeting following the board meetings to share slides and walk through the big takeaways. I think that's preferable to sending the slides, and would be better in sparking discussions.

**Comment by tobie** [comment]
I think that's a great idea.

You could either coordinate with @joesepi prior to the CPC meeting or we could add something to the [meeting template](https://github.com/nodejs/create-node-meeting-artifacts/blob/main/templates/minutes_base_cross_project_council) so that we're reminded each time.

**Comment by joesepi** [comment]
I would be happy to use 15min after each board meeting to get an update. That would be great @SaraJo 🙌

**Comment by PaulaPaul** [comment]
Great idea!

**Comment by SaraJo** [comment]
Questions we answered in today's meeting:
- What is private and can't be shared and what isn't?
- Just share with CPC, things like membership conversations. 
- Let's not stream and limit it to members
- Flag it at the beginning of CPC call
- Should it be a working session? 
- What about legal issues? (Should be removed) 
- How is the best way to schedule? (Should flag at the beginning of meeting)
