### ISSUE TITLE
Proposed changes to Node.js TSC Charter require CPC approval

### ISSUE THREAD

**Issue by Trott** [openjs-foundation/cross-project-council#975]
See https://github.com/nodejs/TSC/pull/1311 for proposed changes to the Node.js TSC Charter that require CPC approval.

**Comment by ljharb** [comment]
I approve this change, fwiw.

**Comment by eemeli** [comment]
Added my approval to the `nodejs/TSC` PR.

**Comment by tobie** [comment]
LGTM

**Comment by anonrig** [comment]
Approved!

**Comment by Trott** [comment]
Total voting members on CPC: 14

Voting members in favor:  5 (@Trott @tobie @eemeli in this issue and @bnb @mhdawson in https://github.com/nodejs/TSC/pull/1311)

Is a 5-0 vote with 9 implicit abstentions sufficient? Or do we need more participation from voting members to make this official?

(Voting members who have not yet voted: @joesepi @TheLarkInn @sokra @dmethvin @timmywil @erickzhao @dylans @imurchie @Jonahss)

**Comment by ljharb** [comment]
@Trott i'm also a voting member of the CPC, and i approved as well.

**Comment by Trott** [comment]
> @Trott i'm also a voting member of the CPC, and i approved as well.

@ljharb We might want to take this discussion offline or to another issue, but the README at https://github.com/openjs-foundation/cross-project-council lists you as a Regular Member, and Regular Members are listed as a separate section from Voting Members. Maybe I'm reading too much into the document structure and I need to look elsewhere for who the voting members are/aren't, but I would certainly expect the voting members to be...uh...listed in the Voting Members section.....

**Comment by ljharb** [comment]
@Trott it seems the readme hasn't been updated since https://github.com/openjs-foundation/cross-project-council/issues/906#issuecomment-1273837919, is all

**Comment by joesepi** [comment]
+1

**Comment by Trott** [comment]
We now have 8 of the 15 CPC voting members in favor, so I think I can go ahead and land the PR to update the charter. I'll close this, but if there's more to do here (like some sort of official vote certification), please re-open. Thanks!

(@ljharb I hid our comments about your voting status as resolved. Feel free to unhide or whatever if you think I've overstepped.)

**Comment by dmethvin** [comment]
+1 even if belated!
