### ISSUE TITLE
Determine what a realistic foundation/cpc review process could look like

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#982]
This has been a goal since early days of the foundation as evidenced by the issues below. Let's discuss what is realistic now that we have been doing this for a while.

You can find more context and commentary in the following issues, which I will now close in favor of this new issue:
https://github.com/openjs-foundation/cross-project-council/issues/592
https://github.com/openjs-foundation/cross-project-council/issues/676
https://github.com/openjs-foundation/cross-project-council/issues/677

**Comment by mhdawson** [comment]
I've always through that an NPS survey to the projects with a few simple questions in terms of the value they get from the Foundation would be a useful value to track. It would be a quantifiable datapoint that could be used to get feedback from the projects and to track if the value perceived by the projects is going up/down each year (hopefull up :)).

**Comment by ljharb** [comment]
as an aside, I've always found NPS to be pretty useless - its only value seems to be that it's *something* quantifiable, but everyone who's ever done a few can instantly recognize one, which makes them easy to game and hard to get a representative sample.

**Comment by mhdawson** [comment]
@ljharb i agree you need to be careful in how you use them, but I think they are still useful and relatively easy to implement and many organizations get value from having the data they provide.

If we can do something better that's great but I'd prefer having NPS values versus nothing or waiting for a long time to get something better.

**Comment by mhdawson** [comment]
We discussed in the CPC meeting today. I think we mentioned that we'd send the nps survey to the "leads" for each project. For example in the Node.js project the TSC.

**Comment by mhdawson** [comment]
https://docs.google.com/document/d/1WEWB_ZcwUAXGX7uAe2jXk2HviuN5ep6Dq9mopy0seUA/edit?usp=sharing

**Comment by tobie** [comment]
We decided to aim for a survey in the fall and work back from there once we have more bandwidth.

**Comment by tobie** [comment]
Closing in favor of #1253
