### ISSUE TITLE
Nominations open for the Code of Conduct Moderation Panel

### ISSUE THREAD

**Issue by joesepi** [openjs-foundation/cross-project-council#985]
This relates to recent PR #984, where we've made changes to the Code of Conduct Moderation Panel, including slimming down the amount of folks on this panel. This panel will consist of 3 people selected by CPC as described in #984. Additionally, the panel will include the Foundation ED and Marketing Lead

Please self-nominate or encourage someone you think would be a good candidate for this role. 🎉

**Comment by ljharb** [comment]
I'd like to self-nominate.

**Comment by tobie** [comment]
@SaraJo wanted to self-nominate. I deleted her message because it contained PII.

**Comment by ljharb** [comment]
@tobie for future reference, instead of deleting the whole comment, you can edit it out, and then delete the previous version from the edit history.

**Comment by benjamingr** [comment]
I am happy to self nominate to help but if there are enough people the CPC is comfortable with that self nominated I am happy to let them take this :)

**Comment by tobie** [comment]
> @tobie for future reference, instead of deleting the whole comment, you can edit it out, and then delete the previous version from the edit history.

Oh wow! Thanks. I had no idea you could delete previous versions. That's super useful to know. Thanks for sharing.

**Comment by tobie** [comment]
Thanks for volunteering y'all.

It would be great to maximize gender and geographic diversity on the CoC team. Also it would be great to include folks who have experience dealing with CoC violations if we have any.

Finally, it would be good to understand nominee's perspective on the Foundation's code of conduct:

- Are you committed to enforcing the Foundation's CoC?
- Do you agree with all of it or are they areas that you find concerning? If so, which are they?
- Are you willing to treat every alleged offender in the same way regardless of the impact of their contributions to open source?
- Are you willing to abide by the commitments described in the [Commitment section of the CoC itself](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md#commitment) and in the [Foundation CoC Requirements doc](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md)?

**Comment by benjamingr** [comment]
> Thanks for volunteering y'all.

> It would be great to maximize gender and geographic diversity on the CoC team. Also it would be great to include folks who have experience dealing with CoC violations if we have any.
> Finally, it would be good to understand nominee's perspective on the Foundation's code of conduct:
> Are you committed to enforcing the Foundation's CoC?

That's the bit I think I am volunteering for. Moderation is typically unglamorous janitorial work (at least from my perspective) and moderators enforce the CoC which helps promote collaboration and a professional, friendly environment.

My experience moderating Node.js core for the past ±5 years (3 of them with @ljharb where I can also note he did a good and impartial job as moderator) is that enforcing the CoC and facilitating discussion is very valuable. 

> Do you agree with all of it or are they areas that you find concerning? If so, which are they?

The CoC is very ambiguous which has in the past lead to issues when enforcing it - that's the big one. That said, I don't really have big improvement suggestions and I like the current CoC. I also believe we've been able to successfully resolve any ambiguous moderation issues in the past by involving project leadership (the CPC in this case).

> Are you willing to treat every alleged offender in the same way regardless of the impact of their contributions to open source?

No, every offender is a human and their background in the project and previous conflicts often weighs in when making moderation decisions.

For example: first time contributors typically get a lot more leniency than long time contributors, and the communication style is often a lot more guiding and different with them. On the other hand project leadership (and moderation) is bound by much stricter standards. 

> Are you willing to abide by the commitments described in the [Commitment section of the CoC itself](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md?rgh-link-date=2022-12-20T11%3A58%3A57Z#commitment) and in the [Foundation CoC Requirements doc](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md?rgh-link-date=2022-12-20T11%3A58%3A57Z)?

That is what I thought I am signing up for :) Again, I am happy to volunteer my time but if there are enough other volunteers I am happy to give my place to improve diversity. The CoC actually being enforced and enough eyes on it is the bit I care about and why I've volunteered moderating in Node.js itself.

**Comment by tobie** [comment]
I'm so happy I asked these questions and got so thoughtful answers. Very humbling.

I'd love to hear from the other folks who nominated themselves too.

<details>
<summary>A few additional meta thoughts about how to figure out who to add to the CoC team</summary>

- Thanks @benjamingr for bringing up [MEMBER_EXPECTATIONS.md](https://github.com/openjs-foundation/cross-project-council/blob/main/conduct/MEMBER_EXPECTATIONS.md. I believe we should more explicitly require the CoC team to abide by it (even if that seems obvious, explicitness is important).

- Among the diversity concerns I brought up above, I also realize that we want diversity of projects represented in the CoC team.

- @benjamingr also made very good points in https://github.com/openjs-foundation/cross-project-council/pull/984#discussion_r1053792683, in particular that more eyes bring a useful diversity of perspective, and that lowering the number of people or making sure they're an odd number for voting purposes aren't conducive to more efficiency or better outcomes.

I'll wrap all of these up and suggest policy changes accordingly in the relevant PRs.

</details>

**Comment by tobie** [comment]
Closing in favor of #1298. If you've self-nominated in the past and are still up for it. Please self-nominate again in the new issue! Thank you!
