### ISSUE TITLE
2023 CPC Meeting Schedule

### ISSUE THREAD

**Issue by tobie** [openjs-foundation/cross-project-council#994]
**Meetings:** the entire CPC meets to discuss issues / items that have been tagged on the cross-project-council-agenda label. These meetings are recorded.

**Working sessions:** CPC members interested in a particular topic/program meet to work on that topic more deeply. These are generally not recorded. 

### 2023 Meetings & Agendas

<details>
<summary>Past meetings</summary>

| Date     | Meeting Type    | Topic     |
| ------- | ---------------- | -------- |
| Jan. 3  | Meeting |  |
| Jan. 10 | Working Session | Code of Conduct work: #991, #972, #851, #984  |
| Jan. 17 | Meeting | |
| Jan. 24 | Working Session | Continuing Code of Conduct work: #991, #972, #851, #984 |
| Jan. 31 | Meeting | |
| Feb. 7 | Working Session | Continuing Code of Conduct work: #991, #972, #851, #984 |
| Feb. 14 | Meeting | |
| Feb. 21 | Working Session | no meeting |
| Feb. 28 | Meeting | |
| Mar. 7 | Working Session | no meeting |
| Mar. 14 | Meeting | |
| Mar. 21 | Working Session | Worked on CoC issues asynchronously; no meeting |
| Mar. 28 | Meeting | |
| Apr. 4 | Working Session | Continuing Code of Conduct work: #972, #851, #984, #985 |
| Apr. 11 | Meeting | |
| Apr. 18 | Working Session | |
| Apr. 25 | Meeting | |
| May 2 | Working Session | |
| May 9 | Meeting | |
| May 16 | Working Session | |
| May 23 | Meeting | |
| May 30 | Working Session | |
| Jun. 6 | Meeting | |
| Jun. 13 | Working Session | Package.json discussion #1082 |
| Jun. 20 | Meeting | |
| Jun. 27 | Working Session | Package.json discussion #1082 #1102 |
| Jul. 4 | Meeting | NO MEETING - US HOLIDAY |
| Jul. 11 | Meeting | |
| Jul. 18 | Working Session | * Claudio and Ben will work on github funding for project needs * Tobie and Joe may work on CoC work |
| Jul. 25 | Meeting | |
| Aug. 1 | Working Session | Work happened on #397 |
| Aug. 8 | Meeting | |
| Aug. 15 | Working Session | Plan to work on #1122 and #1055 |
| Aug. 22 | Meeting | |
| Aug. 29 | Working Session | Plan to work on #1147 |
| Sep. 5 | Meeting | |
| Sep. 12 | Working Session | Plan to work on #1147 |
| Sep. 19 | Meeting | |
| Sep. 26 | Working Session | |
| Oct. 3 | Meeting | |
| Oct. 10 | Working Session | Plan to work on #1147 & #1178 |
| Oct. 17 | Meeting | |
| Oct. 24 | Working Session | |
| Oct. 31 | Meeting | |
| Nov. 7 | Working Session | |
| Nov. 14 | Meeting | |
| Nov. 21 | Working Session | |
| Nov. 28 | Meeting | |
| Dec. 5 | Working Session | Travel fund continuing work |
| Dec. 12 | Meeting | |
| Dec. 19 | Working Session | Travel fund continuing work |
| Dec. 26 | Meeting | |
</details>

### Upcoming Meetings

| Date     | Meeting Type    | Topic     |
| ------- | ---------------- | -------- |

🎉

**Comment by joesepi** [comment]
Good work everyone. Here's to next year (this year)!!!
